### ISSUE TITLE
AppImage fails to run on Ubuntu Studio 19.04

### ISSUE THREAD

**Issue by CoolGames** [OpenShot/openshot-qt#3036] opened 2019-10-08 17:10 UTC
**Describe the bug:**
Downloaded AppImage not executing with large number of complaints

**Steps to reproduce the behavior:**
1. Go to 'Downloads' after download
2. Change to executable on 'chmod +x ./OpenShot-v2.4.4-x86_64.AppImage'
3. Run AppImage './OpenShot-v2.4.4-x86_64.AppImage'
4. I saw a request to create Desktop then
command line results which I pasted to generate attached error file
[AppImage_Errors.txt](https://github.com/OpenShot/openshot-qt/files/3703534/AppImage_Errors.txt)

**Expected behavior:**
To run as before although last seen before 18.04 as Issues report
**System Details:**
- OpenShot Version 2.4.4 as downloaded APPImage

- Operating System / Distro: Ubuntu Studio 19.04 upgraded
 since originally 16.04 (dates Jun 27, 2016)  ( before 18.04 )

I observed these dated files for nudging my memory
~/.openshot/config.xml and
 some other files dated 01/24/2018 may have been last time used and
 have blender attempts that I remember failing causing abandoning use.

**Log Files:**
[libopenshot.log.7z.zip](https://github.com/OpenShot/openshot-qt/files/3703566/libopenshot.log.7z.zip)

**Comment by ferdnyc** [comment] 2019-10-08 18:44
I believe this **might** be a duplicate of #3010, though without the console output of the AppImage I can't be sure. But the solution I provided for that issue (an AppImage build with a different set of included library files) may work better in your case as well. You can download that here if you'd like to try it out:

https://drive.google.com/open?id=1bqSudb-MITqqNJoJrKZub1WHuN-eoicN

As far as Blender issues go, code was checked in to OpenShot a couple of months ago that made it compatible with the new Blender 2.80 release, and that's included in the file I linked to, as well as the other recent Daily Build packages. OpenShot 2.4.4 release is **not** compatible with Blender 2.80, so if you're looking to use that Blender version it wouldn't have worked out for you anyway.

Note, also, that OpenShot 2.4.4-dev2 builds (the latest development releases) are compatible **ONLY** with Blender 2.80 — earlier versions, up to and including 2.79c, will _not_ work with any builds of OpenShot newer than mid-August.

**Comment by ferdnyc** [comment] 2019-10-28 20:07
No response after 3 weeks, closing. It's too bad, I'm pretty sure the linked AppImage above would have run successfully. 

Other than the Fontconfig spew (a known issue with the AppImages, but usually harmless — though these do seem more serious than normal — but which should be corrected in the build I provided by the unbundling of `libfontconfig`.) There are no errors logged on the console. It's only because it received a `KeyboardInterrupt` (<kbd>Ctrl</kbd>+<kbd>C</kbd>) that OpenShot terminates, I don't see any crash or fatal error signs in the provided output.

**Closed by ferdnyc** 2019-10-28 20:07 UTC
Labels: :beetle: bug
