### ISSUE TITLE
Add to timeline feature does not work with image sequence

### ISSUE THREAD

**Issue by tichyion** [OpenShot/openshot-qt#3430] opened 2020-05-01 16:32 UTC
Hi all,

I want to create a slideshow (movie) out of several hundred images.

1. If I use import files and click "No" for "Would you like to import <<Filename>> as image sequence?", OpenShot is asking this for each single file in the directory.
--> I was wondering if there is a possibillity to avoid clicking hundred+ times "Yes and found

2. If I import only the first file and click "yes" OpenShot shows one "file" in the Project Files area but recognizes all the files in the directory, which i have proved by checking File Properties number of frames or Preview the File is showing all pictures.

So far so good, but:
unfortunately the really good feature "add to timeline" does not add "Fade" or "Transitions", if I configure this, i always get only a slideshow containing all the pictures but no delay, fade or transition between the pictures.

Appreciate your Help

Thanks
Marc

**System Details:**
- OpenShot Version: 2.5.1
- Operating System: Windows 10

**Comment by ferdnyc** [comment] 2020-05-01 19:14
@tichyion Image Sequences are one of the features we need to document better.

When you import an image sequence, you're loading the images as the individual frames of a VIDEO. The images must all be the same size, aspect, color depth, etc. and as you saw, they'll be loaded as a single media file (the video made up of those frames).

To do any sort of slideshow or otherwise use the individual files as separate images, they must not be loaded as an image sequence.

If OpenShot is prompting you again for every file, that's a bug we'll have to correct. Until we can get that sorted out, the only suggestion I have is to try going through and choosing "no" for the first few files. I'm not in front of a computer right now, but I think after 4 or 5 files, it MIGHT stop prompting. (You shouldn't have to do it more than once, but like I said... It's a bug.)

If it keeps prompting you beyond 5 or 6 files, then I'm wrong and it probably will keep going for the entire set. Hopefully we'll be able to get that fixed shortly so you won't have to deal with this anymore.

**Comment by Mat35** [comment] 2020-05-01 20:23
Hi,
I have exactly the same problem : 161 images to import to make a birthday stopmotion movie.
So, I don't want to import as a sequence of images, but : I had to click 161 times... (this birthday is tomorrow, I had to do it !)
Thanks
Mat

**Comment by ferdnyc** [comment] 2020-05-01 22:10
@Mat35 Ok, that's definitely a bug then. Thanks for the update. I'll take a look at it tonight and see if I can get that dealt with.

**Comment by tichyion** [comment] 2020-05-02 07:49
Hi,

many thanks for the information. I have stopped importing after 24 times clicking this morning..

Thanks!
Marc

**Comment by MBB232** [comment] 2020-05-02 11:52
> I'm not in front of a computer right now, but I think after 4 or 5 files, it MIGHT stop prompting. (You shouldn't have to do it more than once, but like I said... It's a bug.)

Does Openshot even have a "no to all" interface option? I noticed that when loading a project it keeps telling files are missing in nep popups that want confermation before it continues.. (Was probably less then 5, but certainly 3 or 4 repeated notices, mostly because I only had small projects)

Preferred way for repeated actions would probably be a list of all files the action applies to. (With maybe checkboxes to disable the files you do not want the action to happen to. )

**Comment by ferdnyc** [comment] 2020-05-02 16:27
> Does Openshot even have a "no to all" interface option? 

It doesn't, but it wouldn't make sense for this, as an image sequence import isn't an individual file action, it's an action on a group of files. When you answer "yes" to the question, it applies to the entire group of files. Answering "no" is meant to work the same way. That it doesn't, is exactly the bug. Once it's fixed, prompts will go back to covering the entire range of files.

The imported file recovery thing is a separate issue. Once you match up a missing file to its new location, not only will it not prompt you again for that file, but it'll automatically match up any other missing files in the same directory as well.

The problem is that OpenShot doesn't really support loading project files _without_ all of the media accessible. As soon as a missing-file recovery is cancelled, the project data is in an invalid state as far as OpenShot is concerned, so behavior after that point is... "not ideal". But also unsupported.

**Comment by SuslikV** [comment] 2020-05-03 17:02
@ferdnyc I can report another bug:
try to import image file as sequence, files named `IMG_0135.JPG` and `IMG_0136.JPG` (you may copy and rename any .jpg file you have)
Is it works?

**Comment by ferdnyc** [comment] 2020-05-04 22:43
@SuslikV

No, but it shouldn't, for multiple reasons.

1. Three frames minimum are required to form an image sequence
2. Unless the starting frame number is in the range 0-4, ffmpeg won't accept the sequence as valid.

Really, what I'd point to as the bug there is that it even _offers_. The code should be smarter, but it's decidedly not. Personally I don't consider the existing import code for sequences to be worth any more time spent applying additional Band-Aids. It's not merely injured, it's missing all four limbs and 65% of its internal organs.

A while back in https://github.com/OpenShot/openshot-qt/issues/221#issuecomment-552109791 I sketched out the logic for a completely new algorithm for detecting and importing image sequences, which would be both faster AND smarter than the current one. Mostly it's just looking for someone to actually implement it, although an ideal implementation would also add `start_number` support to libopenshot, which is how we can overcome that second restriction about the first frame having to be numbered in the range 0-4. 

Some partial info regarding `start_number`  is also in that other issue, at least as far as I'd gotten looking into it. There are definitely still some missing pieces of the puzzle, regarding how we'd actually utilize that via the library APIs.

**Comment by ferdnyc** [comment] 2020-05-04 22:47
(Er, despite my previous comments, I do still intend to fix the "prompts once per image" thing reported here. That's too big a disaster to go unaddressed, as much as I'd prefer to never touch that code again.)

**Comment by ferdnyc** [comment] 2020-05-04 22:54
All of these instances where image sequences fail to import are much easier to explain when OpenShot's console output is visible, since FFmpeg will always print a message explaining why it turned its nose up at a particular sequence. So on Windows, using `openshot-qt-cli.exe` to make that output visible is one option.

**Comment by iam01110011** [comment] 2020-05-17 22:02
Just been searching the web because for solutions to this because I've had the same issue- trying to import >100 shots into openshot and for each the box comes up would you like to import <> as an image sequence. im glad it's not just me. Im using the software on linux, BUT...this seems to be an issue on the mac version of open shot too.

will be super happy when the bug is fixed! : D

gonna report one more bug for linux while im here (not sure if it's the right place to report a bug of a different sort) after trying to add an animated title- the software crashes after rendering. I had to install openshot on my old macbook use the animated title feature on there then transfer project back over to linux.

thanks : )

**Comment by HR-grabdpa** [comment] 2020-09-21 23:25
I found a workaround for the import image bug that keeps asking the same question over and over.  create a desktop folder. Give it a name like IMAGE FILES.  Copy all of the iamge files you want to import into OpenShot into the folder.  In windows, perform a CTRL A (selects all files). Right c;ick the first file and select "rename".  If the files all start with somerthing like "IMG_", replace the IMG_ with 0 (zero), press the "end" key and press "enter".  All files will carry the first files name, but Windows gives eac one in succession an additional unique number " (1) (2) etc." Now the image files can be imported sequentially.  Obviously this won't work for files that had names without losing the names, but works great for numbered files.

**Comment by jnelson522** [comment] 2020-11-19 21:47
@ferdnyc Any update on this? I am running OpenShot on both Mac and PC, and having to click "no" to the image sequence dialog for each image imported (at least up to 51 images, the max I've imported).

**Comment by iam01110011** [comment] 2020-12-21 20:43
Yes! So sorry for a huge delay in replying!
So if you re name your files in ascending numerical order. Should transfer across.
I did this by highlighting all my shots and under properties there was an option to organise how my files were labeled/viewed (I'm using Ubuntu but sure osx and windows 10 have their own version). Anyway after being re named with a ascending numerals per shot, the files were able to transfer perfectly. My files looked a bit like this after the PC renamed them: 1.IMG_insertnamehere. 2.IMG_whateverit'scalled. 3.IMG_photoname 
  I hope I've written this clearly enough : p and hope it works for you!!

**Comment by Colorjet3** [comment] 2023-02-01 02:46
The constant prompting message has been fixed in 2.6.x and later.

**Closed by Colorjet3** 2023-02-01 02:46 UTC
Labels: :lady_beetle: bug, docs, media-handling
