### ISSUE TITLE
cx_freeze: Pyhton error in main script (Error while starting up first time after installation)

### ISSUE THREAD

**Issue by aamirology** [OpenShot/openshot-qt#483] opened 2017-01-20 09:17 UTC
I just installed OpenShot on Windows 10 Home 64-bit, x64-based processor and got this error on startup. The program is unable to start since. The screenshot of the error message is attached below.

OS: Windows 10 Home 64-bit, x64-based processor
Processor: AMD A8-7410 APU with AMD Radeon R5 Graphics 2.20 GHz
Installed memory (RAM): 8.00 GB (6.94 GB unusable)

Thanks

![openshot-bug-scrnsht](https://cloud.githubusercontent.com/assets/15388194/22142924/290ffdc0-df1e-11e6-8694-26c42c414887.png)

**Comment by ashieducation** [comment] 2017-01-20 13:46
Just installed Openshot on my desktop and laptop. It works well on my desktop, but displays error on my laptop. 
![picture1](https://cloud.githubusercontent.com/assets/25247429/22151608/0feac3ba-df1f-11e6-9304-fb1f11c39186.png)
![picture1](https://cloud.githubusercontent.com/assets/25247429/22151612/11c3e14e-df1f-11e6-9c6f-186d358ca4d6.png)
![picture1](https://cloud.githubusercontent.com/assets/25247429/22151625/207a4610-df1f-11e6-982b-87a49a6b0233.png)

**Comment by bell18** [comment] 2017-01-22 19:30
i got the same error. i right clicked and pressed 'run as administrator' and it ran perfectly.

**Comment by ashieducation** [comment] 2017-01-23 06:20
It still giving me the error even after running in administrator mode.

**Comment by ZZZett** [comment] 2017-01-24 14:38
I have the same problem on Windows 10. Just installed **OpenShot** and the mentioned error appears when I try to run the program. Any help?

**Comment by ashieducation** [comment] 2017-01-25 06:35
It seems to work perfectly on desktop computers. But flags error on laptops.

**Comment by ZZZett** [comment] 2017-01-25 07:44
Okay, my problem appears on my laptop 64bit Windows 10. Any help on this?

**Comment by bell18** [comment] 2017-01-25 12:34
it works on my desktop, but not my laptop

**Comment by jreynojustin** [comment] 2017-02-28 14:57
Duplicate of #374 Please refer to @jonoomph comment on this for information on how to resolve the issue.

**Closed by jreynojustin** 2017-02-28 14:57 UTC
