### ISSUE TITLE
Eye/mute audio icons are missing

### ISSUE THREAD

**Issue by fmeneuhe** [OpenShot/openshot-qt#1305] opened 2018-02-24 19:33 UTC
**System Details:**
* Operating System / Distro: Windows 10 Pro 64bits
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

Where are the eye and audio mute icons to hide or mute  the whole track? That's a bug right?
The same issue in Ubuntu 16.04

![openshot](https://user-images.githubusercontent.com/8604933/36634279-6f83fcb0-19a2-11e8-9d37-264f08239db2.png)

**Comment by DylanC** [comment] 2018-02-24 20:43
@fmeneuhe - Yes, this used to be the case in the older versions in the 1 series. Those buttons do not exist in v2.x.  There is an enhancement ticket already opened for this: #784

**Comment by ferdnyc** [comment] 2019-07-25 17:24
Closing as duplicate of #784. (We'll keep that one open to track this.)

**Closed by ferdnyc** 2019-07-25 17:24 UTC
Labels: duplicate
