### ISSUE TITLE
Fast forward doesn't work in final output

### ISSUE THREAD

**Issue by ezonakiusagi** [OpenShot/openshot-qt#2516] opened 2019-01-08 00:51 UTC
**Please fill out this template** 

**Describe the bug**
When i fast forward a video, doesn't matter if it is 2x or all the way up to 32x, in the final export, that segment of video only shows a static image of the segment *after* the fast forward for the duration of the fast forward. Example, say i have 60 sec video clip, and fast forward it 2x, so the export is a 30 second clip. when i playback the 30 second clip, it just shows a static image for 30 seconds.

i have previously successfully used fast forward before without this problem. i suspect something has changed since then.

**System Details (please complete the following information):**
 - Operating System / Distro: Fedora 28 Linux / kernel 4.19.10-200.fc28
 - OpenShot Version 2.4.3

**To Reproduce**
1. start openshot
2. add video clip
3. right click on video clip->time->fast->forward->2x (or any other multiple)
4. export video and playback

**Expected behavior**
exported video to show playback at 2x speed instead of a static image.

**Screenshots**

**Logs**
no crash

**Video Profile**
doesn't seem to matter.

**Additional context**

**Comment by eth** [comment] 2019-01-15 07:17
Can confirm, I have the exact same issue.

**Comment by ezonakiusagi** [comment] 2019-01-17 21:04
@eth I was in the same boat. i ended up cutting the clip i wanted to fast forward, and then manually fast forward it with ffmpeg. then stitched it back together in openshot. it worked, but was a hassle for sure.

i'd really like to see this and the memory leak issues fixed...

**Comment by lxtwin** [comment] 2019-02-24 16:46
I also have the same issue on when exported.
Linux 2.4.3 (app image) or 2.4.1 deb install
uname: Linux homepc 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Distro: Mint Linux 19.1 Tessa

**Comment by lduros** [comment] 2019-03-07 18:11
++ having the same issue on OSX... Fast forwarding is super important for my video too lol

**Comment by ezonakiusagi** [comment] 2019-03-07 22:25
i'm not sure what it takes to get attention to this issue. it's been 2 months now and i've moved on to use something else that works without all the issues i've run into with openshot.

**Comment by LeOSW42** [comment] 2019-03-08 07:53
Hi there,

Same issue for me on archlinux, openshot 2.4.3.

Léo

**Comment by eth** [comment] 2019-03-08 17:46
What did you switch to? I'm about to do the same. One man team working in
this editor, I'll check back in a hear and hopefully it's a bit more ironed
out.

**Comment by ezonakiusagi** [comment] 2019-03-08 18:43
@eth i'm using shotcut for now. i haven't run into any bugs with it yet, all the features i use seem to work flawlessly, and it doesn't use up 80+GB of RAM when I export the video. also, recently made it work with my GPU so i can export videos in a lot less time.

i really tried to make openshot work; kept at it for over a year, but every update seem to introduce new problems. and old problems aren't getting fixed. i hope the devs find time to fix the issues and i'll give it another try.

**Comment by pullup** [comment] 2019-03-13 02:27
> @eth i'm using shotcut for now. i haven't run into any bugs with it yet, all the features i use seem to work flawlessly, and it doesn't use up 80+GB of RAM when I export the video. also, recently made it work with my GPU so i can export videos in a lot less time.
> 
> i really tried to make openshot work; kept at it for over a year, but every update seem to introduce new problems. and old problems aren't getting fixed. i hope the devs find time to fix the issues and i'll give it another try.

Woah, I've got some nice cards. Got a link on how to GPU export with it?

**Comment by ezonakiusagi** [comment] 2019-03-13 09:06
@pullup  
> Woah, I've got some nice cards. Got a link on how to GPU export with it?
https://shotcut.org/blog/new-release-181113/

**Comment by delucas** [comment] 2019-03-28 19:07
Same here! I'm about to do the ffmpeg thing for now... but this would be awesome to be fixed! :)

**Comment by eth** [comment] 2019-03-28 23:58
Check out shotcut for that job, having much better luck with that software.

**Comment by ferdnyc** [comment] 2019-07-20 12:34
I just double-checked with 2.4.4 release, and a Clip set to Time > Forward > Fast > 4x exported as a video which plays at 4x normal speed in VLC. Closing as fixed in 2.4.4.

**Closed by ferdnyc** 2019-07-20 12:34 UTC
Labels: Needs Testing

**Comment by llLEOll** [comment] 2020-08-24 22:43
Why this is closed if it is still not fixed???

**Comment by ksaadDE** [comment] 2023-11-25 04:24
Issue is still existent in Version 3.1.1 (Nov/2023) @ferdnyc  

Are there any workarounds?? This is a very unexpected issue.

**Comment by ferdnyc** [comment] 2023-11-25 05:08
@ksaadDE 

I'm no longer involved here, but... to also answer @llLEOll's question, this was closed because, as I said in [my comment](https://github.com/OpenShot/openshot-qt/issues/2516#issuecomment-513463920), I wasn't able to reproduce. It worked fine when I tried it.

The issue would've been closed _anyway_ after 6 months of inactivity by the Stale bot, because old reports aren't kept open forever. 2.4.3 is a very old version.

If you're still experiencing this issue in the current releases, you should open a new issue and provide **detailed** information on how to reproduce it. That means, in addition to what the bug report form asks for, include:

1. _exact_ information about the **format** of your imported clip
2. the _exact_ project configuration you imported it into
3. the _exact_ export settings used, that created an incorrect video.

Because, clearly, _sometimes_ this **does** work. To figure out exactly why it sometimes DOESN'T, the developers will need all of that information.

The Time property — which is how all playback speed/direction changes to video clips are applied — is also **incredibly** difficult to use properly, even in its accelerated "right-click" form. (It's basically IMPOSSIBLE to use it manually, as its value has to be set for every single frame of the clip.)

Some of the issue may be user error. (Which really come down to user interface deficiencies, because like I said that property is just absolutely a nightmare to work with.)

When adjusting clip-wide properties, you should always make sure that you have the playhead positioned right at the first frame of the Clip in question, not anywhere else. That's one thing that often trips people up. The context-menu adjustments aren't _supposed_ to care about playhead position, that's mostly for manual Property changes... buuuuuuut it's still safer to position it at the clip start anyway, just to be safe. It's also probably a bad idea to _move_ a clip that's had any sort of speed-change applied to it, because any changes to how frames are counted and processed can foul up the Time property.

me, in https://github.com/OpenShot/openshot-qt/issues/3081#issuecomment-557240456:
> honestly the Time (speed-change) property is by far the most fragile and unpredictable of the bunch (by like several orders of magnitude), so it never really surprises me when something breaks with it... all that's required is for someone to look at it funny. Deleting the clip and adding a new one to the timeline (IOW, clearing out all adjustments and starting with a clean import) usually clears up the problem, unless of course the same conditions cause it to occur in the new clip as well.
> 
> Long story short, point is that there are probably 100-200 GitHub issues here that all basically amount to: "Tried to use Time parameter to change playback speed of clip. It broke everything." So... misery loves company, maybe? `¯\_(ツ)_/¯`

Probably more likely, though, is that the problem is an input video format that isn't compatible with frame-by-frame access. Or a mismatch between input frame rate, project frame rate, and/or export frame rate. That sort of thing.

Because sometimes, when the stars align, the feature works exactly as expected.

**Comment by ksaadDE** [comment] 2023-11-25 06:04
@ferdnyc  Oh I did not know that you are not responsible for it anymore :D 

Well, I don't think there's much of a description needed. I went right-click duration speed forward 2x. Although the 4x works but not the 2x. 🤣  

Well if you tell me where I can grab some anonymized logs, I will do and publish them here. Might be some frame or editor issue... 

Yea, I opened a new one. 

Thanks for your fast reply tho! :)
