### ISSUE TITLE
Full image returns at end of transition

### ISSUE THREAD

**Issue by ragingwarthog** [OpenShot/openshot-qt#3824] opened 2020-11-05 23:58 UTC
**Describe the bug:**
I see that this bug has been reported previously over the years.  I am adding a circular fade out transition at the end of a short clip. The expectation would be that the track would fade to complete black over a few seconds. Instead, the fade does occur, but for a few frames at the very end, the complete, unfaded image returns in the track, AND in the produced video file.

I've tried a number of different corrective measures without success.

**System Details:**
- OpenShot Version version 2.5.1-dev2
- Operating System / Distro: Windows 10

**Comment by rexdk** [comment] 2020-11-06 07:35
It's implemented/approximated as a cubic bezier curve, by InterpolateBezierCurve() in KeyFrame.cpp - as far I can see. I thought there might br a bug in the code, but it looks pretty sound to me.
I wonder if you have placed the keyframes exactly? Try to zoom in to max resolution on the timeline, and step through the frames using the arrow keys to check that the alpha keyframe is exactly at the end.

You might also try a similar interpolation,like expo or quint. I've just done some graphs on a work-in-progress page:
https://drking.org.uk/openshotguide/manual-animation/

**Comment by rexdk** [comment] 2020-11-06 07:51
My system is similar to yours Win10, with a recent daily build. I've just tried ease out (circ) over a few seconds and everything seemed to work as expected.

**Comment by ragingwarthog** [comment] 2020-11-06 07:58
I can reproduce this problem. It appears that if the transition is resized, then this problem occurs. To confirm, the magnet snap option is on, and there is a corresponding reverse transition at the beginning of the next clip. The effect I am aiming for is a circular fade out of the first clip, and a corresponding circular fade in of the next clip. The producer I am working with is wanting to stick to this type of transition.
 
Steve Hornett,
 
Chief Technology Officer
Raging Warthog Technology Services
Rockwood, Ont
“We’re not clairvoyant. We’ve just seen everything.”
 
M: (519) 501-0900
 
 <mailto:steve@ragingwarthog.com> steve@ragingwarthog.com

**Comment by rexdk** [comment] 2020-11-06 08:28
Ah, I may have misunderstood. I thought you were animating the alpha parameter with the ease out (circ) interpolation type.

Are you simply using the Circle In to out (or Out to In) standard transition?

If so maybe you could zoom in to max timeline resolution and check that the transition is located correctly between the ends of the two clips. I've been aware of a possible problem with 'snap' if the timeline resolution is not max - but haven't had time to look into it and report it.

So the left edge of the transition should be exactly at the start of the second clip, and the right right exactly at the end of the first clip. Is that clear? Can you check that?

**Comment by ragingwarthog** [comment] 2020-11-06 08:33
Yes, I am using the standard circle in / out transition.
 
Yes, I am being very diligent about ensuring that the two clips and transitions are correctly positioned.
 
It still occurs.
 
Steve Hornett,
 
Chief Technology Officer
Raging Warthog Technology Services
Rockwood, Ont
“We’re not clairvoyant. We’ve just seen everything.”
 
M: (519) 501-0900
 
 <mailto:steve@ragingwarthog.com> steve@ragingwarthog.com

**Comment by rexdk** [comment] 2020-11-06 09:20
Sorry to check basics - looks like you're knowledgeable. I'm assuming you've applied the fade out transition and right clicked it to choose 'reverse transition'. It all works fine for me - except that in my daily build I now cannot see the transition properties (I'll report that elsewhere).
I'm a bit out of my depth now, but maybe a workaround would be to have your second clip on a different track (above), which would allow you to extend the fade out transition a few frames past the end of the first clip - just in case this is something to do with frame conversions or something. I hope that helps.

**Comment by ragingwarthog** [comment] 2020-11-08 06:01
This appears to have fixed the problem.  Thanks for the suggestion!
 
The solution is to continue to flip back and forth between tracks 2 and 3, making the fade out slightly longer than the length of the actual clip. I have seven clips that are all in sequence, with a fade in at the start and a fade out at the end of each clip. Unless I extend the fade out for each clip beyond the length of that clip, I get one or two frames of the clip with no transition at the end. It is very noticeable.  There is obviously a bug. I can replicate this issue.
 
Steve Hornett,
 
Chief Technology Officer
Raging Warthog Technology Services
Rockwood, Ont
“We’re not clairvoyant. We’ve just seen everything.”
 
M: (519) 501-0900
 
 <mailto:steve@ragingwarthog.com> steve@ragingwarthog.com

**Comment by rexdk** [comment] 2020-11-08 06:37
Good that you have a fix, even if not ideal. I guess you could also try keeping the clips all al one track, just having a couple of frames between the clips, covered by the first transition.
I know there is something difficult in the logic for the final frames of  a clip, and presumably this is something to do with that. I don't understand the details, but if there's a problem it's a problem. I'll leave it now to those with proper understnading.

**Comment by ragingwarthog** [comment] 2020-11-08 12:44
Thanks,
 
I did try a variety of ways to keep all of the clips in one track, and none of them were reliable.
 
There is definitely a problem, and like many situations that employ technology, in this case, I had a deadline. 
 
I came very close to throwing in the towel and going with a competitive product.
 
Steve Hornett,
 
Chief Technology Officer
Raging Warthog Technology Services
Rockwood, Ont
“We’re not clairvoyant. We’ve just seen everything.”
 
M: (519) 501-0900
 
 <mailto:steve@ragingwarthog.com> steve@ragingwarthog.com

**Comment by troelsfrostholm** [comment] 2020-11-16 15:13
Hi

I encountered the same problem on OsX within 10 minutes of trying OpenShot, as the first knot in a beautiful program. 

Steps to reproduce:
1. Add two stills in succession on Track 1, snapping them end-to-beginning
2. Add a "fade in" transition at the second still (snaps to beginning of the still, covers entire first still timeline by default)
3. Add a "fade out" transition to the first still (snaps to beginning of the still, covers entire second still timeline by default)

This results in the first still fading out, then briefly blinking back in, before the second still fades in. 

Steps to work around: 
1. Move second still and it's transition to track 2

It doesn't solve the problem to:
* Move the second still and transition back to track 1
* Remove the second still's transition
* Resize the first still's transition to obviously end at a later time than the first still. 

It does solve the "blink-back" behaviour to:
* Remove the second still
* Turn off snap and move the beginning of the second still to start shortly after the first still stops, without touching the transitions

I observe that if the beginning of the second still is moved back so there is some overlap with the first still, then the first still is shown without the effect of the transition during the overlapping period. 

My uneducated guess is that snapping the two stills creates a short overlap, and the transitions are not able to handle this. 

A question: Why is it possible to overlap two media pieces within the same track? I can understand the use for transitions and effects, but why for files?

**Comment by troelsfrostholm** [comment] 2021-05-24 11:29
The issue is still present in the latest daily build as of today (for OsX, May 21, 2021, 11:26 a.m.). 

It can also be reproduced with a single fade transition:
1. Add two stills in succession on Track 1, snapping them end-to-beginning
2. Drag/drop a "fade" transition to start at the beginning of the first still
3. Extend the fade to cover the duration of both stills
4. Set the value of "brightness" to -1 at the beginning of the fade, 1 in the middle of the fade, and make sure it is -1 at the end of the fade
5. Play the clip in video preview

Expected: The first still fades out, and the second fades in
Actual: This happens, except for a brief moment when the first still has faded out, it blinks back in at full brightness, then blacks out again.

**Comment by JacksonRG** [comment] 2021-05-24 15:50
@troelsfrostholm I can take a look at this. In the mean time, It seems the leading solution is to extend the fade beyond the end of the first clip, and place the second on the track above.

**Comment by DanPinGF** [comment] 2021-11-30 23:11
Same for me. The workaround is to have the transition end immediately after the clip. I'm on Windows.

**Comment by DanPinGF** [comment] 2022-06-12 23:33
@JacksonRG - This issue still needs to be resolved.

**Comment by DanPinGF** [comment] 2022-07-10 22:13
@JacksonRG - This issue needs to be reopened because it has not been resolved.

**Comment by rexdk** [comment] 2022-07-11 06:10
@DanPinGF 
Sorry to tell you that bugs very rarely get fixed in OpenShot. I've given up reporting them - there's no point, as the bot closes them after a while.
I guess the developers would rather spend their (unpaid) time on 'interesting' new features, but it does mean frustration for the more knowledgeable user.

**Comment by JacksonRG** [comment] 2022-07-25 20:26
With a new change to openshot (currently in internal testing) I wasn't able to reproduce this issue. (In a project that did reproduce it otherwise)

 I'll leave a link here once it's in the daily build. And hope to hear if all of your examples are likewise fixed.

**Comment by JacksonRG** [comment] 2022-07-25 20:27
![](https://github.trello.services/images/mini-trello-icon.png) [Get confirmation PTS fixes fade out](https://trello.com/c/wmiXBfXl/155-get-confirmation-pts-fixes-fade-out)

**Comment by JacksonRG** [comment] 2022-09-16 17:51
@ragingwarthog Happy to say that my testing shows this bug has been fixed in the current daily build! If you see anything to the contrary, feel free to let me know!

**Closed by JacksonRG** 2022-09-16 17:51 UTC
Labels: :lady_beetle: bug
