### ISSUE TITLE
after update title function does not work on linux installation (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by sigrid1410** [OpenShot/openshot-qt#3296] opened 2020-03-17 15:17 UTC
**Beschreiben Sie den Fehler**
after update title function does not work on linux installation

**Schritte zum Reproduzieren des Verhaltens**
1. Gehe Sie nach kopfleiste'
2. Klicken Sie auftitle
3. wählen sie ein template aus
4. setzen sie einen Text ein
5. speichern sie die datei
6. offnen sie das texelement

**Erwartetes Verhalten**
der Text wird nicht in dem Template abgebildet.

außerdem:
- obwohl inkskape installiert ist, kann das Programm in advanced text modus nicht darauf zugreifen.

**Systemdetails**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.3.0-40-generic-x86_64-with-glibc2.2.5
- Processor: 
- Machine: x86_64
- Python version: 3.7.4
- Qt5 version: 5.14.1
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['de-DE']
- LANG Environment Variable: de_DE.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1584020922-816118b6-232f3f79-x86_64.AppImage

**Logdateien**
- http://logs.openshot.org/zadvhx84acgmcudilj6v8655uzfuum0n/openshot-qt.zip
- http://logs.openshot.org/zadvhx84acgmcudilj6v8655uzfuum0n/libopenshot.zip

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
Wenn möglich, fügen Sie Screenshots zur unterstützenden Erklärung Ihres Problems hinzu. Sie können Screenshots einfügen,
indem Sie diese kopieren und auf Github einfügen oder durch Drag and Drop zur GitHub-Seite hinzufügen. Alle Bilder sind öffentlich zugänglich, posten Sie deshalb keine Screenshots die persönliche Informationen enthalten.

**Comment by SuslikV** [comment] 2020-03-17 16:06
Please, after the click title from the main menu, press <kbd>Tab</kbd> key 3 times and hit <kbd>Enter</kbd>. Any changes in the project files?

**Comment by sigrid1410** [comment] 2020-03-17 18:40
dear SuslikV,
thank you for your instant responds and sorry for mixed languages. 
If I choose a template in TITEL the text would not appear on the preview nor in the saves svg file. 
Further on although INKSCAPE is installed the advanced title funktion can not open it. 
Thank you so much for your help, 
Sigrid
![Bildschirmfoto vom 2020-03-17 19-22-16](https://user-images.githubusercontent.com/62297790/76890116-0f03c380-6887-11ea-8e4e-b688b96bc2a7.png)

**Comment by SuslikV** [comment] 2020-03-17 19:28
And what fonts you can select?

**Comment by sigrid1410** [comment] 2020-03-18 08:18
I can select any font that is available in openoffice and all other
programs that use fonts.


_____________________________
http://goutal.blogspot.com
Ich möchte regelmäßig über Ihre Aktivitäten informiert werden
Newsletter Anmeldung <http://eepurl.com/dtoKyL>

Sigrid Goutal

Königsbrücker Landstr. 464, 01108 Dresden

Telefon: 0170/4788216, E-Mail: sigou01@gmail.com

UMSATZSTEUER-ID: 3202/224/07924





Am Di., 17. März 2020 um 20:28 Uhr schrieb SuslikV <notifications@github.com

**Comment by SuslikV** [comment] 2020-03-18 11:45
usually, Arial works well.

**Comment by sigrid1410** [comment] 2020-03-18 15:07
hello SuslikV,

Arial does  not work either. I have used many different fonts in OpenShot -
TITLE functions before.

Normally in the default settings you can see already the proposed text in
the display like "title1, title 2,...."
This is not the case.

I guess the text does not get transferred from the mask to the actual
display.

regards, Sigrid



_____________________________
http://goutal.blogspot.com
Ich möchte regelmäßig über Ihre Aktivitäten informiert werden
Newsletter Anmeldung <http://eepurl.com/dtoKyL>

Sigrid Goutal

Königsbrücker Landstr. 464, 01108 Dresden

Telefon: 0170/4788216, E-Mail: sigou01@gmail.com

UMSATZSTEUER-ID: 3202/224/07924





Am Mi., 18. März 2020 um 12:45 Uhr schrieb SuslikV <notifications@github.com

**Comment by ferdnyc** [comment] 2020-03-18 16:22
@sigrid1410 

I've just discovered that I'm experiencing the _same_ issue, with my local OpenShot install. I think I've discovered what's causing it — though not _why_, at least yet — and I seem to have hit on a stupid, stupid workaround.

When applications are started from the graphical launcher, at least on my Fedora 31 system, GNOME Shell appears to have started launching them inside a [bubblewrap](https://github.com/containers/bubblewrap) container. This sandboxing interferes with OpenShot's access to fonts, and its ability to launch Inkscape. 

```sh
$ ps -ef |grep openshot
ferd     3524911 2551228  0 12:21 ?        00:00:00 bwrap --args 35 openshot-qt
ferd     3524921 3524911  0 12:21 ?        00:00:00 bwrap --args 35 openshot-qt
ferd     3524922 3524921 28 12:21 ?        00:00:02 /usr/bin/python3 /app/bin/openshot-qt
```

(`/app/` is not a real path on my system, and represents the bubblewrap environment.)

The workaround, until we can figure out what's causing this, is to launch OpenShot from the command line directly (usually as just `openshot-qt`). That prevents the sandboxing and fixes the title editor functionality.

**Comment by ferdnyc** [comment] 2020-03-18 16:27
(If you're using an AppImage build, probably the same issue. I wouldn't be surprised if the AppImage mount gets pulled into `bwrap` as well. But running the AppImage directly from the command line should serve as a workaround for that as well.)

**Comment by sigrid1410** [comment] 2020-03-18 17:21
dear Frank,
thank you so much for your detailed explanations!
starting from command line works perfectly.
I can choose any font and i can even pass over to inkscape for advanced
editing.
Best regards
Sigrid
_____________________________
http://goutal.blogspot.com
Ich möchte regelmäßig über Ihre Aktivitäten informiert werden
Newsletter Anmeldung <http://eepurl.com/dtoKyL>

Sigrid Goutal

Königsbrücker Landstr. 464, 01108 Dresden

Telefon: 0170/4788216, E-Mail: sigou01@gmail.com

UMSATZSTEUER-ID: 3202/224/07924





Am Mi., 18. März 2020 um 17:23 Uhr schrieb Frank Dana <
notifications@github.com>:

**Comment by ferdnyc** [comment] 2020-03-18 18:05
**A-HAH!!!**

It seems the issue is that I unknowingly have the `flatpak` version of OpenShot installed, in addition to the native local package, so that's being launched instead. (In fact, it completely hides the one installed on my system, which is extremely annoying.)

```sh
$ flatpak list -v|grep OpenShot
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/ferd/.local/share/flatpak
OpenShot Video Editor	org.openshot.OpenShot	2.5.1	stable	system

$ ps -ef |grep bwrap
ferd     3537221 2551228  0 13:51 ?        00:00:00 bwrap --args 35 openshot-qt
ferd     3537231    1249  0 13:51 ?        00:00:00 bwrap --args 35 xdg-dbus-proxy --args=37
ferd     3537234 3537221  0 13:51 ?        00:00:00 bwrap --args 35 openshot-qt

$ flatpak ps    
Instance  PID     Application           Runtime
702053693 3537221 org.openshot.OpenShot org.kde.Platform
```

It's no great surprise that FlatPak's sandboxing prevents us from reaching Inkscape. Probably Blender, as well. A lot of how we use system resources is not particularly container-friendly.

So, if there's a native package or AppImage you want to use, the drastic workaround is probably to just `flatpak uninstall org.openshot.OpenShot`. It doesn't seem like there's a way to say "keep this around, just don't force me to use it by default." (Though I don't know flatpak well and may just be missing something.)

**Comment by ferdnyc** [comment] 2020-03-18 19:10
Looking at your attached log, it appears you were also running the Flatpak build, probably also inadvertently. The telltale `/app` path:
```
Setting font to /app/lib/python3.7/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
```

#### Developer notes
Hmm. I wonder if there's some way we can reliably detect the Flatpak environment, and just completely disable the Title Editor and Animated Title Editor functionality? (I don't necessarily mean _disappear_ them, but replace their non-functional interfaces with a message that explains that they're not operational inside the Flatpak sandbox.) Neither of them are going to work usefully, and unfortunately that's not something I expect to see fixed anytime soon. Applications launching whole other applications and communicating back and forth between them is, like, the antithesis of everything Flatpak is about.

**Comment by sigrid1410** [comment] 2020-03-18 19:18
Thank you Frank,

The uninstalling has completely solved the problem.

Thank you again for your engagement.
Best whishes
Sigrid

Frank Dana <notifications@github.com> schrieb am Mi., 18. März 2020, 20:10:

**Comment by ferdnyc** [comment] 2020-03-19 04:50
Though I'm tempted to keep this open (since as I mentioned above, I think we could handle this better), I'm going to close this as solved. Ultimately the issue was determined to be a local configuration problem, and while I'd _like_ to improve the situation, realistically it's not a priority right now.

Thanks for reporting, @sigrid1410, I'll be sure to keep this in mind for the future.

**Closed by ferdnyc** 2020-03-19 04:50 UTC

**Comment by gerhardbeck** [comment] 2020-04-12 16:50
@ferdnyc 
I have the same problem with todays daily appimage installed as well as the stable build. saving a title produces a correct svg in .openshot../title but doesn't use it in the programm.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4466689/openshot-qt.log)
![Bildschirmfoto von 2020-04-12 17-53-37](https://user-images.githubusercontent.com/41069802/79074723-4e8ac780-7cee-11ea-8664-e9a30f875e8b.png)

**Comment by eszlari** [comment] 2020-04-21 12:29
I fixed the issue with Inkscape/Blender (https://github.com/flathub/org.openshot.OpenShot/commit/1a2655d1dc37a2674e68ea2ce181a0e9ebf11f01)  and the fonts (https://github.com/flathub/org.openshot.OpenShot/commit/9ffbebc14f4b46c4b91b8884e418735f4b9c02ab).

Please file flatpak specific issues under: https://github.com/flathub/org.openshot.OpenShot/issues
