### ISSUE TITLE
Arrowhead's not showing

### ISSUE THREAD

**Issue by Hunteil** [OpenShot/openshot-qt#1924] opened 2018-07-29 00:06 UTC
**Describe the bug**
Used Inkscape and created a .svg title file and imported into project. During preview, the Arrowheads on my lines don't show up. But the lines do.

**System Details:**
 - Operating System: Windows 10
 - OpenShot Version: 2.4.2
 - Inkscape Version: 0.92.3

**To Reproduce**
1. In Inkscape, Shift+F6 (Draw Bezier curves and straight lines)
2. Picked two points. (created a straight line)
3. Shift+Ctrl+F (Fill and Strokes menu opens)
4. Leave fill tab the X option for no paint. Leave Stroke Paint tab flat color & pick color.
5. In the stroke style tab; At markers pick an arrowhead. (i picked the 9th one down)
6. Increase width of line so you can see it better.
7. Save as .svg. Import in Openshot and see arrowhead is missing.

**Expected behavior**
Arrowhead should show.

**additional info**
I'm not well versed in these programs. But I did watch some videos that showed me how to do this. Seems like a very simple thing.

Note: I did search for this bug on Google and found this webpage listing the issue. https://bugs.launchpad.net/openshot/+bug/1625033

**Comment by ferdnyc** [comment] 2018-07-29 09:39
This comes down to a limitation of the built-in Qt renderer that's currently used to display Title SVG files. QtSVG is a fairly simple renderer (by design), with support for only a limited subset of SVG features. Stroke marker styles is apparently not among them.

Contributor @N3WWN has been working on adding optional support for a new, more capable SVG renderer, ReSVG, to the `libopenshot` library at the heart of OpenShot. (That work is [libopenshot PR #143](https://github.com/OpenShot/libopenshot/pull/143).) Once it's available, versions of OpenShot which have been built with ReSVG will do a vastly better job displaying titles in the same manner they were designed.

Unfortunately, because the current limitation is in the QtSVG renderer itself, there's nothing we can do to fix the _existing_ title rendering. Qt does not consider QtSVG's shortcomings to be a defect, as they never intended it to be a full-featured SVG renderer. 

So, as things stand right now, the only solution is to avoid using unsupported SVG features like stroke marker styles, when creating OpenShot title files. If the arrowheads are a critical part of the design and can't be omitted, you could try creating them yourself as vector graphic objects placed at the ends of the lines. That way they should render properly in the titles.

Afraid for right now that's the best we can offer, due to the limitations of the QtSVG library. Sorry!

**Comment by peanutbutterandcrackers** [comment] 2018-07-30 04:14
Closing this as answered, as a dup of other issues regarding SVG renderings, and as fix is in progress.

**Closed by peanutbutterandcrackers** 2018-07-30 04:14 UTC

**Comment by Hunteil** [comment] 2018-08-07 23:05
Looks like this isn't just a limitation of the preview. I went ahead and used a blur effect behind my words to create a better contrast. Then I exported my video and openshot ignored the blur effect. :-(

**Comment by ferdnyc** [comment] 2018-08-08 00:09
It's definitely not just the preview. As I said, it's a limitation of the SVG renderer itself. QtSVG only supports the [SVG Tiny](http://www.loc.gov/preservation/digital/formats/fdd/fdd000043.shtml) spec, a restricted subset of SVG.
> According to [Adobe Illustrator Help -- Saving artwork: Save in SVG format](https://helpx.adobe.com/illustrator/using/saving-artwork.html#save_in_svg_format), SVG Tiny does not support gradients, transparency, clipping, masks, symbols, patterns, underline text, strike through text, vertical text, or SVG filter effects.

(Pretty sure Adobe's list is very out of date. They left out at least "markers", but OTOH certain simple gradients and basic alpha transparency _are_ supported. Their power/flexibility is greatly reduced in SVG Tiny, though.)

**Comment by Hunteil** [comment] 2018-08-08 14:33
Makes me wonder if I should use a different  format? (I'm a newbie, just trying to make this wood building tutorial look nice lol)

**Comment by DylanC** [comment] 2018-08-08 14:51
@Hunteil - Maybe make what you need in SVG and export to png?
