### ISSUE TITLE
Appimage segmentation fault

### ISSUE THREAD

**Issue by proDOOMman** [OpenShot/openshot-qt#166] opened 2016-04-22 17:39 UTC
$ ./OpenShot-2.0.7.AppImage
/tmp/.mount_iDc1AD/usr/bin/openshot-qt.wrapper
/home/prodoomman/.cache/thumbnails/normal/af1bed3c54cace80ab1f1f50d770fcbb.png is missing. Please run ./bin//openshot-qt.wrapper from within an AppImage.
Loaded modules from current directory: /tmp/.mount_iDc1AD/usr/bin
[1]    5593 segmentation fault (core dumped)  ./OpenShot-2.0.7.AppImage

$ uname -a
Linux chronothug 4.5.0-2-MANJARO #1 SMP PREEMPT Wed Mar 16 04:25:52 CET 2016 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        15.12
Codename:       Capella

Strace log: http://pastebin.com/i3re8E6n
Gdb log: http://pastebin.com/4n9nhppC

**Comment by jonoomph** [comment] 2016-04-22 19:48
Hmmm, not sure what is happening. It's probably missing a .SO file if I had to guess. I have not tested against Manjaro Linux 15.12, but I'll give it a try and see if I can reproduce this issue. =)

**Comment by jonoomph** [comment] 2016-04-22 19:54
I think the error referring to /home/prodoomman/.cache/thumbnails/normal/af1bed3c54cace80ab1f1f50d770fcbb.png is related to Nautalus thumbnail caching... and not related to OpenShot.

**Comment by jonoomph** [comment] 2016-04-22 21:50
Okay, I gave it a try on Manjaro 15.12, and it reports a missing library: **libgtk-x11-2.0.so.0**. So, either I need to prepackage this library (and it's dependencies) into the AppImage, or you need to find a way to install that package. =)

**Comment by jonoomph** [comment] 2016-04-22 23:10
This might be related to https://github.com/OpenShot/openshot-qt/issues/163

**Comment by proDOOMman** [comment] 2016-04-23 06:05
I haven't nautilus installed.
And I have libgtk-x11-2.0.so.0:
$ file /usr/lib/libgtk-x11-2.0.so.0
/usr/lib/libgtk-x11-2.0.so.0: symbolic link to libgtk-x11-2.0.so.0.2400.30
$ file /usr/lib/libgtk-x11-2.0.so.0.2400.30 
/usr/lib/libgtk-x11-2.0.so.0.2400.30: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d9b4c82d4b7fc5ab512bc62089b9a30038ac5902, stripped
$ ./OpenShot-2.0.7.AppImage
/tmp/.mount_DWVqor/usr/bin/openshot-qt.wrapper
/home/prodoomman/.cache/thumbnails/normal/af1bed3c54cace80ab1f1f50d770fcbb.png is missing. Please run ./bin//openshot-qt.wrapper from within an AppImage.
Loaded modules from current directory: /tmp/.mount_DWVqor/usr/bin
[1]    2376 segmentation fault (core dumped)  ./OpenShot-2.0.7.AppImage

How do you check missing libraries? I want to try it on my own system.

**Comment by bardok** [comment] 2016-04-24 09:38
Hello,

i've got a similar problem under Manjaro 15.12 : 

└─ $ ▶ ./OpenShot-v2.0.7-18-g68d44e1-47-533-x86_64.AppImage 
/tmp/.mount_hubr32/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_hubr32/usr/bin
Erreur de segmentation (core dumped)

└─ $ ▶ uname -a
Linux Alphonse 4.5.0-2-MANJARO #1 SMP PREEMPT Wed Mar 16 04:25:52 CET 2016 x86_64 GNU/Linux

└─ $ ▶ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	15.12
Codename:	Capella

└─ $ ▶ file /usr/lib/libgtk-x11-2.0.so.0
/usr/lib/libgtk-x11-2.0.so.0: symbolic link to libgtk-x11-2.0.so.0.2400.30

**Comment by nikmartin** [comment] 2016-05-05 12:26
on arch linux, I just get: 

```
(1:2057)$ ./OpenShot-2.0.7.AppImage 
/tmp/.mount_JE6Etg/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_JE6Etg/usr/bin
Segmentation fault (core dumped)
```

**Comment by owlbrudder** [comment] 2016-07-03 07:09
Under Fedora 24, I see a long list of INFO and other statements, then this:
```
project_data:INFO Setting default profile to HDV 720 24p
Segmentation fault (core dumped)
```
It is a shame, because the application could solve a problem for me. Any suggestions for a work-around would be appreciated.

**Comment by obilodeau** [comment] 2016-07-27 19:11
This is still a problem on the latest builds:
```
$ ~/opt/OpenShot-v2.0.7-31-g1dad240-47-535-x86_64.AppImage --help
/tmp/.mount_VztCEq/usr/bin/openshot-qt.wrapper
Loaded modules from current directory: /tmp/.mount_VztCEq/usr/bin
Segmentation fault (core dumped)
```

It would be nice to have a way to unpack the AppImage and debug the ELF more directly.

Last few lines of strace gives:
```
open("/tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0", O_RDONLY|O_CLOEXEC) = 6</tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0>
read(6</tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0>, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\321\0\0\0\0\0\0"..., 832) = 832
fstat(6</tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0>, {st_mode=S_IFREG|0644, st_size=268368, ...}) = 0
mmap(NULL, 2364496, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 6</tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0>, 0) = 0x7f3e6f992000
mprotect(0x7f3e6f9cd000, 2093056, PROT_NONE) = 0
mmap(0x7f3e6fbcc000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 6</tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0>, 0x3a000) = 0x7f3e6fbcc000
close(6</tmp/.mount_xW5QJL/usr/bin/libp11-kit.so.0>) = 0
mprotect(0x7f3e6fbcc000, 24576, PROT_READ) = 0
mprotect(0x7f3e6fde6000, 4096, PROT_READ) = 0
mprotect(0x7f3e70064000, 4096, PROT_READ) = 0
mprotect(0x7f3e704c8000, 4096, PROT_READ) = 0
mprotect(0x7f3e706d6000, 4096, PROT_READ) = 0
mprotect(0x7f3e70935000, 4096, PROT_READ) = 0
mprotect(0x7f3e70b8d000, 4096, PROT_READ) = 0
mprotect(0x7f3e70da1000, 4096, PROT_READ) = 0
mprotect(0x7f3e70fc3000, 4096, PROT_READ) = 0
mprotect(0x7f3e7120b000, 4096, PROT_READ) = 0
mprotect(0x7f3e714cd000, 8192, PROT_READ) = 0
mprotect(0x7f3e716e8000, 4096, PROT_READ) = 0
mprotect(0x7f3e71901000, 4096, PROT_READ) = 0
mprotect(0x7f3e71b41000, 4096, PROT_READ) = 0
mprotect(0x7f3e71d5e000, 4096, PROT_READ) = 0
mprotect(0x7f3e71f73000, 4096, PROT_READ) = 0
mprotect(0x7f3e72672000, 4096, PROT_READ) = 0
mprotect(0x7f3e729b9000, 4096, PROT_READ) = 0
mprotect(0x7f3e72ce3000, 24576, PROT_READ) = 0
mprotect(0x7f3e72f03000, 4096, PROT_READ) = 0
mprotect(0x7f3e731ed000, 28672, PROT_READ) = 0
mprotect(0x7f3e73402000, 4096, PROT_READ) = 0
mprotect(0x7f3e73657000, 16384, PROT_READ) = 0
mprotect(0x7f3e75718000, 8192, PROT_READ) = 0
mprotect(0x7f3e73876000, 4096, PROT_READ) = 0
mprotect(0x7f3e73abd000, 4096, PROT_READ) = 0
mprotect(0x7f3e74274000, 77824, PROT_READ) = 0
mprotect(0x7f3e74b22000, 32768, PROT_READ) = 0
mprotect(0x7f3e754b5000, 151552, PROT_READ) = 0
mprotect(0x7f3e75a95000, 12288, PROT_READ) = 0
mprotect(0x7f3e75e84000, 12288, PROT_READ) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1b20} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by RealCh4mp** [comment] 2016-08-30 18:51
it still doesn't work with the latest 2.1.0

**Comment by sydneyjd** [comment] 2016-09-06 00:45
Yep, same issue here on Arch Linux, even though it seems to happen on a number of diferent Distros. 

-Sydney

**Comment by mep-mep** [comment] 2016-09-29 12:32
Same here Fedora 24,no way to install 2.1.0 (segmentation fault  for Appimage) ,  2.0.7 cannot import mp3 with continuous chrashes.

**Comment by patanric** [comment] 2016-12-06 13:53
same here on Ubuntu 16.04 LTS:
[...]
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO foundCurrentVersion: Found the latest version: 2.1.0
effects_model:INFO updating effects model.
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
effects_model:INFO category: Video
properties_model:INFO updating clip properties model.
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:INFO Clear all thumbnails: /home/riccardo/.openshot_qt/thumbnail
 main_window:INFO Clear all animations: /home/riccardo/.openshot_qt/blender
 main_window:INFO Clear all backups: /home/riccardo/.openshot_qt/backup
project_data:INFO Setting default profile to HDV 720 24p
**Segmentation fault (core dumped)**


I already had libgtk2.0-0 and I additionally installed libgtk2.0-0-dbg. But still not working.
Any workaround?

Thanks!

**Comment by dirkk** [comment] 2016-12-17 13:22
Same problem persists on Fedora 25.

**Comment by ankitpati** [comment] 2017-03-01 00:31
Dupe of #240.

**Closed** 2017-03-03 22:34 UTC
Labels: duplicate
