### ISSUE TITLE
Windows: not the project is automatically saved

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#49] opened 2016-01-20 16:55 UTC
In the version 14 openshot in Might save preferences automaitcamente 1 min each project or each time you gave the play the video. If there is an error erros the project is not saved. In the Windows version it is not possible to put the option to automatically save.

**Comment by telelauro** [comment] 2016-01-22 10:45
In version 14 openshot in Might save preferences automaitcamente 1 min each project or each time you gave the play the video. If there is an error erros the project is not saved. In the Windows version it is not possible to put the option to automatically save.

**Comment by nwgat** [comment] 2016-01-22 15:21
same as https://github.com/OpenShot/openshot-qt/issues/45

**Comment by telelauro** [comment] 2016-01-22 17:50
yes escuse me... its teh same problem... did you want to post out this one?

**Comment by jonoomph** [comment] 2016-02-07 06:10
Duplicate of https://github.com/OpenShot/openshot-qt/issues/45

**Closed by jonoomph** 2016-02-07 06:10 UTC
