### ISSUE TITLE
Is here any option to change the video screen ratio?

### ISSUE THREAD

**Issue by kodosalbion** [OpenShot/openshot-qt#1568] opened 2018-05-07 11:06 UTC
I imported a video with a 4:3 ratio and would like to save the project with a 16:9 ratio. Any help will be appreciated.

**Comment by N3WWN** [comment] 2018-05-07 13:53
@DylanC Possible dupe of  :

#456
#731
#835
#1093 (item # 4)
#1144
#1402
and
#1427 

?

Essentially, the preview window appears to be somewhat locked to a 16:9 aspect ratio at this time.  The solution isn't as straight-forward as I once thought as a PR that I submitted does not work for all cases and will require quite a bit more work.

**Comment by DylanC** [comment] 2018-05-08 08:01
Dup of #456 and many other similar issues reported.

**Closed** 2019-11-22 21:27 UTC
Labels: duplicate
