### ISSUE TITLE
Turn off video &/or sound for entire clip

### ISSUE THREAD

**Issue by TrueBlueFrog** [OpenShot/openshot-qt#3348] opened 2020-04-05 08:15 UTC
With the old version of Openshot a simple click could turn on or off either the video or sound of any clip, no such function exists now! The use of "Alpha" causes fades! This is very frustrating. This new version is also very prone to crashing, I have 32GB RAM and it seems that even this is no sufficient. A very disappointing "upgrade".

**Comment by SuslikV** [comment] 2020-04-05 14:36
Per clip - the _Property_ exist (_Enable Audio_ or _Enable Video_). Not click-button, but full property. As per track - not yet...

**Comment by ferdnyc** [comment] 2020-04-06 11:54
As @SuslikV says, the 'Enable Audio' and '...Video's properties provide the same functionality, at the cost of an extra click or two.

Actually, they're more flexible, since you can use keyframes to disable audio or video for only selected parts of any clip's runtime.

There's an open request for per-track muting (of either stream), I don't have the reference at hand right now, but closing this as a duplicate of that existing request.

**Closed by ferdnyc** 2020-04-06 11:54 UTC
Labels: 💡 enhancement
