### ISSUE TITLE
Openshot 2.1 Will always seg falt apon exiting.

### ISSUE THREAD

**Issue by firew4lker** [OpenShot/openshot-qt#290] opened 2016-08-30 14:49 UTC
Every time I exit Openshot, it will seg fault.

preview_thread:INFO onModeChanged
Segmentation fault (core dumped)

Latest bzr version Openshot on Archlinux 32-bit.

**Comment by firew4lker** [comment] 2016-08-30 15:20
PID: 21166 (python3)
           UID: 1000 (koko)
           GID: 100 (users)
        **Signal: 11 (SEGV)**
     Timestamp: Tue 2016-08-30 18:18:26 EEST (31s ago)
  Command Line: python3 ./launch.py
    Executable: /usr/bin/python3.5
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (koko)
       Boot ID: 
    Machine ID: 
      Hostname: lala
      Coredump: /var/lib/systemd/coredump/core.python3.1000.lz4
       Message: Process 21166 (python3) of user 1000 dumped core.
                
                Stack trace of thread 21166:
                #0  0x0000000099051c30 n/a (oxygen.so)
                #1  0x000000009901aadf n/a (oxygen.so)
                #2  0x000000009904925a n/a (oxygen.so)
                #3  0x00000000b5fbc1f0 _ZN13QStyleFactory6createERK7QString (libQt5Widgets.so.5)
                #4  0x00000000b5fe3fb3 n/a (libQt5Widgets.so.5)
                #5  0x00000000b5fe4b36 _ZN11QProxyStyle5eventEP6QEvent (libQt5Widgets.so.5)
                #6  0x00000000b5f4420a _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #7  0x00000000b5f4c09c _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #8  0x00000000b66e97a3 n/a (QtWidgets.so)
                #9  0x00000000b567417d _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #10 0x00000000b56a95dc _ZN14QObjectPrivate16setParent_helperEP7QObject (libQt5Core.so.5)
                #11 0x00000000b56a9dac _ZN7QObjectD1Ev (libQt5Core.so.5)
                #12 0x00000000b5fb9cc4 _ZN6QStyleD1Ev (libQt5Widgets.so.5)
                #13 0x00000000b5fc36e4 _ZN12QCommonStyleD2Ev (libQt5Widgets.so.5)
                #14 0x00000000a26257e8 _ZN6KStyleD1Ev (libKF5Style.so.5)
                #15 0x000000009902bb6e n/a (oxygen.so)
                #16 0x00000000b56a1f0e _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #17 0x00000000b56a23fd _ZN11QMetaObject8activateEP7QObjectPKS_iPPv (libQt5Core.so.5)
                #18 0x00000000b56a24c9 _ZN7QObject9destroyedEPS_ (libQt5Core.so.5)
                #19 0x00000000b56a9803 _ZN7QObjectD1Ev (libQt5Core.so.5)
                #20 0x00000000b5fc0794 _ZN12QStylePluginD1Ev (libQt5Widgets.so.5)
                #21 0x0000000099049365 n/a (oxygen.so)
                #22 0x00000000b5668e8a n/a (libQt5Core.so.5)
                #23 0x00000000b565e534 n/a (libQt5Core.so.5)
                #24 0x00000000b565e65a n/a (libQt5Core.so.5)
                #25 0x00000000b56a9dc3 _ZN7QObjectD1Ev (libQt5Core.so.5)
                #26 0x00000000b565da1f _ZN14QFactoryLoaderD1Ev (libQt5Core.so.5)
                #27 0x00000000b5fbe2c8 n/a (libQt5Widgets.so.5)
                #28 0x00000000b72838cb __run_exit_handlers (libc.so.6)
                #29 0x00000000b7283931 exit (libc.so.6)
                #30 0x00000000b754a3e0 Py_Exit (libpython3.5m.so.1.0)
                #31 0x00000000b754d62c n/a (libpython3.5m.so.1.0)
                #32 0x00000000b754d9f5 PyErr_PrintEx (libpython3.5m.so.1.0)
                #33 0x00000000b754dc16 PyErr_Print (libpython3.5m.so.1.0)
                #34 0x00000000b754eea5 PyRun_SimpleFileExFlags (libpython3.5m.so.1.0)
                #35 0x00000000b754efb7 PyRun_AnyFileExFlags (libpython3.5m.so.1.0)
                #36 0x00000000b7566a8e Py_Main (libpython3.5m.so.1.0)
                #37 0x0000000008048896 main (python3.5)
                #38 0x00000000b726d196 __libc_start_main (libc.so.6)
                #39 0x0000000008048938 _start (python3.5)

**Comment by ankitpati** [comment] 2017-03-01 00:21
Dupe of #177.

Closing because that issue identifies another possible segmentation fault in addition to the one at exit.

**Closed by ankitpati** 2017-03-01 00:21 UTC
Labels: duplicate
