### ISSUE TITLE
macOS + ARM64 builds

### ISSUE THREAD

**Issue by verhovsky** [OpenShot/openshot-qt#5379] opened 2023-12-15 20:34 UTC
On the website, for macOS you seem to only distribute x86-64 builds for macOS, but my laptop uses the newer Apple silicon, which is ARM64, not x86-64, although it can almost certainly run the x86-64 app as well, but it adds overhead.

**Comment by coffeemonk** [comment] 2024-12-30 03:41
This appears to be a duplicate of #5258

**Closed as completed** 2024-12-30 04:31 UTC
Labels: 💡 enhancement
