### ISSUE TITLE
Memory usage grows and grows during editing and rendering. V2.4.3

### ISSUE THREAD

**Issue by rekcodocker** [OpenShot/openshot-qt#2165] opened 2018-09-28 16:00 UTC
**Describe the bug**
Memory usage seems excessive both during editing and during rendering.
I am working on a small clip of 3 minutes raw material, cut down to 71 seconds with a considerable number of cuts (>20).
During editing, memory usage grows and grows. It never goes down, only up.  
I need to stop OpenShot and start it again before rendering.
During rendering, same thing. It starts with memory usage low but it keeps using more and more memory. 

**System Details (please complete the following information):**
Linux Mint v 19
Openshot 2.4.3

**To Reproduce**
simple 50fps Full HD with lots of cuts, a few fades, no other transitions.

**Expected behavior**
If OpenShot can operate and render fine without using 8GB of RAM, I would expect it to keep the memory usage down during usage and rendering. 

**Screenshots**

**Logs**
Not available. I have had crashes (system crashes!) because all memory was consumed. No logs.

**Additional context**
Willing to share the material + project if necessary but really, I am not doing anything special. I'm just cutting, cutting, cutting and rendering.

**Comment by LeosWelt** [comment] 2018-10-02 19:37
I have checked with Open Shot and other Video Editing-solutions (Linux).
On Open Shot, a video render of some 4K-files about 9 minutes in length to a 3-minute video uses all 16GB of my acaillable ram. The ram ist still used when rendering is finished.
All other tested editors do the same: consume much RAM, have tested KDEnlive, Flowblade.
Only Open SHot can use my 6 kernels/12 threads when rendering.
I believe the problem is in the used librariers (like melt), and not the program itself.

**Comment by lebrat-jpl** [comment] 2019-09-13 14:19
Problem remains in V2.4.4.
Environment : Kubuntu 18.10.

**Comment by SuslikV** [comment] 2019-09-14 07:36
@lebrat-jpl the major memory leakage that was mentioned by topic starter was solved in OpenShot 2.4.4 (https://github.com/OpenShot/libopenshot/pull/240), thus by using recent build it shouldn't bother you any more (select _Daily Builds_: https://www.openshot.org/download/). Single 4K frame is about 23.7 Mbytes of RAM (RGB format), if video filmed at 60 fps, then 1 second of footage is about 1 422 MBytes of RAM. Video Editor uses uncompressed RGB format to make the edit possible. More cores - more threads - more compositions - more frames are uncompressed - more RAM required.

Please, fill out new issue if you'll find something new (don't forget to attach your logs).

**Comment by lebrat-jpl** [comment] 2019-09-15 05:37
Thanks a lot for your clarification (so, yesterday, I donated for OpenShot
!).
In fact I already ran OpenShot V2.4.4, but I didn't realize the required
RAM amount.
Do you confirm (Rough Order of Magnitude only) that a 15 minutes video,
configured as "HD 1080p 30 fps Medium Quality", requires about 30 Go of
memory (RAM + Swap) ?
Faithfully,
Jean-Philippe

**Comment by ferdnyc** [comment] 2019-10-05 21:25
@lebrat-jpl 

@SuslikV was mistaken or unclear (I'm not sure which, myself :wink: ) — OpenShot/libopenshot#240 wasn't merged until May 30, well after the release of OpenShot 2.4.4 (which was in March). So, **only** the Daily Builds would currently include that fix. The memory usage of recent builds should be much more reasonable than in 2.4.4.

> Do you confirm (Rough Order of Magnitude only) that a 15 minutes video, configured as "HD 1080p 30 fps Medium Quality", requires about 30 Go of memory (RAM + Swap) ?

Not _generally_, no, as the entire output video isn't kept in memory at once. The issue with OpenShot 2.4.4 was, the more separate _clips_ you have in your project, the more memory the export required (due to an issue with not properly freeing the storage for each input file).

The memory required by the export process is difficult to estimate in real-world  terms, it's a function of the input _and_ output video parameters, quality, etc. As well as being multiplied by the number of threads running (each one has its own buffers), so on a 12-core machine the memory requirements are definitely considerable. I run a 4-core machine with 8GB of RAM and that can be tight, so triple the cores but only double the RAM is definitely a concern.

Another advantage the OpenShot Daily Builds bring is, the Performance tab in Preferences has new options to adjust the number of threads used during the encoding process. So, if memory exhaustion is still an issue, you may have to dial the thread count back a bit to keep the memory usage down. Which at least is **possible**, in the newer builds.

**Comment by lebrat-jpl** [comment] 2019-10-08 05:34
Thanks a lot for all of these explanations (I specially re-partitionned my
HDD (in ordre to extend the swap) to produce a video) !
And thanks for OpenShot development (I support) !

Good morning !

**Closed** 2020-02-01 13:35 UTC
