### ISSUE TITLE
Toolbar icons gone in latest daily build...

### ISSUE THREAD

**Issue by nanohtpc** [OpenShot/openshot-qt#2894] opened 2019-07-27 01:41 UTC
**Describe the bug:**
after update.., all icons are gone in toolbar and in timeline...

have to downgrade to :

OpenShot-v2.4.4-dev2-1563230139-ed4b32d4-7939e156-x86_64

**Comment by ferdnyc** [comment] 2019-07-27 01:48
@nanohtpc Which OS are you reporting this issue on? Everything looks fine with the Linux AppImage:

![image](https://user-images.githubusercontent.com/538020/61988423-fc363900-afee-11e9-99a9-116faff97be9.png)

**Comment by ferdnyc** [comment] 2019-07-27 01:51
(Actually, I'll be even more specific: What's the filename of the download where you _had_ the issue?)

**Comment by nanohtpc** [comment] 2019-07-27 02:22
Win10 x64

the last two builds after you change the installer...

**Comment by ferdnyc** [comment] 2019-07-27 02:53
Thanks @nanohtpc , can confirm after installing `OpenShot-v2.4.4-dev2-1564165829-769efd87-574877b9-x86_64.exe (64-bit)` in a Windows 7 VM:

![image](https://user-images.githubusercontent.com/538020/61989094-27715600-aff8-11e9-8a71-5cd22d612915.png)

**Comment by ferdnyc** [comment] 2019-07-27 03:00
@jonoomph 

The issue appears to be a missing `QtSvg.dll` (or I guess `lib/QtSvg.dll`), which is not being packaged, despite still being needed to render the SVG-format interface icons.

Also, I'm seeing two copies of the `QtCore.dll` file now, one in the root install directory, a second in `lib/`.

**Comment by jonoomph** [comment] 2019-07-27 05:23
Still working on the latest windows builds... it might be a few more days before this is resolve. Thx.

**Comment by ferdnyc** [comment] 2019-07-27 05:26
Current status: "New builder, who dis?"

**Comment by SuslikV** [comment] 2019-07-27 19:14
> ..."New builder, who dis?"

@ferdnyc can you explain what exactly this phrase means? (just a linguistic question)

**Comment by ferdnyc** [comment] 2019-07-27 20:09
@SuslikV 

Oh, that's just me riffing on "[New phone, who dis?](https://www.reddit.com/r/OutOfTheLoop/comments/695ui7/where_does_new_phone_who_dis_come_from/)"

**Comment by ferdnyc** [comment] 2019-07-27 22:12
I eventually discovered that all of the Qt DLLs, including `Qt5Svg.dll`, _are_ actually present in the installation. It's just that they've all ended up inside the `lib/PyQt5/` subdirectory! 

(Manually copying all of them to the root of the installation is my current untested, purely-theoretical approach to fixing the affected builds. It'd be great if someone wanted to test out that theory and report back with their results.)

**Comment by nanohtpc** [comment] 2019-07-28 02:01
i can confirm that works... for now...

**Comment by SuslikV** [comment] 2019-07-28 09:59
I personally, for my own builds of OpenShot, ended up in moving (with overwrite) all .dll files (but the `imageformats` and `platforms` folders - these are hardcoded) to the root of the original launch.exe file.

**Comment by ferdnyc** [comment] 2019-07-28 11:26
> i can confirm that works... for now...

 Excellent, thanks for testing @nanohtpc

@SuslikV Yeah, that's pretty much the "Windows way". The irritating thing is that cx_Freeze is meant to be sorting this stuff out, and it's just not doing as good a job as it should be with the dependencies, especially once they get up to a couple of levels of indirection. (e.g.: The Qt DLLs aren't direct OpenShot dependencies. The various PyQt modules are, and the Qt DLLs are dependencies of those modules. A couple of them, but not all, are **also** dependencies of libopenshot, so it's possible that's complicating things for cx_Freeze.)

Whether we're just not using cx_Freeze correctly, or we're putting other things in places it doesn't expect, or if these are just bugs in cx_Freeze itself... that's still not quite clear.)

**Comment by ferdnyc** [comment] 2019-07-28 11:34
I think part of the problem is the existence of a `lib/` directory, which is very un-Windows. Maybe I should try making that change to install `libopenshot.dll` into the `bin/` directory (aka the "RUNTIME INSTALL" path), which is where it really belongs on Windows. cx_Freeze might deal with that better.

**Comment by jonoomph** [comment] 2019-07-28 21:49
Working on a fix now: https://github.com/OpenShot/openshot-qt/issues/2894

**Comment by jonoomph** [comment] 2019-07-28 22:06
This is fixed now.. it should be in the next daily build (maybe in 30 minutes to an hour). Please reopen if you still have this issue. Thx!

**Closed by jonoomph** 2019-07-28 22:06 UTC
Labels: bug, packaging
