### ISSUE TITLE
Feature request: being able to disable the video in a video clip

### ISSUE THREAD

**Issue by LievenHanssen** [OpenShot/openshot-qt#1260] opened 2018-02-08 20:26 UTC
**System Details:**
* Operating System / Distro: 
* OpenShot Version: 2.4.1-dev1

**Issue Description and steps to reproduce:**
In the 1.4-series of OpenShot you were able to disable the audio and video of a clip with a click of the mouse, just as you can see in the screenshot below.
![afbeelding](https://user-images.githubusercontent.com/1892965/35996306-737a786e-0d16-11e8-9528-ffee33223141.png)
I recently [filed a bug](https://github.com/OpenShot/openshot-qt/issues/1257) because of this and found a workaround, but I would very much like to see this feature reimplemented.

**Comment by N3WWN** [comment] 2018-02-08 21:14
Have you tried using the `Enable Video` and `Enable Audio` properties for the clips?  I know it's not quite a single click of the mouse, but it's close. 😁

**Comment by peanutbutterandcrackers** [comment] 2018-02-11 12:11
@LievenHanssen - No, we do not have that feature (back) as of yet... perhaps in the (very near, hopefully) future?

@DylanC - Duplicate of #1202 ?

**Comment by DylanC** [comment] 2018-02-11 12:15
@peanutbutterandcrackers - Yes, Dup of 1202.

**Comment by ferdnyc** [comment] 2019-07-21 09:45
I'm confused about why this was characterized as unsupported: As @N3WWN had said even back then, what about setting the clip's "Enable Video" property to `0`? That's meant to have the exact effect requested here.

Now, it turns out there _does_ seem to be a... quirk... with that (OK, it's a bug), in that when I tried this with the top clip of two that I had on different tracks of the Timeline, I ended up with this:

![image](https://user-images.githubusercontent.com/538020/61589583-1ea4fe00-ab7a-11e9-879a-e1d3f960ebab.png)

...But the workaround there was to **also** set Scaling to "None", at which point the black rectangle disappeared and I was able to see the bottom clip without any interference from the video-disabled upper one.

So, in at least OpenShot 2.4.4 (and surely earlier versions too), the not-quite-a-single-click equivalent of the feature requested is:

1. Move the Playhead to the first frame of the Clip in question, and select it
2. Change the "Enable Video" property from `-1` (the default) to `0`
3. Change the "Scale" property from "Best Fit" (the default) to "None"

And, done.

**Closed** 2019-11-22 21:38 UTC
Labels: duplicate, interface, workaround, 💡 enhancement
