### ISSUE TITLE
Unresponsive tutorial popup

### ISSUE THREAD

**Issue by Petar-np** [OpenShot/openshot-qt#714] opened 2017-06-06 12:41 UTC
**System Details:**
* Operating System / Distro: Arch Linux 4.11.3-1-ARCH (Lenovo Thinkpad L560)
* OpenShot Version: 2.3.4

**Issue Description**
I just started application for the first time and tutorial window showed up. But when I click on "Next" or "Hide Tutorial" buttons nothing happens, it just blinks. I launched application again and actually this time Next button worked, but only once, at the second step of the tutorial problem continued. I am pressing again and all it does is blinking

**Steps to reproduce:**
Just quit and start application again or select tutorial from drop down menu in help section

**Comment by openpianist** [comment] 2017-06-06 16:52
the Tutorial works on my system.

    Operating System / Distro: Linux **Ubuntu 17.04** (Lenovo Thinkpad **T440**)
    OpenShot Version: 2.3.4


- O.

**Comment by Sunno** [comment] 2017-06-23 01:48
I have the same problem, using manjaro linux

**Comment by DarrenCook** [comment] 2017-06-28 12:24
I had same problem (Mint 18.1, xfce)
What worked was "click-drag-release" inside the next button.

**Comment by dogfish12** [comment] 2017-07-15 15:46
Hi what I found to work for removing the tutorial permanent was using alt right arrow and left click to highlight  hide or next  when the programe its self and tutorial are flashing and unresponsive  left  click
take mouse arrow top of the software and turn arrow in to hand and release this will make it responsive keep pressing hide or next. on the difference stages of the tutorial pop up  it will stop it.  Next time you start the programe the pop tutorial will be gone  no more annoying  pop up  joy oh joy

**Comment by DylanC** [comment] 2017-08-28 10:35
Dup of #307

**Comment by DylanC** [comment] 2017-11-19 07:17
Unable to reproduce.

**Comment by meoso** [comment] 2018-01-28 18:46
Same for me on Ubuntu 17.10 after `rm -rf .openshot_qt/`.
Was forced to edit `~/.openshot_qt/openshot.settings` modifying `"setting": "tutorial_enabled", "value": false`

**Comment by Moonbase59** [comment] 2018-03-21 09:20
Same here on Ubuntu Studio 14.04.5, OpenShot Version 2.4.1-dev1.
@meoso’s tip (editing openshot.settings) helped, thanks a bundle!

**Comment by peanutbutterandcrackers** [comment] 2018-07-02 04:49
Hey there! Could you all please try [this build](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN) that incorporates the changes from the PR by @ferdnyc? This issue has, hopefully, been resolved. And if you give confirm it as resolved, we can go ahead and merge the changes into the main source. Thanks!

**Comment by meoso** [comment] 2018-07-02 14:14
@peanutbutterandcrackers  sorry i cannot test windows exe, only linux tarball or AppImage

**Comment by peanutbutterandcrackers** [comment] 2018-07-03 02:46
The following are the beta-builds that contain the changes made to resolve this issue (PR #1726 by the awesome @ferdnyc). Please try them out and report whether this resolves the issue. Thanks!
1. [Windows Builds](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN)
2. [Mac Builds](https://drive.google.com/open?id=10zy1SQz6gGCxfmYZtMnTYHkC5NBQy6Oz)
3. [Linux Builds](https://drive.google.com/open?id=10D6BIF_n8krpYB-goNQ7jj4W33OSv4Yg)

**Comment by meoso** [comment] 2018-07-06 13:09
Success.
Preformed `rm -rf .openshot_qt/`
and ran `OpenShot-v2.4.1-180-gfdd5e96-2f45a4eb-f32c7c30-x86_64.AppImage`
and was able to navigate & hide the tutorial dialog.
`Linux 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.12-1~bpo9+1 (2018-06-03) x86_64 GNU/Linux`

**Comment by ferdnyc** [comment] 2018-07-06 13:31
\o/

Great, thanks @meoso ! That's good news.

Now if I can just figure out why the background isn't transparent on XFCE (#1708)...

**Comment by meoso** [comment] 2018-07-06 14:14
i run XFCE if you need testing on weekdays CST only.

**Comment by ferdnyc** [comment] 2018-07-06 14:18
> i run XFCE if you need testing on weekdays CST only.

@meoso — Please! That would be a huge help. Actually, if you can test the _same_ `OpenShot-v2.4.1-180-gfdd5e96-2f45a4eb-f32c7c30-x86_64.AppImage` build and confirm that the tutorial windows don't have a transparent background, it's be great to get an idea of how widespread the issue is.

And then hopefully at some point there will be newer builds to test, but that can wait until next week.

**Comment by meoso** [comment] 2018-07-06 14:24
add here or #1708 ?

**Comment by ferdnyc** [comment] 2018-07-15 11:17
@peanutbutterandcrackers : please close as dup of... some other Tutorial-problems bug. We'll have to choose the one with the most data about the problem to consolidate on. (Maybe #1708)

**Comment by peanutbutterandcrackers** [comment] 2018-07-16 04:13
Closing as dup (even though this was reported earlier, because of the discussions there) of #1708

**Closed by peanutbutterandcrackers** 2018-07-16 04:13 UTC
Labels: bug, duplicate, fix in progress
