### ISSUE TITLE
Who knows how to handle this error?

### ISSUE THREAD

**Issue by HarrisHan** [OpenShot/openshot-qt#3105] opened 2019-11-29 10:39 UTC
PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
PasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960]
2019-11-29 18:37:44.913 Python[32257:710665] *** CFMessagePort: bootstrap_register(): failed 141 (0x8d) 'unknown error code', port = 0xe6b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by ferdnyc** [comment] 2019-11-30 17:35
@HarrisHan Simple: Don't run Qt applications [under `tmux` or `screen`](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard).

Assuming you're _not_ doing **that**, then please fill out a coherent issue report using the [bug report template](https://github.com/OpenShot/openshot-qt/issues/new?assignees=&labels=%3Abeetle%3A+bug&template=bug-report.md&title=Give+your+bug+report+a+descriptive+title), include as much of the requested detail as possible (including versions of OpenShot and MacOS, and the steps you performed that resulted in this error), and perhaps someone will be able to offer some assistance.

This is not a bug report. Closing.

**Closed by ferdnyc** 2019-11-30 17:35 UTC
Labels: :beetle: bug
