### ISSUE TITLE
Corrupted project JSON (failed to load legacy project error)

### ISSUE THREAD

**Issue by giuliatosarello** [OpenShot/openshot-qt#4551] opened 2021-11-24 19:21 UTC
**Describe the bug:**
![photo_2021-11-24_20-19-47](https://user-images.githubusercontent.com/94993397/143300842-3cfc30ad-646d-4304-a69c-6cc765278936.jpg)

**Steps to reproduce the behavior:**

**Expected behavior:**
to open my saved project

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by DougCoffland** [comment] 2022-02-22 19:58
I have the same problem. After several days of work, I suddenly am getting the same error message. I think it may have started when I opened a second project while the one I was working on was still open.

My operating system is  debian release 10 (buster)

[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/8119753/openshot-qt.zip)
.

**Comment by JacksonRG** [comment] 2022-02-22 20:11
@DougCoffland I'll take a look at your logs. In the mean time you may be able to open a backup of your project. [Here](https://github.com/OpenShot/openshot-qt/wiki/Project-Recovery) are instructions on where to look

**Comment by JacksonRG** [comment] 2022-02-22 20:12
@giuliatosarello Could you include logs of this happening? There are instructions [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging) for how to clear logs before re-creating the issue.

**Comment by DougCoffland** [comment] 2022-02-22 20:16
I tried to open some of the backups, but was unsuccessful and had the same
error.

Thank you for your quick response.

Doug

**Comment by JacksonRG** [comment] 2022-02-22 20:27
Did either of you update OpenShot between creating your projects and getting this bug? Also what version of OpenShot are you using?

**Comment by DougCoffland** [comment] 2022-02-22 21:34
I am running version 2.6.2-dev. I updated it today after it started
crashing. I originally installed it about two weeks ago. I did not check,
but suspect that was the same version.

I think it failed when I tried to run a project that I made a couple of
years ago. My current project was still running in another window when I
opened the old project. i do not know what version I was running when I
created the old project.

**Comment by jonoomph** [comment] 2022-02-25 21:49
@DougCoffland I would love to see your legacy *.osp file also, so we can try and reproduce the load failure.

This is the error from the log files you shared...
```
Traceback (most recent call last):
  File "/tmp/.mount_ucxYZu/usr/bin/classes/project_data.py", line 449, in read_legacy_project_file
    v1_data = pickle.load(f, fix_imports=True, encoding="UTF-8")
_pickle.UnpicklingError: invalid load key, '{'.
11:45:11 ERROR main_window: Couldn't open project Documents/videos/calibrating travel distance/Calibrate Travel Distance.osp.
Traceback (most recent call last):
  File "/tmp/.mount_ucxYZu/usr/bin/classes/json_data.py", line 208, in read_from_file
    return json.loads(contents)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17529 column 85 (char 267114)
```

Just off the top of my head, I'm guessing the following sequence of events might have happened:
 - You opened an older project file
 - We automatically "upgraded" some data structure inside it, causing invalid JSON
 - Now your *.osp file is corrupted with invalid JSON, and will no longer open

Assuming you can share this file with us, we can fix it (and see what was broken)

**Comment by DougCoffland** [comment] 2022-02-25 21:53
I had another failure today. But this time, it did not involve an older
version. I completed a project this morning and created the final video.
Then, I closed it.

After lunch, I decided to reopen it. Sadly, it will not open. I was
manually making backups as well, and I cannot open those either.

What files would you like me to send?

Doug

**Comment by jonoomph** [comment] 2022-02-25 21:54
Just the *.osp project file.

Yes, I suspect the "Legacy" error message is actually misleading. Once we fail to load a normal project file (for any reason), we always attempt to open it as a "legacy" format (as a fallback). Both are failing in your case.

**Comment by DougCoffland** [comment] 2022-02-25 21:56
Here it is.

Doug

**Comment by jonoomph** [comment] 2022-02-25 22:01
Hmmm, I don't see the file attached on GitHub (might be because you are replying via email).  Please forward me the file instead: jonathan@openshot.org, and I would be happy to attach it here.

**Comment by DougCoffland** [comment] 2022-02-25 22:02
try it again

**Comment by jonoomph** [comment] 2022-02-25 22:06
GitHub does not support attachments sent via email replies. Please click on my email: jonathan@openshot.org, and attach the file directly to me via email. That should work fine. :+1: Good luck.

**Comment by jonoomph** [comment] 2022-02-25 22:17
Fixed the JSON in your corrupted project file. If you extract the *.osp from this *.zip file, and drop it in the same folder as your original project file, it should open in OpenShot without any issues.
[Axis Calibration.zip](https://github.com/OpenShot/openshot-qt/files/8145153/Axis.Calibration.zip)

It turns out that you are using file paths with a **" (quote)** character in the file/folder name. For example: `"path": "./final 4\" request.webm"`. However, after saving this in OpenShot, it becomes `"path": "./final 4/" request.webm"` with an invalid forward slash in front of the quote (instead of a backslash).

NOTE: This will probably continue to be corrupted again when you save the *.osp project file until we fix the core issue inside OpenShot. I will keep you posted on that fix.

**Comment by jonoomph** [comment] 2022-02-26 22:05
I did discover the nature of this error. These errors are most likely to happen on Linux or Mac, and are related to using special characters in a file path (any video, audio, image used in your project).

**Example:**
- Videos/10"/My-Video-".mp4

**Special characters** (there might be more, but these for sure can cause issues): 
- Backspace to be replaced with \b
- Form feed to be replaced with \f
- Newline to be replaced with \n
- Carriage return to be replaced with \r
- Tab to be replaced with \t
- Double quote to be replaced with \"
- Backslash to be replaced with \\

Of course, not all these special characters are supported by operating systems, but you get the point. Using one of these was previously unsupported in OpenShot, and would cause the file path to be broken during project saving (when we try and convert the file path from an absolute path to a relative path).

I have a PR open now to solve the issue moving forward (once merged). However, any projects currently broken by this issue can be manually fixed, using a text editor, and searching your *.osp project file for `"path":`, and manually fixing any broken file paths (i.e. ones that look invalid). Once you think you have replaced all the broken file paths in your *.osp file, copy/paste the entire file into this website, to validate the JSON is using the correct syntax: https://jsoneditoronline.org/. Hope that helps someone with corruption. :pray:

**Comment by DougCoffland** [comment] 2022-02-26 22:53
Thanks Jonathan,

That worked. I changed the path names on the files and the references in
the '.osp' file with quotes in them and the project now opens and runs
correctly.

Thank you for your prompt response and hard work in resolving this issue.

I'll avoid non-standard pathnames in the future.

Doug

**Closed as completed** 2022-02-28 20:29 UTC

**Comment by jonoomph** [comment] 2022-02-28 20:32
Our daily build now correctly escapes " quote characters in file paths, along with other special characters escaped in JSON. However, best practice should be to avoid special characters in file names / folder names, if you want to use your *.osp projects in a cross-platform way (i.e. Share a project from Linux to Window, etc...). Thx for the bug report!

**Comment by Francisca-dias** [comment] 2022-06-09 19:28
Hello! I got the same error on my project and I had been working on it for days too..

Can you please help me fix this? It's very important!

Thank you :)

![Capture](https://user-images.githubusercontent.com/107214669/172928675-3f16cc89-358f-439a-ad5f-356a6d574755.PNG)
![Capture2](https://user-images.githubusercontent.com/107214669/172928848-d3ae499a-426d-422e-ba95-f6b4ad544975.PNG)

**Comment by JacksonRG** [comment] 2022-06-11 04:48
@Francisca-dias first of all, you may be able to recover a previous version of this project. [Here](https://github.com/OpenShot/openshot-qt/wiki/Project-Recovery) are instructions to check if a backup of your project exists.

If that doesn't work, I have some questions about this project. Did you recently update openshot before this issue occurred? Does anything change if you drag this project to your `C:` drive and try to open it??

**Comment by Francisca-dias** [comment] 2022-06-11 15:05
Hello!

Thank you so much for replying so quickly.

I was able to recover a previous version of the project! It wasn’t easy
getting it to work though. The files were failling and the exportation
wasn’t working either. For some reason, the exportation started to work
when I changed the destination folder.

For now I’m still able to edit and export the project, so I think I can
manage from here.

If you want my personal opinion, I like OpenShot but i think it has some
problems that are too difficult for people like me to understand and fix.
The audio doesn’t work and the system fails a lot. The error messages are
way too vague, leaving me with no options nor clues on how to fix it.

This error in opening the project is definetely the worst because it makes
you feel desesperate to recover your lost project. If you could add
instructions on how to fix it along with the error message that would be
great for users.

Again, I really appreciate your promptness to help me and I hope I somehow
helped you improve your app!

Best regards,
Francisca Dias

JacksonRG ***@***.***> escreveu em sáb., 11/06/2022 às 05:48 :

**Comment by blogozki** [comment] 2022-07-14 16:14
Good afternoon. May I ask about my problem?

I have the same situation (Failed to load legacy project file). The "recovery" files are not recoverable either. I opened the file in a text editor and fixed the forward slash's as described above, but that didn't make a difference either. This is on Linux Mint 20.2.

How could this be fixed?
