### ISSUE TITLE
diacritics in titles filenames gets translated into unicode entities

### ISSUE THREAD

**Issue by PontiacCZ** [OpenShot/openshot-qt#3241] opened 2020-02-23 18:36 UTC
**Describe the bug:**
When you use diacritics in title filename, next time when opening your project OpenShot will display missing file error - like "u00fd.svg cannot be found". Apparently this is related to how OpenShot works with unicode characters.

**Steps to reproduce the behavior:**
1. open new project in OpenShot and go to "Titles" dialog
2. Pick the first title and give it a filename "modrý" (means blue in Czech). Copy the word from here. Click "Save"
3. you have "modrý.svg" in project files. You don't have to put it on the timeline.
4. now save the Openshot project somewhere and close OpenShot
5. launch your project in OpenShot again.
6. you get following error:

![image](https://user-images.githubusercontent.com/9153595/75117484-077b4100-5672-11ea-9a06-03171e30160a.png)

7. when you look into your .osp file, you can find there lines like:
`   "path": "modry_assets/title/modr/u00fd.svg",`

8. somehow the letter **ý** got translated into unicode entity **/u00fd**

**Expected behavior:**
Title loaded into OpenShot

**System Details:**
- OpenShot Version: 2.5.0
- Operating System / Distro: Windows 10 Pro x64

**Comment by ferdnyc** [comment] 2020-02-23 18:45
> somehow the letter ý got translated into unicode entity /u00fd

SHIT.

That's exactly the problem. Or, well, it's twofold.

I haven't been following this too closely in the other issues where it's been brought up, but I know exactly where the big lives.

The issue is, the glyph ý is encoded to JSON as `\u00fd`. That's correct, and an accurate escaped ASCII representation.

BUT, there's code in the OpenShot project-save code that replaces all `\` characters with `/` characters -- it was intended to fix Windows file paths, but it's corrupting the escaped characters.

**Comment by SuslikV** [comment] 2020-02-23 19:50
Try this: https://github.com/OpenShot/openshot-qt/pull/3229

**Comment by ferdnyc** [comment] 2020-02-23 23:04
#3229 is an option, but I think if we remove the slash-replacement code, we may be able to fix this without having to do all that.

`\u00fd` is a good escaped ASCII representation of a Unicode character, and is actually a safer way of encoding our project files than using utf-8 and having to worry about the encoding possibly being corrupted. We just have to STOP corrupting the files ourselves, worrying about Windows paths. 

If we don't replace the slashes, using escaped ASCII should, _I **believe**_, work fine.

**Comment by SuslikV** [comment] 2020-02-24 04:02
Structure of Python objects in .json is known and fixed. There is no objects that cannot be present as existing set of symbols. The only place where unicode is used - is in Paths. The escaping is rudiment of data transferring - not storing. Years will pass until you'll find a solution suitable for your needs. Also, user friendly paths can be modified directly.

**Comment by EZ57** [comment] 2020-02-24 18:27
Hi! I have exactly the same pb! Have you found somehting to fix it? I'm a total noob in programmation.

Thanks!

**Comment by SuslikV** [comment] 2020-02-24 18:54
@EZ57 use for files names (and path) only English letters.

**Comment by EZ57** [comment] 2020-02-24 19:42
ok thx!

**Comment by EZ57** [comment] 2020-02-24 23:19
I followed your advices. I deleted all diacritics on my files names but it doesn't work! All my files (photo, videos, sounds) are in the same folders. I don't understand!

**Comment by SuslikV** [comment] 2020-02-25 05:52
The @EZ57 issue now in https://github.com/OpenShot/openshot-qt/issues/3246

**Comment by SuslikV** [comment] 2020-02-27 17:27
@PontiacCZ can you try new daily build of OpenShot?
https://www.openshot.org/download/#daily
There were changes that can allow the usage of the diacritics in names (files etc.) for the new projects.

**Comment by PontiacCZ** [comment] 2020-02-27 17:59
Perfect! I used a filename with all Czech diacritic letters and no problem anymore, the projects open fine and the title is still there. :)

![image](https://user-images.githubusercontent.com/9153595/75471765-ef1d6600-5992-11ea-830a-59330b07cb36.png)

I used diacritics in the project filename without issues as well.

Thank you very much, good work! :-)

**Comment by ferdnyc** [comment] 2020-03-08 02:43
The OpenShot 2.5.1 release (now available at https://openshot.org/download/) contains a fix for the project-file encoding bug present in OpenShot 2.5.0. The new release will also recognize and auto-repair damaged encoding, when opening OpenShot 2.5.0 project files.

All OpenShot 2.5.0 users are strongly urged to upgrade to OpenShot 2.5.1 ASAP. After upgrading, it's further recommended that you open any projects previously saved from OpenShot 2.5.0 and re-save them, which will correct any encoding issues that may be present.

**Closed by ferdnyc** 2020-03-08 02:43 UTC
Labels: :beetle: bug
