### ISSUE TITLE
Why is the centre blacked out?

### ISSUE THREAD

**Issue by CodyMol** [OpenShot/openshot-qt#1060] opened 2017-11-21 21:11 UTC
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Why is the centre of the picture blacked out on certain clips? Aargh!!

![snip](https://user-images.githubusercontent.com/33879755/33096872-6417cc40-cf00-11e7-92a3-616b7c84174f.JPG)

**Comment by N3WWN** [comment] 2017-11-21 21:15
Can you also post a screenshot of your OpenShot window showing your timeline?  

Preferably, zoomed out to show the entire clip that this is occurring in with the playhead showing the blacked out portion in the preview frame.

**Comment by CodyMol** [comment] 2017-11-21 22:33
Thanks for asking. Can't do that as I keep binning the clips when it happens. I will save he next one to show you.  Enjoy.  CodyMol.

**Comment by CodyMol** [comment] 2017-11-22 22:22
Found out it happens when you split the sound, as you play the clips it blacks out the centre?  Trying to paste the screen shot but not having much luck there either.  Enjoy. CodyMol

**Comment by CodyMol** [comment] 2017-11-24 10:55
Managed a link to the screen shot.  The screen blacks out when you split the sound/pics. Helps!


![image](https://user-images.githubusercontent.com/33879755/33207468-c0500c5a-d105-11e7-9df5-899eef2ac797.png)

**Comment by DylanC** [comment] 2017-11-29 18:01
@CodyMol - Thanks.

**Comment by N3WWN** [comment] 2017-12-05 14:04
If you swap the order on the timeline, does the box go away?  If so, that may be a workaround while the bug is being addressed.

Currently you have:
* Track 3 => `GOPR0014.MP4 (all channels)`
* Track 2 => `GOPR0014.MP4`

Does the box remain if you swap them like this:
* Track 3 => `GOPR0014.MP4`
* Track 2 => `GOPR0014.MP4 (all channels)`

Or leave the video where it is on Track 2 and move the audio from Track 3 to Track 1 like this:
* Track 2 => `GOPR0014.MP4`
* Track 1 => `GOPR0014.MP4 (all channels)`

**Comment by DylanC** [comment] 2018-04-23 20:18
@N3WWN - This workaround is good, thanks. @CodyMol - Marking as a bug. Hopefully we can get this resolved for you.

**Comment by N3WWN** [comment] 2018-04-24 12:50
Just a guess, but I think the first thing to check is to see if the audio-only clip has the "has video" flag set to true.  If that flag is true, but the reader cannot find a valid frame (because there is none in an audio-only clip), I believe the reader returns a black frame.

**Comment by NecroWizard666** [comment] 2019-09-16 22:30
I'm having the same problem on a video I've attempted to transfer to another computer. I've tried reinstalling OpenShot, switching the order of audio tracks, and enabling/disabling audio to no effect.

**Comment by ferdnyc** [comment] 2019-09-16 22:54
@NecroWizard666 This is most likely because you have a clip with disabled video, but Scale set to the default 'Best Fit'. Right now due to bug #2882 you also need to set Scale to 'None' on clips with disabled video. (An audio-only track counts as a clip with disabled video.)

**Comment by ferdnyc** [comment] 2019-09-16 22:56
Marking this as a duplicate of #2882, only because _that_ issue contains (a) the root cause, and (b) the workaround for this issue.

**Comment by ferdnyc** [comment] 2019-09-17 00:42
I just merged a change to automatically set `Scale: None` on the audio portions, when splitting a clip into audio and video parts. So, that will be in the next daily builds.

Note that this is only a partial workaround, as it won't fix _existing_ audio portions (those have to be  configured to `Scale: None` manually), and it won't affect any **other** types of `Has Video: 0` clips.

**Comment by ferdnyc** [comment] 2019-09-17 00:48
(Note also that this issue only affects audio / no-video clips when they're placed on a layer (Track) that's _above_ a video clip on the Timeline, which is not the typical arrangement. Usually audio clips are located below their corresponding video clips. Which may explain why this wasn't noticed by the libopenshot developers.)

**Comment by ferdnyc** [comment] 2019-10-05 20:58
Closing as duplicated (with additional detail) by #2882.

**Closed by ferdnyc** 2019-10-05 20:58 UTC
Labels: :beetle: bug, duplicate
