### ISSUE TITLE
OpenShot sound crackling in preview/export (not in source)?

### ISSUE THREAD

**Issue by ChameleonRed** [OpenShot/openshot-qt#2514] opened 2019-01-07 08:40 UTC
**Please fill out this template** 

**Describe the bug**
Sound crackling in preview of target video.
Sound crackling in exported video.
No crackling in source video.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.3

**To Reproduce**
1. Create some video with OBS (Kodek: H264 - MPEG-4 AVC (part 10) (avc1), Kodek: MPEG AAC Audio (mp4a))
2. Run source video play (no crackling)
3. Add videos to track.
4. Run preview (1080p 30fps 44100Mhz) -> CRACKLINGS.
5. Export video (1080p 30fps 44100Mhz) -> CRACKLINGS.

**Expected behavior**
No CRACKLINGS.

**Screenshots**
Not need.

**Logs**
Not need.

**Video Profile**
Input:
General
Format                                   : Flash Video
File size                                : 43.3 MiB
Duration                                 : 2 min 15 s
Overall bit rate                         : 2 669 kb/s
Writing application                      : Lavf57.84.100

Video
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : 7
Duration                                 : 2 min 15 s
Bit rate                                 : 2 500 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.040
Stream size                              : 40.5 MiB (94%)
Writing library                          : x264 core 148 r2762 90a61ec
Encoding settings                        : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=12 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=10 / rc=cbr / mbtree=1 / bitrate=2500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=2500 / vbv_bufsize=2500 / nal_hrd=none / filler=1 / ip_ratio=1.40 / aq=1:1.00

Audio
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : 10-2
Duration                                 : 2 min 15 s
Bit rate                                 : 156 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 67 ms
Stream size                              : 2.53 MiB (6%)

**Additional context**

**Comment by speedytechdev** [comment] 2019-01-08 04:02
Hi @ChameleonRed this is a common issue. If you could look at [1069](https://github.com/OpenShot/openshot-qt/issues/1069) and see if there is any information in there that you found that other users did not. This will help us to solve the issue if we can keep all the information in one location. Thanks and have a great day.

**Comment by speedytechdev** [comment] 2019-01-08 04:04
**Closing Warning Reason:** Duplicate of [1069](https://github.com/OpenShot/openshot-qt/issues/1069)

**Closed** 2019-02-26 04:46 UTC
Labels: Closing Warning
