### ISSUE TITLE
Crash when importing *ANY* video file

### ISSUE THREAD

**Issue by a-catgirl-dev** [OpenShot/openshot-qt#4736] opened 2022-03-18 23:25 UTC
**Describe the bug:**
Sudden crash when importing ANY video file

**Steps to reproduce the behavior:**
1. open openshot
2. drag the file into "Project Files"
3. Enjoy a crash

**Expected behavior:**
The files appear in the list called "Project Files"
*fyi, uploading images work as intended*

**System Details:**
- Openshot version 2.6.1
- Windows 11 21H2

**Log Files:**
[Log File](https://github.com/OpenShot/openshot-qt/files/8308070/Logs.zip)

**Exception / Stacktrace:**
*Can't find it*
*But should be easy to re-produce*

**Screenshots:** (Optional)
*No screenshots, sorry*

**Comment by DanPinGF** [comment] 2022-04-03 23:41
@JacksonRG - Sounds like a duplicate of #4480.

**Comment by JacksonRG** [comment] 2022-04-04 04:02
@DanPinGF Oh, thanks for pointing that out. @WilliamAnimate are you running openshot as an administrator?

**Comment by a-catgirl-dev** [comment] 2022-04-12 21:01
sorry for not responding
i tried that too
but it appears that its fixed with 2 reinstalls (it may be a system issue of mine)

**Comment by JacksonRG** [comment] 2022-04-14 01:11
Oh that's good to hear! Let us know if you need any other help!

**Closed as completed by JacksonRG** 2022-04-14 01:11 UTC
