### ISSUE TITLE
Tip popups take app out of maximized mode

### ISSUE THREAD

**Issue by petebachant** [OpenShot/openshot-qt#1036] opened 2017-11-15 01:05 UTC
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.1

**Issue Description and steps to reproduce:**

Opened up OpenShot for the first time on Windows 10. Tips pop up when, e.g., clicking the "effects" tab. If the window is maximized, it will be un-maximized.

**Comment by DylanC** [comment] 2017-11-16 13:08
@petebachant - The version says v2.3.1. Did you test on v2.4.1?

**Comment by petebachant** [comment] 2017-11-17 02:14
I have not. I installed via Chocolatey so I will update as soon as the new version is in those repositories.

**Comment by croco3008** [comment] 2017-11-19 06:33
I Can confirm the issue in 2.4.1. It appears only on bigger screen screen resolutions (full hd). Looks like the tutorial is made only for low resolution laptops.

**Comment by DylanC** [comment] 2017-11-19 07:14
@croco3008 
Thanks, I can see what you mean. Marking as a bug for now unless it is mean't to be this way for some reason.

**Comment by DylanC** [comment] 2017-11-19 07:20
Dup of #307

**Comment by peanutbutterandcrackers** [comment] 2018-06-15 02:28
Hey there, a fix to this issue was just merged into the source tree and is ready for testing. Could you please try out the [latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and see if this has been resolved? Thanks!

**Comment by peanutbutterandcrackers** [comment] 2018-07-03 02:46
The following are the beta-builds that contain the changes made to resolve this issue (PR #1726 by the awesome @ferdnyc). Please try them out and report whether this resolves the issue. Thanks!
1. [Windows Builds](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN)
2. [Mac Builds](https://drive.google.com/open?id=10zy1SQz6gGCxfmYZtMnTYHkC5NBQy6Oz)
3. [Linux Builds](https://drive.google.com/open?id=10D6BIF_n8krpYB-goNQ7jj4W33OSv4Yg)

**Comment by petebachant** [comment] 2018-07-14 13:22
Looks good on Windows!

**Comment by ferdnyc** [comment] 2018-07-14 15:11
I'm confused, _this_ issue was addressed in #1646, it should be part of 2.4.2 release.

**Comment by ferdnyc** [comment] 2018-07-15 11:13
@peanutbutterandcrackers: Can you take another look at this? Like I said, my understanding is that it was fixed in 2.4.2, and this could be closed.

**Comment by DylanC** [comment] 2018-07-16 10:47
@ferdnyc - LGTM on Linux.

**Comment by peanutbutterandcrackers** [comment] 2018-07-16 10:59
Oh, yes. I often get things messed up while trying to juggle all these issues. I am sorry.

The "takes app out of maximized mode" has been fixed in 2.4.2 release already.

Closing as resolved. Thanks to @ferdnyc! :+1:

**Closed by peanutbutterandcrackers** 2018-07-16 10:59 UTC
Labels: duplicate
