### ISSUE TITLE
Error in saving new project in Windows - path is on mount 'C:', start on mount 'D:'

### ISSUE THREAD

**Issue by vladad** [OpenShot/openshot-qt#79] opened 2016-02-10 19:20 UTC
When I create a new project and after adding few videos I tried to save a project on disk D:, but this error is shown:

`path is on mount 'C:', start on mount 'D:'`

After that I tried to save a project on disk C: and another error is shown:

`object of type 'NoneType' has no len()`

**System:**
Windows 8.1 Enterprise 64 bit
OpenShot Beta 2.0.6 installed at: d:\Programs\Media\OpenShot2

**Comment by BF3000** [comment] 2016-02-11 10:19
Same here.

**Comment by jonoomph** [comment] 2016-02-13 22:41
Can you attach your /Users/USER/.openshot_qt/openshot-qt.log file? Even better, delete this log file, re-run OpenShot and get this error again, and then attach the newly created log file. Thx

**Comment by vladad** [comment] 2016-02-14 10:02
Here is the application log:
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/129608/openshot-qt.zip)

I create a new project, added few videos and try to save project. Firstly to disk D:, secondly to disk C:
Same error messages were shown as I described in issue message.

Thanks.

**Comment by jonoomph** [comment] 2016-02-14 20:53
@vladad, Thanks for the log. I'm going to add some additional error logging around saving projects. It looks like the issue is related to this Python bug report: http://bugs.python.org/issue7195.

When saving a project, I'm trying to create a relative path between the "project folder" and the media files in your project (so it is portable between different computers... and even different operating systems). However, in your example, it's trying to create a relative path across drives in Windows (from C: to D:) and that is not possible.

I'm going to make the project save handle this particular error, and just ignore it. In cases where you have media from different drive letters, I'll just keep those paths absolute instead of trying to make them relative.

**Comment by jonoomph** [comment] 2016-02-14 21:00
Okay, I've made some improvements, and it should successfully save your project now... although it will log an error trying to convert your paths to relative paths. This fix will be in the next Windows release. Thanks!

**Closed by jonoomph** 2016-02-14 21:00 UTC
