### ISSUE TITLE
Very slow preview

### ISSUE THREAD

**Issue by progidev** [OpenShot/openshot-qt#129] opened 2016-03-21 16:26 UTC
Using Arch on Intel I5 5th generation, 8GB memory and onboard Intel Graphics

Setting up simple picture slideshow with 12 pictures (4000 x 3000 px) and randon transitions. In app preview is so slow I can almost count the frames and when rendering a transition in the preview it becomes unusable.

Please keep up the good work

**Comment by jonoomph** [comment] 2016-03-22 03:55
Thanks for the report! This is actually a dupe of #29. In general, it's a known issue, because OpenShot keeps the original image's pixels in memory, rather than a scaled version. So, the bigger the picture, the more work required for each frame. It should be smarter, and scale down the original (if no animation or zooming is needed).

**Closed by jonoomph** 2016-03-22 03:55 UTC
