### ISSUE TITLE
rotate 90 degrees does 180

### ISSUE THREAD

**Issue by EDDemilne** [OpenShot/openshot-qt#2998] opened 2019-09-15 09:09 UTC
**Describe the bug:**

**Steps to reproduce the behavior:**
1. Go to 

**Expected behavior:**
A clear and concise description of what you expected to happen.           when I put my video clip into line one, it is at 90 degrees. when I try to rotate it 90 degrees left or right, it rotates 180 degrees. when I flip it 180 degrees, it is correctly horizontal, but upside down. 

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / win 7 pro

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ferdnyc** [comment] 2019-09-15 12:02
Duplicate of #2794 / #2969.

**Closed by ferdnyc** 2019-09-15 12:02 UTC
Labels: bug
