### ISSUE TITLE
Zooming in to within 100 milliseconds

### ISSUE THREAD

**Issue by Gunnar-Vestergaard** [OpenShot/openshot-qt#1327] opened 2018-03-02 19:41 UTC
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
I need to do this: I have an mp4 video that has an audio track that is far out of sync with its own video track. I need to slide that audio track by about 40 ms (milliseconds) or 80 ms or 120 ms or whatever. But the user interface in OpenShot v2.4.1 won't let me zoom in to more than 1 second.
How can I do this in OpenShot?
Gunnar

**Comment by gary9872** [comment] 2018-03-03 00:11
Click on your audio clip then >  Go to properties ( left bottom pane) and adjust the position. You should be able to adjust 1/100 of a second.

Cheers,

Gary

**Comment by peanutbutterandcrackers** [comment] 2018-03-03 11:06
Also, we do have plans to improve the time-line zoom in the future. Please do wait for future versions. :)

**Comment by DylanC** [comment] 2018-03-03 11:21
@Gunnar-Vestergaard - Already have an enhancement open at #891. Hopefully this can be implemented in the future. 

(Dup of #891)

**Comment by ferdnyc** [comment] 2019-07-21 09:34
Closing as duplicate of #891.

**Closed by ferdnyc** 2019-07-21 09:34 UTC
Labels: duplicate
