### ISSUE TITLE
Animated Title: "Dissolving Text" is not working properly

### ISSUE THREAD

**Issue by bobonov** [OpenShot/openshot-qt#3350] opened 2020-04-05 15:44 UTC
**Describe the bug:**
Using the animated title "Dissolving Text" result in an incomplete animation or probably.
I tried to make a rendering using all defeault values, even for the title and the name
But the result is not correct.
I do not know how this effect should be, but for sure the should not be half title reapparing at the end.
1. Basicalli it start with the whole title
2. Then the title start dissolving
3. When it is almost dissolved the title start to reappear one char per time 
4. The title do not show completely again, it stop after some char

Probably the title should show char by char and then start dissolving, but for sure it should not half show at the end of the animation

**Steps to reproduce the behavior:**
1. Go to Anomated Title
2. Select "dissolving Text" effect 
3. Click on render

**Expected behavior:**
A proper animated text.

**System Details:**
- OpenShot-v2.5.1-dev2-1585970041-166f6938-232f3f79-x86_64
- Operating System / Distro: Windows 10
- Blender: 2.82

**Screenshots:** 
Here is a screenshot of the last frame of the animation.
![openshot-qt_spauUMrvsP](https://user-images.githubusercontent.com/1412083/78501631-a6f51e80-775c-11ea-82cc-2d2a83c6294f.png)
I attach also the video export 
[export.zip](https://github.com/OpenShot/openshot-qt/files/4434211/export.zip)

**Comment by pappou99** [comment] 2020-04-05 17:56
I can confirm this also under Ubuntu.
Could be an error in libopenshot or dissolve.py

**Comment by ferdnyc** [comment] 2020-04-06 05:25
Yeah, I see it — the error is in the particle system `lifetime` setting, on line 116 of `dissolve.py`.

https://github.com/OpenShot/openshot-qt/blob/03b8f8d0ee39dcac3dc3222ee797062b03ab93aa/src/blender/scripts/dissolve.py#L111-L118

Because the particle system _**starts**_ affecting particles in frame 10, with a lifetime of 80 some of the earliest particles will start to die off at frame 90, before the 128-frame animation is complete. It appears that, when particles die, they "reset" to their starting point.

The `lifetime` value should be 120, to ensure that the particle system keeps control of all particles for the entire duration of the animation.

**Comment by ferdnyc** [comment] 2020-04-06 05:42
I just merged that change, which you can test by downloading the most recent Daily Build from https://openshot.org/download/

**Closed** 2020-04-06 05:41 UTC
Labels: :beetle: bug

**Comment by bobonov** [comment] 2020-04-07 07:56
Just confirming it works, thanks
