### ISSUE TITLE
Preview won't play end of this and other files

### ISSUE THREAD

**Issue by theelectricsoul** [OpenShot/openshot-qt#1444] opened 2018-03-29 20:38 UTC
**System Details:**
* Operating System / Distro: Win Server 2016
* OpenShot Version: 2.4.1 dev1

https://streamable.com/xthbg

[Video file for download](http://www9.zippyshare.com/v/Fh1eF1Jk/file.html
)

**Comment by peanutbutterandcrackers** [comment] 2018-03-30 03:54
Like I pointed out in [another comment](https://github.com/OpenShot/openshot-qt/issues/1443#issuecomment-377438379) you might perhaps want to try out the latest build.

If that doesn't help either, you might want to transcode the video using something like [HandBrake](https://handbrake.fr/) and see if the transcoded file works.

However, if you want this issue to be fully resolved, you might want to find out the information about the video. The encoder used. The container. And all other sorts of stuff. There are a lot of smart people around here who can help. I am not really one of them, sadly.

Hope that helps!

**Comment by theelectricsoul** [comment] 2018-03-30 13:42
tested with 2.4.1-53
Not need to transcode, the problem appears ONLY with the preview functionality. And this is a videofile straight from youtube. Should I call them up maybe :)??

**Comment by peanutbutterandcrackers** [comment] 2018-03-31 01:57
Perhaps not? Because OpenShot does not really have the best of previews right now... maybe the preview window needs some more work?

Thank you for your patience. Hope you make awesome videos with OpenShot, good sir! :)

**Comment by theelectricsoul** [comment] 2018-03-31 02:10
The affected files can only be played until 00:29:59:XX
The millseconds vary from file to file.

**Comment by peanutbutterandcrackers** [comment] 2018-04-06 03:28
@N3WWN - You once gave some commands to a user to test his video, if I remember correctly. I believe this could use your help, too.

@theelectricsoul - Sorry for the inconvenience. We'll try our best to help you. This is just a community that scratches each other's backs. So, it might be a while before we are able to find a solution to this issue. Thank you for your patience. :)

**Comment by N3WWN** [comment] 2018-04-09 18:05
I don't recall commands that I may have provided to test a video, but could this be a dupe of https://github.com/OpenShot/openshot-qt/issues/1136 , https://github.com/OpenShot/openshot-qt/issues/940  and/or https://github.com/OpenShot/openshot-qt/issues/629 ?

**Comment by DylanC** [comment] 2018-04-24 08:33
Sounds like a dup of those issues mentioned by @N3WWN

**Closed** 2019-11-22 21:35 UTC
Labels: duplicate
