### ISSUE TITLE
Cannot start appimage

### ISSUE THREAD

**Issue by Ygarr** [OpenShot/openshot-qt#2278] opened 2018-10-25 00:52 UTC
**Describe the bug**
Application appimage

**System Details (please complete the following information):**
 - Operating System Arch Linux 64 bit
 - OpenShot Version 2.4.3,
- error:
./OpenShot-v2.4.3-x86_64.AppImage
./bin//openshot-qt.wrapper: line 110: 23564 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2> /dev/null
Loaded modules from current directory: /tmp/.mount_qmMwVj/usr/bin
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

**To Reproduce**
1. Go to folder with app
2. Click on Enter or run with terminal
3. Scroll down to error log

**Expected behavior**
Running

**Screenshots**

**Logs**
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 54, in <module>
    from classes.app import OpenShotApp
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_qmMwVj/usr/bin/classes/app.py", line 41, in <module>
    from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_qmMwVj/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory

**Additional context**
Add any other context about the problem here. install openshot-qt via  package manager working good.

**Comment by peanutbutterandcrackers** [comment] 2018-11-27 09:06
@DylanC - Any thoughts, Cap'ain?

**Comment by besworks** [comment] 2019-03-27 17:02
I just ran into this same issue. The problem is that Arch doesn't officially support SELinux.

https://wiki.archlinux.org/index.php/SELinux#Current_status_in_Arch_Linux

You can probably get it working by installing SELinux from AUR. I won't be doing that so I can't comment on how effective this workaround is.

Looks like this issue was fixed upstream though so it would probably be a good idea for the OpenShot AppImage to be rebuilt with the latest version.

https://github.com/AppImage/pkg2appimage/issues/83

**Comment by rexct** [comment] 2019-03-31 10:42
Found a workaround.  In Archlinux, try installing [libselinux](https://aur.archlinux.org/packages/libselinux) from AUR, which include libselinux.so.1.
Although there are lots of Fontconfig warnings, it works finally.

**Comment by lsevero** [comment] 2019-10-20 15:15
Got the same error as @Ygarr and fixed with @rexct's solution. Thanks :+1:

**Comment by ferdnyc** [comment] 2019-10-20 18:20
Ooh, I wasn't aware that libselinux wasn't installed by default on Arch.

We don't use `pkg2appimage` in the first place, unfortunately, so regeneration isn't an option. The tool used on the builders, `AppImageAssistant`, is _very_ old and long since deprecated/unsupported.

Upgrading to `pkg2appimage` would probably be prudent for lots of reasons, but unfortunately none of that is part of the public repo. The AppImage tooling lives only on the build servers, and since the build servers are @jonoomph -private, he's the only one who's able to address this.

What I **can** say is:
* I've checked our AppImage builds
* _several_ of the libraries packaged are linked with `libselinux.so.1`
* `libselinux.so.1` is **not** included in the AppImage
* looks like it needs to be included (though I'm very nervous about version compatibility), since it's apparently not present on all distros by default
* since none of our tools (`freeze.py`, `build-server.py`) explicitly exclude it, the exclusion is most likely coming from `AppImageAssistant`
   (Which is actually **_very_** likely, since the issue @besworks linked to shows that it was only around a year ago that the AppImage tool developers came around to the idea that it _shouldn't_ be excluded.)

### `libselinux` dependencies in current OpenShot AppImage builds:

```console
$ ~/Downloads/OpenShot-v2.4.4-dev2-1570651270-f3fc0d8c-f17a7ed4-x86_64.AppImage &
$ cd /tmp/.mount_RANDOM/usr/bin/
$ for file in lib*.so*; do echo $file; ldd $file|grep -i selinux; done 
libavcodec.so.54
libavcodec.so.57
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f7972faf000)
libavformat.so.57
libavutil.so.52
libavutil.so.55
libbluray.so.1
libbz2.so.1.0
libcairo.so.2
libchromaprint.so.0
libcroco-0.6.so.3
libcrypto.so.1.0.0
libcrystalhd.so.3
libdatrie.so.1
libfdk-aac.so.1
libffi.so.6
libfftw3.so.3
libfontconfig.so.1
libfreetype.so.6
libgcrypt.so.11
libgdk_pixbuf-2.0.so.0
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f4cea7c3000)
libgio-2.0.so
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f6055eee000)
libgio-2.0.so.0
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f8962753000)
libglapi.so.0
libglib-2.0.so
libgme.so.0
libgmodule-2.0.so
libgmodule-2.0.so.0
libgmp.so.10
libgnutls.so.28
libgomp.so.1
libgraphite2.so.3
libgsm.so.1
libgssapi_krb5.so.2
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f48f0ccf000)
libgstapp-1.0.so.0
libgstaudio-1.0.so.0
libgstbase-1.0.so.0
libgstpbutils-1.0.so.0
libgstreamer-1.0.so.0
libgsttag-1.0.so.0
libgstvideo-1.0.so.0
libgthread-2.0.so
libharfbuzz.so.0
libhogweed.so.2
libicudata.so.52
libicui18n.so.52
libicuuc.so.52
libjpeg.so.8
libk5crypto.so.3
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ff7bdd22000)
libkrb5.so.3
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f3ce3af8000)
libkrb5support.so.0
liblcms2.so.2
liblqr-1.so.0
libltdl.so.7
libMagickCore.so.5
libMagick++.so.5
libMagickWand.so.5
libmodplug.so.1
libmp3lame.so.0
libnettle.so.4
libnuma.so.1
libogg.so.0
libopencore-amrnb.so.0
libopencore-amrwb.so.0
libopenjp2.so.7
libopenjpeg.so.2
libopenshot-audio.so.6
libopenshot.so.17
libopus.so.0
liborc-0.4.so.0
libpango-1.0.so.0
libpangocairo-1.0.so.0
libpangoft2-1.0.so.0
libpgm-5.1.so.0
libpixman-1.so.0
libpng12.so.0
libpython3.4m.so.1.0
libQt5Core.so.5
libQt5DBus.so.5
libQt5Gui.so.5
libQt5Network.so.5
libQt5OpenGL.so.5
libQt5Positioning.so.5
libQt5PrintSupport.so.5
libQt5Qml.so.5
libQt5Quick.so.5
libQt5Sensors.so.5
libQt5Sql.so.5
libQt5Svg.so.5
libQt5WebKit.so.5
libQt5WebKitWidgets.so.5
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f13049a5000)
libQt5Widgets.so.5
libresvg.so
librsvg-2.so.2
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f08c0417000)
libschroedinger-1.0.so.0
libshine.so.3
libsnappy.so.1
libsoxr.so.0
libspeex.so.1
libsqlite3.so.0
libssh-gcrypt.so.4
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f00934de000)
libssl.so.1.0.0
libswresample.so.2
libswscale.so.4
libtasn1.so.6
libthai.so.0
libtheoradec.so.1
libtheoraenc.so.1
libtwolame.so.0
libva-drm.so.1
libva.so.1
libva-x11.so.1
libvdpau.so.1
libvo-amrwbenc.so.0
libvorbisenc.so.2
libvorbis.so.0
libvpx.so.1
libwavpack.so.1
libwebp.so.5
libX11-xcb.so.1
libx264.so.148
libx264.so.152
libx265.so.151
libXau.so.6
libxcb-dri2.so.0
libxcb-dri3.so.0
libxcb-glx.so.0
libxcb-icccm.so.4
libxcb-image.so.0
libxcb-keysyms.so.1
libxcb-present.so.0
libxcb-randr.so.0
libxcb-render.so.0
libxcb-render-util.so.0
libxcb-shape.so.0
libxcb-shm.so.0
libxcb-sync.so.1
libxcb-util.so.0
libxcb-xfixes.so.0
libxcb-xkb.so.1
libXcomposite.so.1
libXdamage.so.1
libXdmcp.so.6
libXext.so.6
libXfixes.so.3
libXi.so.6
libxkbcommon.so.0
libxkbcommon-x11.so.0
libxml2.so.2
libXrender.so.1
libxshmfence.so.1
libxslt.so.1
libxvidcore.so.4
libXxf86vm.so.1
libzmq.so.3
libzvbi.so.0
```

**Closed** 2020-08-20 18:19 UTC
Labels: OS:Linux 🐧, pending
