### ISSUE TITLE
Crash when play video preview

### ISSUE THREAD

**Issue by alex-lairan** [OpenShot/openshot-qt#787] opened 2017-07-12 11:31 UTC
**System Details:**
* Operating System / Distro: 
Fedora 25
```
$ uname -a
Linux keios 4.11.8-200.fc25.x86_64 #1 SMP Thu Jun 29 16:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.1 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #2 (rev d5)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d5)
00:1c.4 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 (rev d5)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation HM86 Express LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 860M] (rev a2)
08:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
09:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 10)
0a:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5249 PCI Express Card Reader (rev 01)
```

* OpenShot Version: 

Openshot 2.3.3

* _Please attach log files if crash_

```
preview_thread:INFO onModeChanged

Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /lib64/libopenshot.so.11       ( openshot::FFmpegReader::Close()           + 0x53c )  [0x7f1b008185bc]
  /lib64/libopenshot.so.11       ( openshot::FFmpegReader::Seek(long)        + 0x680 )  [0x7f1b00819bf0]
  /lib64/libopenshot.so.11       ( openshot::FFmpegReader::GetFrame(long)    + 0xa5b )  [0x7f1b00820dfb]
  /lib64/libopenshot.so.11       ( openshot::FrameMapper::GetOrCreateFrame(long)  + 0x2e9 )  [0x7f1b0083c589]
  /lib64/libopenshot.so.11       (                                           + 0xa734d)  [0x7f1b0083f34d]
  /lib64/libgomp.so.1            (                                           + 0x16de6)  [0x7f1afd4b5de6]
  /lib64/libpthread.so.0         (                                           + 0x773a)  [0x7f1b2327873a]
  /lib64/libc.so.6               ( clone                                     + 0x3f  )  [0x7f1b228a2e0f]
---- End of Stack Trace ----
QObject::~QObject: Timers cannot be stopped from another thread
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /lib64/libQt5DBus.so.5         (                                           + 0x29570)  [0x7f1b0f0bb570]
  /lib64/libQt5DBus.so.5         (                                           + 0x180f2)  [0x7f1b0f0aa0f2]
  /lib64/libQt5Core.so.5         (                                           + 0xa69ca)  [0x7f1b159119ca]
  /lib64/libpthread.so.0         (                                           + 0x773a)  [0x7f1b2327873a]
  /lib64/libc.so.6               ( clone                                     + 0x3f  )  [0x7f1b228a2e0f]
---- End of Stack Trace ----
```

**Issue Description and steps to reproduce:**

Import 2 files,

```
developpement.webm  
dev.wav
```

Place on track 0 and 1

Play the preview

Thanks for review ;)

Good luck !

**Comment by DylanC** [comment] 2017-08-28 12:28
@alex-lairan - Thanks for the feedback. I will test this shortly.

**Comment by alex-lairan** [comment] 2017-11-13 14:18
I quit Fedora for Arch and didn't retry since.

I can't test this case sorry :/

**Comment by DylanC** [comment] 2017-11-13 14:24
@alex-lairan - No problem. I can't reproduce this one on Fedora with the AppImage anyway. Closing for now.

**Closed by DylanC** 2017-11-13 14:24 UTC
