### ISSUE TITLE
Ending of video not rendering properly

### ISSUE THREAD

**Issue by SilasLaspada** [OpenShot/openshot-qt#1528] opened 2018-04-22 02:03 UTC
**System Details:**
* Operating System / Distro: Windows 10 x64 Build 1709
* OpenShot Version: Daily Build OpenShot-v2.4.1-88-g93cbd7a-59-697-x86_64

**Issue Description and steps to reproduce:**
After rendering a video (in this case a 2-3 minute video made of several clips), the end of the video sticks and just stops for the last few seconds. Audio appears to be unaffected, and this does not happen in the current stable release of OpenShot.

**Comment by peanutbutterandcrackers** [comment] 2018-04-22 02:51
@DylanC - Possible bug in the latest build, Cap'ain?

**Comment by N3WWN** [comment] 2018-05-01 13:17
Are you able to create a project using the smallest and fewest clips that can reliably recreate the issue?

Would you be able to capture and post screen video of the latest stable (showing it working properly) and a daily build (showing the bug)?  

Also, if you wouldn't mind posting the clip(s) and .osp file, that would be very helpful!

With the video showing exactly what you are doing, we can recreate _your_ setup with _your_ clips in _our_ development environments so we can troubleshoot the precise problem that you are encountering.

There has been a lot of work put into improving the performance of OpenShot since the last stable release that will be included in the next stable release.  If there's a bug introduced with those changes, we would like to know much more about it.

Thanks!

**Comment by SilasLaspada** [comment] 2018-05-10 20:27
This seems to be related to #1547

**Comment by N3WWN** [comment] 2018-05-10 20:29
Confirmed... I think it is probably related.  I've got some notes (I need to update them) in #1478 regarding the issues seen with image sequences.

**Comment by DylanC** [comment] 2018-07-02 09:46
@SilasLaspada Can you try v2.4.2 and let us know if you have any success?

**Comment by SilasLaspada** [comment] 2018-07-02 14:57
It is still broken as of the newest stable release. I used the default rendering options for both version  (except for file location), and I didn't alter anything in the project that wasn't already done by the project file.
[New Project.zip](https://github.com/OpenShot/openshot-qt/files/2155689/New.Project.zip)

**Comment by peanutbutterandcrackers** [comment] 2018-07-03 01:11
@SilasLaspada - Thank you for the info, sir! We'll try to fix it in the 2.4.2.x bug-fix releases.

**Comment by peanutbutterandcrackers** [comment] 2018-07-03 01:12
Possibly related to #1762

**Comment by Patrik356b** [comment] 2018-07-24 02:43
This is like my issue on Windows 10 #1909

**Comment by peanutbutterandcrackers** [comment] 2018-12-12 08:54
Hey there, a fix had gone in the libopenshot repo for this. Could you please check out the latest version and see if this still persists? I am pretty sure this has been resolved.

Closing this for now. If it hasn't been resolved, please feel free to re-open this issue. Thanks!

**Closed by peanutbutterandcrackers** 2018-12-12 08:54 UTC
Labels: 2.4.2-issue

**Comment by nick1982ad** [comment] 2020-06-11 17:19
Hello!
I'm afraid that issue still actaul.
Here clip example [issue_demo.zip](https://github.com/OpenShot/openshot-qt/files/4766225/issue_demo.zip) which demonstrates it (properly rendered it should show text "This is some text demonstrating last frames issue", but OpenShot stop rendering at "This is some text demonstrating last fra").

I'm using OpenShot ver. 2.5.1, libopenshot 0.2.5.
OS: Windows 10 Pro build 18363
