### ISSUE TITLE
Last few frames frozen when importing videos

### ISSUE THREAD

**Issue by Jenteco** [OpenShot/openshot-qt#2435] opened 2018-12-07 12:02 UTC
When i try import a video the last few frames are frozen while i didn't put on fades or anything, i dont know how it keeps happening. I am using 2.4.3 of openshot. Any tips?

**Comment by peanutbutterandcrackers** [comment] 2018-12-15 06:50
What kind of video is it? We had this problem a few months back but a solution was made and pushed in to the main source tree. I wonder if using [HandBrake](https://handbrake.fr) to transcode the video into something like `.mkv` will help fix the issue...

**Comment by skylarmt** [comment] 2019-06-27 02:35
[Here is a sample video](https://skylarittner.name/files/windows-10-update-spinning.mp4) that causes this problem on the latest stable version (2.4.4).

**Comment by skylarmt** [comment] 2019-06-27 02:43
Tested the above video again using the daily builds PPA, same issue.  Kubuntu 18.04.

**Comment by Elyoukey** [comment] 2020-04-18 15:10
I have the same issue here Ubuntu 18.04.4 LTS 
64 ibts
with Graphics GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2

and Openshot 2.5.1-dev-2
i also have the same issue on other videos.

**Comment by neurotrance** [comment] 2020-09-26 17:19
Exact same issue here. The half-second or so of certain imported video clips is frozen. The issue isn't just in preview, but also present in the exported video.

Using OpenShot 2.5.1 on Windows 10 Pro 64 bit.

The clips I'm trying to use are mp4. I converted these to mkv as @peanutbutterandcrackers suggested above, but that doesn't fix the issue. Converting to mkv does seem to make the frozen period at the end shorter, but it's still there. It also has the side effect of messing up the preview in OpenShot, which becomes super jumpy / lots of dropped frames. It seems, maybe?? to be more common of a problem with shorter clips, but I'm not sure.

This is an example video with this issue: [example](https://i.giphy.com/media/tHVzBCkKnaPKQBW9UO/giphy.mp4), but I'm having it with lots of similar videos.

**Comment by jamesbrunet** [comment] 2021-02-23 02:09
Exact same issue for me, I've noticed this on multiple source video files.

I hadn't noticed this issue until I worked with very short input clips (less than 20s) with lower than normal frame rates.

**Comment by JacksonRG** [comment] 2021-08-23 23:19
@jamesbrunet Thanks for pointing that out! We've patched a few timing bugs recently, and I'd love to hear if this issue is still bothering you.

**Comment by discgolfer5000** [comment] 2021-08-31 15:21
This issue happens to me also with OpenShot versions 2.5.1 and 2.6.0 on Windows 10. I've done complete uninstalls and manual file removals.

The last 8 frames are static in the OpenShot preview, scrubbing frame by frame, and in the exported video, but not in the source clip or frames.

It happens whether I import my source clip as an mp4, mkv, or a png image sequence of 120 frames.

I tried a different free and open source video editor and the same clips/frames worked fine there, so the issue is within OpenShot.

Issues #2435, #2609, #3585, #4032 all appear to be the same, some of which have auto-closed while unresolved.

**Comment by jamesbrunet** [comment] 2021-09-02 14:36
Yes, this is still happening in 2.6.0 on Windows 10.

**Comment by Colorjet3** [comment] 2023-01-24 02:51
This has been fixed in the latest DEV Daily Build of v3.0.0.

**Closed by Colorjet3** 2023-01-24 02:51 UTC
