### ISSUE TITLE
Is there a way to change the video color? my recording software i use, for some reason, changes the recording to tinted red

### ISSUE THREAD

**Issue by yeetmobile** [OpenShot/openshot-qt#2929] opened 2019-08-10 16:00 UTC
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment] 2019-08-11 10:45
Screenshot required (and if possible, share video source that causes the tint, a short sample of few seconds is well enough). The red color tint can be caused by different reasons.

**Comment by ferdnyc** [comment] 2019-09-09 22:20
Regardless, no OpenShot doesn't currently have any color-correction abilities. There's a feature request for something along those lines in #2970, I'm going to close this in favor of that request.

**Closed by ferdnyc** 2019-09-09 22:20 UTC
Labels: question
