### ISSUE TITLE
Takes for ever to render a video.

### ISSUE THREAD

**Issue by chibill** [OpenShot/openshot-qt#515] opened 2017-03-02 15:11 UTC
**System Details:**
* Operating System / Distro: ? Windows 10 (with i7 Skylake 16 GB RAM and gtx960M)
* OpenShot Version: ? Latest Download under other Downloads. As of March 1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Make  and video and render it at 1080 60 fps. It takes forever. Over 30 Minutes when WMM (Windows Movie Maker) and other editors render it in under 10 Minutes

**Comment by JtLively** [comment] 2017-03-03 00:28
What other render settings are you using?

**Comment by chibill** [comment] 2017-03-03 00:37
The default for 1080 at 60 fps like I said...

**Comment by Sirusdark** [comment] 2017-03-21 19:20
What's the video resolution and how long is that timeline you're trying to render **chibill**?

**Comment by chibill** [comment] 2017-03-21 20:08
How many times do I have to say this.1080p 60 fps  and is only a 20 min
video.

**Comment by jebeld17** [comment] 2017-03-28 00:10
#550

**Comment by chibill** [comment] 2017-03-28 00:12
That issue does not relate to mine. The window is fully responsive and not
slow.
Just rendering takes forever.

**Comment by finchamp** [comment] 2017-03-29 17:06
I have the same/similar issue with my 3 min video. I have tried a multitude of resolutions and codecs, and unless I have the render set to Low Quality at 360p, it will always go slowly, and end up stopping somewhere midway through the render, never completing (at least within 24 hours, when I close it).

My system:
Windows 10/OpenShot V2.2.0
Core-i5 @3.4Ghz
16Gb DDR4
GTX1060

**Comment by chibill** [comment] 2017-03-29 17:09
I expected OpenShot (which is actively developed) to at least be half as fast as Windows Movie Maker..... which has been ELOd for a while

**Comment by DylanC** [comment] 2017-08-25 12:33
Closing due to lack of detail.

**Closed by DylanC** 2017-08-25 12:33 UTC

**Comment by chibill** [comment] 2017-08-25 12:51
What more detail do you need? Jsut try and render a video it takes over an hour for 15 minute of 1080 video

**Comment by DylanC** [comment] 2017-08-25 13:44
@chibill - Need information as this cannot be reproduced on daily builds newer than 20th Aug.

**Comment by chibill** [comment] 2017-08-25 17:21
Well I can still reproduce it on an i7 6th gen with a GTX960 newest build. (Just reinstalled t yesterday)

**Comment by wgaylord** [comment] 2018-02-07 08:38
This is still a problem with the same exact parameters as before. So yea.
