### ISSUE TITLE
AppImage crashing with Fedora 33 and Python 3.9.0

### ISSUE THREAD

**Issue by supravirtual** [OpenShot/openshot-qt#3821] opened 2020-11-04 18:16 UTC
I've downloaded the AppImage version 2.5.1 and it's crashing at startup.

         app:INFO ------------------------------------------------
         app:INFO             Wed Nov  4 20:05:58 2020            
         app:INFO               Starting new session              
         app:ERROR OpenShotApp::Import Error: /lib64/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items
         app:INFO             OpenShot's session ended            
         app:INFO             Wed Nov  4 20:06:00 2020            
         app:INFO ================================================

The error message thrown is the next one:

Module: _openshot

Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_w60wwM/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_w60wwM/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: /lib64/libpango-1.0.so.0: undefined symbol: g_list_model_get_n_items

The error with the daily version (1 november 2020):

20:08:00 INFO app: ------------------------------------------------
20:08:00 INFO app:             Wed Nov  4 20:08:00 2020            
20:08:00 INFO app:               Starting new session              
20:08:00 ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 14, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_U1MvHm/usr/bin/classes/app.py", line 87, in __init__
    from classes import (
  File "/tmp/.mount_U1MvHm/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 17, in <module>
  File "/home/gitlab-runner/builds/d0022447/0/OpenShot/openshot-qt/openshot.py", line 16, in swig_import_helper
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
ImportError: /lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref
20:08:02 INFO app:             OpenShot's session ended            
20:08:02 INFO app:             Wed Nov  4 20:08:02 2020            
20:08:02 INFO app: ================================================

**Comment by ferdnyc** [comment] 2020-11-11 03:34
Mmm, this appears to be the same issue as #3807 (reported on antiX Linux).

I'm becoming even more convinced the problem lies with the fact that we're bundling `libgio-2.0.so.0`, `libgmodule-2.0.so.0`, and `libglib-2.0.so.0` _without_ bundling `libgobject-2.0.so.0`. Whether that means we need to _include_ gmodule, or _remove_ the rest of them... well, my money right now is on the latter, so #3830 will attempt to do that.

I'm trying to get test builds generated for that PR, the project build servers are down right now and @jonoomph hasn't been responding to my emails. Hopefully soon.

**Comment by ferdnyc** [comment] 2020-11-12 02:06
@supravirtual 

Sorry for the delay. This AppImage build:
[OpenShot-v2.5.1-dev2-no-glib-1605133643-b910d2f6-2cb4eeff-x86_64.AppImage](https://drive.google.com/file/d/1S1cOT2MTTKEB1sijZHWfxZMmnl9Qjnmf/view?usp=sharing)
has all of the glib components excluded from bundling. Would you be able to test and let us know if it solves the launch errors on Fedora 33?

**Comment by ferdnyc** [comment] 2020-11-12 03:40
I'm actually going to close this as a duplicate of #3807, it's clear both bugs have the same underlying cause. Please do subscribe to that bug, though, and report the results there if you're able to test the AppImage, thanks!

**Closed by ferdnyc** 2020-11-12 03:40 UTC
Labels: :beetle: bug
