### ISSUE TITLE
UI Lock On Export

### ISSUE THREAD

**Issue by TheOpenDevProject** [OpenShot/openshot-qt#135] opened 2016-03-27 23:38 UTC
When exporting a video the UI locks and goes into a very unstable state. This often causes OpenShot to crash.

![image](https://cloud.githubusercontent.com/assets/6072108/14068516/29df5c1a-f4d1-11e5-9360-88d673091bab.png)

```
 launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.6)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.0.6
         app:INFO libopenshot version: 0.1.0
         app:INFO platform: Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3+
         app:INFO qt5 version: 5.4.2
         app:INFO pyqt5 version: 5.4.2
```

**Comment by komackaj** [comment] 2016-03-28 08:13
Possible duplicate of #82

**Comment by TheOpenDevProject** [comment] 2016-03-28 09:34
@komackaj I can confirm this looks very similar to my issue.

**Comment by ZackTheCardshark** [comment] 2016-05-09 02:29
I'm a Mac user (El Capitan) who just discovered OpenShot, and would like to like it—but the program hangs every time I try to export. It seems to be this issue, or https://github.com/OpenShot/openshot-qt/issues/82 (which seems to have more helpful information). This is kind of the ultimate showstopper of a bug; is anybody looking into it?

BTW, also cross-posting to similar issues, since all of them are still open: https://github.com/OpenShot/openshot-qt/issues/82, https://github.com/OpenShot/openshot-qt/issues/119 and https://github.com/OpenShot/openshot-qt/issues/179

**Comment by TheOpenDevProject** [comment] 2016-06-13 11:37
About to test on 16.04

**Comment by jonoomph** [comment] 2017-03-02 06:44
Please retest with our latest daily build: Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. I have a feeling this is now fixed. Thanks!

**Closed by jonoomph** 2017-03-02 06:44 UTC
