### ISSUE TITLE
Open Shot crashes when I want to export. I use Mac osx

### ISSUE THREAD

**Issue by jeaustdulac** [OpenShot/openshot-qt#1862] opened 2018-07-16 14:22 UTC
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by peanutbutterandcrackers** [comment] 2018-07-17 01:23
Duplicate of #1787 
Please head over to #1787 and [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) there so that the devs can help out with your issue.
Closing this to keep the number of issues in check. Thanks

**Closed by peanutbutterandcrackers** 2018-07-17 01:23 UTC
Labels: duplicate
