### ISSUE TITLE
Still crashes on my Mac every time I attempt to open it.

### ISSUE THREAD

**Issue by marketingvp** [OpenShot/openshot-qt#127] opened 2016-03-12 15:21 UTC
Crash report:

Process:               launch [1582]
Path:                  /Applications/OpenShot Video Editor.app/Contents/MacOS/launch-mac.sh
Identifier:            launch
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           launch [1582]
User ID:               502

Date/Time:             2016-03-12 16:14:12.756 +0100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        

Time Awake Since Boot: 5700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   Python                        	0x0000000105ff63ce collect_with_callback + 58
1   Python                        	0x0000000105ff6f36 _PyObject_GC_Malloc + 213
2   Python                        	0x0000000105ff6f5d _PyObject_GC_New + 18
3   Python                        	0x0000000105fa8ed2 new_weakref + 28
4   Python                        	0x0000000105fa8d8e PyWeakref_NewRef + 104
5   Python                        	0x0000000105f806f5 add_subclass + 66
6   Python                        	0x0000000105f7ed2c PyType_Ready + 5181
7   Python                        	0x0000000105f73d92 _Py_ReadyTypes + 356
8   Python                        	0x0000000105fe3031 _Py_InitializeEx_Private + 439
9   launch                        	0x0000000105d7963c main + 284
10  libdyld.dylib                 	0x00007fff804365ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00000001060299ab  rsi: 0x0000000000000000  rbp: 0x00007fff59e86bc0  rsp: 0x00007fff59e86b00
   r8: 0x0000000000000003   r9: 0x0000000000000000  r10: 0x0000000000000004  r11: 0x00007fbd91400000
  r12: 0x0000000000000000  r13: 0x0000000000000170  r14: 0x0000000000000000  r15: 0x000000010609a6e0
  rip: 0x0000000105ff63ce  rfl: 0x0000000000010202  cr2: 0x0000000105fd502a
  
Logical CPU:     6
Error Code:      0x00000000
Trap Number:     6

**Comment by jonoomph** [comment] 2016-03-17 02:48
Thanks for the bug report. This is actually a duplicate of #75, and will be fixed in the next release (coming soon).

**Closed by jonoomph** 2016-03-17 02:48 UTC
