### ISSUE TITLE
Aspect Ratio of Preview Window

### ISSUE THREAD

**Issue by emmemmberlin** [OpenShot/openshot-qt#1796] opened 2018-07-05 15:19 UTC
Hi there,
i could not find a way how the preview window (and hence also all animations etc) uses the aspect ratio of my selected profile. It seems to remain in 16:9, while, for example, my profile is 9:16.
Could you please help?
thanks
Matthias

**Comment by peanutbutterandcrackers** [comment] 2018-07-05 23:57
Duplicate of #456 #731 #835 #1093 (item # 4) #1144 #1402

**Comment by peanutbutterandcrackers** [comment] 2018-07-06 00:00
@emmemmberlin - Hi there! This is currently a fix-in-progress. A [PR](https://github.com/OpenShot/openshot-qt/pull/1407) has already been made to fix this. Please follow the discussion over at one of the issues given here. This should be fixed soon. I will try to make this high-priority (so as to get it fixed in the 2.4.2.x bug fix series). Closing this for now (in order to maintain the huge amount of issues that we have) as this is a duplicate.

Please do keep on loving and supporting OpenShot! This [free software](https://en.wikipedia.org/wiki/Free_software) gem will only get better with time. :)

**Closed by peanutbutterandcrackers** 2018-07-06 00:00 UTC
Labels: duplicate
