### ISSUE TITLE
When previewing or exporting MP3 audio files, the software closes immediately

### ISSUE THREAD

**Issue by Evo224** [OpenShot/openshot-qt#2756] opened 2019-04-29 06:40 UTC
**Describe the bug:**
I have a video with an mp4 video playing over a slide-show of images. I added in another audio track for music (mp3) and now sometimes when I preview the MP3 part the software will close/crash. When I try exporting, the same thing happens when it gets to the percent where it would be exporting the mp3 file. 

**Steps to reproduce the behavior:**
1. Import an Mp3 file
2. Add it to the time line
3. Press play and skip to the part where the mp3 starts playing
4. Application freezes for a bit, then closes. Same result when exporting; application freezes then closes. 

**Expected behavior:**
When the bug occurs, the software just closes. I've tried different formats and settings, but the issue seems inherent to the mp3 file.

**System Details:**
- OpenShot Version 2.4.4 (downloaded today): 
- Operating System / Distro: Windows 10

**Log Files:**
[openshot-qt - Copy.log](https://github.com/OpenShot/openshot-qt/files/3126167/openshot-qt.-.Copy.log)
I could not compress it into a zip, so hopefully this works. 

If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
I am not seeing any popup messages, I crash and then when I restart the program nothing comes up.

**Comment by SuslikV** [comment] 2019-04-29 13:34
Something special about your mp3? I cannot reproduce the issue.
And if you make new project? Restart OpenShot, add your mp3 and export the blank (black screen) video. Is it crashes? Attach new logs (from this attempt) please.

**Comment by Evo224** [comment] 2019-04-29 19:04
> Something special about your mp3? I cannot reproduce the issue.
> And if you make new project? Restart OpenShot, add your mp3 and export the blank (black screen) video. Is it crashes? Attach new logs (from this attempt) please.

I tried restarting and in a fresh project exporting the same MP3, same result. I think I might have found the cause: the MP3 gets imported as a video rather than audio, so maybe it is trying to render visuals where there are none?

**Comment by Evo224** [comment] 2019-04-29 19:05
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3128831/openshot-qt.log)
The log file from after I tested it again, not sure if they actually got updated though.

**Comment by SuslikV** [comment] 2019-04-30 09:18
To workaround this, please import into OpenShot only mp3 files without album cover or any other images included.

Workaround steps:
1. Copy your mp3 file to new folder (this file will be modified)
2. Open this copied mp3 file with the foobar2000 player (I tested with old v1.2.9)
3. Stop foobar2000 playback.
4. Right-click over desired track (you may select number of files) and choose option _Tagging->Remove all pictures_

See screenshot under the spoiler
<details>
  <summary>Click to expand</summary>

**foobar2000 v1.2.9**

![foobar_remove_images_from_mp3_file](https://user-images.githubusercontent.com/19683044/56949942-ee326280-6b3c-11e9-9331-17d2e176beef.png)

</details>

5. Agree to the confirmation dialog to remove the picture.
6. The file will be automatically overwritten.
7. Import this updated (by foobar2000) file into OpenShot.

Now the file should import into OpenShot as Audio only.

--------
The example files to help discover the bug, ~32KB to download (CRC of the zip archive MD5:E953A725BF558E3EBE219B01BF28F24A):

[OpenShotAudioTestMP3WithImage.zip](https://github.com/OpenShot/openshot-qt/files/3130527/OpenShotAudioTestMP3WithImage.zip)

Includes two stereo mp3 files, 2 sec long, 1 kHz tone in the Right channel; silence for 1 sec and then same 1 kHz tone in the Left channel.

Actually, the mentioned files didn't produce any freeze or application crash for me (OpenShot-v2.4.4-1553153504-d04a71ee-fbfac789-x86_64.exe). But sound file with the embedded image has stutters during preview playback in the _Timeline_ , and that stutters renders back into the exported file. So, it's issue with the file import of OpenShot.

I think, for the mp3 container OpenShot should ignore any video data (to not attempt to import it as MJPEG as it do it right now).

**Comment by ferdnyc** [comment] 2019-10-25 23:57
Closing as a duplicate of #3043, the issue is being tracked there.

**Closed by ferdnyc** 2019-10-25 23:57 UTC
Labels: :beetle: bug, duplicate

**Comment by theoryshaw** [comment] 2019-10-31 13:14
+1 - same.
