### ISSUE TITLE
crop function  OS X

### ISSUE THREAD

**Issue by osvtonosx** [OpenShot/openshot-qt#1077] opened 2017-11-28 11:53 UTC
**System Details:** OS X 10.5
* Operating System / Distro: ? OS X 10.5
* OpenShot Version: ?  2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Hi
I'm looking for the crop commands, sorry and thanks
i hope you can see the screens here:
https://user-images.githubusercontent.com/33726263/33184626-d317295a-d07d-11e7-8202-ed85bd38bfff.png

**Comment by osvtonosx** [comment] 2017-11-28 11:58
to be sure :)
I'd like to take off a part of the picture all around ( cause I have artfacts on border line)

Thanks

**Comment by N3WWN** [comment] 2017-11-28 14:40
Looks like you're in the right place in the properties, but using the opposite values needed.

The scale values of 0,57 and 0,62 will shrink the clip, effectively giving you a border around the video (zoomed out).  

If you increase the scale values over 1, the image will be expanded (zoomed in) and the edges will be outside of the view port and therefore invisible.  

Think of the values as a percentage.  0,57 will make the video 57% of it's original size (43% smaller) and a larger value, like 1,20, will make the video 120% of it's original size (20% larger).

**Comment by osvtonosx** [comment] 2017-11-28 15:13
Thank you Richard
found it but the situat ion is one video track is 1/4 left up corner with the artifact on right descending line, with a another track full screen behind... so I'd like to cut an edge of the 1/4 video...

**Comment by N3WWN** [comment] 2017-11-28 15:47
Ah!  I do the same thing (just lower left corner) 😁 

To get rid of my border artifacts and to set the overlayed video apart from the background video, I created a transparent 1280x720 still image with an opaque border.  I place this "frame" image on a track above the overlayed video, scale it accordingly and place it where I want it.  I then right-click on the "frame" clip, `Copy -> Keyframes -> All`, select the overlayed video, right-click and `Paste`.  The overlayed video will be scaled and moved to the same location as the "frame" image, making alignment easy peasy.

I find that `Scale: Best Fit` doesn't always work and the Scale property is not copied between the clips with Copy/Paste, so I set the Scale to `Stretch` manually on both videos to ensure that everything fits as intended.

While I thought that I'd need different sized "frame" images for different resolutions, but, so far, this one "frame" image works just fine regardless of HD resolution.

For completeness, here are the properties that I set on the "frame" image (I use the same ones each time, so it's easy once you remember them):

**Lower Left Picture-In-Picture**
> Gravity: Bottom left
Location X: 0.01
Location Y: -0.01
Scale: Stretch
Scale X: 0.40
Scale Y: 0.40

**Lower Right Picture-In-Picture**
> Gravity: Bottom right
Location X: -0.01
Location Y: -0.01
Scale: Stretch
Scale X: 0.40
Scale Y: 0.40

Let me know if you need any additional help using this technique.  

Included below is the "frame" image that I use, in case you find it useful.

![video frame 1280x720 - 170504](https://user-images.githubusercontent.com/19431804/33328687-9cfc3f6e-d428-11e7-9bca-3d3ac831e0f3.png)

**Comment by osvtonosx** [comment] 2017-11-29 19:03
I will post some pictures to show a few artifacts in relation with chrominance...

**Comment by osvtonosx** [comment] 2017-11-29 19:43
could find a solution by changing the " canal alpha" values :) thanks

**Comment by osvtonosx** [comment] 2017-12-01 09:41
in a different way, tried a short piece...
https://www.youtube.com/watch?v=ZcQR8cBPGL4

**Comment by DylanC** [comment] 2018-01-04 13:58
Closing as this seems to be sorted. Thanks @N3WWN

**Closed by DylanC** 2018-01-04 13:58 UTC
