### ISSUE TITLE
"duplicate titles" hotkey does not work

### ISSUE THREAD

**Issue by Asteroid1642** [OpenShot/openshot-qt#3310] opened 2020-03-21 19:51 UTC
**Describe the bug:**

"duplicate titles" hotkey does not work.
 I wanted to reassign it, but there is not even such an option in the hotkey settings.
The function itself works if you click on the context menu.

**System Details:**
- OpenShot Version: 2.5.1-dev2
- Operating System:  Windows 10

**Comment by ferdnyc** [comment] 2020-03-22 18:07
Ah! Well, it's obvious why that would be the case:
![image](https://user-images.githubusercontent.com/538020/77256698-2a375000-6c46-11ea-96ca-39f1b57dfc02.png)

Pretty sure you can't have two actions with the same shortcut. And, indeed, in our default mapping <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> is _neither_ of those, it's Add Track. Which is why it blocks both of them from working.

I'm going to have to change it anyway, since Add Track is already established, so what were you going to change it to? I can probably just make that the new default. :laughing:

**Comment by ferdnyc** [comment] 2020-03-23 01:50
I had to pick something, so I went with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>. Should hopefully be fixed in development soon.

**Comment by Asteroid1642** [comment] 2020-03-23 17:10
I tried reassigning the "Add Track" keyboard shortcuts. "Duplicate title" still did not work.

**Comment by ferdnyc** [comment] 2020-03-24 03:48
Okay, wow. That's the SECOND time that's happened! I've been trying out Github's new Android app, and whenever I "Quote reply" to a message in a repo, it ends up EDITING the original message instead!

Apologies @Asteroid1642 , that wasn't my intention at all. I'll fix up your message just as soon as I uninstall that screwy app!

**Comment by ferdnyc** [comment] 2020-03-24 03:52
> I tried reassigning the "Add Track" keyboard shortcuts. "Duplicate title" still did not work with Ctrl+Shift+T.

No, it wouldn't yet, there's no implementation of keyboard controls for Duplicate Title or Edit Title in the 2.5.1 code. For now those are essentially just decorative labels.

I'll update this issue when the problem is fixed in development, then you'll be able to test it by installing a Daily Build. Sorry for the delay.

**Closed** 2020-05-09 22:54 UTC
Labels: :beetle: bug, interface
