### ISSUE TITLE
French language not detected when install v2.4.2

### ISSUE THREAD

**Issue by dmapdm** [OpenShot/openshot-qt#1784] opened 2018-07-04 05:58 UTC
**Describe the bug**
After a new installation, At first launch the Language is not in French for me.

**System Details (please complete the following information):**
 - Operating System / Windows 10
 - OpenShot Version [e.g. 2.4.2]

**To Reproduce**
Installation with unattended option is ok
OpenShot-v2.4.2-x86_64.exe /SILENT /NORESTART /CLOSEAPPLICATIONS
at the first launch, i'm in english language. i need go to the preferences to change it.
Before with 2.4.1 it was automatic.

**Expected behavior**
I'm an little integrator in France, I install for all user your software: great jobs man (girls ?)

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by peanutbutterandcrackers** [comment] 2018-07-04 06:11
@dmapdm - Thank you for the report. This is a duplicate of #1608. We will work on solving this too, soon. Could you please follow the discussion over there? Closing this as a duplicate so as to manage the amount of issues.

**Closed by peanutbutterandcrackers** 2018-07-04 06:11 UTC
Labels: bug, duplicate
