### ISSUE TITLE
Ends of all clips freeze for 1-2 seconds unless a transition is applied

### ISSUE THREAD

**Issue by mokahless** [OpenShot/openshot-qt#2609] opened 2019-02-12 21:42 UTC
I unfortunately made the poor choice of using Openshot to edit my videos. Fortunately, end-quality is more affected by the poor source (720p at 10fps with long exposures for each frame and a poor lens for low light) than by my editing ability or that of the program so I pushed forward regardless.

Anyway, this is the first of the (many) issues I've had with openshot during the process that doesn't already have an existing bug report (some issues I've run into have bug reports going back as far as 2009 - still unsolved - but I was able to get around them with workarounds).

Source videos: H264 in .3gp container, 2-channel AAC audio, variable video frame rate averaging 10fps.

Issue: Any clip added to the project has the video freeze 1-2 seconds before the end of the clip. Audio continues. Exporting the project maintains this issue. Issue is present on both an Intel i7 8750H and an AMD 2700X system. Operating system was Windows 10 on both.

I've been working around the issue using fades and effects at the end to cut off those couple seconds of freezing.

I tried shaving off the last 0.1 seconds of the clip to see what would happen. The end of the clip became where it would freeze before while for some reason some of the freezing moved to about 0.5 before it was before, then it would resume before continuing on to where it initially froze, then freeze as before.

Another observation: Since my original test encode, it's almost like this issue has become more prevalent. The more I move the clips around, the worse it gets. At one point, the entire audio of one file became distorted and stuttery. I had to revert to my backup project file.

Sorry I can't provide the video and project files as it is a personal video.

Anyway, I figured I'd file the bug report. I hope someday this project becomes usable. I'm using 2.4.3, the latest version as of writing.

**Comment by ctsdownloads** [comment] 2020-05-19 20:44
Old version of OpenShot. Closing as it's outdated.

**Closed by ctsdownloads** 2020-05-19 20:44 UTC

**Comment by discgolfer5000** [comment] 2021-08-31 15:21
This issue happens to me also with OpenShot versions 2.5.1 and 2.6.0 on Windows 10. I've done complete uninstalls and manual file removals.

The last 8 frames are static in the OpenShot preview, scrubbing frame by frame, and in the exported video, but not in the source clip or frames.

It happens whether I import my source clip as an mp4, mkv, or a png image sequence of 120 frames.

I tried a different free and open source video editor and the same clips/frames worked fine there, so the issue is within OpenShot.

Issues #2435, #2609, #3585, #4032 all appear to be the same, some of which have auto-closed while unresolved.

**Comment by JacksonRG** [comment] 2021-08-31 18:42
@discgolfer5000

What is the frame rate of the source file, and what's the frame rate that you're trying to export at?

**Comment by discgolfer5000** [comment] 2021-08-31 19:29
Hi @JacksonRG, thank you for responding! I am new here and signed up for github just to report this issue.

I am trying to do everything at 30fps (OpenShot project is set to 30fps), although with an image sequence of png files I don't think there is any frame rate defined there. The issue appears to while importing. I have turned debug settings and done some logging as detailed in the rabbit hole that is issue #3585 and I am seeing that my 120 image sequence frames at 30fps (duration 4.00s) is somehow behind the scenes being overridden by 25fps in many places and I see an incorrect duration value (4.80s). Here is what I think is the relevant from the version 2.6.0 logs. Note all the "25.0000" references. Hope it helps.

INFO files_model: Prompt user to import sequence starting from wf_0001.png
INFO files_model: Imported D:/frames/wf_0001.png as image sequence wf_%04d.png
INFO logger_libopenshot: Decode in software is used
 ()
INFO project_data: _set key: ['files'] values: {'acodec': '', 'audio_bit_rate': 0, 'audio_stream_index': -1, 'audio_timebase': {'den': 1, 'num': 1}, 'channel_layout': 4, 'channels': 0, 'display_ratio': {'den': 9, 'num': 16}, 'duration': 4.800000190734863, 'file_size': '8294400', 'fps': {'den': 1, 'num': 30}, 'has_audio': False, 'has_single_image': True, 'has_video': True, 'height': 1080, 'interlaced_frame': False, 'metadata': {}, 'path': 'D:/frames\\wf_%04d.png', 'pixel_format': -1, 'pixel_ratio': {'den': 1, 'num': 1}, 'sample_rate': 0, 'top_field_first': True, 'type': 'QtImageReader', 'vcodec': '', 'video_bit_rate': 0, 'video_length': 120, 'video_stream_index': -1, 'video_timebase': {'den': 30, 'num': 1}, 'width': 1920, 'media_type': 'video', 'id': '65P9US4ODA'} add: True partial: False remove: False
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (info.fps.num=25.0000, info.fps.den=1.0000)
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (pStream->avg_frame_rate) (num=25.0000, den=1.0000)
INFO logger_libopenshot: FFmpegReader::Close ()
INFO logger_libopenshot: Decode in software is used
 ()
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (info.fps.num=25.0000, info.fps.den=1.0000)
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (pStream->avg_frame_rate) (num=25.0000, den=1.0000)
INFO logger_libopenshot: FFmpegReader::Close ()
INFO logger_libopenshot: Decode in software is used
 ()
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (info.fps.num=25.0000, info.fps.den=1.0000)
INFO logger_libopenshot: FFmpegReader::UpdateVideoInfo (pStream->avg_frame_rate) (num=25.0000, den=1.0000)

**Comment by JacksonRG** [comment] 2021-08-31 19:44
Could you provide a zip file? As simple as possible to exemplify the problem. Once we developers can reproduce the bug, we'll be much closer to solving it.

**Comment by JacksonRG** [comment] 2021-08-31 19:52
@discgolfer5000
Also please try right clicking on your image sequence and going to the properties.

Here you'll find the image sequence's frame rate. Changing this to match your project frame rate may help.

**Comment by discgolfer5000** [comment] 2021-08-31 20:05
The image sequence properties already default to the project frame rate of 30. What all would you like to have in the zip file? I tried zipping a project and all the frames to import but the zip file is too large for github.

**Comment by JacksonRG** [comment] 2021-08-31 20:17
Just the smallest project that still has the problem. If you can reproduce the error with just a shorter image sequence and no other files, that would be ideal

**Comment by discgolfer5000** [comment] 2021-08-31 20:22
OK, I have taken it down to just 12 frames and added numbers to each one. A small zip file is attached with the frames, project file, and an exported mp4. Let me know if you need more.
[frames.zip](https://github.com/OpenShot/openshot-qt/files/7086626/frames.zip)

**Comment by discgolfer5000** [comment] 2021-08-31 22:08
This might explain why the log files showed a lot of 25 fps values, assuming the code is using this to read from a list of image files specified by a pattern:

"framerate
Set the frame rate for the video stream. It defaults to 25."

https://www.ffmpeg.org/ffmpeg-formats.html#image2-1

Maybe if you can pass the openshot project's frame rate value using this framerate option, it will override the default of 25. I will be curious what you find out.
