### ISSUE TITLE
Rename/label clips in timeline

### ISSUE THREAD

**Issue by FF-Brown** [OpenShot/openshot-qt#5539] opened 2024-06-13 04:58 UTC
**Describe the problem:**
Somewhat often I have enough clips of a single video floating around (haven't found their place yet) that I start to lose track of what they contain. Since the preview only shows the video in the top track, it's annoying when I forget what's in a clip to have to shift things around to put it on the top track to see what's in it again.

**Describe the solution you'd like:**
Easiest would be to add the ability to rename a clip in the timeline without changing the name of the source video.

**Describe alternatives you have considered:**
Another alternative would be a way to preview clips that are not in the top track. Maybe this already exists, and if so it would solve my problem, but I have yet to find it.

Loving this tool so far, though!

**Comment by Colorjet3** [comment] 2024-06-13 12:14
Hello @FF-Brown I can submit an enhancement request for the lead developer to review/approve/reject.  However, I need further clarification.  If you can, please provide me a step-by-step use case so I can review it with you.  Other users will benefit from further clarification and might have additional input.

Once clearly defined, I can ask the lead developer to review/approve/reject.  If approved, then we will create an enhancement request and put it in the queue.

I am aware of one enhancement request in the queue that has to do with hiding Tracks.  Meaning, if you have clips on Tracks 5 & 4 but you just want to deal with Track 4, you can right click on Track 5 header and select hide.  The idea would be that now, when you preview it only plays the content of Track 4 and any other clips on tracks below it.  This is not a simple task as there are many other factors that have to be considered.

Thank you!

**Comment by FF-Brown** [comment] 2024-06-13 15:40
Thanks for the response! I'll try to give some more detail. 

This would be useful when I've got one or more videos that I have split into multiple clips that I'm piecing together. So, there are a lot of clips on the timeline. One way it could work is to right-click a clip on the timeline and have the option to either Rename or Tag/Label. It would preserve the name of its source video in the background but display the new name in its place. So I could label each clip with its contents roughly indicated and avoid mixing up clips for different scenes. 
So essentially I'm looking for the option to set an alias for a specific clip. 
If an aliased clip gets split, the alias could just get assigned to both new clips so it's clear where they came from, and they could be renamed if necessary. 

That timeline hiding feature could do the trick if it's easy to turn on and off. Sounds like a neat idea. This is something I'd want to do often (remind myself what the contents of a particular clip are) so if it took more than a couple clicks it wouldn't be worth it. Current workaround is to have my "main" track be the second from the top, and my main working track just below that so I can move stuff up to the top track when I need to check on it. So it'd need to be easier than that to be helpful.

**Comment by ronzulu** [comment] 2024-07-06 03:15
I would also find this  enhancement useful. Great product!

**Comment by Colorjet3** [comment] 2024-07-08 17:10
Thank @FF-Brown for the additional information and @ronzulu for seconding this enhancement.

A recent enhancement was made that is included in the latest dev daily build (openshot.org/download/#daily) that gives you a bit more control over the labeling/tagging of clips.  However, this feature/functionality is not on the timeline, for now.

1.  Download/install the latest dev daily build.
2.  Start a new project and import a video file.
3.  Right click in an empty spot in the "Project Files" window and select "Details  View".
4.  In the Name column, double click the Name value and change it to "Test 01"
5.  Now drag this onto the timeline and note the Name.

Shortcomings:
1.  If you rename the file in "Project Files", drag it onto a timeline, that name stays on the timeline.  It is not linked back to the file in "Project Files.
2.  Meaning, if you rename the file again in "Project Files" window, that name change does not reflect on the timeline.  However, if you drag this file onto the timeline, now the new name is assumed on the 2nd clip on the timeline.

This solution isn't fully baked yet, but just small steps to make it a bit easier to identify clips on the timeline.  Here are a few tricks that I use to leverage this functionality:
1.  In the Shortcomings section, I resolve this by:
a.  Right click on the imported file in "Project Files".
b.  Select "Split Clips".
c.  For Choose Start and End, I select the first frame and the last frame, I can give it a Name right away or rename it later.
d.  Essentially, I just created a duplicate of my original imported file.  I can repeat 1.c as many times as needed.
e.  Additionally, I can split the original files into shorter clips and rename them as well.

This is a start and hope it gives you some more flexibility.

Appreciate any feedback on your thoughts on this feature and if you find it helpful for now.

**Comment by ronzulu** [comment] 2024-08-04 08:28
Hi @Colorjet3, I'm only a novice user, but it does do what I was hoping for! Thanks!

**Closed as completed** 2024-08-04 16:54 UTC
Labels: 💡 enhancement

**Comment by FF-Brown** [comment] 2025-03-27 20:51
> A recent enhancement was made that is included in the latest dev daily build (openshot.org/download/#daily) that gives you a bit more control over the labeling/tagging of clips. However, this feature/functionality is not on the timeline, for now.

I might pull that dev build down. This would be super helpful.

As for the workaround of splitting the clip from the list of Project Files, this has been helpful for me. At least it lets me break up the project files there. The problem is once I add them to the timeline, it reverts to naming them with the file path, not the name I just gave them when splitting, which kinda defeats the purpose.

Will try out the dev build with the naming feature. From what you described, I think that would be exactly what I need. The name not staying current with the Project Files name doesn't matter to me. I do a lot of splitting and rearranging in the timeline. There's not really any back-and-forth between the Project Files and the Timeline for me. So it'd be awesome if that feature got added to the release.

I thought I replied to this ages ago, just now came back to remind myself what the suggested workaround was and saw I never did.
Thanks!

**Comment by Colorjet3** [comment] 2025-06-19 01:10
Hello @FF-Brown 

I wanted to inform you that there is a new version about to be released into production in the coming weeks.  v3.4.0-Release-Candidate-.... is going through testing right now.

In this version, and enhancement has been implemented so that when you use the Split File option, and you provide a name to the new split file you created, that name now is maintained when you drag it onto the timeline.

For example,
1.  You import a file into OpenShot.
2.  You right click on the imported file and select "Split File".
3.  You select a Start and End Frames and you name it Test01 (let's assume that your original file you imported is name Test).
4.  When you click on Create, you will see a new file in the Project Files named Test01.
5.  Now drag Test01 onto a track and note that the name on the clip is Test01. 

Previously (or in the current version), the clip would revert back to the source file (Test).

If you have time, and willing, please give v3.4.0 a try.  Go to openshot.org/download/#daily and get v3.4.0-Release-Candidate.

**Comment by FF-Brown** [comment] 2025-06-23 06:16
@Colorjet3 That sounds amazing! Yeah I'll check it out this week, thanks for letting me know!

**Comment by Colorjet3** [comment] 2025-07-29 14:11
Hello @FF-Brown Did you get a chance to test this out?  Just looking for feedback on how it worked for you.

**Comment by FF-Brown** [comment] 2025-07-29 22:24
Haven't yet but I will, and I'll let you know. Exciting work, though!

**Comment by FF-Brown** [comment] 2025-07-30 03:27
@Colorjet3 Just tested it out - sorry for the delay. It looks great! Exactly what I needed. It'll be so much easier to keep track of my clips, their content, and their origin now. Thank you!

**Comment by Colorjet3** [comment] 2025-07-30 13:27
That is great @FF-Brown Good luck with your projects.
