### ISSUE TITLE
Make Computer Fonts Available In Titles

### ISSUE THREAD

**Issue by bbacle** [OpenShot/openshot-qt#3270] opened 2020-03-01 22:57 UTC
Make all fonts on the computer available to be used in OpenShot.

**Comment by ferdnyc** [comment] 2020-03-02 01:07
Unfortunately not possible, sorry. That's a Blender limitation, out of our control. See #3063.

Closing as duplicate of #3063

**Closed by ferdnyc** 2020-03-02 01:07 UTC
Labels: duplicate, 💡 enhancement
