### ISSUE TITLE
OpenShot 3.0 in Ubuntu 22.10 - Preview Audio Device change - no effect

### ISSUE THREAD

**Issue by jgruber** [OpenShot/openshot-qt#5135] opened 2023-02-10 11:38 UTC
**Describe the bug:**
I've tried the latest daily AppImage and the openshot-qt debian package. Preview audio ALWAYS uses the default ALSA audio device. Switching audio device in Preview preferences and restarting does not change the audio playback device at all.

**Steps to reproduce the behavior:**
1. Go to 'Edit' -> 'Preferences' -> 'Preview' tab
2. Change 'Playback Audio Device' to any device
3. Hit 'Close' button
4. Hit 'OK' button on 'Restart Required' modal dialog
5. Restart OpenShot (acknowledging UI preserves changes in audio device)
6. Open a Project
7. Play preview
8. Listen to audio come out default ALSA device, no matter what you set in the UI

**Expected behavior:**
Preview audio playback stream set to ALSA device selected UI.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: openshot-qt version: 3.0.0
- Operating System / Distro: Ubuntu 22.10 (gnome desktop) - platform: Linux-5.19.0-29-generic-x86_64-with-glibc2.36

**Log Files:**
None - No errors on debug - see correct 'INFO project_data: Apply default audio playback settings: 48000, 2 channels' - device is 48000 sample rate.. 

**Exception / Stacktrace:**
None

**Screenshots:** (Optional)
None

**Comment by sc0nway** [comment] 2023-05-16 02:51
Hi @jgruber!
Please try downloading and installing our latest version of OpenShot from our Website at https://www.openshot.org/download/. You can download our AppImage or use our PPA by following the links on the Download page. Our development team spent a lot of time resolving audio issues and included the fixes in OpenShot v3.1.1.

**Comment by ammgws** [comment] 2023-06-10 01:19
I experience this issue on 3.1.1 (via https://archlinux.org/packages/extra/any/openshot/), so perhaps there is a remaining bug..

**Comment by jgruber** [comment] 2023-06-11 16:37
Sorry for the delay.. 3.1.1 installed. No change in behavior. The preview audio devices remained fixed, no matter what UI has selected.

**Comment by johntrimble** [comment] 2023-08-20 04:28
I'm also having the same issue. OpenShot version 3.1.1 and Ubuntu 22.10

**Comment by johntrimble** [comment] 2023-08-20 04:41
For those looking for a workaround, I changed the default audio device in alsa so that OpenShot would use my preferred audio device during the preview. You can get a list of your audio devices via:

```
cat /proc/asound/cards
```

Edit or create or create `/etc/asound.conf` as so:

```
defaults.pcm.card 2
defaults.ctl.card 2
```

Replacing the 2 above with the audio device number from `/proc/asound/cards`. You can then reload alsa with:

```
sudo alsactl restore
```

**Comment by Colorjet3** [comment] 2023-08-20 18:38
Thank you @johntrimble for the workaround.  This same issue also exists in Windows operating system environments.  OpenShot, during startup, always looks at the sample rate for the Default Audio Device set in the operating system and matches it.

This is really not a bug but rather an understanding of how OpenShot works.

**Closed as completed by Colorjet3** 2023-08-20 18:38 UTC

**Comment by johntrimble** [comment] 2023-08-20 19:03
> This is really not a bug but rather an understanding of how OpenShot works.

@Colorjet3 why is there an option to change the audio device in the preferences if it is not expected to work?

**Comment by Colorjet3** [comment] 2023-08-20 19:47
Hello @johntrimble That is a very good question.  What I can tell you for sure is that the change in the code regarding the audio happened primarily when Microsoft, starting with Windows 11 and then Windows 10 changed the sample rate from 44100 to 48000 for the operating system default devices.  This assumes that the audio device can handle the 48000 setting.  When this change was made by Microsoft, OpenShot was not accounting for it and was hard set to 44100.  This caused many issue with audio (crackling, no audio, garbled audio, etc.).  During the troubleshooting we identified the issue having to do with the mismatched sample rate.

The lead developer then decided to add new code in OpenShot to check the sample rate of the operating system environment and ensure that OpenShot matches it.

It most likely should be greyed out.  I like the fact that it is there so you know that at least OpenShot is correctly matching your operating system default audio device sample rate.

I hope this makes sense.  I will bring this up with the lead developer for a future enhancement.

**Comment by johntrimble** [comment] 2023-08-20 20:00
Interesting, so two things that makes this confusing:

1. There is an audio device selector which currently has no effect
2. The default audio device set through the Ubuntu desktop interface is not the same "default" audio device used by OpenShot

You've addressed 1, but it might be nice if for 2 OpenShot used the default audio device set in the Ubuntu desktop environment. I'm not sure how hard that is, the fact the default desktop audio device is not the same as the default alsa audio device does not bode well, but other applications (Zoom, Chrome, etc.) seem to figure this out.

I like the idea of keeping the audio device used by OpenShot visible in some fashion (such as via a greyed out audio device selector as you mentioned) for cases like this where, somehow, an unexpected audio device is being used.

**Comment by Colorjet3** [comment] 2023-08-20 21:23
Yeah, I don't know either about the technical challenges with the code.  I did assign this ticket to the lead developer as well.  This is a very small team and very dependent on volunteers so things don't move very fast, unfortunately.

Once the lead developer has had a chance to review this, he will then decide if further action is needed and submitted to the queue of fixes and enhancements for a future release.

**Comment by eric-burel** [comment] 2023-10-31 20:40
Hi, I couldn't get any sound and couldn't display any other device than "Default" in the preview config tab. However downloading and running the latest daily build (09/10/2023) got the sound back in preview for me.
