### ISSUE TITLE
Error opening OpenShot 2.4.3

### ISSUE THREAD

**Issue by osve001** [OpenShot/openshot-qt#2421] opened 2018-12-02 19:31 UTC
**Describe the bug**
Double-clicking the .osp file does not open the project and the attached error message is displayed.
![openshot243_error_message](https://user-images.githubusercontent.com/28224249/49343837-34f45d00-f670-11e8-878c-10ea60d4a3f9.png)
On the other hand, it works fine just by opening first OpenShot, and then opening your .osp file.

**System Details (please complete the following information):**
 - Operating System: Windows 10 Pro
 - OpenShot Version: 2.4.3

**To Reproduce**
1. Double-click an .osp file

**Expected behavior**
Open the project as usual, just by double-clicking the file (OpenShot 2.4.1 worked fine with that)

**Screenshots**

**Logs**

**Additional context**

**Comment by peanutbutterandcrackers** [comment] 2018-12-15 03:07
Please delete the `.openshot_qt` folder that exists in the same folder as the one where `My Documents` exists, and then this should work.

Closing as a duplicate of #2429 (as that issue has got more discussions).

**Closed by peanutbutterandcrackers** 2018-12-15 03:07 UTC
