### ISSUE TITLE
Audio did not output to export file. When playing back the exported file there was no sound output.

### ISSUE THREAD

**Issue by BigRed1963** [OpenShot/openshot-qt#1718] opened 2018-06-21 00:45 UTC
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by N3WWN** [comment] 2018-06-21 13:50
@DylanC - I think we can add this to the ever-growing list of incompatible audio codec issues that we've been seeing.  Issue #1594 (resolved by PR #1595) should fix this, provided the new build system provides aac support for all builds.

@BigRed1963 - Please try [VLC](https://www.videolan.org/vlc/index.html) to test if the audio is, in fact, present, but simply unable to be decoded by your normal player.  If so, the items I mentioned above to DylanC will resolve this problem, when they are finalized into all of the builds.

**Comment by BigRed1963** [comment] 2018-06-21 16:01
Playing on VLC did reproduce the sound.


Gary Carson
10612 West Schimmer Drive
Wood River, NE 68883-9658

Cell: 308-379-7542
E-mail: garyhcarson@msn.com<mailto:gcarson@charter.net>

**Comment by N3WWN** [comment] 2018-06-21 17:14
@BigRed1963 - Thanks for confirming this!

@DylanC (and @peanutbutterandcrackers) - Since this is again confirmed, should we put this in the rc-bugs so it's definitely considered before 2.4.2 is published?

**Comment by DylanC** [comment] 2018-06-22 07:27
@N3WWN - I think so but I'll wait until @peanutbutterandcrackers shares his opinion.

**Comment by peanutbutterandcrackers** [comment] 2018-06-22 08:20
@N3WWN @DylanC - Yes, I definitely think this is high priority. I will put this on the rc-bugs right away and let Mr. Thomas know about it. Maybe he can cherry-pick the fix, if not merge it in. But this definitely needs attention.

**Comment by peanutbutterandcrackers** [comment] 2018-06-22 08:27
Done!

**Comment by DylanC** [comment] 2018-07-02 10:09
@BigRed1963 Can you try v2.4.2 and let us know if you have any success?

**Comment by BigRed1963** [comment] 2018-07-03 13:54
When I try to export a project – several different formats – I get “Export Error”

Gary

**Comment by peanutbutterandcrackers** [comment] 2018-07-04 03:04
@BigRed1963 - Sir, are you sure you are using v2.4.2 (it's available at openshot.org)? If this issue is really there in version 2.4.2, I would suggest that you [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) and also, please do tell us which profile you are trying to export to. Thank you.

**Closed** 2018-07-27 14:54 UTC
