### ISSUE TITLE
Windows: Cannot save project file on D:

### ISSUE THREAD

**Issue by wgemm** [OpenShot/openshot-qt#105] opened 2016-02-18 18:40 UTC
Hi,
I am using Version 2.0.6 on Windows 7.
I cannot save the project file on D:
When I save the project I get a message "Error saving the project"
path is on mount 'C:', start on mount 'D:'

Wolfram

**Comment by wgemm** [comment] 2016-02-18 18:43
Some more details.

I even cannot save it on C:. I have a special case. I have moved my Windows "Documents" folder to D:. 

If you need more details just drop me an email.

Wolfram

**Comment by BF3000** [comment] 2016-02-18 19:11
Duplicate of bug #79
Will be fixed in the next release.

**Closed** 2016-03-17 03:38 UTC
