### ISSUE TITLE
Slicing slices all tracks at the same time when you use keyboard shortcuts

### ISSUE THREAD

**Issue by guiljo** [OpenShot/openshot-qt#3500] opened 2020-05-18 15:43 UTC
**Describe the bug:**
When you slice a clip on a track using a keyboard shortcut, clips get sliced on the other tracks

**Steps to reproduce the behavior:**
1. Add a clip on track 5 and one on track 4
2. Select the timing where you want to slice your clip
2. Click on track 5 to select only one clip
3. Slice using one of the keyboard shortcuts (eg. Ctrl + K...)
4. Both clips get sliced

**Expected behavior:**
Only the selected clip(s) gets sliced.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Windows 10

**Screenshots:**
![image](https://user-images.githubusercontent.com/13487812/82232149-8361ee00-992e-11ea-9d5c-ad89bdf84ed5.png)
![image](https://user-images.githubusercontent.com/13487812/82232209-9c6a9f00-992e-11ea-8943-ad069206ff15.png)

**Comment by ferdnyc** [comment] 2020-05-18 17:03
@guiljo 

This was fixed by #3447, which added new shortcuts <kbd>s</kbd>, <kbd>a</kbd>, and <kbd>d</kbd> for slicing just the selected clip(s). However, you'll have to use a Daily Build, or wait for the 2.5.2 release, if you want to use those shortcuts.

Closing as duplicate of #1764 (the report fixed by #3447).

**Closed by ferdnyc** 2020-05-18 17:03 UTC
Labels: :beetle: bug, duplicate
