### ISSUE TITLE
Timeline Color As Solid

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1738] opened 2018-06-27 14:43 UTC
**Is your feature request related to a problem? Please describe.**
The timeline's color displays as a solid color

**Describe the solution you'd like**
The timeline's color does not blend in with the rest of Openshot's UI Color so i think the timeline needs to have solid colors

**Describe alternatives you've considered**
Technically you could go into the timeline folder in Openshot's folder and change the ruler_ticks.png color using a image editor to a solid color and overwrite it to the default image

**Additional context**

**Comment by peanutbutterandcrackers** [comment] 2018-06-28 02:05
Hmm... I didn't know I could change the timeline color, technically. Do you perhaps have a screenshot of your custom timeline? Can the change also be made through the `.openshot_qt` folder in one's home directory? If so, perhaps that should be added in the docs so that the users can put their own manual styles easily?

**Comment by DylanC** [comment] 2018-06-28 12:16
@peanutbutterandcrackers - Seems almost like a duplicate of this #1425 , what do you think?

**Comment by DylanC** [comment] 2018-06-28 13:04
@peanutbutterandcrackers - Yes, it is a much smaller change to be fair.

**Closed** 2018-09-02 15:13 UTC
Labels: enhancement
