### ISSUE TITLE
"Please fix the following error and restart OpenShot The input and output devices don't share a common sample rate!" What does this mean?

### ISSUE THREAD

**Issue by PlushieGamer1228** [OpenShot/openshot-qt#3073] opened 2019-11-11 03:10 UTC
I looked it up and this bug has not been reported

When booting up the latest 64 bit version of the dev build of open shot it gives me the message "Please fix the following error and restart OpenShot
The input and output devices don't share a common sample rate!"

1. boot up openshot 2.4.4 64 bit dev build
2. Look at error
3. Stare at error
4. Read error

**Expected behavior:**
Happens every time

**System Details:**
- OpenShot Version 2.4.4 dev2
- Windows 10

IDK where to get the log

Its in the title

**Comment by PlushieGamer1228** [comment] 2019-11-11 03:21
Another update, my game also crashes every time I am exporting to 20.2% on my video, idk whats happening. I went to the dev version to see if it was fixed and it wasn't. I need help.

**Comment by ferdnyc** [comment] 2019-11-11 07:52
Duplicate of #2957, same steps to fix.

**Closed by ferdnyc** 2019-11-11 07:52 UTC
Labels: :beetle: bug, duplicate

**Comment by ferdnyc** [comment] 2019-11-14 12:47
I've applied a patch to the JUCE audio library that's reported to fix this issue, and Daily Build versions starting from the Nov. 13 2019 builds should no longer have this problem. The new installers:

* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705363-c2713520-12a15298-x86_64.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705361-c2713520-12a15298-x86.exe
