### ISSUE TITLE
Application crashes when playback reaches a transition.

### ISSUE THREAD

**Issue by srmeijer95** [OpenShot/openshot-qt#1856] opened 2018-07-15 19:26 UTC
**Describe the bug**
The program crashes when you are watching the video. When the player reaches the transition between to clips in the same track.

**System Details**
 Windows 10 x64
 OpenShot 2.4.2

**To Reproduce**
1. Make two clips overlap and thus form a transition between the two.
2. Click on play.
3. When the player reaches the point of the transition, it crashes.

**Screenshot**
It crashes when it hits the blue thing.
![crash](https://user-images.githubusercontent.com/41270654/42737546-22c4d90c-8875-11e8-98fe-577597a0e9ac.png)

**Comment by peanutbutterandcrackers** [comment] 2018-07-16 11:04
Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14)? Thank you!

**Comment by srmeijer95** [comment] 2018-07-16 11:23
Done. ;)

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2197389/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2197390/openshot-qt.log)

**Comment by MarcBooster** [comment] 2018-08-01 08:12
Hello there,
Just joining the feed to see if any progress has been made on this topic? I am experiencing the exact same crash in the exact same circumstances...
Thank you !

**Comment by guerda** [comment] 2018-08-01 17:26
I experience the same issue, with 2.4.2 on Windows. Some transitions work, others crash reproducible. 
I also tried it out with the daily build OpenShot-v2.4.2-dev1-1532898209-53c400da-554d9f2f-x86_64.exe from July 29, 2018, 11:09 a.m.

**Comment by DylanC** [comment] 2018-08-02 09:03
@guerda - Can you list some transitions that produce a crash?

**Comment by guerda** [comment] 2018-08-04 10:15
@DylanC I only used `transitions/common/fade`. Interestingly, most of the transitions work, one repeatedly crashed, during playback and during export.

The transition crashing is a longer one. You can see the culprit here:
![grafik](https://user-images.githubusercontent.com/230782/43675173-035a570c-97e0-11e8-8381-178959dd276a.png)

**Comment by DylanC** [comment] 2018-08-04 10:49
@guerda - Thanks, I'll have a look at this later.

**Comment by N3WWN** [comment] 2018-08-06 12:56
@guerda - The normal way that transitions are supposed to used is to overlap both videos, not extend beyond them.  If you wish the transition to be twice as long as the overlap of the videos, try not using a transition at all and add a fade to the start/end of the clip(s) using the `Right Click -> Fade` menu.  

I find it's easier to avoid the automatic transitions if I put the clips on different tracks.  You'd only need two tracks for a simple project like this, alternating between the two.

**Comment by Cicoz** [comment] 2018-08-15 12:57
i can't work anymore with openshot video, it just crashes over and over every 2-3 transitions. can't find a real reason.  did just have a crash on an automatic fade transitions, the one when when you collide two videos. as soon as you review it it just crash when reaching the second portion of the video.

2.4.2 \ win10

**Comment by BabyCharmander** [comment] 2018-09-06 21:09
I'm having this problem too. Crashes every time it hits a transition. Has a solution been found? It looks like this problem is months old...

**Comment by NimmNimm** [comment] 2018-09-15 03:55
Im having this problem as well, makes me want to use a new program which is sad cause other than the transitions crashing its a great program

**Comment by KK029302** [comment] 2018-09-17 03:11
I am also having this issue even with small clips and transitions.

**Comment by DylanC** [comment] 2018-09-17 09:41
@srmeijer95 @MarcBooster @guerda @N3WWN @Cicoz @BabyCharmander @NimmNimm @KK029302 - Can everyone try the latest daily build? I've been told a fix has been put in for the automatic transitions. However, we need feedback to know if this fix works for everyone. 👍

**Comment by KK029302** [comment] 2018-09-17 19:52
@DylanC I installed the latest daily build (OpenShot-v2.4.3-release-candidate-1537166623-x86_64.exe) and I am still having the same issue.

**Comment by DylanC** [comment] 2018-09-24 12:11
@srmeijer95 - This transitions bug has been fixed. See #2125.

**Closed by DylanC** 2018-09-24 12:11 UTC
Labels: 2.4.2-issue
