### ISSUE TITLE
App won't load

### ISSUE THREAD

**Issue by rballin1** [OpenShot/openshot-qt#5549] opened 2024-06-25 14:19 UTC
**Describe the bug:**
I just downloaded the new update (version 3.2). The app won't load. When I try to open OpenShot, it opens, but then it freezes and windows says that the app is not responding. I have tried several times and the same thing happens each time. I have even uninstalled the app and reinstalled it and the problem persists. (I had no problem running the previous version of OpenShot.)

**Steps to reproduce the behavior:**
Happens whenever I try to start the app.

**Expected behavior:**
I expect the app to open properly so that I can use it.

**System Details:**
- OpenShot Version: 3.2
- Operating System: Windows 10, 64 bit

**Log Files:**
[libopenshot.log](https://github.com/user-attachments/files/15972847/libopenshot.log)
[openshot-qt.log](https://github.com/user-attachments/files/15972848/openshot-qt.log)

**Comment by johnhaire89** [comment] 2024-06-26 05:06
I've also got this problem after updating and trying to run OpenShot
I tried renaming the folder at C:\Users\username\\.openshot_qt, but part where it hangs moved from 

```
14:36:36 WARNING preview_thread: Your sample rate (48000) does not match OpenShot (44100). Adjusting your 'Preferences->Preview->Default Sample Rate to match your system rate: 48000.
14:36:36 INFO main_window: updateStatusChanged
```

to
```
14:46:33 WARNING preview_thread: Your active audio device (||) does not match OpenShot (). Adjusting your 'Preferences->Playback->Audio Device' to match your active audio device: ||
```


**System Details:**
OpenShot Version: 3.2.0.0
Windows 11, 64 bit.

**Log Files:**
[openshot-qt (after deleting folder).log](https://github.com/user-attachments/files/15982565/openshot-qt.after.deleting.folder.log)
[openshot-qt (before deleting folder).log](https://github.com/user-attachments/files/15982566/openshot-qt.before.deleting.folder.log)

**Comment by johnhaire89** [comment] 2024-06-26 05:14
Just tried uninstalling OpenShot, deleting C:\Users\username\\.openshot_qt, and installing the daily build.
Same issue.
![image](https://github.com/OpenShot/openshot-qt/assets/13926753/0b3f2d02-7c6d-41f3-b46c-ad7dcbd9f106)


When I first run the program and it hangs, it doesn't create openshot-qt.log. When I force close it and start it again, it does.

Logs from what should be a fresh install are below:

[libopenshot.log](https://github.com/user-attachments/files/15982659/libopenshot.log)

[openshot-qt.log](https://github.com/user-attachments/files/15982661/openshot-qt.log)

**Comment by NicCrockett** [comment] 2024-06-26 05:51
I'm having this issue too. My screen is similar to @johnhaire89 except it shows it twice in the same OpenShot window. It isn't open twice, it just shows what looks like smaller overlapping windows of OpenShot. I tried opening OpenShot from the start menu and opening the file I was working on. Both attempted to open an untitled project before locking up. I also tried running as admin, but the results were the same. I'd post an image, but I needed to get work done. So, I reinstalled previous version and that worked for now. I'm running Windows 10 Pro 22H2 64 bit.

**Comment by jonoomph** [comment] 2024-06-28 04:09
Please give our latest daily build a try: https://www.openshot.org/download/#daily. I fixed a bug that was happening when applying the themes (on launch), but it was a race condition, which didn't always happen. Please let me know if OpenShot still freezes, after running this new version. Thanks!

**Comment by johnhaire89** [comment] 2024-06-28 06:14
Looks like that fixed it. Thanks!
For anyone else reading this, I think the current version needs to be uninstalled before running the installer for the daily build. I didn't do this at first and the bug was still there.

Edit: Nope, spoke too soon

**Comment by jonoomph** [comment] 2024-07-01 20:26
I am still investigating this issue. It's my top priority to find a fix and release a new version of OpenShot. But this is incredibly difficult to reproduce. I have access to two Windows 10 machines (and one Windows 11), and all of them work fine with no issues.

I have noticed a few things though... The "tutorial" window appears stuck on the main window (which might be a clue... and it's not supposed to do that), and also, some users report 2 main windows appear right before the freeze.... hmmm

**Comment by jonoomph** [comment] 2024-07-01 20:42
@johnhaire89 When running the latest daily build, can you send an updated screenshot of what OpenShot looks like after it launches? I'm curious if it moves further than the 3.2 release build before freezing?

**Comment by jonoomph** [comment] 2024-07-02 02:53
I have an experimental build with lots of extra logging in the ThemeManager code (which I suspect might be causing an issue):
https://drive.google.com/file/d/1dmGta325WUE5IUpEZP5c4qpchXqgsVmQ/view?usp=sharing. 

**Steps:**
1. Please delete `C:\Users\USER\.openshot_qt\openshot-qt.log` and `C:\Users\USER\.openshot_qt\openshot.settings`
2. Please uninstall OpenShot (i.e. **Add / Remove Programs**)
3. Install this [test build](https://drive.google.com/file/d/1dmGta325WUE5IUpEZP5c4qpchXqgsVmQ/view?usp=sharing)
4. Launch OpenShot until it freezes, then kill OpenShot
5. Upload the `C:\Users\USER\.openshot_qt\openshot-qt.log` log file here

**Comment by johnhaire89** [comment] 2024-07-02 03:26
![image](https://github.com/OpenShot/openshot-qt/assets/13926753/20707ab2-64f4-4dca-a326-a2caf4b9ab00)

I should've mentioned this earlier, but if

1. Delete .openshot_qt
2. Run OpenShot
3. Kill OpenShot after it freezes

Then openshot-qt.log doesn't get created.
![image](https://github.com/OpenShot/openshot-qt/assets/13926753/da8f1e4f-05aa-4900-a240-7fee67c056a0)

It gets created and updated whenever I try running the app after that.

This is the file that was created the second time I tried running it. The app froze at the same spot.
[openshot-qt.log](https://github.com/user-attachments/files/16061144/openshot-qt.log)

> Looks like that fixed it. Thanks!

When I posted this, I made it into the app but it worked only once.

Is this guide still relevant/accurate? I tried the steps last week but without the debugging symbols I'm not sure if it helps https://cdn.openshot.org/static/files/user-guide/troubleshoot.html#windows-debugging-with-gdb
Here's the output anyway. 
The line where it freezes is `warning: mincore\com\oleaut32\dispatch\ups.cpp(2126)\OLEAUT32.dll!00007FFC4E71470C: (caller: 00007FFC4E7149FA) ReturnHr(1) tid(4c3c) 8002801D Library not registered.
`
[openshot gdb output.txt](https://github.com/user-attachments/files/16061244/openshot.gdb.output.txt)

Hope all this helps.

**Comment by johnhaire89** [comment] 2024-07-02 03:51
I have oleaut32.dll in `C:\Windows\System32` but the registry described in this content from 2012 (https://answers.microsoft.com/en-us/msoffice/forum/all/8002801d-automation-error-library-not-registered/5717123b-4c0b-4a3d-8bb5-7d0fe84e6ac9) seems to have moved to Computer\HKEY_CLASSES_ROOT\TypeLib\{00020813-0000-0000-C000-000000000046}\1.9


Looks like windows updated oleaut32.dll as part of "2024-06 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5039212)"

Perhaps it's a similar issue to this?
https://stackoverflow.com/questions/44579720/qt-widget-application-library-not-registered-error?rq=2

**Comment by johnhaire89** [comment] 2024-07-02 04:15
I've just installed Windows update "2024-06 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5039302)" and now I can successfully launch OpenShot.

![image](https://github.com/OpenShot/openshot-qt/assets/13926753/2c487226-bfcf-4990-95a6-12eef0ecf5d8)

**Comment by jonoomph** [comment] 2024-07-02 04:36
@johnhaire89 This looks really promising! Let me have a few other users test this theory out! Thanks and nice work.

**Comment by johnhaire89** [comment] 2024-07-02 05:02
https://bugreports.qt.io/browse/QTBUG-63789

**Comment by jonoomph** [comment] 2024-07-02 22:43
@NicCrockett @rballin1 Can you confirm installing KB5039302 update resolves the issue for you?

**Comment by verdelf** [comment] 2024-07-03 17:16
Windows 11 user here. Version 22H2. Last cumulative update KB5039302 was installed on 6.26.24. I am having this issue after downloading the latest version of Open Shot two days ago. I tried deleting the openshot-qt folder as suggested and restarting and the issue persists. I have uninstalled and reinstalled Open Shot twice now. The program does not respond and is stuck on this screen. I end up having to manually end the task every time. I also tried running the daily build and the issue persists. 
![open_shot](https://github.com/OpenShot/openshot-qt/assets/140131032/d1be7a81-083c-4906-a15c-6f731ccb59b8).

**Comment by SinbadBC** [comment] 2024-07-07 20:03
July 7, 2024.  Windows 10 user here.  Same problem  Freezes on start up.  All previous versions have been deleted.  All directories under programs and users have been deleted. Same problem...

**Comment by jonoomph** [comment] 2024-07-07 21:24
Please test the following Windows build, and let me know if you still experience the freeze: :crossed_fingers: https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.2.0-dev-daily-12610-044bb224-23713d3a-x86_64.exe

**Comment by SinbadBC** [comment] 2024-07-07 22:12
I loaded it and it worked.  This was the second time that I loaded it.  The only difference was that I did not check the box that asked me if I wanted to create a desktop icon.

**Closed as completed** 2024-07-07 23:23 UTC

**Comment by verdelf** [comment] 2024-07-08 16:30
The daily build reinstall worked for me too, and I the only thing I did differently this time was uncheck the "create desktop shortcut" box. Interesting!

**Comment by jonoomph** [comment] 2024-07-08 18:55
Interesting... I'll look into the create desktop shortcut option.

**Comment by NicCrockett** [comment] 2024-07-19 23:01
Sorry for the delayed response. Wanted to let you know that I just tested the lasted update and everything appears to be working fine. Thanks for your help and a great product!

**Comment by Colorjet3** [comment] 2024-07-20 02:38
No worries @NicCrockett and great to hear that OpenShot is working for you.
