### ISSUE TITLE
Saved project cannot open: "NoneType object is not subscriptable"

### ISSUE THREAD

**Issue by ktheijs** [OpenShot/openshot-qt#1200] opened 2018-01-13 01:52 UTC
I am running OpenShot 2.4.1 on Windows 10 64x. 

There is no crash, but any time I try to open a project that I have saved it shows a popup with the message: "NoneType"object is not subscriptable.

The project does not open. Is there a way to recover my project? I have put a lot of work into it...
It is not just this project that doesn't open. No project opens.

**Comment by peanutbutterandcrackers** [comment] 2018-02-14 10:01
@DylanC - Duplicate of #1151

**Comment by ferdnyc** [comment] 2019-07-20 12:17
Closing all remaining open issues regarding "NoneType" error messages, which I believe were all found to be attributable to various project-file data export bugs (like the history corruption), all of which have (AFAIK) since been corrected.

**Closed by ferdnyc** 2019-07-20 12:17 UTC
Labels: duplicate

**Comment by hrimhari** [comment] 2019-07-26 17:19
I have version 2.4.4 and I just got into a NoneType situation.

**Comment by ferdnyc** [comment] 2019-07-26 22:58
@hrimhari Please file a [new issue](https://github.com/OpenShot/openshot-qt/issues/new/choose) using the Bug Report template, including the requested logfiles, and we'll hopefully be able to sort out why.
