### ISSUE TITLE
Audio is scratchy

### ISSUE THREAD

**Issue by tkr34** [OpenShot/openshot-qt#2505] opened 2019-01-02 01:15 UTC
**Please fill out this template** 

**Describe the bug**
My audio is scratchy and I don't understand why it's happening because it's been fine before. And it skips and acts weird.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version [e.g. 2.4.3]

**To Reproduce**

**Expected behavior**
My audio to be clear and smooth

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**

**Comment by speedytechdev** [comment] 2019-01-02 08:05
Hi @tkr34 I am going to close this issue since it seems to be a duplicate of [#1069](https://github.com/OpenShot/openshot-qt/issues/1069) Unless otherwise proven. 

Thanks for report and have a great day

**Closed** 2019-01-02 08:06 UTC
Labels: duplicate
