### ISSUE TITLE
win 10 error message bug latest dev 2 version

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2500] opened 2018-12-31 02:47 UTC
hello everyone, whilst doing an short animation today i discovered a bug in the latest dev 2 version
of openshot windows 10 
when you save a project, then go to new project or change your mind and reset openshot , i got an 
error message pop up about an invalid file and "}" showing up,
 This error is not on the linux app version either latest dev.
heres a pic to show what im talking about.
cheers bob
![openshot bug win 10 dev 2](https://user-images.githubusercontent.com/40479177/50553804-7c6b1900-0d02-11e9-8860-34badf5117f6.JPG)

**Comment by peanutbutterandcrackers** [comment] 2018-12-31 10:07
I wonder if this is just a matter of corrupted `.osp` file...

**Comment by bobcrikey** [comment] 2019-01-02 06:17
@peanutbutterandcrackers ,i dont know mate, but iv tried a couple different times with different file names and still the same error is 
popping up, so definately a bug to look into .
normally i use my linux partition to do all my animations in but occasionally i will try out the latest win10 dev version,
 so i was a little disapointed to discover a new little bug. since its the first time to see such an error
message. since openshot is at a late dev 2 stage.

cheers bob

**Comment by peanutbutterandcrackers** [comment] 2019-01-02 07:57
Could you try deleting the `.openshot_qt` folder in your home folder and see if that works out?

**Comment by bobcrikey** [comment] 2019-01-04 04:39
@peanutbutterandcrackers , i deleted all the files in the folder and i started new project and saved it however again same problem win 10 came up with the same error again.

bob

**Comment by peanutbutterandcrackers** [comment] 2019-01-04 06:02
If this issue does not arise with any other .osp file, and/or while running OpenShot just so - as a new session, in order to work on a new project - that  would mean this is just an issue of the `.osp` file being corrupted. If that is the case, I would suggest that you zip your `osp` file and then post it here (just the osp file and nothing else). If not, I have no idea. We'll need someone smarter to look into this.

**Comment by bobcrikey** [comment] 2019-01-05 23:05
@peanutbutterandcrackers , well i discover something very interesting mate, I uniinstalled dec 29 win 10
dev version and deleted the openshot_qt folder , and then i re-installed dec 3 win 10 dev version started
a new project used the same pictures as before, saved the project, closed down openshot then 
i reopened openshot and sucessfully reloaded the project.

so just to clarify , i uninstalled dec 3 version  of openshot,deleted the openshot-qt folder and then
i re-installed the dec 29 win 10 version again , 
 and guess what the same bug error came back so its definately a bug that needs to be corrected
in dec 29 win 10 dev version . as the dec 3 win 10 dev version works perfectly even exporting vids.

 cheers bob

**Comment by peanutbutterandcrackers** [comment] 2019-01-08 11:14
Confirmed by https://github.com/OpenShot/openshot-qt/issues/2429#issuecomment-452214339. Marking as a bug. Thank you @bobcrikey and @drdan811

**Comment by drdan811** [comment] 2019-01-09 03:55
Interestingly, I have rolled back to the first 2.4.3 daily. I can now open 3 of my .osp files which would not open before because of this error;
 "Failed to load project file C:/Users/Dan/Videos/showreel master.osp: invalid load key, '{'.", 
however, one of them I still cannot (the one I really need to open, of course!) The difference of this one .osp file is that it was made by the latest daily, the others were not. This may not be surprising to you? But if anyone has any ideas how I might be able to open this file, it would be greatly appreciated, I dont want to have to make it again (it was not a brilliant video, I just need to get it out there, Im not sure how the make a brilliant video yet).
Cheers
Dan

**Comment by nanohtpc** [comment] 2019-01-19 13:10
seems fixed on the build of 01.18.19....

**Comment by ferdnyc** [comment] 2019-07-20 11:22
Closing as a (thankfully!) transient issue with the development builds. (That's why we test things this way! ...I mean, we'd have even _more_ bugs if releases went out completely untested, think on that. **#DARKEST_TIMELINE**)

**Closed by ferdnyc** 2019-07-20 11:22 UTC
Labels: bug
