### ISSUE TITLE
Audio does not work

### ISSUE THREAD

**Issue by ssoxide** [OpenShot/openshot-qt#4380] opened 2021-09-01 20:02 UTC
**Describe the bug**
Every time I open openshot the audio on my entire computer stops.  I can't even hear audio on videos I play from my desktop without using openshot.  When I close openshot everything returns to normal.

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.0-dev
- libopenshot Version:  0.2.6-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.0-dev-daily-8190-d58febf1-5ec3bc21-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/trq5o9waqjtmi24mnllkejngbi66q6j2/openshot-qt.zip) (18 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment] 2021-09-02 06:20
Hi, @ssoxide this seems to be a common issue recently. If you could help our dev team out and tell us what steps you took to get you to the issue? E.g:

1. Launch Openshot using the shortcut
2. Import Clips
3. Start a new project.

Please let me know if you get stuck or need help.

Enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by ssoxide** [comment] 2021-09-02 14:46
I launched openshot with a shortcut.  I added a long movie and cut it in pieces a few times.  I added some other clips and realized that I should be hearing audio.  Every time I played the final clip or previewed a clip i thought about adding I got nothing.  I tried playing videos from my desktop with my own media player and nothing.  As soon as I closed openshot, everything returned to normal.  I tried rebooting my computer several times.  I tried changing my preview output device setting and rebooting openshoot many times.  I tried going into windows settings to restore audio.  One time I tested chimes on my computer in windows settings and it worked, so I went back to open shot and I still had no audio and now the video was lagging.  I tried plugging in external speakers into my laptop but it didnt help.

**Comment by speedytechdev** [comment] 2021-09-04 02:06
Thank you for that. Your notes will help our dev team out a lot. Sorry for any inconvenience this has caused you. If you have any questions or concerns please feel free to ask.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by ghost** [comment] 2021-09-30 17:30
I have tried OpenShot from Fedora 34 version 2.5.1 / 0.2.5 here the preview shows correct audio and video. But when I export a video, there is no audio track.

When I install the appimage from https://www.openshot.org/ I get what sounds like clipping audio in both preview and exported video.

When I install from flatpak https://flathub.org/apps/details/org.openshot.OpenShot  I get what sounds like clipping audio in both preview and exported video.

The only way I found to create a usable video is use the Fedora version of OpenShot, detach and maximize the preview and make a screen capture of that with Simplescreenrecorder. The end result is lower quality video but doable.

Would be nice if this was fixed.

**Comment by ghosalya** [comment] 2021-10-28 08:25
I am having a similar problem where my audio stops completely when OpenShot is trying to play audio in preview. However, in my case my audio does not return when I close OpenShot; I have to restart my computer. I'm using OpenShot 2.6.1 on Windows 10.

**Comment by DanPinGF** [comment] 2021-11-30 23:34
Does the preview act extremely slow when playing w/ no audio? If so, consider this a duplicate of #4303

**Comment by ghost** [comment] 2021-12-01 06:10
plays at normal speed for me

**Comment by DanPinGF** [comment] 2021-12-01 06:12
> plays at normal speed for me
> […](#)
> On 1 Dec 2021, at 07:03, DanPinGF ***@***.***> wrote: ﻿ Does the preview act extremely slow when playing w/ no audio? If so, consider this a duplicate of #4303 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hmm... then I wonder what's the difference. I do not have this problem.

**Comment by Colorjet3** [comment] 2023-01-24 03:06
This has been resolved in the latest DEV Daily build of v3.0.0.

**Closed by Colorjet3** 2023-01-24 03:06 UTC
Labels: :lady_beetle: bug, 🔥 hot
