### ISSUE TITLE
Ability to pass and/or select a different font for animated titles

### ISSUE THREAD

**Issue by endsguy** [OpenShot/openshot-qt#1192] opened 2018-01-09 07:50 UTC
**System Details:**
* Operating System / Distro: Debian with kernel 4.14.2-1
* OpenShot Version: OpenShot-v2.4.1-3-g8e96e17-57-663-x86_64.AppImage / OpenShot-v2.4.1-x86_64.AppImage
* Blender Version: Blender 2.79 (sub 0)

**Issue Description and steps to reproduce:**

- I am using Cyrillic characters, UTF-8
- When creating an animated title "dissolve.py" with Blender and using only English characters all works fine. 
- When I am creating an animated title to dissolve and field "Title" is with Russian characters I either get no Frame output from Blender error (if only russian characters) or Blender renders just the english characters, completly missing any Russian characters I enter.  
Issue is obviously that default font of Blender "BFont" on my distribution doesn't have Russian characters. I was able to reproduce that, by starting blender, adding text object and trying to edit it to put russian characters there. (result no single russian character is displayed).  I am sure this applies to some other International characters and hopefully is reproducible in other distributions. 

Reason for asking for the changes:
- In blender I can add another font (with russian characters) easily and I can do nothing with the font at all when blender is called from Openshot. 
- "Animated title" is a very nice feature for newbie, PRO would probably just render what he wants directly in blender and later add to Openshot. It would be great that users who rely on "Animated titles" can use a different font in case their character set is not part of the default bfont in Blender and they don't have to change .py code or .xml files (which I guess is problematic if we use .AppImage) or mess with Blender config to allow it to accept their international characters in the Bfont.  

So I think Openshot users would greatly benefit from being able to select a font other then the default BFont for any of the "animated titles".  

So nature of my requirement:
-  add a font selection section for Animated titles (like in normal titles)
- in the font seclection selection should be a mix of hardcoded (Bfont, others that are now hardcoded to .xml) for backwards compatibility and loadable fonts. Default should be Bfont as now. 
- optional: we should be carefull and ideally show hardcoded fonts and only those loadable fonts that blender could use. (but at the end being able to play with the font and select the one that works with blender is better then not being able to do anything, so this requirement is optional)  
- use the selected font and pass it to Blender so it uses the font provided there instead of those that are in dissolve.xml XML file

For this we need to modify each of the "animated title effects" .xml files and also amend the .py code so it loads the selected font prior to passing things to blender.   
 
P.S. There could be another solution  to this of course, like having fonts in Openshot with international support and using those in blender, or for example having a mapping screen between fonts suggested for animated titles and real fonts, etc. The above, however, would not only resolve my issue, but also add needed flexibility for openshot users of the "Animated titles", I am sure they would love to use their custom font their without the need to change files of the distribution. 

I've noticed there is a request for Blender on the similair case:
https://developer.blender.org/T53744

I would prefer if we still add this functionality (font selection) to the "animated titles"

**Comment by peanutbutterandcrackers** [comment] 2018-02-14 01:13
@endsguy - Hey there, could you please perhaps submit a patch for it? (You seem to have the know-how)

I have the same issue myself.

@DylanC - This affects me too.
Can we also haz cheezeburgers, pls?

**Comment by DylanC** [comment] 2018-02-14 08:53
@peanutbutterandcrackers - Yeah, this looks like a good one for the project.

**Comment by peanutbutterandcrackers** [comment] 2018-02-14 14:06
@endsguy - @DylanC approves. I don't see why you shouldn't make a PR soon. :)

**Comment by peanutbutterandcrackers** [comment] 2018-02-14 14:07
@endsguy - @DylanC approves. I don't see why you shouldn't make a PR soon. :)

**Comment by mikelacsa** [comment] 2020-01-12 19:41
Hi!

I will be closing this request as this is a duplicate of #1090. 

However, we sincerely thank you for your enhancement request. Don't hesitate to let us know if you have other features that you want to be added to OpenShot.

**Closed by mikelacsa** 2020-01-12 19:41 UTC
Labels: 💡 enhancement
