### ISSUE TITLE
Openshot Crashes on open on OSX 10.11.3 

### ISSUE THREAD

**Issue by walshd1** [OpenShot/openshot-qt#104] opened 2016-02-18 15:45 UTC
Open shot (installed from 2.0.6 Beta DMG file crashes on open 

OS:10.11.3 (15D21) (El Capitan)
IMAC Mid 2010 
2.8ghz 
4GB RAM

According to Console 

com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x1000001a.launch-mac.sh[1582]) Service exited due to signal: Illegal instruction: 4

I have attached the full crash report generated by OSX for your info

[Openshot crash report 18216.pdf](https://github.com/OpenShot/openshot-qt/files/136454/Openshot.crash.report.18216.pdf)

I hope this is helpful

**Comment by jonoomph** [comment] 2016-02-18 16:05
Thanks for the bug report. This is actually a duplicate of https://github.com/OpenShot/openshot-qt/issues/75

**Closed by jonoomph** 2016-02-18 16:05 UTC
