### ISSUE TITLE
Openshot ends up in an infinitive loop when trying to open a missing project  and bad naming in the task manager

### ISSUE THREAD

**Issue by bevort** [OpenShot/openshot-qt#1320] opened 2018-02-28 09:54 UTC
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_; Can't find the log file. The program doesn not create one when forse closing it via the task manager!

**Issue Description and steps to reproduce:**
When trying top open a recent project (via the recent projects menu option) on a remote location that is currently not accessable the program tells you that the file could not be found. When clicking OK, the program opens the open file popup. When canceling this action (as I do not have access to the remote location right now), the program again pops up the message that the file could not be found and again on OK opens the open file popup, and again, and again, and again ........ never ending story!
Please add a "Cancel" button to this popup.

I had to kill the program using the task manager!
That leads to the next issue. **There is no OpenShot program running**!!!!!
I found a program called "Launch" (of all names!) and killed it. Is proved to be OpenShot.
This is really bad naming. if you really need to to cal it "launch" than at least call it "Launch OpenShot" so we know what it is about and not just a virus.

**Comment by peanutbutterandcrackers** [comment] 2018-03-03 11:19
@DylanC - Since the 'infinite loop' issue has already got a probable fix in #1325, I'll ignore that part. However, I think the latter part of this issue --- the process being called 'launch' on windows, does need to be solved....

**Comment by peanutbutterandcrackers** [comment] 2018-07-16 04:56
Closing this as a duplicate of #1118; fix is in progress and should be fixed in the upcoming releases.

**Closed by peanutbutterandcrackers** 2018-07-16 04:57 UTC
Labels: duplicate, enhancement, fix in progress
