### ISSUE TITLE
Inform users their privacy is violated by default.

### ISSUE THREAD

**Issue by eggzample** [OpenShot/openshot-qt#3014] opened 2019-09-25 16:44 UTC
Sending data to google-analytics should be opt-in.  This is, frankly, terrible.

I have stopped using this application but future users who are unaware should be warned.

**Comment by ferdnyc** [comment] 2019-09-25 17:07
@eggzample 

While I'm personally rather sympathetic to your POV (#1626), and as I say in that issue I'm not 100% sold on our current config, I _am_ forced to acknowledge that the metrics collection is fully anonymized (with the technical exception of originating IP, as I discuss in https://github.com/OpenShot/openshot-qt/issues/1626#issuecomment-396556959 ), so casting it as a privacy violation is a bit extreme. It's very likely that 50% or more of the websites you visit every day, including GitHub, send anonymized metrics to Google Analytics. None of them ask your permission first.

The fact that OpenShot notifies the user of the data collection as the _very first_ thing it does when starting up for the first time (via the checkbox in the first Tutorial popup) is already more transparency than the norm for anonymous tracking data.

I'd prefer the tracking were opt-in as well, just philosophically. But that's been considered, it's been decided that our current tracking with prominent opt-out si sufficient, and I can't really fault the arguments leading to that conclusion.

Closing as duplicate of #1626.

**Closed by ferdnyc** 2019-09-25 17:07 UTC
Labels: duplicate, enhancement

**Comment by eggzample** [comment] 2019-09-25 18:23
I expect external websites to do this, and I can prevent them from doing this by using privacy add-ons in my browser.  I don't expect it from GPL software that I install onto my computer.

**Comment by ferdnyc** [comment] 2019-09-25 18:39
`¯\_(ツ)_/¯`

Adjust your expectations.
