### ISSUE TITLE
Unable to launch openshot 2.3.0 

### ISSUE THREAD

**Issue by wahogo** [OpenShot/openshot-qt#595] opened 2017-04-19 15:25 UTC
**System Details:**
* Operating System / Distro: Windows 7
* OpenShot Version: 2.3.0 and others
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
![openshot-startup-error](https://cloud.githubusercontent.com/assets/27776374/25187993/4b5c3b00-252d-11e7-96f3-0ea8b49fb503.jpg)

Please assist. This came about after restarting the computer. It has been working okay since I installed it many weeks ago. I have uninstalled, reinstalled and even tried older versions of openshot. Nothing has worked.
Thankyou.

**Comment by DylanC** [comment] 2017-08-28 09:51
@wahogo - Does this issue happen in the newer versions? I cannot reproduce this issue on Win7.

**Comment by DylanC** [comment] 2017-09-05 08:55
Cannot reproduce this. Closing for now.

**Closed by DylanC** 2017-09-05 08:55 UTC
