### ISSUE TITLE
Can't change back from detail view in "Project files"

### ISSUE THREAD

**Issue by BF3000** [OpenShot/openshot-qt#84] opened 2016-02-11 10:33 UTC
Windows 10 x64 Build 14257.rs1
Openshot 2.0.6
If I change view mode in Project files window to "detail view", right mouse button menu doesn't appear anymore, so I cant load files or change view mode back (Ctrl+D shortcut doesn't work).
The only way I was able to change it back is delete 'openshot.settings' file.

**Comment by jonoomph** [comment] 2016-02-11 16:34
Hmmm... that doesn't sound good. Can anyone else verify this on their computer?

**Comment by jonoomph** [comment] 2016-02-11 16:44
Okay, I can verify it. It was a regression caused by a fix to keyboard shortcuts the other day. It's fixed now. It will be in the next beta release (which might come sooner than later).

**Closed by jonoomph** 2016-02-11 16:44 UTC

**Comment by codeling** [comment] 2016-03-07 14:33
I'm also experiencing this issue - is that beta release out yet, or is there any other possibility to get a build with that fix in it? Thanks!
