### ISSUE TITLE
save section as new file

### ISSUE THREAD

**Issue by video-git** [OpenShot/openshot-qt#1189] opened 2018-01-07 20:09 UTC
Hi, I am looking to do two simple things:
    1) Save a selection as a new file.
    2) Remove the audio.

And yes, I do feel stupid. But I just can't figure out how to do this.

System Details:
    Operating System / Distro: Ubuntu / 14.04
    OpenShot Version: 2.4.1

**Comment by N3WWN** [comment] 2018-01-08 14:29
Saving a selection is not currently possible in OpenShot.  

What you will need to do is to create a project which contains only the selection, moved all the way to the left of the timeline (so that it starts immediately).

Removing the audio should be simply as right clicking on the clip in the timeline and selecting `Volume` -> `Entire Clip` -> `Level 0%`.

Alternatively, you could place the playhead at the start of the clip and change the `Volume` property to `0`.

**Comment by video-git** [comment] 2018-01-08 21:09
Thanks,
I would have thought this to be a simple task. Seems a bit too tedious this way, if one wants to cut several single clips. I'll see if I can find another program that will do that.

But thanks for the tip with the audio. That worked fine.

**Comment by mikelacsa** [comment] 2020-01-12 19:38
Hi!

I will be closing this request as this is a duplicate of #259.  

However, we sincerely thank you for your enhancement request. Don't hesitate to let us know if you have other features that you want to be added to OpenShot.

**Closed by mikelacsa** 2020-01-12 19:38 UTC
Labels: 💡 enhancement
