### ISSUE TITLE
Can't create or load anything with a random transition on it...

### ISSUE THREAD

**Issue by nanohtpc** [OpenShot/openshot-qt#3466] opened 2020-05-08 21:35 UTC
Can't create or load anything with a random transition on it...

winx64

latest daily...

8((((

**Comment by SuslikV** [comment] 2020-05-09 05:34
Duplicate of: https://github.com/OpenShot/openshot-qt/issues/3401

**Comment by nanohtpc** [comment] 2020-05-16 06:42
probkem REMAINS, even editing the hidden files....

**Closed** 2020-06-07 02:35 UTC
Labels: :beetle: bug

**Comment by jonoomph** [comment] 2020-06-07 19:51
This is fixed in the latest daily build: https://www.openshot.org/download#daily
