### ISSUE TITLE
Name column not working in Project Files

### ISSUE THREAD

**Issue by Sirusdark** [OpenShot/openshot-qt#543] opened 2017-03-21 19:15 UTC
**System Details:**
* Operating System: Windows 10 Pro 64bit
* OpenShot Version: v2.2.0-60-gc4c3cfd-49-614-x86_64

**Issue Description and steps to reproduce:**
The name column in Project Files is not working properly. The "name" column does not extend to full file names' length when double clicked or manually extending it. See screenshot.
![name-field_limitation](https://cloud.githubusercontent.com/assets/6478223/24165058/d503211a-0e45-11e7-9b65-21d2766e1c91.jpg)

**Comment by ankitpati** [comment] 2017-03-22 02:55
Perfect repro on Ubuntu 16.04 with OpenShot 2.2.0 AppImage.

**Comment by Magnatrix** [comment] 2017-03-23 14:35
I can also reproduce on Ubuntu 16.04 using the ppa version.

**Comment by DylanC** [comment] 2017-09-08 17:00
This has since been fixed in the latest version

**Closed by DylanC** 2017-09-08 17:00 UTC
Labels: bug
