### ISSUE TITLE
<CTRL> T (for choosing template to do a title) functions like font, size, effects don't work

### ISSUE THREAD

**Issue by Zippydo** [OpenShot/openshot-qt#1867] opened 2018-07-18 02:35 UTC
When I try to do a <CTRL> T to choose a template to do a title, I discover I can't change font, size, effects for "line 1" and/or "line 2". I have Windows 10 and OpenShot version 2.4.2.

What I do is type <CTRL> T and choose "Cloud 1", then type in my text for "line 1" or "line 2" and click on "change font" and choose a size and font and effect and then click on "OK" but it does not take as I expected.

**Comment by DylanC** [comment] 2018-07-20 07:03
@Zippydo - I think this has always been the case. Not sure if we can do something for it but I will mark as enhancement for now.

**Comment by peanutbutterandcrackers** [comment] 2018-12-11 04:03
Possibly related to #2069

**Comment by ferdnyc** [comment] 2019-08-26 01:04
Closing this as a duplicate of #2069, more details there as to how all this works.

**Closed** 2019-08-26 01:05 UTC
Labels: duplicate
