### ISSUE TITLE
No sound of imported files to OneShoot

### ISSUE THREAD

**Issue by Likuli717** [OpenShot/openshot-qt#3116] opened 2019-12-07 22:50 UTC
No sound in preview videos and any videos that i upload to OneShot Video Editor

1. Run program
2. Import any video with sound
3. Try to play it
4. No sound played

I want to hear what im doing its important for every video

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3-dev1
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['pl-PL', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1575749079-99565bb3-12a15298-x86_64.exe

**Log Files**
- http://logs.openshot.org/f85iwchqd5v169905kt2abxc7myyhtj2/openshot-qt.zip
- http://logs.openshot.org/f85iwchqd5v169905kt2abxc7myyhtj2/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment] 2019-12-08 07:03
The commit in question is: https://github.com/OpenShot/openshot-qt/commit/bd31282f54281a202e92e90ca084db05f44b12d9

Can you share the mp4 file sample? Or make new one with the same behavior for the test purposes and share it instead?

Meanwhile try to use earlier test builds of OpenShot (before the 02 Oct 2019): https://github.com/OpenShot/openshot-qt/releases/tag/daily
But it is hard to tell for me which one of the setup files is before the mentioned date. Maybe @ferdnyc knows more.

Or better try the release files: https://github.com/OpenShot/openshot-qt/releases (look for the `OpenShot-v2.4.4-x86_64.exe`)

**Comment by Likuli717** [comment] 2019-12-08 09:41
This is one of the videos that i was uploading

niedz., 8 gru 2019 o 08:03 SuslikV <notifications@github.com> napisał(a):

**Comment by SuslikV** [comment] 2019-12-08 13:04
Try Google Drive link to share the sample. Because there is no file in your latest post.

**Comment by Likuli717** [comment] 2019-12-08 18:07
https://drive.google.com/file/d/0B7Z3g6DCmBzKeDQ0M2hrMFd4RTRqbWxwTTBWYzR5UnpzOTdn/view?usp=drivesdk

Its here

niedz., 8 gru 2019, 14:05 użytkownik SuslikV <notifications@github.com>
napisał:

**Comment by SuslikV** [comment] 2019-12-08 20:25
The steps to reproduce the issue is not clear. I cannot reproduce the muting of the sound on my end. But I see the error during _Split Clip..._ action (the one in the _Project Files_). Can you try to use right-click menu  _Slice > Keep Both Sides_ over the clip in the _Timeline_ instead? Is the sound still not playable for you?

**Comment by ferdnyc** [comment] 2019-12-08 20:46
> The commit in question is: [bd31282](https://github.com/OpenShot/openshot-qt/commit/bd31282f54281a202e92e90ca084db05f44b12d9)

@SuslikV 
Sorry, I'm not following, how is that commit related?

**Comment by ferdnyc** [comment] 2019-12-08 20:57
As far as identifying builds by date, the first number in the Daily Build filenames is a Unix epoch time, seconds since 1970-01-01. I wouldn't be surprised if Google can convert those dates, and there are plenty of web tools around, but on the Linux command line you can also use the `date` command:
```sh
$ date --date="2019-10-02 00:00:01" +%s
1569988801
$ # Date actually defaults to midnight at the start of the date in question,
$ # and you don't have to be that precise...
$ date --date="2 October 2019" +%s
1569988800
```
So any file labeled with a number lower than `1569988800` was created on 2019-10-01 or earlier, meaning the latest Windows 64-bit installer would be: [OpenShot-v2.4.4-dev2-1569790398-c2ac8ebc-f17a7ed4-x86_64.exe](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1569790398-c2ac8ebc-f17a7ed4-x86_64.exe)

**Comment by ferdnyc** [comment] 2019-12-08 21:05
@Likuli717 

If you're not getting ANY sound in OpenShot, my guess would be that it isn't connecting to the correct audio device. Can you check the Preferences, in the Preview tab, and make sure that the Playback Audio Device is set correctly for your sound interface / output? (Speakers vs. headphones, line out vs. USB vs. Bluetooth, etc.) Also check that the Default Audio Sample Rate and Default Audio Channels are set to match your hardware.

**Comment by Likuli717** [comment] 2019-12-08 21:10
I have check it, everything is good

niedz., 8 gru 2019, 22:05 użytkownik Frank Dana <notifications@github.com>
napisał:

**Comment by ferdnyc** [comment] 2019-12-08 21:25
Hmmm. And what about this:

1. Import a short video you know has sound
2. Place it on one of the Timeline tracks at `00:00:00:01`
3. Go to Export, set a filename and save location, and use these settings:
   1. Profile: All Formats
   2. Target: MP4
   3. Video Profile: HD 720p 30fps (1280x720)
   4. Quality: Low
   (We just want a quick test, quality doesn't matter)
4. Click Export Video

...After OpenShot exports the video, if you play it in VLC or another Windows video player, does the _export_ have sound? (I'm trying to determine whether the issue is with OpenShot **playing** the audio, or if it's a problem reading it from the source video.)

**Comment by Likuli717** [comment] 2019-12-08 21:37
Yes the exported file has sound

niedz., 8 gru 2019, 22:25 użytkownik Frank Dana <notifications@github.com>
napisał:

**Comment by ferdnyc** [comment] 2019-12-08 21:58
OK, so it's definitely an issue just with OpenShot playing audio.

> > The commit in question is: [bd31282](https://github.com/OpenShot/openshot-qt/commit/bd31282f54281a202e92e90ca084db05f44b12d9)
> 
> @SuslikV
> Sorry, I'm not following, how is that commit related?

Ohhh, NOW I see, you're talking about this, from the logs:
```
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
preview_thread:INFO onModeChanged
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\preview_thread.py", line 61, in onModeChanged
    self.parent.SetPlayheadFollow(True)
AttributeError: 'Cutting' object has no attribute 'SetPlayheadFollow'
```

Yeah, looks like there's a bug in the playhead-follow code, in that we didn't think to implement it (or, to implement a dummy function that ignores it) for the Cutting interface. 

But that's not related to this issue, or it would only affect Cutting and the Timeline preview would play. (Actually, on my system the Cutting bug doesn't interfere with sound _there_ either.) 

The issue you're seeing isn't just related to the "Split Clip..." viewer, right @Likuli717 ? As I'm understanding it you have no sound AT ALL from OpenShot, even in the main window?

**Comment by Likuli717** [comment] 2019-12-08 22:04
when i use openshoot video maker i dont have any sound on my pc. And when i
was playing video on YT and then opened openshoot the sound crushes :(

niedz., 8 gru 2019 o 22:58 Frank Dana <notifications@github.com> napisał(a):

**Comment by SuslikV** [comment] 2019-12-09 09:24
It is strange behavior. Can you say what is your _Playback devices > the_device_name > Properties > Advanced tab_ is set to? (located in the right-click menu over the speaker icon in the tray of the Windows).
![Playback devices](https://user-images.githubusercontent.com/19683044/70423320-ed1fc700-1a75-11ea-858a-f1949ca984fa.png)

Is it set similar to this, for example?

**Comment by Likuli717** [comment] 2019-12-09 12:51
Yes i have the same settings


pon., 9 gru 2019 o 10:24 SuslikV <notifications@github.com> napisał(a):

**Comment by Likuli717** [comment] 2019-12-09 13:03
and now i have that communicate

[image: image.png]

pon., 9 gru 2019 o 10:24 SuslikV <notifications@github.com> napisał(a):

**Comment by SuslikV** [comment] 2019-12-09 17:16
Is there was screenshot? I don't see it. Is something was changed in Win10 for _Communications_ tab?

**Comment by Likuli717** [comment] 2019-12-09 17:32
It is an audio error
say: Please fix the following error and restart OpenShot. The input and
output devices don't share a common sample rate!

pon., 9 gru 2019 o 18:16 SuslikV <notifications@github.com> napisał(a):

**Comment by ferdnyc** [comment] 2019-12-09 20:13
@Likuli717 You can't send images as email attachments, they don't come through. You can post them via the web interface at https://github.com/OpenShot/openshot-qt/issues/3116

But _that_ error we're very familiar with. (And I thought we fixed it, or maybe we didn't merge that commit? It's due to a JUCE library bug that was fixed in a later update.)

**Comment by ferdnyc** [comment] 2019-12-09 20:16
Yeah, the fix for that should have gone in with OpenShot/libopenshot-audio#79 on October 26. So, a newer OpenShot _shouldn't_ have that issue.

The version in your original report, OpenShot-v2.4.4-dev2-1575749079-99565bb3-12a15298-x86_64.exe is supposed to include the fix for that issue. Are you still running that version, or did you downgrade at some point?

**Comment by ferdnyc** [comment] 2019-12-09 20:17
Dammit, GitHub, stop being TOO helpful! That URL two comments ago should be:

[`https://github.com/OpenShot/openshot-qt/issues/3116`](https://github.com/OpenShot/openshot-qt/issues/3116)

**Comment by SuslikV** [comment] 2019-12-09 21:14
@ferdnyc you have to post workarounds for the "common sample rate" error as well. I only know that _Recording devices_ in Windows has _Advanced_ tab setting for the shared mode too.

By the way, do you know why I landed with the OpenShot? Only because number of other (mainly linux based ports) simply refuses to start on my PC or were unable to encode simple video sample right. And I didn't write reports to everyone of them because it is boring. That's why I wrote "you have to...". I looked at first or second Google answer to error with each program I tried, and because there was no useful info for me, just switched to another program. It is very rare when user stays with you for 2 days (or longer) waiting for the support.

**Comment by ferdnyc** [comment] 2019-12-10 00:58
> you have to post workarounds for the "common sample rate" error as well.

Yeah, sorry, I was on my phone earlier. I'll just copy https://github.com/OpenShot/openshot-qt/issues/2957#issuecomment-526464558 which is probably the most concise explanation.

This is generally-speaking a system configuration error: it means that the Windows Audio settings for your input and output audio device don't match. I can only give you the process to fix it in Windows 7 because I don't have access to a Windows 10 machine, but hopefully it's somewhat similar. 

In Win7, right-clicking on the volume control in the system tray would let you open a list of "Playback devices" or "Recording devices", each list has a default device and each device has a Properties window. In the Advanced tab of that window is the setting for the "Default Format" of the device, and if those formats don't match you'll see that error when starting OpenShot. Here are the Properties for the "Speakers" playback device and "Line In" recording device on a Win7 machine, for example:

![image](https://user-images.githubusercontent.com/538020/63995575-06a09280-cac7-11e9-8732-0275e69f454d.png)

Changing either device's Default Format to match the other one would clear up this error.

**Comment by ferdnyc** [comment] 2019-12-10 01:36
> It is very rare when user stays with you for 2 days (or longer) waiting for the support.

Then that's their problem. I understand your point, but keep in mind that at least _my_ help here is completely voluntary as I don't get paid, directly or indirectly, to do this. I have absolutely nothing to gain here, whether someone continues as an OpenShot user or not. So, "user retention" is nowhere on my list of concerns. My goal here is to improve OpenShot for everyone who wants to use it — and if anyone doesn't want to, then I 100% encourage them to use something else. I'm much more interested in _addressing_ problems with long-term solutions than I am in helping any individual user fix their immediate, individual issue.

Add to that the fact that I'm gamely trying to help users on an operating system I don't run, would prefer _not_ to run, and in the case of Windows 10 don't even have **access** to. I'm willing to give it my best shot, but anyone expecting Adobe helpline-level support will be greatly disappointed. (Of course these days, I doubt they'd get very responsive support from Adobe either. They'd probably be stuck with community support, though at least it's a much bigger community.) As much as I don't care if ANYONE runs OpenShot, I _especially_ don't care if Windows users run it, because they're the hardest to support both technically and socially.

So, to be blunt, I really have no sympathy for impatient users who post a problem they're encountering looking for an immediate quick-fix, are suggested a workaround, and then stop responding to all requests for information that would help us prevent the problem in the future — often, not even responding with feedback on whether the fix was successful or not. (IOW, the majority of them.) If they aren't willing to do _their_ part in helping us **solve** these problems, rather than work around them, then there's nothing to gain from helping them. Heck, I'd _rather_ they use some other software, so they can bother its developers instead.

Apologies if this got a little ranty, but like I said: I get nothing out of this. So no, quite frankly I really _don't_ "have to" do **anything**.

**Comment by ferdnyc** [comment] 2019-12-10 01:36
@Likuli717 has been very responsive so far, which is greatly appreciated. Thanks, @Likuli717, for taking the time to work with us on this. It's turning out to be a surprisingly tricky problem, one that we haven't seen before. And I really would like to help you solve it, and equally to figure out the cause so that it doesn't continue to impact other users in the future.

There are two pieces of information that, if you could provide them, would be _extremely_ helpful:

1. Did you in fact get the "input and output devices don't share a common sample rate" error with the `1575749079` (aka December 7) version of OpenShot from your original post? Because, if so, that was _not_ supposed to happen and we'll have to figure out why the fix from OpenShot/libopenshot-audio#79 failed to work.

2. Assuming the sample rate fix from my previous comment _does_ solve the issue with the build you CURRENTLY have installed (if it's not the `1575749079` version), then does it _also_ solve the issue once you reinstall the later version? Because, my biggest fear here is the possibility that OpenShot/libopenshot-audio#79 removed the error message, but **not** the problem, meaning we're now silently failing with a problem we used to at least notify users about. I _doubt_ that's the case, but I really want to rule out that possibility.

**Comment by Likuli717** [comment] 2019-12-10 06:08
I'm doing everything in rush really. I'll figure it out today and I'll do
my best to help you. There is a possibility that i fu*ked up sth in one
stage of fixing it. I'm not an IT specialist so sometimes it's hard for me
to do everything right :(

wt., 10 gru 2019, 02:36 użytkownik Frank Dana <notifications@github.com>
napisał:

**Comment by SuslikV** [comment] 2019-12-10 10:07
@ferdnyc there is always place to learn something new. You know how internet works, there is no magic in it. Linked post, picture, description. When I looking for the solution online - I see "yeah, common problem..." only. No solution. About the posted info, if you add picture how it "shouldn't be"  - it is better to add next to it "should be" picture, to have two kind of pictures: the wrong doing (faulty) and the right one (should).

@Likuli717 I think you need to:
1) Uninstall previous build of the OpenShot.
2) Make sure that there is no folder named `.openshot_qt` in the `C:\Users\helod` folder of your PC (this your user's folder as I see from the log-file). If the folder `.openshot_qt` is exist - delete it. The folder `.openshot_qt` is very special - it is very hard to handle it in Windows because the name is special (it's Linux incompatibility tail left during porting), so you have to check manually if it was removed completely. This folder stores all current settings of the OpenShot and log-files, thus it can be huge.
3) Install the http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1575749079-99565bb3-12a15298-x86_64.exe Do not run it yet! Or if it is running anyway - close the application and restart PC.
4) Set in Windows by right-click menu over the speaker icon in the tray the _Playback devices > the_device_name > Properties > Advanced_ tab shared mode Default Format to the value - for example `2 channel 16 bit, 44100 Hz` (I really don't know what value is better for your PC)
5) Set in Windows by right-click menu over the speaker icon in the tray the _Recording devices > the_device_name > Properties > Advanced_ tab shared mode Default Format to the value - same to the one set in p.5 (make sure that the number of channels the same too)
6) Make sure that the `the_device_name` icons from the p.4 and p.5 was marked as default (on my screens, posted above, they has small green checkmark in the lower right corner). Because it is hard to tell which device on your PC is used by default, thus I'm not quite sure that you applied p.4 and p.5 settings for the right devices. If you set the p4. and p.5 for the wrong devices - just repeat the actions from p.4 and p.5 for the right one.
7) Set in Windows by right-click menu over the speaker icon in the tray the _Playback devices > 
Communications tab_ the communications activity to value: `Do nothing`.
8) Set in Windows by right-click menu over the speaker icon in the tray the _Recording devices > Communications tab_ the communications activity to value: `Do nothing`.
9) Run recently installed OpenShot and drag-n-drop the file: https://drive.google.com/file/d/0B7Z3g6DCmBzKeDQ0M2hrMFd4RTRqbWxwTTBWYzR5UnpzOTdn/view?usp=drivesdk (your sample clip) directly into the _Timeline_ closer to the beginning.
10) Click Preview playback button. Wait when playback stops itself.
11) During playback try to hear to the sound - if there any?

**Comment by Likuli717** [comment] 2019-12-10 15:55
I'm doing it but the link that you have sent here (to the program) is not
working. It says the page is not found i'll try to find it by hand

wt., 10 gru 2019 o 11:08 SuslikV <notifications@github.com> napisał(a):

**Comment by Likuli717** [comment] 2019-12-10 16:21
There is no sound. I have made everything you write. Here are my settings
for speakers and mic
https://drive.google.com/open?id=12HcCnYdyHtygEhe1Waz0TXyQG3N1KA1f
https://drive.google.com/open?id=1hJcG_gHKwmY1V6-CPrJm93xiuYE8XqgD
I installed main program from this web https://www.openshot.org/download/

wt., 10 gru 2019 o 11:08 SuslikV <notifications@github.com> napisał(a):

**Comment by SuslikV** [comment] 2019-12-10 17:16
1) Please, change the Microphone settings to 24-bit 48000 Hz too (the screenshot shows that it is set to value that differs from the one was set for the Speakers).

2) Look at the _Communications_ tab (_Komunikacja_) that is common for all devices (the window opened before you clicked the _Properties_). Post a screenshot of it opened (for _Playback devices_ for example)

When performing tests do not close the Windows _Sound_  ( _Playback devices_ ) window - just leave it on the screen to see if volume level bar is moving when audio playbacks.

**Comment by Likuli717** [comment] 2019-12-10 19:30
Nothing happened
https://drive.google.com/open?id=1RgVZ7WO4inVAOF99JTNyi6ZE4wpgTTHd
Still i dont have sound on openshot or any other program or yt videos. This
only happens when i run openshot and then instantly everything is silent
without reason. After shuting down openshot everything is normal as always

wt., 10 gru 2019 o 18:16 SuslikV <notifications@github.com> napisał(a):

**Comment by Likuli717** [comment] 2019-12-10 19:31
i think i may be one person for million so....

wt., 10 gru 2019 o 18:16 SuslikV <notifications@github.com> napisał(a):

**Comment by SuslikV** [comment] 2019-12-10 20:39
@Likuli717 Heh, unique you say? W10 simply changed a lot, so I cannot help there. But only thing I found is that page that describes how to find _Communications_ tab, maybe it can help you: https://digitalproductkey.com/eb-blog/228-how-to-customize-the-communication-tab-in-Windows-10-Sounds or maybe this info outdated too. If OpenShots mutes everything else on your PC, that means something going wrong (at least it wasn't intended to do so).

**Comment by Likuli717** [comment] 2019-12-11 02:02
I'll check it at home and give you an answer if it helps indeed. Thanks a
lot for all your help and others. It so kind of you 😇

wt., 10 gru 2019, 21:39 użytkownik SuslikV <notifications@github.com>
napisał:

**Comment by mikelacsa** [comment] 2019-12-19 01:57
@Likuli717 I want to follow up on this? Have you tried @SuslikV 's suggestions?

**Comment by Likuli717** [comment] 2019-12-19 19:54
Yes i have done everything that he said and nothing helped. I dont need
that program now so the problem solved itself. Like i said maybe im one of
milion and it will never happen to anyone else 😇

czw., 19 gru 2019, 02:57 użytkownik mikelacsa <notifications@github.com>
napisał:

**Comment by mikelacsa** [comment] 2019-12-19 20:58
Thank you @Likuli717 

I'm closing the ticket now.

**Closed by mikelacsa** 2019-12-19 20:58 UTC

**Comment by SuslikV** [comment] 2019-12-20 20:22
So sad,that the solution was simple - "uninstall and don't use it", and 2 weeks of time was wasted on this. There will be one on a million times more sadness in this world from now on.

**Comment by Likuli717** [comment] 2019-12-20 21:32
It's not that easy... I mean i wanted to use this program for a present so
time was runing as hell i really see your love for this program and this
all effort that youre making. Dont be sad im not giving up! I thanks for
your help a lot but maybe this time problem is without solution

pt., 20 gru 2019, 21:22 użytkownik SuslikV <notifications@github.com>
napisał:

**Comment by MBB232** [comment] 2020-04-14 10:32
You are probably not going to do anything with this either, but I think I can confirm all 3 bugs 
- Not automatically selecting correct default settings of audio device, manually setting frequency does not seem to help
- "No such device" error (only on 1 of the 5 listed audio devices)
- if 'dim sounds during conference call' is selected, sounds from other players are muted too. (Or give microphone/noise likes sounds after disable-re-ableing this function.) NB: I don't think I see any new recording devices added to windows, or recording options in Openshot. 

For the main issue, it does list 5 devices while only internal laptop speakers are connected. 
I am not an audio guy and it is a new laptop, so I am unsure myself which one it *should* be, so I think I tried all. I have not had similar issues on any software before. 

IRRC, on installation it chose the top one at 42.000 Hz. (May have headphones connected at startup, which I later removed for testing)
As the screenshot shows, the speakers should run at 48.000 Hz, which value I then tried for all devices. 
None of them seemed to work, and the 4th 'Direct sound Primary sound driver' gave the error mentioned. 

I would offer to continue testing if you have questions (like try the NVIDEA HDMI output), but it is probably better for both of us if you keep it closed as 'not-a-bug'. Luckily this toke less time. 

NB: For testing settings, it would really help if there was a 'test sound' button in the setting box connected to an audio file with known codec. 
Restarting the program after every change takes a bit of time, but importing new video files takes about as much time. And it leaves the risk that audio codecs are not recognized, or that Openshot takes preferences settings from the opened project file. 

I understand that programming is difficult, otherwise I could do it myself ;-). But why are you programming a complex audio connection for simple playback? Can you not pull in relevant code from VLC or MPC classic or something that is proven? Why is Openshot triggering a microphone option anyway? 

Windows 10 1909
Openshot 2.5.1
Realtec HD audio 6.0.8750.1
Optional? driver/not installed:   Realtek Audio Control (Windows store app)

![DeviceList](https://user-images.githubusercontent.com/62191951/79214084-7ee77880-7e4a-11ea-8b45-791dec5c36bf.jpg)
<img width="840" alt="ErrorDirectSoundPrimaryDriver" src="https://user-images.githubusercontent.com/62191951/79214086-7f800f00-7e4a-11ea-8214-81c972f7a28a.PNG">
<img width="298" alt="SoundPlaybackDevices" src="https://user-images.githubusercontent.com/62191951/79214088-8018a580-7e4a-11ea-913b-747f045bc4ad.PNG">
<img width="298" alt="Speakers48000hz" src="https://user-images.githubusercontent.com/62191951/79214089-8018a580-7e4a-11ea-9fdf-ba330ee9fd01.PNG">

**Comment by MBB232** [comment] 2020-04-19 12:40
Did some more testing, and got it working. 

For me, it turned out to be the setting 'enable audio enhancements' that needss to be disabled for the Realtec sound. 

I can think of two reasons: 
1:  some oddness in Realtec driver
2: On this laptop, the switch from speakers to microphone is made automatically by the Realtec driver, not by the user in Windows. Perhaps it shows a different number of devices internally to Openshot then it does to the user?

I also tested using the sound of the Nvidia videocard over HDMI and Displayport>HDMI. Both worked directly on the 'default' choice in Openshot. 
On this it did not matter if 'audio enhancements' were checked on. 

By the way, when adding a second audio device, the number of audio options that openshot offers balloons  to way too much to test. 
![RealtectSpeakers_DisableEnhancements](https://user-images.githubusercontent.com/62191951/79688041-bfc8fe00-824b-11ea-8e57-939584f5e11b.jpg)
![NvideaAudioWindows](https://user-images.githubusercontent.com/62191951/79688043-c0fa2b00-824b-11ea-9c0a-0b67f2fe9d71.jpg)
![NvideaAudio](https://user-images.githubusercontent.com/62191951/79688044-c0fa2b00-824b-11ea-8656-5993dac3c39b.jpg)

**Comment by mkov608** [comment] 2020-12-23 19:07
Unchecking "Enable Audio Enhancements" worked for me!

![Sound Settings](https://user-images.githubusercontent.com/75637717/103029617-6a9a6600-4517-11eb-9ebe-bd87c8898526.jpg)
