### ISSUE TITLE
Changing the profile from a low framerate to a higher framerate will force some clips/sequences to overlap.

### ISSUE THREAD

**Issue by AntonSax** [OpenShot/openshot-qt#5490] opened 2024-04-04 20:02 UTC
Apologies if this bug has been reported before I couldn't find an issue for it.

**Describe the bug:**
Starting with a lower framerate and changing the profile to a higher framerate, including when exporting, can rearrange the connection point of video clips such that they overlap in unintentional ways.
My experiences with this are editing my video at 30 fps (so that it is quicker to render and play in the editor) and then exporting the video at 60 fps. It is not extremely noticeable if jump cuts are used, but when this issue occurs during a fade transition between two clips, it is possible that the latter clip gets rearranged to be in front of the fade transition, which creates a flicker/stutter as the latter video briefly appears before the fade starts.
It's not difficult to fix this if you are aware of the problem, especially because you can catch it if you change the profile of the project before exporting, but can be very confusing if you export to a higher fps without first changing to that profile and rewatching your video.

**Steps to reproduce the behavior:**
1. Create a project with a framerate lower than you plan to export to. I have seen the issue when I start at 30 fps.
2. Edit your project with many clips that preferably overlap (creating a fade transition), but you can also make them touch/connect to each other. I've seen this happen between clips that are only ~3 seconds long.
3. Change the profile to a higher framerate (e.g. 60 fps).
4. Get lucky. This issue doesn't always occur and when trying to intentionally replicate it I haven't been able to.
5. Rewatch your video to find spots where the video flickers between two clips for a frame or two.

**Expected behavior:**
I understand that some rearranging of clips might need to happen when increasing framerate (I think?), but it should not change the structure of your video. Sequences should not be rearranged to places they weren't.

**System Details:**
- OpenShot Version: OpenShot-v3.1.1-dev-daily-11909-a9e34a9b-839d7edc
- libopenshot: 0.3.2
- Build Date: 2024-03-27 20:06
- Operating System: Windows 10

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/14876581/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/14876582/libopenshot.log)

**Comment by Colorjet3** [comment] 2024-04-05 14:04
Hello @AntonSax.  

1.  What kind of files are your working with (.jpg? .mp4? etc?)
2.  If using video files what is/are the frame rates before importing?
3.  Are you setting up the proper profile in OpenShot before you import your video files, if any, so they match?
4.  What specific Profile are you selecting while editing?
5  What specific Profile are your selecting when Exporting?
6. Any other details you would like to share?

I am asking so I can run a test myself to see if I can replicate your issue.

**Comment by AntonSax** [comment] 2024-04-05 19:21
1. I'm using .mkv files
2. Should be 60 fps based on my OBS settings. (Not sure if it's important, but OBS also uses the Common FPS Values. I don't know what the difference between that and Integer FPS Value or Fractional FPS Value is.)
3. Yeah I usually have the profile I want to use set before I import any video or image files, but typically have the fps downgraded. 
4. Typically FHD 1080p 30fps or FHD 720p 30fps and occasionally FHD Vertical 720p 30fps.
    a. Typically just exporting with the resolution and fps upgraded. Most cases to FHD 1080p 60fps or FHD Vertical 720 60fps.
5. I don't think so. I've seen this occur in both <1 min videos and >10 min videos.

**Comment by Colorjet3** [comment] 2024-04-05 21:21
Thank you @AntonSax.  When time permits I'll do some testing.  I do have OBS so I'll create some videos and give it a try.

**Comment by Colorjet3** [comment] 2024-04-08 01:59
Hello @AntonSax I am running into an interesting issue in Windows environment where I am unable to display the profile information (the metadata) of a .mkv file outside of OpenShot.  Doing some research it sounds like there is some kind of an issue parsing out the data with File Explorer in Windows 10 & 11.

I then tried to use FFmpeg to extract that data and the same issue.  Since OpenShot uses FFmpeg I am wondering if the fact that it is unable to parse that data it is challenged by what FPS to use at the start of a project (I am not 100% on this since OpenShot is able to import it and preview it just fine).

I have tested three different projects and used a combination of .mkv and .mp4 files as well and I am unable to reproduce the issue.

Unless we can consistently reproduce this it is going to be difficult to troubleshoot.

**Comment by AntonSax** [comment] 2024-04-08 22:20
No worries then. It's not too difficult of an issue to catch once you know it exists. Thanks for the time you've put into trying to replicate the issue.

Do you think I should switch to recording in another format such as .mp4 in the future?

**Comment by Colorjet3** [comment] 2024-04-08 23:31
You are welcome!  OpenShot works best with .mp4 files so that would make sense to change OBS to record to .mp4 instead.  This way if you run into the issue again, we know that there must be something else that is going on in OpenShot.

This will also help us focus on root cause.  I am going to go ahead and close this ticket but feel free to reopen if you run into the issue again.

**Closed as completed by Colorjet3** 2024-04-08 23:31 UTC
