### ISSUE TITLE
Newbie Title Questions

### ISSUE THREAD

**Issue by Jeffrey-Levine** [OpenShot/openshot-qt#1477] opened 2018-04-06 17:11 UTC
**System Details:**
* Windows 10  64 bit    Core  i7  2.5 GHz 
* OpenShot Version: 2.4.1

Sorry...   I feel I've made a fair attempt to solve this on my own, although it seems pretty simple. 

I'm trying to start very simple, No  animations....  Just two lines of text.   Fade in.   Fade out.   
What could be easier?    (Answer:  ZERO lines of text)

Q1) I've tried to create two lines of text in a single Title clip, but no joy.  
I've tried Inserting CR/LF  (Enter),    Shift-Enter  
When I do, it creates a new line in the Text Entry field, but the resulting title appears as just a single line.  
It does enter a non-printing character where I'd like the new line to be inserted.  
The only workaround I've come up with---which I hope will be temporary--is to create two separate Title clips that are overlaid on separate Tracks.   (Too much work.)     

Q2) Using the built-in title Title Editor, every time I want to try some change to the font (e.g. change font size, font style),it always wipes out my previous formatting and reverts to "Ubuntu" font @ 11 pt.  
It's just a nuisance resetting it each time.  Is this the way it's supposed to work? 

Q3) If I use the Right-Click animation options to create Fade in - Fade out, it inserts tiny green tick marks where the animation will begin and end.  a) What are these called (so I know for the future)? and b) Is there any way to edit these?  The only thing I've figured out to do is to delete them entirely and start over.   Another option is to drag a "fade" transition onto the clip, which is then very easy to edit.  
 (Maybe I just answered my own question??)    

Q4) Can I assume that the Properties Window, with Tabs,, that I've seen in some of the older Tutorials & documentation, is no longer a feature, and has been replaced by the Property panel?     

I really like OpenShot, and look forward to becoming more facile with it.  I appreciate your time in answering, and regret asking what I assume are "dumb" questions.    
And I just saw another question that wondered whether the Preview Panel is too hardware intensive...  Just f.y.i.  My computer struggles to keep up, with even simple animations, & the sound track is very intermittent  (on an embedded .mp4 track)  

Thx, JRL

**Comment by peanutbutterandcrackers** [comment] 2018-04-07 14:17
Whoa! That is a lot of questions!

I'll try to answer a few.

Q1) Yeah. It seems OpenShot does not have that feature. Rather, it seems that it is so by design. After all, the title dialogue does say 'Line 1' and 'Line 2' and stuff. So, can't really blame OpenShot for that. However, you might want to use the advanced editor to do all of those stuffs that you plan to do. (You'll have to install [inkscape](https://inkscape.org/en/), though.
![screenshot from 2018-04-07 19 58 20](https://user-images.githubusercontent.com/26764547/38455915-1461fa36-3a9e-11e8-86e9-e352efdc8a32.png)

Q2) That is an actual bug, I think, now that you've also pointed it out. Would you like to open a separate issue for that, good sir, so that we can get the devs attention towards it, and label it accordingly?

Q3) a. Those are called keyframe markers. Keyframes are awesome. You should totally learn about them.
       b. Please consult the list of tutorials at the end of this comment (or maybe I'll add a new comment, IDK)

Q4) Same answer as Q3) b. :)

Hope that helps!

**Comment by peanutbutterandcrackers** [comment] 2018-04-07 14:27
Since you say that you are just starting out with OpenShot, here are some helpful links:

1. [Video tutorials by Mr. Jonathan Thomas, the creator of OpenShot, himself.](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T)
2. [Introduction to Keyframes, in general](https://www.youtube.com/watch?v=J8EdjrZ1zFw)
3. [1st video to watch for keyframes in OpenShot, IMHO](https://www.youtube.com/watch?v=mgi4esWA84M&t=298s).
4. [2nd video for keyframes in OpenShot](https://www.youtube.com/watch?v=P3zIprwr1rk&t=1s)
5. [3rd video](https://www.youtube.com/watch?v=nEyrC1v-M1s&t=18s)
6. [User guide](https://www.openshot.org/static/files/user-guide/introduction.html)

Hope that helps! :)

I hope you create amazing videos using OpenShot!

**Comment by DylanC** [comment] 2018-04-08 20:32
@Jeffrey-Levine - If you don't mind im closing this as answered. Just follow the answered provided by @peanutbutterandcrackers

**Closed by DylanC** 2018-04-08 20:32 UTC
Labels: question

**Comment by peanutbutterandcrackers** [comment] 2018-04-14 14:49
Those are not all by Mr. Thomas. Many are. Many are by other's though.

I hope you create amazing videos using OpenShot!
