### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3011] opened 2019-09-22 09:12 UTC
Create a project with a animated title,

Save it

Close openshot

Open Openshot

Re-open the project

I have always this message : 
'NoneType' object has no attribute 'get'

windows 10 , openshot 2.4.4

**Comment by mikelacsa** [comment] 2019-09-29 19:53
Hello!

Thanks for your input. Have you tried testing it with the latest daily build?

https://www.openshot.org/download/

Also, can you send us your log files, please? Delete them first, then reproduce the problem and send us the new log files that will show.

**Comment by mouarfff** [comment] 2019-09-30 11:08
I'm afraid about daily build.. I need to finish some work and i don't want to loose something

i need stable software

**Comment by SuslikV** [comment] 2019-09-30 16:25
@mouarfff just make copy of your project's folder before experiments.

**Comment by hrimhari** [comment] 2019-10-08 21:01
Hi, when this happens to me, the 'history' property seems to become 'null'. As a work around, I edit the project file on a text editor (vim in my case) and replace the 'null' by an empty JSON object: {} .
I also see "6: null, 7: null"s after that, that I remove.

**Comment by mikelacsa** [comment] 2019-10-10 21:57
Thanks @ferdnyc 

@mouarfff @hrimhari have you tried out the latest daily build?

**Comment by ferdnyc** [comment] 2019-10-11 01:31
Indeed, I'd be especially interested in @mouarfff 's results with the new builds, especially for the exact problem reported in this issue, because I can't reproduce. So, if it's still happening with the development code, then we could really use:
1. A sample project file that triggers this error
2. (non-Debug) Logs from both the session where it was created, and the subsequent session where OpenShot attempted to load it

**Comment by ferdnyc** [comment] 2019-10-11 01:39
@mouarfff

> i need stable software

An understandable concern, but if version 2.4.4 is crashing on you, is it really all that "stable"? The OpenShot codebase is not a particularly fast-moving environment, commits are made fairly infrequently and they have to pass CI testing before they _can_ be merged. New commits are generally tested, and anything that causes issues is backed out. But, there have been a _lot_ of bugfixes since the release of 2.4.4, which was more than 6 months ago.

All of which is to say, at _this_ point and in their current state, I'd personally consider the Daily Builds **more** stable than the 2.4.4 release version.

That could change if @jonoomph decides to get caught up on the 33 PRs currently pending in the repo, because then a lot of code would be in flux for a few days and stability might drop, but the _current_ set of Daily Build downloads is low-risk vs. continuing to run with all of the know bugs in 2.4.4.

**Comment by mikelacsa** [comment] 2019-10-15 18:39
@mouarfff @hrimhari just following up on this? Have you tried the latest daily build?

**Comment by mouarfff** [comment] 2019-10-24 17:58
I have another bug when i tried the last daylibuild

when i launch openshot i have this : 
"please fix the following error and restart openshot : 
the input and the output don't share comon sample rate"

but i reset the config in c:\users\myuser\.openshotqt 
(why it's not in appadata\local ?)

**Comment by mouarfff** [comment] 2019-10-25 08:38
I have another bug when i tried the last daylibuild

when i launch openshot i have this : 
"please fix the following error and restart openshot : 
the input and the output don't share comon sample rate"

but i reset the config in c:\users\myuser\.openshotqt 
(why it's not in appadata\local ?)

**Comment by mouarfff** [comment] 2019-10-25 10:10
I have another bug when i tried the last daylibuild

when i launch openshot i have this : 
"please fix the following error and restart openshot : 
the input and the output don't share comon sample rate"

but i reset the config in c:\users\myuser\.openshotqt 
(why it's not in appadata\local ?)

**Comment by mouarfff** [comment] 2019-10-26 12:07
I have another bug when i tried the last daylibuild

when i launch openshot i have this : 
"please fix the following error and restart openshot : 
the input and the output don't share comon sample rate"

but i reset the config in c:\users\myuser\.openshotqt 
(why it's not in appadata\local ?)

**Comment by ferdnyc** [comment] 2019-10-27 05:46
@mouarfff Yeah, that's a problem some Windows users have been hitting, related to the new audio device selection. Instructions for correcting it can be found at https://github.com/OpenShot/openshot-qt/issues/2957#issuecomment-526464558

**Comment by mouarfff** [comment] 2019-10-28 12:56
thx, i don'ty have this issue now, but i had to go down the sound quality of my hardware

**Closed** 2019-11-05 21:37 UTC
Labels: :beetle: bug, :question: needs info

**Comment by ferdnyc** [comment] 2019-11-14 12:47
@mouarfff 

I've applied a patch to the JUCE audio library that's reported to fix this issue, and Daily Build versions starting from the Nov. 13 2019 builds should no longer have this problem. The new installers:

* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705363-c2713520-12a15298-x86_64.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705361-c2713520-12a15298-x86.exe
