### ISSUE TITLE
cx_freeze: python error in main script

### ISSUE THREAD

**Issue by fawxyz** [OpenShot/openshot-qt#126] opened 2016-03-12 13:24 UTC
just download this software. when i tried to open, an error window pop out 
windows 7 pro 32bit

![cxfreeze](https://cloud.githubusercontent.com/assets/17798466/13723194/360c2a6a-e890-11e5-9eba-b858d195c461.jpg)

**Comment by jonoomph** [comment] 2016-03-17 02:50
This is due to an error in the translation file. I've fixed many of these already, so probably this will work fine in the next release. What language are you using?

**Comment by fawxyz** [comment] 2016-03-17 19:13
I think i choose the default language/english.

**Comment by TheInaneRambler** [comment] 2016-08-20 03:10
Jonoomph......so how do we fix this then?

**Comment by hgpuke** [comment] 2016-08-29 11:56
I just downloaded it today and experience the same error. I am running Windows 7 Enterprise, 64-bit and choose to use the default English language.

**Comment by jreynojustin** [comment] 2017-02-28 14:58
Closing because a duplicate of #374 and a non-active issue.

**Closed by jreynojustin** 2017-02-28 14:58 UTC
