### ISSUE TITLE
Missing clip properties dialogue

### ISSUE THREAD

**Issue by econrad003** [OpenShot/openshot-qt#760] opened 2017-06-29 16:50 UTC
**System Details:**
* Operating System / Distro: Windows 7 Home Premium
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
(1) Import video.
(2) Copy clip to timeline.
(3) Right click on timeline, select properties.  (Nothing happens.)

**Comment by DylanC** [comment] 2017-08-25 13:13
Duplicate of #541

**Closed** 2019-07-19 03:51 UTC
Labels: duplicate
