### ISSUE TITLE
Truble with animated title

### ISSUE THREAD

**Issue by elpuentedetito** [OpenShot/openshot-qt#379] opened 2016-10-17 13:07 UTC
Hello,
I have 
Windows 8 
Openshot 2.1.0
Blender 2.78
Inkscape 0.48
When I try to generate an animated title, I have writen correctly the path of both programs in preferences, always send me the following error:
"El error indicó:
No se encontró ningún fotograma en la salida de Blender"

By the way, each time I run the program I must write the path of the blender and Inkscape beacuse it does not save it.

Can you sove that?
I am trying to use it with my students in a Sapnish Secondary School but I still have my doubts. 
Thank you for the program

**Comment by sorghe** [comment] 2016-10-17 16:35
I have the same issue on the Blender side: English error: No frame was found in the output from Blender.
Tested with:
Openshot 2.1.0
Blender 2.62 and Blender 2.78

**Comment by sydneyjd** [comment] 2016-10-19 00:33
Was  just about to make a bug report on this, never had an issue with pre 2.1 versions of openshot, but not this issue has popped up.
here is a link to the terminal output im getting, hopefully it can help. https://cloud.openmailbox.org/index.php/s/ONafjGZYmKh33nT
Running an Up to date Arch Linux system.

Thanks!
-Sydney

**Comment by IMBJR** [comment] 2016-10-24 12:34
Running fully-updated Arch:
. Openshot version 2.1.0-3
. Blender version 17:2.78-1
Running openshot at the CLI, I see the following reported when trying to do the blur animated title:

blender_model:INFO updating effects model.
blender_treeview:INFO File Name
blender_treeview:INFO Title
blender_treeview:INFO Extrude
blender_treeview:INFO Bevel Depth
blender_treeview:INFO Font Name
blender_treeview:INFO Bfont
blender_treeview:INFO Text Alignment
blender_treeview:INFO CENTER
blender_treeview:INFO Text Size
blender_treeview:INFO Text Width
blender_treeview:INFO Diffuse Color
blender_treeview:INFO Specular Color
blender_treeview:INFO Specular Intensity
blender_treeview:INFO Start Frame
blender_treeview:INFO End Frame
blender_treeview:INFO Animation Length
blender_treeview:INFO 2
blender_treeview:INFO 1
blender_treeview:INFO init_slider_values
blender_treeview:INFO sliderPreview_valueChanged: 1
blender_treeview:INFO sliderPreview_valueChanged: 105
blender_treeview:INFO btnRefresh_clicked
blender_treeview:INFO QThread Render Method Invoked
blender_treeview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.5/site-packages/openshot_qt/blender/blend/blur.blend' -P '/home/imbjr/.openshot_qt/blender/25f271ee-961d-11e6-aca6-3497f66766eb/blur.py'
Traceback (most recent call last):
  File "/home/imbjr/.openshot_qt/blender/25f271ee-961d-11e6-aca6-3497f66766eb/blur.py", line 122, in <module>
    text_object.align = params["spacemode"]
AttributeError: 'TextCurve' object has no attribute 'align'
blender_treeview:INFO Blender render thread finished
blender_treeview:INFO onRenableInterface
blender_treeview:INFO onBlenderErrorMessage
blender_treeview:INFO preview_timer_onTimeout
blender_treeview:INFO QThread Render Method Invoked
blender_treeview:INFO Blender command: /usr/bin/blender -b '/usr/lib/python3.5/site-packages/openshot_qt/blender/blend/blur.blend' -P '/home/imbjr/.openshot_qt/blender/25f271ee-961d-11e6-aca6-3497f66766eb/blur.py'
Traceback (most recent call last):
  File "/home/imbjr/.openshot_qt/blender/25f271ee-961d-11e6-aca6-3497f66766eb/blur.py", line 122, in <module>
    text_object.align = params["spacemode"]
AttributeError: 'TextCurve' object has no attribute 'align'
blender_treeview:INFO Blender render thread finished
blender_treeview:INFO onRenableInterface
blender_treeview:INFO onBlenderErrorMessage

**Comment by mixedbredie** [comment] 2016-11-08 10:01
I think it has to do with changes in the Blender Python API. The Python scripts included with OpenShot set some parameters that are passed to Blender and one of them `text_object.align` needs to be changed to `text_object.align_x`. I changed 16 files (blinds, blur, colors, defocus, explode, fly by 1, fly by 2 titles, glare, glass slider, halo zoom out, neon curves, rotate 360, slide left to right, trees, wireframe text, zoom clapboard) which now work when called from OpenShot. Go out for lunch while you wait for the render.

**Comment by kip-cadmgr** [comment] 2016-11-16 14:38
Quick fix for debian: `cd /usr/share/pyshared/openshot/blender/scripts; sed -i -e 's/text_object.align/text_object.align_x/g' *.py`

**Comment by 07pepa** [comment] 2016-11-19 14:22
had same problem and theoritized that is because i have all my programs on separate HDD  😃 .... hope somebody will fix it...

**Comment by janagyjr** [comment] 2016-11-27 19:18
I'm having the same problem, @mixedbredie solution does not work for me. 

OpenShot 2.1
Blender 2.78
Windows 7 Pro 64-bit
Xeon W3550 3GHz
12GB DDR-3 RAM

**Comment by mixedbredie** [comment] 2016-11-28 15:37
Can you run the OpenShot .blend file from the command line?

```/path/to/blender -b /path/to/blend/file.blend -P /path/to/python/script.py```

What error messages do you get?  In the example above from @IMBJR it says the problem is with ```AttributeError: 'TextCurve' object has no attribute 'align'```

**Comment by janagyjr** [comment] 2016-11-28 17:08
I just opened oneshot to try just a plain text animation, and it seems to be going swimmingly.

**Comment by mixedbredie** [comment] 2016-11-29 10:09
That's good news! Running the scripts from the command line will return an error for some of the animations as they are expecting user input (earth is looking for lat/lon coordinates) but when you run from  OpenShot they work as expected.

**Comment by jonoomph** [comment] 2017-02-28 23:25
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!

**Closed by jonoomph** 2017-02-28 23:25 UTC
