### ISSUE TITLE
OpenShot needs proper blur

### ISSUE THREAD

**Issue by TavernSenses** [OpenShot/openshot-qt#1575] opened 2018-05-09 08:41 UTC
OpenShot needs **out-of-focus blur**. The attached picture explains why!

![blur](https://user-images.githubusercontent.com/38319606/39804845-785b78f6-5375-11e8-846b-dbefedda9f12.jpg)

**Comment by N3WWN** [comment] 2018-05-09 14:31
@DylanC - This is an exact dupe of #1554 , but since this issue includes a sample screenshot, I think this should be the one that is kept and the other one closed as the dupe.  

If you agree, would you mind adding the "enhancement" tag here and updating the tags on the other issue?

**Comment by DylanC** [comment] 2018-05-09 14:54
Dup of #1554.

**Comment by DylanC** [comment] 2018-05-09 14:56
@N3WWN - I will add the tags but I would prefer to keep both if you don't mind.

**Comment by N3WWN** [comment] 2018-05-09 15:07
Oh sure thing!  I don't mind at all ;)

I'm looking at this right now.  

The current blur is supposed to be a Gaussian blur, but it's only being applied in one direction and for one iteration, resulting in a motion blur.

At present, a vertical blur negates the horizontal blur, so the only way to get a horizontal blur is to set the vertical radius to 0.  There is currently no way to get both blurs with one effect.

**Comment by N3WWN** [comment] 2018-05-09 15:50
Original image:

![tv-test-pattern](https://user-images.githubusercontent.com/19431804/39824839-57031e94-537e-11e8-8d4c-1ade61754b28.png)

Here is the current blur effect (`6 horizontal radius`, `3 iterations`, `3 sigma`, `6 vertical radius`):

![frame0001-current-6hr-3i-3s-6vr](https://user-images.githubusercontent.com/19431804/39824736-0f49af6e-537e-11e8-82b9-cd706f8523d2.png)

You can see that the only blur is in the vertical component.  Changing the `interation` value does not alter the effect, either.

Here is the fixed blur effect (same as above: `6 horizontal radius`, `3 iterations`, `3 sigma`, `6 vertical radius`) [pending PR]:

![frame0001-fixed-6hr-3i-3s-6vr](https://user-images.githubusercontent.com/19431804/39824759-1dcf2af0-537e-11e8-930d-c9a7156b3f20.png)

Now the horizontal radius can be specified along with the vertical radius (or any combination of the two) and changing the iterations will result in more or less blur.


Here's an example with some text overlayed with a "rack focus" (`0 horizontal radius`, `3 iterations`, `3 sigma`, `0 vertical radius` to `10 horizontal radius`, `3 iterations`, `3 sigma`, `10 vertical radius`) over 2 seconds.

Frame 1 (0s) - in focus:

![frame0001-fixed-text_example-0hr-3i-3s-0vr](https://user-images.githubusercontent.com/19431804/39824797-37d659aa-537e-11e8-84b7-536ba63faabd.png)

Frame 48 (2s) - out of focus:

![frame0001-fixed-text_example-10hr-3i-3s-10vr](https://user-images.githubusercontent.com/19431804/39824813-3f5c7baa-537e-11e8-8abf-73d89e1409cb.png)

**Closed** 2019-11-22 21:26 UTC
Labels: duplicate, 💡 enhancement
