### ISSUE TITLE
Show frames in timeline

### ISSUE THREAD

**Issue by qubodup** [OpenShot/openshot-qt#1429] opened 2018-03-28 00:14 UTC
As a video editor, often it is necessary to make keyframe-exact operations. In OpenShot, it is impossible to zoom in close enough for easy keyframe-exact actions.

Allow zooming so close that each frame has a tick in the timeline would make OpenShot much more useable. The current "1 seconds" info in the top right corner seems to be wrong:

![it says 1 second but it's more like 10](https://user-images.githubusercontent.com/18312/38001542-9b589de8-322d-11e8-9457-a6a311d8f65b.png)

**Comment by peanutbutterandcrackers** [comment] 2018-03-28 11:30
This is something that we might see in a not-so-distant future release. I am also looking forward to this feature, good sir.

@DylanC - Kinda' dup of #891

**Comment by DylanC** [comment] 2018-03-28 13:35
@peanutbutterandcrackers - Yes, its the same thing really.

**Comment by ferdnyc** [comment] 2019-07-21 09:34
Closing as duplicate of #891.

**Closed by ferdnyc** 2019-07-21 09:34 UTC
Labels: duplicate
