### ISSUE TITLE
How can i set the path of blender in openshot which i have downloaded from microsoft store

### ISSUE THREAD

**Issue by Mayank0681** [OpenShot/openshot-qt#3412] opened 2020-04-27 04:51 UTC
I have downoaded blender and openshot both from microsoft store. I want to create animated titles and it requires to specify the path of blender. I am unable to find the path of blender which i downloaded from microsoft store. Can anyone tell how to specify its path???

**Comment by SuslikV** [comment] 2020-04-27 05:18
You need regular blender and openshot to use them together. Third party Store software is running in sandbox. Very similar to: https://github.com/OpenShot/openshot-qt/issues/3136

**Comment by ferdnyc** [comment] 2020-04-27 10:02
Agreed, I'm going to close this as a duplicate of #3136 because it's ultimately the same question. (And we unfortunately have the same lack of solutions for both. From all we've been able to determine so far, the answer seems to be: You can't.)

**Closed by ferdnyc** 2020-04-27 10:02 UTC
Labels: OS:Windows, duplicate, question

**Comment by ferdnyc** [comment] 2020-04-27 10:06
Also, I don't know how OpenShot made it into the Microsoft Store, but I don't think we had anything to do with it. Or if we did, it's news to me. Hopefully the version listed there is current, and it's unaltered from the [official releases](https://openshot.org/download/).
