### ISSUE TITLE
Problem Delay sound-pictures

### ISSUE THREAD

**Issue by Maxime0912** [OpenShot/openshot-qt#1502] opened 2018-04-13 20:20 UTC
PC : HP Laptop 17 bs0xx
Windows 10 famille, Version 1709. OpenShot Video Version 2.4.1

Hi,
When I finish a project, I get a mp4 file ..
When I put it online on YouTube, there is a gap between the sound and the image.
How to correct this ?
Thank you for helping me.. Regards.
MP

**Comment by peanutbutterandcrackers** [comment] 2018-04-14 15:06
Could you please try using a daily build? Go over to the [download](https://www.openshot.org/download/) page, click on the 'daily builds' button and grab the latest one from there. Hope the issue has been resolved in the latest daily build.

**Comment by cromo1** [comment] 2018-05-15 10:10
When a video with sound is exported, the exported file has a syncronisation problem: sound is nearly 1,4 seconds late. How to solve. Thanks in advance for your help.

**Comment by peanutbutterandcrackers** [comment] 2018-05-15 11:58
@cromo1 - First, it is very likely that it is indeed the problem of the media player not being able to decode the media stream properly. In which case, I would like to recommend something more stable, like [VLC](https://www.videolan.org/vlc/download-windows.html) instead.
Second, you might want to [try out the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) as a lot of the issues have been resolved in the daily builds and a lot more features have been added, too.
Third, you might want to try out different export profiles and see how they render the video.

Hope that helps!

**Comment by cromo1** [comment] 2018-05-15 14:39
Hello, we have tried out the latest build, same result. Using VLC-media player gives the same result. We are exporting to mp4 files. We think the problem lies in your video editor.

**Comment by peanutbutterandcrackers** [comment] 2018-05-16 03:02
Hmm... could you then perhaps
1. Get the information about the particular media file using [MediaInfo](https://mediaarea.net/en/MediaInfo) and paste it here, please? That would help people help you.
2. Use [HandBrake](https://handbrake.fr/) to transcode the video into something else - like .mkv or something and then try to edit that using OpenShot?

Hope that helps!

**Comment by cromo1** [comment] 2018-05-16 08:37
Here you have the information you have been asking for. To determine the delay we have been using VLC.
[Example-BB-test.txt](https://github.com/OpenShot/openshot-qt/files/2008189/Example-BB-test.txt)

**Comment by peanutbutterandcrackers** [comment] 2018-05-17 03:58
Whoa. Did I see it right? It says framerate: 24,000 FPS!!! Maybe that is the reason why it is having delays. Perhaps you might want to [create your own custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) to edit the videos with. Usually, if your video is shot in a certain FPS and the profile you use to edit it is in a different FPS, these kind of issues arise. Is this, like, a super slow motion video? o.O The profile you are editing the video in needs to match the original footage.

Hope that helps!

**Comment by cromo1** [comment] 2018-05-17 19:30
Hello, in our country 24,000 does mean 24, in the contrary 24.000 does mean 24000. So the framerate is 24 FPS. When I am using Handbrake to convert the file, ererything is OK. When I study Example-BB-test.txt, we do remark there is a different framerate for the video and the audio. could this cause the lack of synchonisation?
Thanks in advance.

**Comment by peanutbutterandcrackers** [comment] 2018-05-18 01:15
@cromo1 - Whoa, that is a strange country. Hehe :laughing: But yes, this might be the main reason. So, I suggest that you switch to a 24FPS profile. That just might fix the problem. Hope this helps!

**Comment by peanutbutterandcrackers** [comment] 2018-05-22 01:38
@cromo1 - Hmm... I see. Well, that is the usual mistake that most of the users make - using different FPS-es. So, yeah. So, yeah. This might be an issue that needs some fixing.
This is not really my app, per say. It is our app. This is a community project that runs from us volunteering to serve and help each other out. I am just a normal user who wants this project to get better, and that is why I try to do my bit to help out. Sorry for the inconvenience (and if my light-hearted remark regarding your nation's numeric format was a tad bit insensitive). I hope the devs can soon get around to fixing this issue.

**Comment by DylanC** [comment] 2018-07-02 09:44
@Maxime0912 Can you try v2.4.2 and let us know if you have any success?

**Comment by cromo1** [comment] 2018-07-03 09:56
Hello Maxime0912,
We have been trying version 2.4.2, Exporting of the Video is not more working.
It seems the problem is not solved, but has grown very much.
We hope you can solve it.
Thanks in advance.
Bert Crommar.

**Comment by peanutbutterandcrackers** [comment] 2018-07-03 10:50
@cromo1 - Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14), too? Thank you!

**Comment by cromo1** [comment] 2018-07-20 10:09
I have good news. About exporting not working: I made a mistake, the video was not added to the timeline. When added it just works fine. And what is more the time gap has dissapeared, everything is working OK.
Maybe insert a message when video is not added to the timeline. Many thanks.

**Comment by DylanC** [comment] 2018-07-20 10:57
@cromo1 - Thanks for letting us know!

**Closed by DylanC** 2018-07-20 10:57 UTC
Labels: 2.4.2-issue

**Comment by Maxime0912** [comment] 2018-07-20 15:04
Hello. In fact, the problem occurs as soon as the video file is loaded into the OpenShot Video Editor app.
The loaded file has the extension "m2ts". As soon as I switch to play mode, there is this shift sound-images ... (the sound is about 1 second behind).
How to cure it ? Ty !

**Comment by cromo1** [comment] 2018-07-21 10:37
Hello,
The only thing I can say is that in my case the timeshift only occurred after the video had been exported. Initial file .ts exported .mp4.
For now, version 2.2, problem seems to be solved, but I have to say I didn't test thoroughly. Initial file .mp4 exported .mp4.
If you find different outcomes, let us know.
Thanks.

**Comment by Kaleriia** [comment] 2018-08-04 01:48
I am with Maxime0912
uploaded Open Shot, checking it out.... pull up a video - previewing ONLY.... no sync between pic and audio

**Comment by cromo1** [comment] 2018-08-04 09:58
OK for the moment we have a video waiting for transforming to .mp4, from the moment it's done we'll check it and let you know. Greetings.

**Comment by cromo1** [comment] 2018-08-04 22:42
We have been transforming the video partially, and there is still a gap between image and sound, but it has become narrower.
It still has to be adjusted.
Thanks in advance.

**Comment by Maxime0912** [comment] 2018-08-05 00:53
Thank you cromo1.. Regards. 
MP

**Comment by Kaleriia** [comment] 2018-08-05 02:29
That will make me so happy.  Still looking at other programs... not found one I like - I like yours except for this small glitch.

    On Saturday, August 4, 2018, 6:42:24 PM EDT, cromo1 <notifications@github.com> wrote:  
 
 
We have been transforming the video partially, and there is still a gap between image and sound, but it has become narrower.
It still has to be adjusted.
Thanks in advance.
