### ISSUE TITLE
Playback preview stops working

### ISSUE THREAD

**Issue by TheOpenDevProject** [OpenShot/openshot-qt#136] opened 2016-03-27 23:41 UTC
After about 1 minute of video being previewed the `Video Preview` component of OpenShot becomes non-responsive. This makes it impossible to continue working. I have checked the memory / CPU usage while this issue is occurring. CPU runs about half and memory still has 8/16GB free with most of that being consumed by other programs. (Open shot using about 1.7)

```
 launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.6)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.0.6
         app:INFO libopenshot version: 0.1.0
         app:INFO platform: Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3+
         app:INFO qt5 version: 5.4.2
         app:INFO pyqt5 version: 5.4.2

```

**Comment by nazikus** [comment] 2016-04-06 12:33
have the same problem, but it stops on the first few frames.
Windows 7, MP4(AVC/AAC) files

**Comment by oyvindstegard** [comment] 2016-11-05 20:56
OpenShot(-qt) 2.1.0 (build from PPA) on Ubuntu 16.04 [Core i5 CPU@3.5GHz, nvidia GTX 960, 16GB RAM]: preview stops after a few seconds, even when pre-converting 1080p@23.97fps raw input material to basic huffyuv codec in AVI container. It can be started again by moving timeline+stop/start, but always stops after a few seconds of playback (with Openshot using huge amounts of CPU). (Also, dragging timeline is generally laggy, and often it fails to follow the mouse pointer all the way. Maybe there are some graphics interaction problems.)

**Comment by DylanC** [comment] 2017-08-22 17:37
@TheOpenDevProject  @nazikus @oyvindstegard - Does this still happen in newer versions of OpenShot?

**Comment by nazikus** [comment] 2017-08-22 18:25
@DylanC it seems better now, but not fully fixed on Windows 8.1 x64.
Before playback was freezing on first several drags of timeline cursor. Now it seems to work ok, but after continuous timeline manipulation, it freezes again.

Here are the debug logs and what I did:
[openshot_logs.zip](https://github.com/OpenShot/openshot-qt/files/1242948/openshot_logs.zip)

- freshly installed v2.3.4, clean run
- added a mp4 (AVC/AAC) video to timeline
- dragged several times back'n'forth cursor on the timeline
- playback freezes, closed application, which took a while, ~10sec

**Comment by oyvindstegard** [comment] 2017-08-22 18:36
@DylanC Hi, I am not able to reproduce this particular failure on Ubuntu 16.04, using Openshot 2.3.4. It used to occur rather quickly after I started dragging the timeline cursor around, play/pause preview, etc, but now it seems fine.

**Comment by DylanC** [comment] 2017-08-23 11:58
@nazikus @oyvindstegard Thanks guys. I will see if we have duplicates of this issue and leave one of them open.

**Comment by DylanC** [comment] 2017-08-24 11:18
@TheOpenDevProject - Closing this ticket since it relates to an older version of OpenShot. Please open a new ticket if the issue exists in the latest version. Thanks.

**Closed by DylanC** 2017-08-24 11:18 UTC
