### ISSUE TITLE
dll load failed openshot

### ISSUE THREAD

**Issue by nanohtpc** [OpenShot/openshot-qt#2841] opened 2019-06-26 15:00 UTC
**Describe the bug:**
After install the latest daily, gives that error..

**Steps to reproduce the behavior:**
Just installed latest daily

**Expected behavior:**
To run the program ...

**System Details:**
- OpenShot Version [e.g. 2.4.4]
- Operating System / Distro: Windows 10 x64

![Screenshot (151)](https://user-images.githubusercontent.com/34278444/60190989-2ed6f100-97f9-11e9-80b9-982ef0b1e70d.png)

**Comment by SuslikV** [comment] 2019-06-26 17:18
Please, follow the instruction on your screenshot and when it fails second time - upload the log-file named `openshot-qt.log` here (thus it will be short and clean of other errors).

WARNING! By deleting the mentioned folder - you also eliminates all application's preferences (they will resets to their defaults).

**Comment by nanohtpc** [comment] 2019-06-26 19:03
well guess what, the log is EMPTY, and got the same message... 8(((

pd. how can i backup the settings then?

**Comment by ferdnyc** [comment] 2019-06-26 21:27
I can reproduce with the x86 version in Wine on Linux. Console output:
```
wine: Call from 0x7bc8eed9 to unimplemented function libopenshot-audio.dll._ZN4juce78this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_release_modeC1Ev, aborting
002e:fixme:ntdll:RtlNtStatusToDosErrorNoTeb no mapping for 80000100
wine: Call from 0x7bc8eed9 to unimplemented function libopenshot-audio.dll._ZN4juce78this_will_fail_to_link_if_some_of_your_compile_units_are_built_in_release_modeC1Ev, aborting
002e:fixme:ntdll:RtlNtStatusToDosErrorNoTeb no mapping for 80000100
002e:fixme:shell:SHGetStockIconInfo Couldn`t find SIID 78, returning default values (IDI_SHELL_FILE)
002e:fixme:shell:SHGetStockIconInfo flags 0x1 not implemented
002e:fixme:shell:SHGetStockIconInfo Couldn`t find SIID 78, returning default values (IDI_SHELL_FILE)
002e:fixme:dwmapi:DwmIsCompositionEnabled 0061D040
```

Looks like an issue caused by the changes to the libopenshot-audio build. I'll hunt down what changed.

**Comment by ferdnyc** [comment] 2019-06-27 00:16
I believe OpenShot/libopenshot-audio#52 will solve this, sorry about that.

**Comment by nanohtpc** [comment] 2019-06-30 03:48
Same error on :

OpenShot-v2.4.4-dev2-1561818534-a8d545ea-9b278998-x86_64.exe

**Comment by ferdnyc** [comment] 2019-06-30 04:08
@nanohtpc Any new Daily Builds produced will have the same problem until OpenShot/libopenshot-audio#52 is merged, which has not yet happened. Stick with [OpenShot-v2.4.4-dev2-1561161190-a8d545ea-9b278998-x86_64.exe](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1561161190-a8d545ea-9b278998-x86_64.exe) for the time being.

**Comment by ferdnyc** [comment] 2019-07-03 18:25
@nanohtpc et al:

With the merge of OpenShot/libopenshot-audio#52, this should now be fixed, and daily builds from July 2 forward should be functional. Please report any issues you encounter with these daily builds or newer:

* [OpenShot-v2.4.4-dev2-1562109194-1b19ae7f-e86f12b6-x86.exe (32-bit)](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1562109194-1b19ae7f-e86f12b6-x86.exe)
* [OpenShot-v2.4.4-dev2-1562107961-1b19ae7f-e86f12b6-x86_64.exe (64-bit)](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1562107961-1b19ae7f-e86f12b6-x86_64.exe)

**Closed by ferdnyc** 2019-07-03 18:25 UTC
Labels: bug
