### ISSUE TITLE
Audio not working?

### ISSUE THREAD

**Issue by HyprNova7** [OpenShot/openshot-qt#4133] opened 2021-05-11 03:36 UTC
So, I edit my friend's youtube videos, he streams them on youtube, then I download them. i have tried 4 seperate clips but I cant get the audio to turn on and it shuts all my other audio off. (music, computer functions, etc) Is there anything i can do to fix this?

**Comment by HyprNova7** [comment] 2021-05-11 21:38
> We overhauled the audio processing system in the Daily Build of OpenShot Video Editor. Download and install the [latest Daily Build](https://www.openshot.org/download/#daily) to address your issue.

thank you so much

**Comment by trougnouf** [comment] 2021-06-05 02:43
> We overhauled the audio processing system in the Daily Build of OpenShot Video Editor. Download and install the [latest Daily Build](https://www.openshot.org/download/#daily) to address your issue.

I just installed the latest git versions and I still get no audio in the exported files.

**Comment by JacksonRG** [comment] 2021-06-07 19:31
@trougnouf are you able to hear the video if you close openshot? Certain operating systems have an issue that openshot blocks other audio outputs, and we're looking for the cause of that.

**Comment by trougnouf** [comment] 2021-06-07 19:46
> @trougnouf are you able to hear the video if you close openshot? Certain operating systems have an issue that openshot blocks other audio outputs, and we're looking for the cause of that.
> 
> Edit: Just saw that you responded to this same advice on #4167.

No, vlc does not even detect an audio stream. In fact I tested exporting the audio only and ended up with an empty (157 bytes) file: [manypriorsaud.zip](https://github.com/OpenShot/openshot-qt/files/6611602/manypriorsaud.zip)

**Comment by JacksonRG** [comment] 2021-06-07 20:34
@trougnouf Thanks for helping me rule that out. I'll take a look into this

**Comment by blegat** [comment] 2021-07-05 21:58
I have the same issue and I can confirm that the daily build solves my issue.

Using Openshot v2.5.1 (given by [ArchLinux](https://archlinux.org/packages/community/any/openshot/)), I have a simple project that combines two mp4 recorded with Zoom (the start and end time of each one are moved and they are placed one after the other).
Opening the input MP4 with VLC, I get the Codec infos:
```
Stream 0
Codec: MPEG AAC Audio (mp4a)
Type: Audio
Channels: Stereo
Sample rate: 32000 Hz
Bits per sample: 32
Stream 1
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Type: Video
Video resolution: 1920x1080
Buffer dimensions: 1920x1088
Frame rate: 25
Decoded format: 
Orientation: Top left
```
The output has simply no audio stream even if in the Advanced Options, "Export To" is set to "Video & Audio".
VLC gives:
```
Stream 0
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Type: Video
Video resolution: 1280x720
Buffer dimensions: 1280x720
Frame rate: 23.997814
Decoded format: 
Orientation: Top left
Chroma location: Left
```
I downloaded the daily build `OpenShot-v2.5.1-dev3-daily-7703-dd859001-6da5d97d-x86_64.AppImage` (dated 3rd of June), opened the same project, exported and it worked, I have sound and audio.

**Comment by JacksonRG** [comment] 2021-07-06 16:15
Closing, as it seems using the daily build addressed the issue.

**Closed by JacksonRG** 2021-07-06 16:15 UTC
Labels: question
