### ISSUE TITLE
Absoultely laggy as heck while trying to watch my preview

### ISSUE THREAD

**Issue by not83** [OpenShot/openshot-qt#284] opened 2016-08-30 09:23 UTC
As soon as video touches the preview the program stops rendering frames and pauses playback. In about 5-10 seconds it while resume but have skipped over clips I have wanted to preview. Start preview again to preview the things you want to see but the same thing happens.

Unless this is fixed then there is no way this editor will  ever be usable.

Ubuntu 14.04 LTS
OpenShot version 2.0.7
Nvidia 660Ti
i5-4570 
8 gigs of RAM

**Comment by rolandixor** [comment] 2016-08-31 05:50
Confirmed on Ubuntu 16.04 - Sandybridge graphics, Openshot 2.1.

In 1.4.3 the "SDL Preview" option used to make playback usable. Not sure if that option can be brought back.

**Comment by DylanC** [comment] 2017-08-24 12:21
@not83 - Closing since this was on a much older version of OpenShot. Please either open a new ticket or comment on a recent issue if you still have the problem. Thanks.

**Closed by DylanC** 2017-08-24 12:21 UTC
