### ISSUE TITLE
2.0.6 segmentation faults

### ISSUE THREAD

**Issue by eGax** [OpenShot/openshot-qt#177] opened 2016-05-04 13:25 UTC
Running OpenShot 2.0.6 from the terminal so I can see the exceptions being thrown. OpenShot throws segmentation faults (core dumped) even when you normally just close out of the application. Also placing a video file of any format type onto the timeline is fine, but trying to touch it to manipulate it in any way gets you, "Unhandled Python exception. Aborted (core dumped)" crash. It reproducible every time and renders OpenShot useless unfortunately. Something else I've observed is sometimes the programs freezes my whole computer for a few seconds as I access menus & features within OpenShot.

Openshot 2.0.6 built from AUR https://aur.archlinux.org/packages/openshot-qt/

My distro/kernel info:
Kernel: 4.4.8-1-MANJARO x86_64 (64 bit) Desktop: Xfce 4.12.3 Distro: Manjaro Linux
CPU:   i5-3570K
MEM:  32GB memory

**Comment by kleinash** [comment] 2016-05-04 16:59
Same here:

OS 2.0.7. Ubuntu 14.04. I have a number of clips that work just fine, but a slice of one of them when I try and move it it gets me this: 

###
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
*** Error in `/usr/bin/python3': corrupted double-linked list: 0x00007fc3a401eb10 ***
Aborted (core dumped)
###
And when I try and up its speed it gives me this: 

###
preview_thread:INFO self.player.Position(): 1
*** Error in `/usr/bin/python3': free(): corrupted unsorted chunks: 0x00007f4b3401aca0 ***
Aborted (core dumped)
###

**Comment by jonoomph** [comment] 2016-07-01 20:33
Yikes, that is ugly. =) Can you please try with our latest preview version? Thx!

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.

**Comment by eGax** [comment] 2016-07-01 23:44
I will when I can and report back.

**Comment by ankitpati** [comment] 2017-02-25 14:02
I notice the segfault when closing the 2.2 AppImage normally on Ubuntu 16.04. Reproducible, and happens every single time.

**Comment by sils** [comment] 2017-03-12 23:00
Getting this as well, makes it unusable :/

**Comment by dpat** [comment] 2017-08-15 21:44
Having this issue as well... it is almost comical, takes multiple attempts to make a small edit

**Comment by DylanC** [comment] 2017-08-22 12:55
@eGax - Do you still have an issue with this on newer versions of OpenShot?

**Comment by DylanC** [comment] 2017-08-23 16:00
@eGax - Closing for now since this was reported on an older version of OpenShot. Please reopen if issue still exists. Thanks.

**Closed by DylanC** 2017-08-23 16:00 UTC
