### ISSUE TITLE
Timeline / Tracks Missing in Ubuntu 22.04

### ISSUE THREAD

**Issue by step4wd** [OpenShot/openshot-qt#4779] opened 2022-04-27 18:34 UTC
**Describe the bug:**
When the application is launched in Ubuntu 22.04, the timeline and tracks are not appearing.A clear and concise description of what the bug is.

**Steps to reproduce the behavior:**
1. On Ubuntu 22.04, download the AppImage version of 2.6.1 and launch it
2. When the window appears, the tracks / timeline is missing

![Screenshot from 2022-04-25 15-04-11](https://user-images.githubusercontent.com/2865249/165595145-d82d67a1-77f5-42ee-88ec-27441d565b07.png)

**Expected behavior:**
Timeline / Tracks should appear for editing

**System Details:**
- OpenShot Version [e.g. 2.6.1]
- Operating System / Distro: [Ubuntu 22.04]
- Python version 3.10.4
-

**Comment by ChrisRolando** [comment] 2022-04-29 21:33
Same exact problem.  Now following

**Comment by jonoomph** [comment] 2022-05-03 18:52
This is fixed in https://github.com/OpenShot/openshot-qt/pull/4787

**Comment by Vidyut** [comment] 2022-05-18 00:05
I have the same problem. Some issue with webengine. Relevant parts from the output:

```
Installed Qt WebEngine locales directory not found at location /tmp/.mount_MiBCtd/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_MiBCtd/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/vidyut/.openshot'
[0518/053126.549404:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
/tmp/.mount_MiBCtd/usr/bin/QtWebEngineProcess: /tmp/.mount_MiBCtd/usr/bin/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
/tmp/.mount_MiBCtd/usr/bin/QtWebEngineProcess: /tmp/.mount_MiBCtd/usr/bin/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)
Installed Qt WebEngine locales directory not found at location /tmp/.mount_MiBCtd/usr/bin/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_MiBCtd/usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/home/vidyut/.QtWebEngineProcess'
[0518/053127.224841:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
...
...
INFO preview_thread: player Position(): 1
INFO timeline: Adjusting max size of preview image: PyQt5.QtCore.QSize(620, 348)
INFO preview_thread: player Position(): 1
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
WARNING webengine: WebEngine backend still not ready after 5 retries.
...
...
Traceback (most recent call last):
  File "/tmp/.mount_MiBCtd/usr/bin/windows/views/webview_backend/webengine.py", line 88, in run_js
    def run_js(self, code, callback=None, retries=0):

```

**Comment by Vidyut** [comment] 2022-05-18 00:06
The line about webengine backend keeps going on and incrementing. So far, it has never resolved with waiting.

The timeline doesn't appear, ever (I accidentally left it overnight once.)

**Comment by JacksonRG** [comment] 2022-05-19 04:36
@step4wd @Vidyut

Are either of you running OpenShot daily build as an appimage?

I believe the fix for this is known. Please try running this  command in a terminal:
`QTWEBENGINE_DISABLE_SANDBOX="1"`
Then launch openshot from that same terminal. If that doesn't work, we'll know this needs more investigation.

Otherwise, are working on including that option in Openshot's launch process.

**Comment by Vidyut** [comment] 2022-05-19 04:58
Thank you for the suggestion, @JacksonRG but I'm sorry to report that it didn't work. Everything I've tried so far:

1. Didn't work with the appimage. 
2. I installed the daily version from repository, which does show the timeline without any hacks needed and is also more stable than the regular version, but it has sync issues between video and audio while editing (though a rendered file seemed fine - it wasn't one where a sync problem would be obvious)
3. I'm uninstalling it and seeing if it will work with the regular version (which used to work well before) - developers/ppa doesn't have a release file
4. Installing from the regular Ubuntu repository - Doesn't launch at all.

Round 2:

Uninstalled the ubuntu repository openshot - it was useless and reinstalled the daily that works for immediate use.

Tried launching the appimage by going to the directory and `QTWEBENGINE_DISABLE_SANDBOX="1" && ./OpenShot-v2.6.1-x86_64.AppImage` No difference. Openshot launches, but no timeline.

Current status, sticking with the daily version and figuring out the sync or a way past it.

**Comment by Vidyut** [comment] 2022-05-19 05:02
Forgot to mention in previous comment - the repository suggests a bleeding edge version repository as well that can be added with `add-apt-repository ppa:jonoomph/openshot-edge` it doesn't have a release file for jammy either.

The only ppa that works with jammp is openshot.developers/libopenshot-daily

The sync issues may well be peculiar to my settings or file or system (still troubleshooting), so I'd recommend anyone with problems with openshot and Ubuntu 22.04 giving it a shot. It seems much better overall. Faster, doesn't crash so far, timeline zooms correctly. Adding clips to the end of the timeline is a bit fiddly, but not even close to a dealbreaker. Downside: It isn't a stable version, so I guess no guarantees it won't wreck something at some point.

**Comment by JacksonRG** [comment] 2022-05-25 19:14
@Vidyut Thanks for your troubleshooting! We'll have to look into why our appimage isn't working, when the PPA of the same code *is*.

Have you tried launching the Appimage now that you've installed openshot and libopenshot daily builds from PPA? It may the Appimage is missing some library that was included when you installed the daily.

**Comment by Vidyut** [comment] 2022-05-25 22:06
Update:

Audio-video sync issues may be due to audio sampling rate mismatch.

Daily appimage now works. Not sure if issue was fixed by ppa installing some library or because my earlier daily appimage wasn't the latest.

With the daily from the ppa the preferences can't be accessed. Openshot crashes. So the current winner now is the appimage. 

The ppa suspect for preferences resulting in crash. must be whatever changed between the package being compiled and the daily appimage.

Remains to be seen if it remains the winner if I uninstall the ppa daily.

Update 2: Uninstalled ppa version.

Appimage wins.

**Comment by lwinmoe51** [comment] 2022-07-23 01:13
I got same problem. How did you solve it? Can you explain in noob way please?

**Comment by kerryhatcher** [comment] 2022-08-10 23:38
@jonoomph @Vidyut I'm running latest daily Appimage on PopOS 22.04 and have the same missing timeline issue. I tried using the latest daily out of the PPA with APT but I ran into a different problem with that, check out my comment on #4086 for those deatils. Running `QTWEBENGINE_DISABLE_SANDBOX="1" && ./OpenShot-v2.6.1-x86_64\(1\).AppImage` doesn't seem to have any effect. 

![image](https://user-images.githubusercontent.com/1011814/184040654-b266c3a6-32c3-45de-8dc2-2e60fd6af328.png)




OS: PopOS 22.04
RAM: 64GB
CPU: AMD® Ryzen 7 5800x 8-core processor 
GPU: NVIDIA Corporation GA106 [GeForce RTX 3060]

GNOME: 42.2
Windowing: X11

Installed via: AppImage

openshot-qt version: 2.6.1
libopenshot version: 0.2.7
platform: Linux-5.18.10-76051810-generic-x86_64-with-Pop-22.04-jammy
processor: x86_64
machine: x86_64
python version: 3.6.9
qt5 version: 5.9.5
pyqt5 version: 5.10.1

GPU Details: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:2D:00.0  On |                  N/A |
|  0%   54C    P0    30W / 170W |    693MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9305120/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9305121/openshot-qt.log)

**Comment by kerryhatcher** [comment] 2022-08-11 00:29
I did some more digging and I realized that the AppImage version I downloaded from the site wasn't the daily build. I really don't know how that happened. I specifically went to the daily page and somehow still downloaded the exact same version I had before. 

The latest daily build AppImage works fine, even solves #4086 for me :shrug: The last few days have been such a time sink to sort this all out...

**Comment by wahabmirjan** [comment] 2022-10-04 03:11
Still not working. Is this released? I downloaded the latest Openshot (2.6.1) to work with Ubuntu 22.04 but I cannot see the timeline.

**Comment by jonoomph** [comment] 2022-10-04 13:51
Please try and download our latest daily build: https://openshot.org/download/#daily. If this does not work for you, please attach a screenshot of your "About OpenShot" dialog, which contains the version information. Thanks and good luck.

On a side note, we will be releasing a new version VERY soon, which will hopefully prevent more people from having issues trying to locate our daily builds.

**Comment by methatronc** [comment] 2022-11-07 20:13
I use an ubuntu-based distro ( mint ) and encountered the same issue, but if it can help I got rid of this problem by using the parameter indicated by JacksonRG in an env command before the link.
Here is my .desktop file :
```
[Desktop Entry]
Name=OpenShot Video Editor
GenericName=Video Editor
X-GNOME-FullName=OpenShot Video Editor
Comment=Create and edit amazing videos and movies
Exec=env QTWEBENGINE_DISABLE_SANDBOX="1" "/home/user/path/to/OpenShot-v2.6.1-x86_64.AppImage"
Terminal=false
Type=Application
Icon=/home/user/path/to/icon
Categories=GNOME;GTK;AudioVideo;Video;AudioVideoEditing;
```

**Comment by TheTimeSink** [comment] 2022-12-01 05:44
New to this, but:
No tracks showing with the AppImage from the download page.
Same for the PPA.
Then: the AppImage from the daily page is showing the tracks!
Ubuntu 22.04.1

**Comment by basedSkeleton** [comment] 2022-12-08 02:07
> Thank you for the suggestion, @JacksonRG but I'm sorry to report that it didn't work. Everything I've tried so far:
> 
>     1. Didn't work with the appimage.
> 
>     2. I installed the daily version from repository, which does show the timeline without any hacks needed and is also more stable than the regular version, but it has sync issues between video and audio while editing (though a rendered file seemed fine - it wasn't one where a sync problem would be obvious)
> 
>     3. I'm uninstalling it and seeing if it will work with the regular version (which used to work well before) - developers/ppa doesn't have a release file
> 
>     4. Installing from the regular Ubuntu repository - Doesn't launch at all.
> 
> 
> Round 2:
> 
> Uninstalled the ubuntu repository openshot - it was useless and reinstalled the daily that works for immediate use.
> 
> Tried launching the appimage by going to the directory and `QTWEBENGINE_DISABLE_SANDBOX="1" && ./OpenShot-v2.6.1-x86_64.AppImage` No difference. Openshot launches, but no timeline.
> 
> Current status, sticking with the daily version and figuring out the sync or a way past it.

FYI you're loading it wrong.
The proper way to set enviroment variables is like so:
`QTWEBENGINE_DISABLE_SANDBOX="1" ./OpenShot-v2.6.1-x86_64.AppImage`
This fixed the issue for me.

**Comment by smittie** [comment] 2023-02-24 21:31
OpenShot installed from ppa on 23Feb2023
Version: 3.0.0 libopenshot: 0.3.0
Installed on Linux Mint 21.1 Cinnamon 5.6.7
Python 3.10.6
Intel Core i7-1170
62.5 GiB RAM
NVIDIA TU116 [GeForce GTX 1660 Ti]
Full sysinfo available if requested

If I open OpenShot from the DE launch menu, the new project window is missing the timeline and the blue scrub bar.
If I open an existing project the timeline and blue scrub bar are there. If I choose New Project from the file menu from the existing project window, the new project window has the timeline and scrub bar.
Launching OpenShot from the terminal window shows errors that indicate something related to WebEngine got broken (output in attached file).
All of the above is 100% reproducible.

Questions welcome.

[openshot-qt bug 4779 WebEng Error.txt](https://github.com/OpenShot/openshot-qt/files/10828959/openshot-qt.bug.4779.WebEng.Error.txt)

**Comment by Colorjet3** [comment] 2023-02-24 21:38
Hello @smittie Please give the following options a try as this issue has been fixed in the latest DEV Daily build of v3.0.0.

Option 1 - Download and run the AppImage
1.  go to openshot.org/download/#daily.
2.  Download the latest available AppImage and run it.

Option 2 - Install the Daily Build via PPA.
1.  apt purge openshot-qt.
2.  apt autoremove
3.  apt-add-repository ppa:openshot.developers/ppa
4.  apt install openshot-qt.
5.  Find the Openshot icon and run it.

Let me know the results.

**Comment by smittie** [comment] 2023-02-24 22:02
Followed all steps in Option 2 which installed the following:

INFO app: openshot-qt version: 3.0.0
INFO app: libopenshot version: 0.3.0
INFO app: platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
INFO app: processor: x86_64
INFO app: machine: x86_64
INFO app: python version: 3.10.6
INFO app: qt5 version: 5.15.3
INFO app: pyqt5 version: 5.15.6

On first launch, issue did not reproduce.
Select New Project from File menu on open window, issue did not reproduce.
Quit OpenShot, went to existing project file. Right clicked and opened file
with OpenShot. Issue did not reproduce.

Launch OpenShot from terminal command line, 62 lines of "...of object
'TimelineWebView' has no notify signal and is not constant, value updates
in HTML will be broken!" registered.

Removing OpenShot, deleting the TimeLineWebView objects and reinstalling
OpenShot from the stable PPA temporarily fixed this issue once before. I
would like to see if the problem recurs. I am not sure what behaviour
causes the TimeLineWebView to break.

I really appreciate the quick response and clear course of action to
follow.

Respectfully,
   Smittie

**Comment by Colorjet3** [comment] 2023-02-25 01:33
Hello @smittie You should be running the "Daily PPA" and not the "Stable PPA" as there were specific fixes made in the Daily Build to address the issue in Ubuntu.

**Comment by smittie** [comment] 2023-02-25 02:53
OK. I wondered if I had not successfully changed the PPA. Will fix it
correctly and try again.

**Comment by smittie** [comment] 2023-03-03 19:29
Downloaded the most recent AppImage release available on openshot.org/download/#daily (OpenShot-v3.0.0-daily-11058-8f92bac0-b5bbab66-x86_64.AppImage). Timeline and Scrub bar are missing. If I quit OpenShot and reopen by double click on the AppImage icon and then open the project from the Recent menu, the timeline and scrub bar are back.

What additional information would you like to have?

![Screenshot for Bug #4779](https://user-images.githubusercontent.com/12665975/222809515-e5eece8b-0bf7-4d95-95d8-07114ce10ca5.png)

**Comment by Colorjet3** [comment] 2023-03-04 01:33
Hi @smittie.  Thank you so much for that information.  I need to get lead developer to look at this.  Stay tuned...

**Comment by smittie** [comment] 2023-03-04 01:38
The libopenshot.log contains nothing interesting. The openshot-qt.log might be interesting. Attached here.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10887207/openshot-qt.log)

**Comment by jonoomph** [comment] 2023-03-05 21:44
@smittie Thanks for helping us explore this bug in more detail. I am a little confused though. When you double click the AppImage (latest daily image), are the scrub bar and timeline always visible? Just to be clear, the PPA installed version of OpenShot is completely different than the AppImage - and so, we need to be very clear on which one we are testing, and which one is exhibiting an issue.

If the AppImage is still having this issue, please describe the step by step instructions for our team to reproduce the issue. If it's the PPA that is having the issue, please describe the step by step for that as well.

And as always, if you can record a quick video demonstrating your experience, that is almost always super helpful! Thanks again for helping us with this bug report.

**Comment by smittie** [comment] 2023-03-05 22:17
I removed the daily PPA version of OpenShot (via sudo apt remove openshot-qt). I deleted the .openshot_qt directory in the home directory. I then used the Cinnamon File Manager GUI to search for all the occurrences of 'OpenShot' and deleted anything that might be used by the application. I then downloaded the most recent AppImage. All of the testing that I reported here is, to the best of my knowledge, using only what has been created using the AppImage. I am wiling to redo this if my test results here are questionable.

Opening the AppImage (OpenShot-v3.0.0-daily-11058-8f92bac0-b5bbab66-x86_64.AppImage) always results in a complete project window; scrub bar and timeline intact. I apologize but I do not remember how I got to the project window not having scrub bar and timeline.

As of yet, I do not have a reproducible test case. I have only seen the issue one time on the AppImage that I am using. I have tried a few things to get the issue to repro. I use OpenShot daily.

**Comment by Colorjet3** [comment] 2023-04-23 02:16
Hell @smittie I am reviewing and cleaning up some old open issues.  I see that you indicate that the AppImage seems to be working for you.

I also want to let you know that v3.1.1 has been released with many more bug fixes and some minor enhancements.

If you want to run the PPA instead of the AppImage please perform these commands for a clean installation:

# sudo apt purge openshot-qt
# sudo apt autoremove
# sudo apt-add-repository ppa:openshot.developers/ppa
# sudo apt update
# sudo apt install openshot-qt

**Closed as completed by Colorjet3** 2023-04-23 02:16 UTC

**Comment by TheTimeSink** [comment] 2023-04-23 02:21
Thank you! I'm just learning editing and this looked like a good tool to use,
Dan
    On Saturday, April 22, 2023 at 07:17:32 PM PDT, Colorjet3 ***@***.***> wrote:  
 
 


Hell @smittie I am reviewing and cleaning up some old open issues. I see that you indicate that the AppImage seems to be working for you.

I also want to let you know that v3.1.1 has been released with many more bug fixes and some minor enhancements.

If you want to run the PPA instead of the AppImage please perform these commands for a clean installation:

sudo apt purge openshot-qt

sudo apt autoremove

sudo apt-add-repository ppa:openshot.developers/ppa

sudo apt update

sudo apt install openshot-qt

**Comment by smittie** [comment] 2023-04-23 02:27
I've been on the daily PPA since shortly after my last message. I keep the daily PPA for bug regressions. I generally don't use AppImages at all. They're a pain in the a$$ on linux.

**Comment by Colorjet3** [comment] 2023-04-24 18:57
Sounds good @smittie You can run the Stable PPA now (v3.1.1).  I've been using the AppImage because as a tester I need to get the daily build to test the new code and this is the only way to get to it.  However, I agree, whenever possible I'd rather install via PPA.  Unfortunately, it seems like each distro has their own timing on when they make the latest and greatest available.

Have a great day!
