### ISSUE TITLE
Replace clip

### ISSUE THREAD

**Issue by stefan-reich** [OpenShot/openshot-qt#2792] opened 2019-05-17 12:57 UTC
I would like to replace the content file (image/video/audio) that a clip is based on, without moving the clip or changing its properties and effects etc.

I think that is an extremely common use case?

Let's say I have an existing project and want to keep its structure, just replace the title, audio and video files. How would I do that?

I'm using OpenShot-v2.4.3-x86_64.AppImage.

Thanks.

**Comment by SuslikV** [comment] 2019-05-17 17:28
Each source clip has different characteristics (length, for example), so just add new clip to _Timeline_ (at different track) align the start of the clip to existing one (use max enlarge of the _Timeline_ view, because alignment accuracy may depend of magnification, that itself probably the web engine's bug that is used in OpenShot). Cut the new clip via right-click menu _Slice_ at needed position. Titles editable.

If only path to the source clip needs to be changed, then right-click in _Project Files > Files Properties > the button "Browse"_ , update changes.

**Comment by peanutbutterandcrackers** [comment] 2019-05-19 13:24
Something like this is kinda'-sorta' possible. If you click on the file in the 'project files' tab, there should be something called 'browse' that might do this. I'm sorry I can't remember exactly what it was. @SuslikV seems to have gotten it right.

**Comment by stefan-reich** [comment] 2019-05-19 16:11
OK, replace in the project files, not in the time line... yeah, might do it.

**Comment by stefan-reich** [comment] 2019-06-30 15:09
Well it seems the "browse" button has disappeared... [Screenshot](http://botcompany.de/images/1101683)

**Comment by SuslikV** [comment] 2019-06-30 17:01
Try to use Tab key to see if still here (right after dialog opened: hit the Tab button 3 times and press Space bar).

**Comment by ferdnyc** [comment] 2019-07-21 07:31
@stefan-reich I can't reproduce the missing Browse button issue with either 2.4.4 release or the current development code — can you let us know if you're still seeing that issue? Otherwise I think this can be closed?

Actually, because this was submitted as a question which has been answered, I'm going to close it anyway. If you're still seeing the Browse button issue, please report that using the Bug Report template. Thanks!

**Closed by ferdnyc** 2019-07-21 07:31 UTC
Labels: enhancement
