### ISSUE TITLE
AppImage fails on Arch Linux running XFCE

### ISSUE THREAD

**Issue by DaveJarvis** [OpenShot/openshot-qt#3659] opened 2020-08-09 20:26 UTC
``` 
$ ./OpenShot-v2.5.1-x86_64.AppImage 
Loaded modules from current directory: /tmp/.mount_gD9RzA/usr/bin
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
         app:INFO ------------------------------------------------
         app:INFO             Sun Aug  9 13:22:20 2020            
         app:INFO               Starting new session              
         app:ERROR OpenShotApp::Import Error: libselinux.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 104, in <module>
    main()
  File "openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/tmp/.mount_gD9RzA/usr/bin/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2284, in _handle_fromlist
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1200, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1129, in _exec
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1471, in exec_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
  File "/tmp/.mount_gD9RzA/usr/bin/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 28, in <module>
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 20, in swig_import_helper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2237, in _find_and_load
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 2226, in _find_and_load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1191, in _load_unlocked
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 539, in _check_name_wrapper
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 1715, in load_module
  File "/usr/lib/python3.4/importlib/_bootstrap.py", line 321, in _call_with_frames_removed
ImportError: libselinux.so.1: cannot open shared object file: No such file or directory
         app:INFO             OpenShot's session ended            
         app:INFO             Sun Aug  9 13:22:27 2020            
         app:INFO ================================================
```

However:

```
$ pacman -S openshot
```

Installs fine, then runs fine:

```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3.8/site-packages/openshot_qt
QFont::fromString: Invalid description '(empty)'
QFont::fromString: Invalid description '(empty)'
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: bb10dark, bb10bright, cleanlooks, gtk2, cde, motif, plastique, qt5ct-style, Windows, Fusion
         app:INFO ------------------------------------------------
         app:INFO             Sun Aug  9 13:24:55 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.7.12-arch1-1-x86_64-with-glibc2.2.5
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.8.5
         app:INFO qt5 version: 5.15.0
         app:INFO pyqt5 version: 5.15.0
     metrics:ERROR Error determining OS version in metrics.py
    language:INFO Qt Detected Languages: ['en-CA']
    language:INFO LANG Environment Variable: en_CA.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /usr/lib/python3.8/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
files_listview:INFO currentChanged
files_listview:INFO updateSelection
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
     version:INFO Found current version: {"openshot_version": "2.5.1"}
 files_model:INFO updating files model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
 main_window:INFO Clear all thumbnails: /home/username/.openshot_qt/thumbnail
preview_thread:INFO initPlayer
 main_window:INFO Clear all animations: /home/username/.openshot_qt/blender
 main_window:INFO Clear all titles: /home/username/.openshot_qt/title
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['/usr/bin/openshot-qt']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HD 720p 30 fps
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
video_widget:INFO Set video widget pixel aspect ratio to: 1.0
 main_window:INFO updateStatusChanged
 main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
preview_thread:INFO onModeChanged
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(724, 407)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO SetThumbAddress: http://127.0.0.1:35849/thumbnails/
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
```

Not sure what this means for the AppImage, but thought you should know it doesn't work everywhere.

**Comment by ferdnyc** [comment] 2020-08-09 22:00
@DaveJarvis 

Does the AppImage run correctly _after_ you installed OpenShot via `pacman`? It may be that it brought in a dependency with it.

AppImages will never run _everywhere_, there's a certain minimum host system capability that's assumed to be present. One of those capabilities is `libselinux`, which is what your system is/was lacking originally.

It's possible installing OpenShot brought along `libselinux.so.1` as a dependency. Or it's possible that the OpenShot dependencies on Arch are built without linking to `libselinux.so.1`, in which case we should probably explore whether we can package the AppImage the same way. (Though I'm a little worried what implications that might possibly have on systems that **do** use SELinux.)

**Comment by DaveJarvis** [comment] 2020-08-09 22:44
From the homepage:

> Linux (64-bit AppImage)
> AppImage requires no installation. Just download, make executable, and run.


> AppImages will never run everywhere, there's a certain minimum host system capability that's 

The prose on the homepage is a _little_ misleading, then: on Arch Linux the steps didn't work.

> It's possible installing OpenShot brought along libselinux.so.1 as a dependency.

Not sure if that's the root cause. After installing using `pacman` then running the AppImage, the same (?) error occurs:

```
$ ./OpenShot-v2.5.1-x86_64.AppImage 
Loaded modules from current directory: /tmp/.mount_ZYFZK1/usr/bin
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
         app:INFO ------------------------------------------------
         app:INFO             Sun Aug  9 15:42:44 2020            
         app:INFO               Starting new session              
         app:ERROR OpenShotApp::Import Error: libselinux.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot.py", line 18, in swig_import_helper
  File "/usr/lib/python3.4/imp.py", line 297, in find_module
ImportError: No module named '_openshot'
```

Hope it helps!

**Comment by ferdnyc** [comment] 2020-08-10 03:27
@DaveJarvis 

Agreed, the website overpromises. Or AppImages under-deliver. Probably a bit of both, I suppose. They've definitely been a disappointment on the compatibility front, though. I can see why container-based systems like Flatpak have grown more prominent, though those have their own problems. (For one, sandboxing would prevent our integrations with external apps like Inkscape and Blender.)

Anyway, this is a known issue, closing as duplicate of #2278.

**Closed by ferdnyc** 2020-08-10 03:27 UTC
Labels: :beetle: bug
