### ISSUE TITLE
Flipping Video

### ISSUE THREAD

**Issue by H2vegas** [OpenShot/openshot-qt#2700] opened 2019-03-22 17:34 UTC
Hello,

This is Tony from How 2 Vegas. I am currently having problems with rotating a video of mine.  I have rotated other clips with OpenShot before but this clip will not rotate for me.

What I normally do is right click on the video clip I need to rotate and click on the rotate icon. Then I use the 90 or 180 and that flips it to where I need it.  The problem I currently have is that when I use the 90 it just puts the video vertically on its side.  When I do the 180 it puts the video nice and full screened but upside down.

Please help

**Comment by ferdnyc** [comment] 2019-09-15 12:05
I'm going to close this as a duplicate of #2794 / #2969, which contain the most detail on this issue.

**Closed by ferdnyc** 2019-09-15 12:05 UTC
Labels: duplicate
