### ISSUE TITLE
Overlapped frame in side by side placed images

### ISSUE THREAD

**Issue by croco3008** [OpenShot/openshot-qt#1337] opened 2018-03-05 12:30 UTC
* Operating System: Ubuntu 16.04_x86_64
* OpenShot Version: 2.4.1/ Latest GIT

How to reproduce:
1. Download example images:
https://www.dropbox.com/s/6rlyw94t6fmtmum/A.png?dl=0 and https://www.dropbox.com/s/wrzt321civappbo/B.png?dl=0
2. Drag images to timeline side by side
3. Use zoom=1s.
4. Seek to position 10:01

Result: Both images are visible in that frame, but they shouldn't.

**Comment by peanutbutterandcrackers** [comment] 2018-03-06 04:15
@DylanC - Turns out that happens. I can confirm. Perhaps this needs to be sorted out? o.O

![screenshot from 2018-03-06 09 59 33](https://user-images.githubusercontent.com/26764547/37013928-33ec1928-2125-11e8-8e88-1d8b2893e942.png)

**Comment by gary9872** [comment] 2018-03-10 20:53
Same thing here. The snap seems to be out by a 1/2 second?

Whilst I was advancing by frames I noticed a jump from 9:24 to 10:01. Anyone else having that issue as well?

**Comment by peanutbutterandcrackers** [comment] 2018-03-11 02:57
@gary9872 - I think OpenShot does Hr:Min:Sec:Frames and since you're probably using 24fps, it moves from 9:24 to 10:01. I think that is what's happening. Do you think we need to change the display format so that it can be more clearer? Do you perhaps have any ideas, good sir?

**Comment by N3WWN** [comment] 2018-05-09 20:55
I can confirm this bug.  I was recently placing SVG files onto the timeline with snapping enabled and there was definite overlap when the images were butted up against each other.

Not sure if it's the same bug that is causing the issue reported in #1478, but I'd like to see that bug resolved first and then see if this one is sorted automagically by the same change.

**Comment by jkenny23** [comment] 2019-01-07 23:47
Still seeing this is 2.4.3. Easy to reproduce, create 2 titles, place side by side (snap together in the timeline), and there is a 2-frame overlap. Project settings 1080p 59.94, and I tried setting both of the titles to 59.94 (60000 / 1001, same as project settings) before adding them to the timeline via file properties also, still get an overlap.

**Comment by N3WWN** [comment] 2020-10-27 13:04
This issue is still present in the OpenShot-v2.5.1-dev2 daily builds.

**Comment by N3WWN** [comment] 2021-04-26 13:37
Confirmed that this is still an issue in the most recent nightly build (April 26, 2021, 6:02 a.m.): https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.5.1-dev2-daily-7320-a00bbb76-503515e6-x86_64.dmg

**Comment by DanPinGF** [comment] 2021-10-27 21:50
It happens to me, too. I'm on Windows.

**Comment by N3WWN** [comment] 2021-10-28 12:37
This issue is still present in the OpenShot-v2.6.1-dev-daily-8409-111026d8-73c519f0-x86_64.AppImage daily build, but it is only a single frame of overlap now.  We're half way to having this issue resolved ;)

**Comment by DanPinGF** [comment] 2021-10-28 18:21
And I would consider this a long-term bug, since it appears to be persistent since 2.4.1 or earlier. I’d probably add a ‘🔥 hot’ label to this issue.

**Comment by DanPinGF** [comment] 2022-04-27 17:50
@JacksonRG - This issue needs fixing...

**Comment by DanPinGF** [comment] 2022-10-29 03:05
@JacksonRG - We still need to get this fixed...

**Comment by N3WWN** [comment] 2022-11-07 23:34
Yes, this is still an issue in the latest daily builds, too

**Comment by Colorjet3** [comment] 2023-01-24 02:50
Hello @N3WWN This should be fixed in the latest DEV Daily build of v3.0.0.  Give it a try and let us know either way.

**Comment by N3WWN** [comment] 2023-01-24 14:37
@Colorjet3 I was unable to replicate the problem with the Jan 18 daily build (OpenShot-v3.0.0-daily-10947-510a7690-b5bbab66-x86_64.AppImage), so it appears to be resolved... at least on Linux.  

@DanPinGF Can you test on Windows?

Thanks!

**Comment by Colorjet3** [comment] 2023-01-24 16:55
@N3WWN Thank you for testing and confirming that the issue is resolved in Linux.  I just tested in Windows 11 and the issue is resolved.  However, I will wait until @DanPinGF confirms as well and then I'll close this ticket.

**Comment by DanPinGF** [comment] 2023-01-24 18:44
@Colorjet3 - I actually did see it got fixed in version 3.0.0, so I think it’s safe to wrap up this issue.

**Comment by Colorjet3** [comment] 2023-01-24 18:51
That is great @DanPinGF

**Closed by Colorjet3** 2023-01-24 18:51 UTC
Labels: :lady_beetle: bug
