### ISSUE TITLE
Video preview incredible slow

### ISSUE THREAD

**Issue by Symbai** [OpenShot/openshot-qt#447] opened 2016-12-29 12:16 UTC
I got 64GB ram and assigned up to 10GB for openshot cache.
However even a 500mb video file, the video preview stutters and hangs and freezes if I switch through the timeline.

It is impossible to make cuts this way. My computer is definitely fast enough (8 physicals cores, 16 total). Openshot + video files are on SSD.

(Windows, Openshot 2.2, Memory cache method)

//edit: The slowdown / freeze happens after many preview images have been created in short time. Let's say I hold down the position marker and scroll through the time line. Then after 10-20 preview images have been created the last preview image remains. It won't generate any new preview images. I have to wait a minute or so then I can do the same thing again until it stucks again.

From my point of view it looks like something isn't cleared/closed and I have to wait for a garbage collector.

**Comment by exaveal** [comment] 2016-12-29 15:41
Same problem for me. The computer is out of memory. 8GB are fully used after several seconds of preview or moving the position marker. see attached screenshot.
![openshot_ram](https://cloud.githubusercontent.com/assets/21370398/21547317/93dd75b4-cde5-11e6-9357-34f4dda9ce60.png)

**Comment by gasparfm** [comment] 2016-12-30 02:39
Mee too. Had the same problem in Linux Mint KDE. 16Gb RAM on my system and over 10Gb eaten up by Openshot. I had this problem with all video files but it is worse when using mp4 video files (h264 codec). I tried converting them to xvid and I could preview a little bit faster (I think it should be even faster as I tried with KDEnlive and Blender too), and it uses less RAM.

**Comment by exaveal** [comment] 2016-12-30 12:15
Thats a pitty, it's not possible for me to change the codec of all source-files. I'm looking now for an alternative software. After 5 years :(

**Comment by exaveal** [comment] 2016-12-30 12:25
I opened the same project with Openshot 1.4.3 on the same computer. Preview isn't lagging and the programm uses much less of memory. This is a memory-leak bug somewhere in the new openshot.
![openshot1 4 3_ram](https://cloud.githubusercontent.com/assets/21370398/21565058/6c72a284-ce93-11e6-99d1-7c47ce0cebb8.png)

**Comment by exaveal** [comment] 2017-01-03 13:36
I reported the bug in launchpad and tried to describe it as best as possible (for me 😄 ): https://bugs.launchpad.net/openshot/+bug/1653241
Please support a fix of the problems via "This bug affects you" and/or add more details.

**Comment by CHazz** [comment] 2017-03-07 22:24
confirmed preview is unusable

**Comment by zoterite** [comment] 2017-05-11 16:35
I have the same problem! Lags in video preview(windows 7 x64).

**Comment by DylanC** [comment] 2017-08-25 12:44
Duplicate of #427. We can track the issue there instead.

**Closed by DylanC** 2017-08-25 12:44 UTC
Labels: duplicate
