### ISSUE TITLE
Letter case in project name is discarded in main window title and export file name

### ISSUE THREAD

**Issue by kimsey0** [OpenShot/openshot-qt#2622] opened 2019-02-14 21:33 UTC
**Describe the bug:**
When opening a OpenShot project with a file name that includes upper case letters, these will be converted to lower case in the main window title and the file name field in the export dialog. As an example, opening a project file named "My Video Project.osp" will result in a main window title of "My video project ... - OpenShot Video Editor" and a default value of the file name field in the export dialog of "My video project".

**Steps to reproduce the behavior:**
1. Run OpenShot and create a new project.
2. Save it as "My Video Project.osp"
3. Open the Export video dialog by clicking the 🔴 icon.

**Expected behavior:**
After saving the project, the main window title should be "My Video Project [Default Settings] - OpenShot Video Editor".
After opening the Export video dialog, the File name field should be pre-filled with the value "My Video Project".

**System Details:**
- OpenShot Version 2.4.3
- Operating System / Distro: N/A

**Technical Details:**
This behavior is caused by two calls to `str.capitalize` in [main_window.py](https://github.com/OpenShot/openshot-qt/blob/dca828bd1deb9677ecfb83153f735c8cc01fd8cb/src/windows/main_window.py#L1939) and [export.py](https://github.com/OpenShot/openshot-qt/blob/6e7fa7657506faaef18aa170315e34fcfd6cd342/src/windows/export.py#L156), which don't just capitalize the first letter of the file name, as might be expected, but also [lower cases the rest of the letters](https://docs.python.org/3/library/stdtypes.html#str.capitalize).

It could be fixed either by only capitalizing the first letter, leaving the case of the rest of the letters intact, by capitalizing the first letter of each word, using for example [`string.capwords`](https://docs.python.org/3/library/string.html#string.capwords), or (my favorite) by leaving the casing the user chose as is.

I'll be happy to implement either solution if there's consensus about it.

**Comment by N3WWN** [comment] 2019-02-14 22:30
I can confirm that this has been an issue for quite a while.  

IIRC, things like hyphens are also removed from the saved files, so "Project - 1 of 2 - Draft.osp" would be exported as "Project 1 of 2 draft.mp4".

**Comment by kimsey0** [comment] 2019-02-14 22:40
Yea, hyphens and underscores are also removed in the line in export.py that's linked above. I don't know why that happens either, and would probably prefer for it to be changed.

**Comment by udippel** [comment] 2019-05-26 11:08
As a *nix-user for the last 20 years, I'd also appreciate this. Because the dino that I am, the first rule for filenames I learned was: 'no blanks!'.

**Comment by jandermoreira** [comment] 2019-12-06 18:24
I think the filename (as well as the project name) should not be modified at all. I don't like space in filenames and use hyphens and underscores meaningfully. I don't capitalize letters too.

**Comment by nanohtpc** [comment] 2019-12-06 18:29
The project name SHOULD BE  exactly as the .OSP file.... like it is right
now... in the latest daily build

**Comment by ferdnyc** [comment] 2019-12-06 18:37
Indeed, this was fixed in #3052.

**Closed by ferdnyc** 2019-12-06 18:37 UTC
Labels: :beetle: bug
