### ISSUE TITLE
American English (en_US) language setting not working

### ISSUE THREAD

**Issue by andyrays** [OpenShot/openshot-qt#331] opened 2016-09-09 23:31 UTC
When I choose "American English (en_US)" under Preferences -> General -> Language, it still shows the application in "Dansk (da)" (which is a mix of English and Danish).
![skaermbillede 2016-09-10 01 18 33](https://cloud.githubusercontent.com/assets/1384649/18405861/25bca9ba-76f6-11e6-8553-7e52430e5df4.png)

![skaermbillede 2016-09-10 01 18 24](https://cloud.githubusercontent.com/assets/1384649/18405863/286da84e-76f6-11e6-8d91-37b3c02c612f.png)

"The British English (en_GB)" seems to work fine.
My system language is English, but location is Denmark.

Update: On Windows 10 Home 64 bit, OpenShot 2.1.0

**Comment by gebeleixis** [comment] 2016-09-10 12:22
happens the same to me win openshot 2.1.0 on win 10 64 insider preview 14915 in english with region italy.

**Comment by firepol** [comment] 2017-02-17 16:06
Happens to me too, Openshot 2.2.0, Win 10 64 in English, Region: German Switzerland.

British English works fine for me too.

**Comment by peanutbutterandcrackers** [comment] 2018-02-16 03:31
I think this has been resolved in OpenShot 2.4.1; could you all please try that version out, kind sirs? *tips top hat* (Yeah, too much victorian era novels. lol)

**Comment by MadOPcode** [comment] 2018-03-02 15:00
In 2.4.1 the bug is still present.

**Comment by peanutbutterandcrackers** [comment] 2018-03-03 10:55
I hae a good news. Someone has figured out why the bug is still there. https://github.com/OpenShot/openshot-qt/issues/1256#issuecomment-368326693 And @DylanC will be making a Pull Request as soon as the pending PRs are sorted. That should fix it. So, yeah. :)

**Comment by peanutbutterandcrackers** [comment] 2018-03-05 08:08
@andyrays - A PR has just been merged, that will probably solve this. Could you please try the [latest build of OpenShot](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.1-30-gce4232b-59-683-x86.exe) and see if this bug is fixed or not? Thank you!

**Comment by peanutbutterandcrackers** [comment] 2018-03-07 04:26
[Daily Builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily)

**Comment by MadOPcode** [comment] 2018-03-07 15:02
Changing interface language to American English works fine in OpenShot-v2.4.1-34-g6a9257e-59-685.

**Comment by DylanC** [comment] 2018-03-20 15:25
@peanutbutterandcrackers - Closing this issue now since it has been confirmed as working. All duplicates have also been closed.

**Closed by DylanC** 2018-03-20 15:25 UTC
Labels: bug

**Comment by peanutbutterandcrackers** [comment] 2018-03-21 04:08
@DylanC - As you see fit, Cap'ain! I hope others will confirm too, soon. Thank you for the great work!
