### ISSUE TITLE
Lose Wave Form on Openshot

### ISSUE THREAD

**Issue by LokiDawg** [OpenShot/openshot-qt#2634] opened 2019-02-21 13:48 UTC
The displayed wave form vanishes and I cannot get it back after a clip is cut into another strip.  When I try to create waveform for audio again, it will only show on one (first) clip regardless of which clip is hignlighted.  other clips sometimes show a flatline.

**System Details:**
- OpenShot Version2.4.3
- Operating System windows 10  64BIT 1809

**Screenshots:** (Optional)
These clips all have audio and it displays/plays properly.

<img width="715" alt="open shot screenshot" src="https://user-images.githubusercontent.com/47857581/53173223-79730300-35a4-11e9-8489-e33aec66a975.png">

**Comment by Brooderman** [comment] 2019-03-01 04:29
I can confirm this. be nice to expand the y axis to see more waveform detail.

**Comment by jonoomph** [comment] 2019-03-18 05:34
This is fixed in our release branch. Should have a new release candidate available on the website soon to verify this works correctly. Feel free to re-open this issue if the verification goes badly. =)

**Closed by jonoomph** 2019-03-18 05:34 UTC
Labels: bug

**Comment by XanderLeaDaren** [comment] 2020-06-15 14:33
Looks like it’s related to #3456
