### ISSUE TITLE
Export Dialog Does Not Open, "ERROR Unhandled Exception"

### ISSUE THREAD

**Issue by clockworkpc** [OpenShot/openshot-qt#594] opened 2017-04-19 02:07 UTC
**System Details:**
* Ubuntu 16.04
* OpenShot Version: 2.3.1 (freshly installed from PPA)

**Issue Description and steps to reproduce:**

Load up a video, click on the big red EXPORT button and the export dialog window does not open.  No response from the GUI, and the following in the terminal:

```
exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/main_window.py", line 626, in actionExportVideo_trigger
    win = Export()
  File "/usr/lib/python3/dist-packages/openshot_qt/windows/export.py", line 88, in __init__
    get_app().window.timeline_sync.timeline.ClearAllCache()
  File "/usr/lib/python3/dist-packages/openshot.py", line 4108, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Timeline, name)
  File "/usr/lib/python3/dist-packages/openshot.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python3/dist-packages/openshot.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
     metrics:INFO Track metric: {'access-control-allow-origin': '*', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'content-type': 'image/gif', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'content-length': '35', 'content-location': 'http://www.google-analytics.com/collect?ul=en-au&v=1&tid=UA-4381101-5&cd3=5.5.1&aip=1&aid=org.openshot.openshot-qt&cd5=Ubuntu-16.04-xenial&an=OpenShot+Video+Editor&av=2.3.1&cid=8519a859-01e8-43f7-a564-04ce8b0ab2ba&cd1=0.1.3&cd2=3.5.2&cd=export-screen&cd4=5.5.1&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&t=screenview', 'cache-control': 'no-cache, no-store, must-revalidate', 'server': 'Golfe2', 'pragma': 'no-cache', 'x-content-type-options': 'nosniff', 'status': '200', 'age': '449241', 'date': 'Thu, 13 Apr 2017 21:16:57 GMT'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
     metrics:INFO Track exception: {'server': 'Apache/2.2.22 (Ubuntu)', 'status': '200', 'date': 'Wed, 19 Apr 2017 02:07:43 GMT', 'content-type': 'text/html; charset=utf-8', '-content-encoding': 'gzip', 'content-length': '29', 'vary': 'Accept-Encoding'} (b'*duplicate-exception-ignored*')
```

**Comment by jachiam** [comment] 2017-04-19 08:21
I have the same system, the same setup, and the same error. Hoping there is a work-around.

**Comment by ankitpati** [comment] 2017-04-19 15:40
No repro on Ubuntu 16.04 with the latest AppImage.

Please try the latest [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.3.1/OpenShot-v2.3.1-x86_64.AppImage "OpenShot 2.3.1"), and let us know if the issue persists.

**Comment by deeepaaa** [comment] 2017-04-19 21:03
@ankitpati That is not the point. The issue is there in the AUR as well. You can't force everyone to use AppImages, especially because they're a waste of bandwidth.

**Comment by jachiam** [comment] 2017-04-19 22:26
The AppImage did work. A permanent solution is preferrable though.

**Comment by ankitpati** [comment] 2017-04-20 00:32
@deeepaaa Please understand that OpenShot is understaffed. It is not possible for the sole developer to maintain packages and track dependencies for all distros. For that, please contact your distro maintainers.

@jachiam Thank you for the confirmation. The AppImage _is_ the permanent solution to the dependency hell.

**Comment by jachiam** [comment] 2017-04-20 01:29
Haha, all right. Well, thanks for making free stuff that (mostly) works! Appreciate it.

**Comment by jonoomph** [comment] 2017-04-20 03:26
ClearAllCache() was a new method introduced in the latest version of libopenshot. It sounds like you have updated your openshot-qt package, but it's still using an old libopenshot package... or your distro has not yet updated it's packaging. Be sure to apply all updates, and hopefully your distro has an updated version of libopenshot for you very soon.

The AppImage works because I package up a bunch of dependencies (including the latest version of libopenshot). 

I have added a new check when openshot-qt launches, to verify the correct version of libopenshot is found... which will display a friendly message, and not allow OpenShot to launch at all (since it will almost certainly crash). Then, at least the maintainers will quickly notice they only packaged 1/2 of openshot, and need to also update their libopenshot packages. 

I'm closing this bug for now, since this is not a source code issue, but a packaging issue with your distros. Thanks!

**Closed by jonoomph** 2017-04-20 03:26 UTC
