### ISSUE TITLE
crashes during export in Windows

### ISSUE THREAD

**Issue by Soul-Proprietor** [OpenShot/openshot-qt#503] opened 2017-02-19 20:25 UTC
First project I made was taking forever to export, then became unresponsive. I shut it down but it won't start, even after re-install. Message= "this application has requested to terminate Runtime in an unusual way" 

I'm hoping you have some solution for this. 

Thanks, Dan

**Comment by jonoomph** [comment] 2017-02-28 08:31
Duplicate of https://github.com/OpenShot/openshot-qt/issues/513 (I think). If not, please reopen this issue. Thanks!

**Closed by jonoomph** 2017-02-28 08:31 UTC
Labels: bug
