### ISSUE TITLE
Infinite loop when you open file with missing media files.

### ISSUE THREAD

**Issue by azacchino** [OpenShot/openshot-qt#3047] opened 2019-10-21 13:35 UTC
**Describe the bug:**
Copy the files and the project from one pc to the other. When I use the project on the other PC it indicates that I am missing a file (do not copy it) and asks me to open the folder that contains it. When I cancel, it asks for the file again and so in a loop.

**Steps to reproduce the behavior:**
1. Go to 'File'
2. Click on 'Open proyect'
3. Select the proyect 

**Expected behavior:**
the project  was opened without the missing media or the project is not open

**System Details:**
- OpenShot Version: 2.4.4
- Operating System / Distro: Windows 10

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
![imagen](https://user-images.githubusercontent.com/10451904/67209707-3cd70000-f3ee-11e9-8e5a-b8dce5f122c4.png)
![imagen](https://user-images.githubusercontent.com/10451904/67209742-50826680-f3ee-11e9-834d-086c0fbe1947.png)
When click on Cancel or OK and screenshot2 go to screenshot 1

**Comment by ferdnyc** [comment] 2019-10-21 18:30
Duplicate of... we'll call it #1118.

OpenShot is not in an infinite loop, in fact if you actually provide the location of the missing file, it will reconnect not only all instances of that file, but all files in the same directory.

If you _cancel_ the request, however, it will be shown again each time that file is encountered in the project data. (Meaning, if you used a file once on the Timeline, you'll have to cancel twice: Once for the Project Files entry, once for the Clip containing that file. If you used the same missing file at _four_ different places on the Timeline, you will have to cancel the request 5 times. But hitting the <kbd>Esc</kbd> key is a quick shortcut to dismissing those requests (individually, and you'll still have to respond to all of them).

Once you've either reconnected all missing files, or canceled all of the requests for them, the project will open.

**Closed by ferdnyc** 2019-10-21 18:30 UTC
Labels: :beetle: bug
