### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by crag2012** [OpenShot/openshot-qt#5495] opened 2024-04-11 02:53 UTC
**Describe the new feature:**
A clear and concise description of what the new feature or problem is.

**Describe the solution you'd like:**

**Describe alternatives you have considered:**

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by Colorjet3** [comment] 2024-04-14 00:13
Duplicate of #5496

**Closed as completed by Colorjet3** 2024-04-14 00:13 UTC
Labels: duplicate, 💡 enhancement
