### ISSUE TITLE
Cracking sound on all tracks

### ISSUE THREAD

**Issue by CanadianCuro** [OpenShot/openshot-qt#2457] opened 2018-12-18 04:11 UTC
After updating my Openshot from version 2.3.1 to version 2.4.3, all the audio in my project has severe crackling/static sounds. This only seems to affect clips that were imported using the previous version. Updating to the newest daily build does not solve this problem. However, removing all my clips and re-importing them (aka starting over from scratch) does fix the problem for each clip.

**Comment by speedytechdev** [comment] 2018-12-19 05:38
duplicate of [1069](https://github.com/OpenShot/openshot-qt/issues/1069) This issue will be closed since the same issue has been reported and has more information. Thanks for trying to let us know anyway.

**Closed by speedytechdev** 2018-12-19 05:38 UTC
Labels: duplicate
