### ISSUE TITLE
Open shot is broken because its stuck on a missing file.

### ISSUE THREAD

**Issue by Green52705** [OpenShot/openshot-qt#1118] opened 2017-12-13 05:18 UTC
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: v2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I was editing a video that was very reliant on keyframing lots of pngs, and open shot crashed. no big deal, I thought, because normally it has an autosave feature. but when I go back on to open shot, it is stuck on missing files (which are not actually missing) and cannot get off of the subject. I don't need my project back, I just want to be able to use the software again.

![i393 pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/34499681/33922772-b2652120-df92-11e7-925a-b109130e88f4.jpg)

**Comment by DylanC** [comment] 2017-12-13 18:04
@Green52705 - Do you have a bigger screenshot?

**Comment by DylanC** [comment] 2017-12-21 10:11
@Green52705 - It looked like this had become inactive. Reopened now.

**Comment by bizzymonkey** [comment] 2018-01-16 17:23
I brought this to our IT guy at work and he fixed it in like two minutes. Basically, there's a file on your computer probably called ".openshot_qt" that you need to delete. Once deleted, Open Shot will think it's the first time it has been opened.

**Comment by DylanC** [comment] 2018-01-16 17:42
An enhancement item exists for this #1061 but I will also mark this as a bug since it affects so many people. I will try to get the guys to work on it.

**Comment by bizzymonkey** [comment] 2018-01-17 14:32
Great thank you!  This is a terrific program by the way.

Sent from my iPhone

On Jan 16, 2018, at 11:42 AM, DylanC <notifications@github.com<mailto:notifications@github.com>> wrote:


An enhancement item exists for this #1061<https://github.com/OpenShot/openshot-qt/issues/1061> but I will also mark this as a bug since it affects so many people. I will try to get the guys to work on it.

**Comment by warre70** [comment] 2018-02-20 20:36
Is there any way to get your project back, I was working on a school project for a long time and it crashed so is there any way to get it back?

**Comment by Aseeah23** [comment] 2018-02-21 15:34
I was also working on a project last night and now openshot doesn’t want to open the file is there any way to recover this file as messages keep popping up that files cannot be found

**Comment by shiftee** [comment] 2018-02-21 15:41
For me it was an SVG file, I created an empty one with Inkscape and I could open the project.
You could try the same or similar if it's a JPEG etc.

**Comment by Aseeah23** [comment] 2018-02-21 15:43
Some of the files I have put are there but it seems to be opening an older version of the project

**Comment by peanutbutterandcrackers** [comment] 2018-02-25 12:19
@shiftee @Aseeah23 Could you please try @bizzymonkey's solution please? Try and see if deleting the .openshot_qt folder does the trick for you guys...

**Comment by shiftee** [comment] 2018-02-26 18:27
I was actually troubleshooting for another user so have extremely limited experience with OpenShot.

I have created a basic project and have tried killing the process but I have failed to reproduce the issue.

As far as I remember I tried bizzymonkeys method first but it did not work.
I then just tried to create the missing file which resolved the issue (as best as I remember).

Let me know if you want me to try anything

**Comment by shiftee** [comment] 2018-02-26 18:43
I've just found out that the file may have been created as part of an animated title using OpenShot 1.4.3 (as found in Ubuntu 16.04).

We think the project worked fine initially after upgrading to a recent appimage but then the issue happened.

I have tried deleting generated svg files without success

**Comment by peanutbutterandcrackers** [comment] 2018-02-28 03:24
I don't think OpenShot 2.x series is made to handle OpenShot 1.x files that well. OpenShot 1.x was based on MLT framework, whereas OpenShot 2.x has got it's own multimedia frameword - libopenshot. Perhaps that has got something to do with it? Probably not because animated titles are just videos in the end... but still.....

**Comment by peanutbutterandcrackers** [comment] 2018-02-28 03:29
@DylanC - I think this needs your attention, good sir.

**Comment by DylanC** [comment] 2018-02-28 13:40
@Green52705 - You need to either recreate a file with the same name or delete your OpenShot preferences folder.  ".openshot_qt"

**Comment by redvoltron** [comment] 2018-05-15 02:13
If you click OK and then just close the file selector, it'll work.

**Comment by edwardudell** [comment] 2018-05-19 15:28
I too am having the problem that Openshot will not let me re-open projects, in some cases projects I've been working on for hours.  

I tried to delete  .openshot_qt, according to the advice here. That did not work. Here's what I did:

I did a search for .openshot_qt using File Explorer, and three instances came up. 

I tried to delete them and the computer did something a bit like what open shot is doing -- my computer says the files are not located in some spot, so can't be deleted -- yet the computer just searched and found them!  here's a screen shot:

![image](https://user-images.githubusercontent.com/39439203/40270223-0edd9d34-5b57-11e8-9608-5dd686fe42b2.png)

Thanks very much for any assistance.

**Comment by edwardudell** [comment] 2018-05-19 16:50
Now another problem. I saw a discussion thread that said to move files to another directory that openshot uses. I put a sound recording in the open shot "assets" folder, and now that sound recording has disappeared. Nothing seems to be in the "assets" folder. When I search my PC for the file, it comes up in "recent" -- but if I then click on the title, the computer says "the file has been moved and these short cuts will no longer work." Then I look in all the other openshot folders I can find, and do not find the audio file. I look in the recycle bin, and do not find the audio file there. Any clues to where it might be? Thanks very much for any assistance.

**Comment by graham8** [comment] 2019-02-07 11:26
> 
> 
> If you click OK and then just close the file selector, it'll work.

Not an option when you have a few dozen pngs it can't find.

**Comment by jeske** [comment] 2019-03-01 10:43
I clicked OK, and it brought up the file selector, and I closed it, and it just keeps giving me the dialog over and over for every file.. It wasn't until I came to this bug that I realized if I kept doing it long enough maybe it would start. Sure enough, 20 clicks later it finally started up.

This is a really bad bug.. because it bascially makes Open Shot -seem- stuck and unusuable. 

Please just put a "cancel reloading project" button on the same window with the error loading file...

**Comment by ferdnyc** [comment] 2019-07-20 08:13
This was fixed in commit bdd2135 which will be included in the next release of OpenShot. Once you select the directory where your disconnected file can be found, all files in that directory will be recovered automatically.

**Closed by ferdnyc** 2019-07-20 08:13 UTC
Labels: bug

**Comment by ThatCoffeeGuy** [comment] 2019-07-27 21:22
Really not to be a mean ass, but it really did take 2 years to fix this showstopper bug?

**Comment by RayCodeMaster** [comment] 2020-03-26 22:26
I got the solution i was in the same problem if your on windows just hold ALT+F4 don't just press it hold it the deleting somehow is faster than the loop and will delete the loop

**Comment by RayCodeMaster** [comment] 2020-03-26 22:27
> @DylanC here you go, why is this closed?
> ![work](https://user-images.githubusercontent.com/34499681/34225479-44b9eb6a-e58c-11e7-9166-49fcd2a3df0f.png)

**Comment by RayCodeMaster** [comment] 2020-03-26 22:27
I got the solution i was in the same problem if your on windows just hold ALT+F4 don't just press it hold it the deleting somehow is faster than the loop and will delete the loop
