### ISSUE TITLE
Cannot Import Any Video or Image Files (no crashes), Windows 8.1

### ISSUE THREAD

**Issue by tominterval** [OpenShot/openshot-qt#3093] opened 2019-11-23 02:25 UTC
**Describe the bug**
Cannot Import Any Video or Image Files (no crashes), Windows 8.1

**Steps to reproduce the behavior:**
1. Open OpenShot
2. Click on the Import Files icon (green +) OR select File > Import Files from menu OR Ctrl+F
3. Browse to file to be imported
4. Select file
5. Click Open
6. [Nothing happens](https://www.youtube.com/watch?v=JPg2BfmpbPY). No import. No crash. No nothing. OpenShot completely ignores the request, and the Project Files pane remains empty. This is a major problem since I can no longer use OpenShot due to the failure of this basic function.

**Expected behavior**
To import files with no problem as I've been doing in OpenShot for more than a year on the same computer. I have the latest daily build and am up-to-date on Windows Updates, etc.

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3-dev1
- Platform: Windows-8.1-6.3.9600
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1574202649-d539e468-12a15298-x86_64.exe

**Log Files**
- http://logs.openshot.org/spa3pwqv33ocdz9j62tejuzyqxlvup0z/openshot-qt.zip
- http://logs.openshot.org/spa3pwqv33ocdz9j62tejuzyqxlvup0z/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Here's a video capture so you can see precisely what I see: https://www.youtube.com/watch?v=JPg2BfmpbPY

**Comment by tominterval** [comment] 2019-11-24 18:20
**UPDATE:** I resolved the issue but am not closing this report because the initial problem that occurred could still be a bug. I resolved it by completely uninstalling OpenShot, then reinstalling it. I'm not a developer, but perhaps this issue had something to do with downloading daily builds over time. A fresh install immediately fixed the problem.

**Comment by speedytechdev** [comment] 2019-11-25 09:19
Hi @tominterval , Yes this is a bug. This is one of the bugs we found in the daily build. Hopefully, we can find a fix to it. Please let us know if you find out anything else.

**Comment by tominterval** [comment] 2019-11-25 19:50
Hey @speedytechdev. Thanks for the reply and clarification. I'm relieved it's not a local issue but hope it's an easy fix for you. And thanks to you and everyone who works on OpenShot. Greatly appreciating everything you've done and do.

**Comment by tominterval** [comment] 2019-11-25 19:57
BTW, @speedytechdev, when I was experiencing that issue, I also tested to see if I could add a title. Although I was able to fill out all the fields in the Titles dialogue box, nothing happened after I clicked the Save button (the Project Files pane remained empty).

**Comment by speedytechdev** [comment] 2019-11-26 00:33
@ferdnyc Could you take a look at this when you get the chance.

**Comment by ferdnyc** [comment] 2019-11-28 10:42
Yeah, I need to check the exact timeframe of the Daily Build in question... I'll go do that now. There _was_  a brief period (a day or two) when the new thumbnail code was breaking Windows file-loading. (Both imported and generated files, due to the thumbnails failing to render.) It's possible @tominterval just happened to catch it within that window. That issue's been resolved and the fix should already be in the newest Daily Builds... _if_ that was indeed the cause.

**Comment by ferdnyc** [comment] 2019-11-28 10:52
Yeah, that Daily Build was from November 19 which was after the new thumbnail code merge. Thumbnailing (and therefore file import) was broken on Windows until #3087 merged on November 23. But all Daily Builds since the November 26 run should have the fixed code.

So, just a case of bad timing, it appears. Sorry about that, @tominterval . I'm going to close this since all signs point to a known issue that's already been addressed, but feel free to reopen if you encounter any similar issues with Daily Build versions from November 26 or later.

**Closed by ferdnyc** 2019-11-28 10:52 UTC
Labels: :beetle: bug, 📅 Daily Build

**Comment by tominterval** [comment] 2019-11-28 17:43
Thanks, @ferdnyc!
