### ISSUE TITLE
Chosing color animated title crash

### ISSUE THREAD

**Issue by sydneyjd** [OpenShot/openshot-qt#21] opened 2016-01-12 19:29 UTC
Hello, 
Thanks for al lthe work you are doing on this video editor! Its quite impressive!
Ok, so im running an up to date version of Arch, and when i go to make a animated title, then try to change a color in any of the animated tiles, openshot crashes with: 

> Unhandled Python exception
> Aborted (core dumped)

I hope this helps!

-Sydney

**Comment by firew4lker** [comment] 2016-01-12 21:22
I can confirm it.

**Comment by jonoomph** [comment] 2016-01-13 06:39
I think this is related (or possibly a duplicate of issue https://github.com/OpenShot/openshot-qt/issues/18). However, I think I found the problem that is likely crashing this and fixed it. =) Closing issue.

**Closed by jonoomph** 2016-01-13 06:39 UTC
