### ISSUE TITLE
Can't Keyframe Clip Speed (to combine fast-forwarding with normal speed)

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1198] opened 2018-01-12 06:00 UTC
So, I wanted to have a clip change it's speed while playing and proceeded to mark keyframes in it (not the preset style - because I want some part of the clip to go fast while other one remains the same; I thought Bezier keyframe would give it a neat look/effect); but the clip is just stuck.

I figure it is because only the 'Time' property has changed but the 'End' and 'Duration' property have not and that is why OpenShot is getting confused. If the 'End' and 'Duration' property could be dynamically allocated when 'Time' property is changed. It could probably work. There is no way one could calculate all of the time changes and put it in there manually. It just is not possible.

Also, I am eagerly waiting for frame-by-frame timeline mode in OpenShot.

"It is not perfect. But it's imperfections are easier to live with than a perfected restrictiveness."
-Some book authors on the C programming language
-Also me regarding OpenShot (and a few other FOSS projects)

**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4.1-dev1

**Comment by peanutbutterandcrackers** [comment] 2018-02-12 11:38
@DylanC - In light of #1032 and the fact that this one kinda' theorizes something too, can I haz 'bug' and/or 'enhancement' label plz?

**Comment by DylanC** [comment] 2018-02-12 11:44
@peanutbutterandcrackers - No problem.  Also definitely a duplicate of #1032.

**Comment by peanutbutterandcrackers** [comment] 2018-02-12 12:03
@DylanC - Haha. True. Thank you! :)

**Comment by ferdnyc** [comment] 2018-07-27 14:13
As in #1032, I think this can be closed, as it's merely an issue of knowing _how_ to set the Time parameter. (See my explanation in #1032.) There are bugs in the Time handling (See #1819), and the fact that it would be a major chore to manually keyframe any Time effects is certainly a valid concern, but overall the Time and End/Duration processing is working as intended — even if that intended operation is very, very weird.

**Comment by DylanC** [comment] 2018-07-27 14:34
@ferdnyc - No problem. Thanks again! (Good sir)

**Closed by DylanC** 2018-07-27 14:34 UTC
Labels: bug, duplicate
