### ISSUE TITLE
Openshot crashes with transition or two image blend

### ISSUE THREAD

**Issue by marcelkloes** [OpenShot/openshot-qt#1861] opened 2018-07-16 13:19 UTC
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by marcelkloes** [comment] 2018-07-16 13:21
Hi, 

whenever I try to add a transition or have two image blend (blue marked part) Openshot crashes. I use windows 10 pro version 1709

**Comment by peanutbutterandcrackers** [comment] 2018-07-17 01:19
Duplicate of #1856 

@marcelkloes - Please head over to #1856 and follow the discussions there. [Please attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) there. That should help the devs figure out this issue. Closing this one in order to keep the number of issues in check. Thank you!

**Closed by peanutbutterandcrackers** 2018-07-17 01:19 UTC
Labels: duplicate
