### ISSUE TITLE
Adding many pictures (74) to the timeline VERY slow

### ISSUE THREAD

**Issue by brmmm3** [OpenShot/openshot-qt#445] opened 2016-12-26 07:07 UTC
Openshot 2.2.0:
After adding 74 pictures (each 1024x768) to the timeline openshot freezes for a long time.
This makes openshot unusable for most projects, especially for stop motion videos.

**Comment by ankitpati** [comment] 2017-03-04 17:49
Dupe of #444.

Closing as #444 is more detailed.

**Closed by ankitpati** 2017-03-04 17:49 UTC
Labels: duplicate
