### ISSUE TITLE
OpenShot 2.2.0 x64: Pauses, Launch Problem, and Language

### ISSUE THREAD

**Issue by adhitrm** [OpenShot/openshot-qt#556] opened 2017-03-29 07:52 UTC
System Details:
* Operating System / Distro: Windows 10 x64
* OpenShot Version: 2.2.0 (x64)
* System Specs (ASUS A456UR): 
 - Intel Core(TM) i7-7500U
 - Intel HD Graphics 620 (active) / NVIDIA GeForce 940MX
 - 8GB RAM

Issues:
- Project playback always pauses after 10 seconds
- There's a little chance to launch the program properly (about 2 of 6 successful program launch)
- Language doesn't change from Indonesian [id-ID] (default) to American English [en-US] after program restart

**Comment by DylanC** [comment] 2017-08-28 12:30
@adhitrm - Thanks for your feedback. Issues with crashing and language issues are known. We will work on resolving them.

**Comment by DylanC** [comment] 2017-09-18 13:13
I could not reproduce the playback or launch issue. Please try the latest v2.4 release and let us know.

**Closed by DylanC** 2017-09-18 13:13 UTC
