### ISSUE TITLE
Freezes on exporting (Windows)

### ISSUE THREAD

**Issue by MHDSinc** [OpenShot/openshot-qt#119] opened 2016-03-06 03:17 UTC
I am trying to create a video, have added several videos to the timeline, titles, and audio.  After choosing to export video, I provide the name and choose export video.  It starts, but then goes to 'Not Responding' after a certain amount of time.  I've tried various formats, and I get a little further with some than others, but I think it is more a time thing...

**Comment by MHDSinc** [comment] 2016-03-07 01:21
Sorry for the lack of info...I running Windows 7 32 bit, 3 GB RAM, all .avi clips, one mp3 clip, and various footer titles.  I have tried this with multiple computers (windows 7, windows 10, 32 bit, 64 bit), and with fewer clips.  It never finishes any exports, even with just two clips.  It just 'freezes' and the title bar says 'Not Responding'.

**Comment by jonoomph** [comment] 2016-03-17 03:10
I have fixed a few critical Windows bugs in the past week, and it's likely this issue is already fixed. However, it could also be related to the video files you are using (just a guess)... But I am interested to see if the new version (which will be released in the next few days) fixes this. Thx.

**Comment by MHDSinc** [comment] 2016-03-23 16:21
Any idea on how soon that update will arrive?  I have tried it on three more Windows systems using very minimal video clips (of varying types) and there is still NO file being exported...

**Comment by komackaj** [comment] 2016-03-25 12:24
Possible duplicate of #82

**Comment by mrmelg** [comment] 2016-03-29 12:02
I find it crashes timeline on videos longer than about 16 secs and on export (default settings) that length with multiple transitions. Could it be memory usage? win 7 dell desktop i5 12 Gb ram. 
Exports on shorter comps worked fine

**Comment by ZackTheCardshark** [comment] 2016-05-09 02:22
I'm a Mac user (El Capitan) who just discovered OpenShot, and would like to like it—but the program hangs every time I try to export. It seems to be this issue (clearly not Windows-specific), or https://github.com/OpenShot/openshot-qt/issues/82 (which seems to have more helpful information). This is kind of the ultimate showstopper of a bug; is anybody looking into it?

**Comment by ZackTheCardshark** [comment] 2016-05-09 02:23
BTW, also cross-posting to similar issues, since all of them are still open: https://github.com/OpenShot/openshot-qt/issues/82 and https://github.com/OpenShot/openshot-qt/issues/179.

**Comment by foto1000** [comment] 2016-05-26 07:03
same, on 2.0.7, does anyone know an openshot version which can export? and where to download it.

**Comment by chibill** [comment] 2017-01-30 21:00
Still happening on latest downloadable 64-bit windows version.

**Comment by DylanC** [comment] 2017-08-22 12:53
@chibill - Does this still happen on the very latest version?

**Comment by DylanC** [comment] 2017-08-23 15:56
According to many other bug reports, export issues are resolved.  Feel free to reopen if that is not the case with the latest version.

**Closed by DylanC** 2017-08-23 15:56 UTC

**Comment by markma05** [comment] 2018-09-08 05:44
yes, it still happen
