### ISSUE TITLE
Unable to stretch picture element on timeline from the left but works from the right

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5112] opened 2023-01-24 20:29 UTC
Running openshot 3.0.0 daily 2023-01-18

very minor UI issue, 
When you place a picture on the timeline, you can't stretch it from the left

https://user-images.githubusercontent.com/10621885/214401803-5000a8fe-53dc-4f29-93a5-b17f98daf878.mp4

**Comment by ghost** [comment] 2023-01-25 23:00
Duplicate of https://github.com/OpenShot/openshot-qt/issues/5085

**Comment by Colorjet3** [comment] 2023-01-26 01:10
Hello @DaveJarvis I wonder if this is by design.  I don't remember if this had ever worked since I started using OpenShot with 2.51.  As a matter of fact I never had even tried it because logically I would drag the image onto a track, line up the left edge with another clip and then stretch the right side.

Are you thinking this is a bug or you think it is an enhancement request?

**Comment by ghost** [comment] 2023-01-26 06:51
> Are you thinking this is a bug or you think it is an enhancement request?

It's possible it was done by design. I'd say it is a bug though, there's no technical reason why a static image can't be stretched indefinitely in either direction at any time.

**Comment by Colorjet3** [comment] 2023-01-30 18:37
Hello @DaveJarvis I created a Trello card and labeled it as a Bug and Enhancement request:  https://trello.com/c/AyA6SGfa/123-unable-to-stretch-picture-element-on-timeline-from-the-left-but-works-from-the-right

**Comment by Colorjet3** [comment] 2023-04-23 02:01
This is still in the queue and will be fixed in one of the next two v3.1.x releases.

**Closed as completed by Colorjet3** 2023-04-23 02:01 UTC
