### ISSUE TITLE
Animated Titles not working with latest Blender, Win10

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3744] opened 2020-09-29 13:55 UTC
This is pulling together issues #3740 and #3730, with a 'bug' label

Menu >Title >Animated Title
The Animated Title window opens successfully, but when a title is selected, the rotating blue wait circle cursor becomes permanent, with no further title action.

It seems that OpenShot doesn't work with the latest Blender 2.90.1. It does work with 2.80 on my system, but apparently not on another system. Details in the aforementioned issues.

The 3 systems affected have all been Win10, and I think OpenShot Version: 2.5.1-dev2.

A second issue (probably related) is that if Blender is not installed, OpenShot gives no warning message.

**Comment by ferdnyc** [comment] 2020-10-06 23:08
That should be fixed once my PR #3749 merges — Blender changed the format of their `-v` message _again_ in 2.83, and we were no longer able to detect the version number.

**Comment by ferdnyc** [comment] 2020-10-06 23:15
Closing as a dupe of #3740, just to keep everything consolidated.

**Closed by ferdnyc** 2020-10-06 23:15 UTC
Labels: :beetle: bug

**Comment by rexdk** [comment] 2020-10-07 06:18
@ferdnyc 
Grand - thank you
