### ISSUE TITLE
The timeline view doesn't even display, so there isn't much editing you can do for a video that you ...

### ISSUE THREAD

**Issue by andrigmiller** [OpenShot/openshot-qt#4657] opened 2022-01-24 22:14 UTC
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Open OpenShot
2. Timeline view doesn't display
3. 
4. 

**Expected behavior**
The timeline view should display with the default 5 tracks, but there is nothing there.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.15.14-200.fc35.x86_64-x86_64-with-fedora-35-Thirty_Five
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9005-49d6ba3b-2b8b05c7-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/23obo0nrqbbnsknjmwthi3redsdy7mz3/openshot-qt.zip) (135 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/23obo0nrqbbnsknjmwthi3redsdy7mz3/libopenshot.zip) (96 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JacksonRG** [comment] 2022-01-24 23:45
If you click on `View` > `Views` > `Simple View` in the top right corner does anything change? Also does anything change if you re-open the project?

**Comment by Bert-H** [comment] 2022-01-26 02:44
This is a duplicate of issue 4633 that was logged by me three weeks ago.
Issue still exists today with latest FC35 updates.

**Comment by jonoomph** [comment] 2022-05-03 18:54
This is fixed in https://github.com/OpenShot/openshot-qt/pull/4787

**Closed as completed by jonoomph** 2022-05-03 18:54 UTC

**Comment by tethragon** [comment] 2022-12-11 05:11
The latest openshot appimage V3.0.0.0 (just released yesterday) fixed the UI problem (no timeline)

https://www.openshot.org/download/
