### ISSUE TITLE
Problems with svg files in 2.5.0, Fedora Linux 30

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#3215] opened 2020-02-11 20:41 UTC
**Describe the bug:**
Using 2.5.0, I import an svg file containing the introduction text of the video, and get the question "Would you like to import Donation-request-wit5-10.svg as an image sequence?". When I answer No, it is imported totally black. Not usable. When I answer Yes, it is imported an an image, but the part of the title changes. It's name end e.g. with xx-5.10.svg and changes into xx-5.%d.svg. Each other svg file, such as 5.9 and further, is renamed into 5-%d.svg. When put on the timeline, a digit placed at the bottom of the imported svg image, is garbled. Also, when I give it a timelength of 1 second, it's reduced to 0.33 seconds. From the properties, I can change it to 1 second, but this is cumbersome. Also, when I try to use the mouse to drag the righthand side over the timeline to make it 1 second, it doesn't work. Dragging the complete image over the timeline to another time, it does work.
Next, importing a .MOV file takes 10 seconds, putting it on the timeline another 5 seconds. but looks fine afterwards. 

**Steps to reproduce the behavior:**

**Expected behavior:**
SVG files to have the given time on the timeline, as works for me in the nightly-version of 2.4.4. The import of MOV files should take just a seconds. Again, it works in 2.4.4/

**System Details:**
- OpenShot Version [e.g. 2.5.0]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: Fedora Linux 30
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/4188146/openshot-qt.log)]
![Screenshot-OpenShot-2 5 0-svg-2020-02-11_21-39-24](https://user-images.githubusercontent.com/13077765/74277019-18918d00-4d17-11ea-8abf-f09f36493d5f.png)

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ferdnyc** [comment] 2020-02-11 21:00
@huubvanniekerk 

As a workaround, if you rename the file to something like `Donation-request-wit5-10aaa.svg`, can the file be imported? It sounds like the image-sequence detection logic is getting in the way, but I'm curious whether the import works successfully if that's avoided.

**Comment by ferdnyc** [comment] 2020-02-11 21:02
(You definitely _don't_ want to import the file(s) as an image sequence, which will attempt to load all of your `Donation-request-wit5-*.svg` files as frames of an animation.)

**Comment by ferdnyc** [comment] 2020-02-11 21:06
As far as the numbers placed on the file — if you don't have Frame Number display turned on (and you don't, from that screenshot), then that must be coming from the contents of your SVG file _somehow_. Can you post one of the SVG files, perhaps?

**Comment by huubvanniekerk** [comment] 2020-02-15 11:11
> @huubvanniekerk
> 
> As a workaround, if you rename the file to something like `Donation-request-wit5-10aaa.svg`, can the file be imported? It sounds like the image-sequence detection logic is getting in the way, but I'm curious whether the import works successfully if that's avoided.

@ferdnyc I can import it then, and don't get the question about image-sequence, but instead of text it's all black. So unusable.

**Comment by huubvanniekerk** [comment] 2020-02-15 11:19
> As far as the numbers placed on the file — if you don't have Frame Number display turned on (and you don't, from that screenshot), then that must be coming from the contents of your SVG file _somehow_. Can you post one of the SVG files, perhaps?

Sure. Have to compress it to zip since the uploader doesn't accept svg extension.
[Donation-request.zip](https://github.com/OpenShot/openshot-qt/files/4208387/Donation-request.zip)

**Comment by ferdnyc** [comment] 2020-02-15 13:51
Ah, OK — I had to reread your original comment, I thought you were saying that the digit _wasn't_ supposed to be there (and OpenShot was adding it), but now I see you inserted the digit, and it was only the rendering that was a problem. My mistake, I should've read more carefully.

But in terms of importing the SVG file itself... I have to say, I'm having trouble reproducing any issues. I've tried local builds of OpenShot+libopenshot with and without Resvg enabled, as well as the `OpenShot-2.5.0-x86_64.AppImage` release version (which has Resvg included), and everything seems to work perfectly. The file imports and can be previewed:

![image](https://user-images.githubusercontent.com/538020/74588766-6a633d00-4fcd-11ea-912a-87f4aa9861ca.png)

And it overlays on top of other videos fine as well:

![image](https://user-images.githubusercontent.com/538020/74588954-148f9480-4fcf-11ea-8918-52dbfac995cf.png)

Here's the video of that timeline exported at Medium quality (to keep it under 10MB)
[overlay.zip](https://github.com/OpenShot/openshot-qt/files/4208522/overlay.zip)

And here's the first 3 seconds as an animated GIF, but with your personal information censored out, because after rendering the video I thought better of including that in my sample output.

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/538020/74588948-0772a580-4fcf-11ea-9c29-fc1e64560694.gif)

So, I really can't explain it, though it does seem to be a localized issue. You said you were seeing _layout_ issues (text being distorted/shifted), so.. I suppose it's **possible** that could indicate a font issue, maybe the SVG renderer is making a bad choice to satisfy the `font-family:times` in the SVG source.

I never thought to ask how you're running OpenShot, whether it's from AppImage, a local build, etc... I know it's not from RPM Fusion packages, because I only finished the 2.5.0 builds yesterday and I'm not even sure they've hit the testing repos yet. (Just checked, they're not.)

They will be available soon, though. I think it's usually around a week for new builds to reach the updates repo. So that's an option you could try to maybe fix this, installing 2.5.0 from `rpmfusion-free-updates` once it's available.

Otherwise... well if you're **not** already running from the AppImage, I'd definitely suggest giving that a try. But if you _are_ then I really don't know, because I just used it with the file you provided, and everything worked fine.

**Comment by ferdnyc** [comment] 2020-02-16 03:27
OpenShot 2.5.0 is now in rpmfusion's updates-testing repository, so if you wanted to jump the gun on it reaching the updates repo, and assuming you have the rpmfusion-free-release package installed in the first place (meaning you have the rpmfusion repo configs available to dnf), another  thing you could try is:
```sh
sudo dnf --enablerepo=rpmfusion-free-updates-testing install openshot-2.5.0
```
...To install `/usr/bin/openshot-qt` from RPM Fusion (== my Fedora builds), and see if you get different results with it.

**Comment by huubvanniekerk** [comment] 2020-02-16 05:46
@ferdnyc Ok, some more information: yes, I do run OpenShot-2.4.4 and 2.5.0 from AppImage because I can't find an rpm version. But as said: using 2.4.4 gives no problem at all. Then, on your suggestion I installed 2.5.0 from RPM Fusion and get the SVG files imported. Only to find out it (in my case..) suffers from the same SVG import problem I experienced before, as shown in the screenshot: only the first line is visible.
![Screenshot-Openshot-2 5 0-Fusion-Fedora30-2020-02-16 06-38-01](https://user-images.githubusercontent.com/13077765/74599782-e1f5a280-5087-11ea-9228-310d281a7e89.png)

**Comment by SuslikV** [comment] 2020-02-16 13:18
Try to change fonts in Inscape for this text fragment or, if it doesn't help, just convert text _Object to Path_ in Inscape menu before adding it to OpenShot. Keep copy of the unconverted _.svg_ file to be able to modify it later.

**Comment by ferdnyc** [comment] 2020-02-16 16:37
@huubvanniekerk 
Huh. That's _very_ strange... but @SuslikV 's suggestion might be a workaround. Or, even easier, you could actually just export the SVG file as a transparent PNG and import THAT because, in all honesty, that's all OpenShot does internally anyway. The very first thing it does when reading an SVG file is convert it to PNG and cache the results. You could just cut out the middleman.

**Comment by ferdnyc** [comment] 2020-02-16 16:44
(Slight correction: It converts the SVG to an internal bitmap representation, it's not actually PNG data _per se_ but it's equivalent, so importing a transparent PNG would have the exact same net effect. All scaling and other operations on frames-from-SVG are performed _after_ the rendering step, so there's no real advantage to using SVG for titles because all of the benefits (scalability, resolution-independence, etc.) of SVG files are currently discarded by OpenShot's early rasterization of the data. It's a... deficiency in our current SVG implementation.)

**Comment by huubvanniekerk** [comment] 2020-02-16 18:00
@SuslikV The converted file actually does import and show nicely.
@ferdnyc Any chance that this SVG implementation will change soon to comply with (all) SVG benefits?

**Comment by ferdnyc** [comment] 2020-02-17 13:51
@huubvanniekerk Definitely not _soon_, I wouldn't think. Unfortunately not.

**Comment by ferdnyc** [comment] 2020-02-17 14:15
I'm going to close this one since the issue (whatever it is) _appears_ to be a local system issue, and a workaround has been confirmed. If converting to paths fixed the importing then it can only be a font problem, and there's nothing we can do to fix local font support unfortunately.

(Though, it may still be possible to fix the input files so they'll work without having to convert to paths.) Two observations about font use in the example you provided:
1. The `<text>` element `style` contains `font-family:sans-serif;`, but all of the `<tspan style"">`s inside it use `font-family:times;`. That's not in any way invalid or even necessarily wrong, but it is a bit unusual.
2. `font-family:times;` is a generic name, which may be causing problems. Most likely it triggers font fallback, hopefully to some appropriate substitute... but different SVG engines may have different ideas of what that should be. An explicit font name like `font-family:Times New Roman;` or `font-family:DejaVu Serif;` or `font-family:Garamond;` etc. might work better.

For instance, on my system the ImageMagick command `identify -list Font` shows that the name Times maps to Nimbus Roman... but that's a PostScript Type 1 font, so it's not available to SVG. Presumably the next fallback is some substitute like DejaVu Serif or similar.
```console
$ identify -list Font
[...]
  Font: Times-Italic
    family: Times
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/urw-base35/NimbusRoman-Italic.t1
  Font: Times-Roman
    family: Times
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/urw-base35/NimbusRoman-Regular.t1
```

**Closed by ferdnyc** 2020-02-17 14:15 UTC
Labels: :beetle: bug
