### ISSUE TITLE
WINDOWS: GOOD things ...

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#63] opened 2016-01-23 19:45 UTC
GOOD things ...
1) turn the program is very fast
2) the automatic transitions between two video files.
3) drag and loaded into the window very quickly  with any file.
4) video effects remain intuitive and fast
5) Where is the cutter to cut the video files in the project. I've seen through the right mouse button but there is no icon, like in ubuntu version?
6) I'm testing the program I have long wanted to make it a reference programa of video editor, I encourage everyone !!

**Comment by jonoomph** [comment] 2016-02-07 06:56
Thanks for the feedback. Closing since this is not a bug. =)

**Closed by jonoomph** 2016-02-07 06:56 UTC

**Comment by telelauro** [comment] 2016-02-09 14:51
thanks for you!
sorry, but where I can download the new beta? if you are ok I coult try it
!!!!
unai

2016-02-07 7:56 GMT+01:00 Jonathan Thomas <notifications@github.com>:

> Thanks for the feedback. Closing since this is not a bug. =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/63#issuecomment-180964572>
> .
>



-- 
"Dabilen kamerari Kroma-keyrik ez"
