### ISSUE TITLE
Installer needs admin on windows

### ISSUE THREAD

**Issue by MysticOdin** [OpenShot/openshot-qt#1782] opened 2018-07-03 21:48 UTC
I know this is more of a question than a bug, unfortunately there isn't a "question" type issue.

Why does the installer need admin? the tool works out of a zip with no issues, the installer also automatically shuts if the permission is not granted.

**Comment by peanutbutterandcrackers** [comment] 2018-07-04 01:41
It requires admin privileges to install the program into the C:\ directory. It is not a stand-alone/portable type programs that can work out of the box. That is why it needs admin. You can give it admin rights. It does not contain any malicious code.

Hope that helps.

**Comment by DylanC** [comment] 2018-07-10 09:17
@MysticOdin - Most Windows programs need to be installed like this to have a nice shortcut in the menu etc.

**Comment by ankostis** [comment] 2019-01-25 20:31
But what if we don't care about the nice shortu in the menu?  
Is there some other shotcoming if it is not installed through the executable?

**Comment by generic-user** [comment] 2019-06-04 14:14
If you only need admin rights for installing to the program folder, you really should only ask for those privileges **when the user asks your installer to install in that location**. 
Otherwise, just let the user select where he wants to install the application.
I never understood why developers **keep asking for elevated privilege's, even wen they are not needed** for the application to function correctly.

_Anyway, just my two cent's._

**Comment by half2me** [comment] 2020-02-17 09:23
Can we please reopen this? I'm on a machine where I don't have admin priviledges, but would love to use this program. Why does it force admin privileges, instead of letting me choose to install to my own folder?

**Comment by DylanC** [comment] 2020-02-17 10:14
@generic-user @half2me - Makes sense.

**Comment by ferdnyc** [comment] 2020-02-17 11:26
Hrm. I need to refresh my memory of the Inno Setup configs we use... ah, yeah.

The installer currently performs several functions that require administrative privileges. They vary in how readily they could be made non-privileged:
1. Installs into "Program Files". That could be redirected fairly easily.
1. Installs file association registry keys under `HKEY_LOCAL_MACHINE\Software\Classes` in the registry. It should be possible to install the same associations in the `HKEY_CURRENT_USER` hive, instead. Ditto the installation of shortcuts and etc. into the All Users profile, which could be redirected to the current user's profile.
1. Removes some _old_ registry keys we used to install, but no longer do. Honestly it's been > 3 years now since OpenShot last had an installer that created those keys, and that logic should just be dropped in general — it's unnecessary in all cases.
1. Installs a firewall rule. It does that using a `netsh.exe` command that's launched during the post-install phase. That's a trickier one, I don't think there's any mechanism for regular users to do that. We'd have to disable the firewall rule creation entirely (or, actually, just uncheck and disable that option in the installer tasks)
1. This is the big, ugly one: Renames `zlib1.dll` files that some (unknown) _other_, poorly-behaved software has previously installed **in the `C:\Windows\System32\` directory**. 

Clearly, the last one has no possibility of offering a non-privileged alternative, and that's critical because we have found **no solution** to the problem: numerous bug reports have been filed from users who, for unknown reasons, have a `zlib1.dll` file in the System32 directory, who are unable to run OpenShot at all as a result. The DLL is not part of Windows, it was never part of Windows, and it _shouldn't_ be in there. But when it's placed there, Windows will **ALWAYS** load that DLL rather than the one bundled with the application, and if it's an outdated version that doesn't have all of the functions we make use of, the program crashes instantly.

So, for a non-administrative installation option, we'd also have to turn off _that_ part of the installer logic. In which case, anyone who installs without administrative privileges and who also has an outdated `zlib1.dll` lurking in their `System32` directory is going to end up with an OpenShot install that won't run.

(I realize that _sounds_ like an unusual case that shouldn't be allowed to impact general installer functionality, but the number of bug reports that came in about it begged to differ. Hence the whole forcibly-renaming-"system"-DLLs-from-the-installer method resorted to, an ugly hack which we'd definitely not be doing if we knew of any other solution to the problem.)

There would also have to be a few other changes, mostly around detecting previous installs and using the same location by default, but _mostly_ that additional stuff would only require flipping the correct Inno Setup switches to enable some additional logic.

**Comment by half2me** [comment] 2020-02-17 11:44
I understand. But then again, it seems really weird that an installer is renaming files in the system32 directory. I 100% understand why you do that, but maybe that should be an optional thing? For example, check if the file is there (non-admin) If it is there, prompt the user to rename (require priv esc. here).
For now, I'm just using the portableapps version, but would be nice to be able to install it.

**Comment by generic-user** [comment] 2020-02-18 21:07
> I understand. But then again, it seems really weird that an installer is renaming files in the system32 directory.

It's such a bad behavior to go around and clean up dll files while not informing the user what you are doing. 

Be a good housefather while given administrative privileges. Inform the user about the suspicious/malicious dlls in their system 32 folder, and recommend them to perform a "cleanup". When performing that cleanup ask for the key to the house. Never ask for the key beforehand. 

It could even be a seperate tool that performs the cleanup. It would then be executed at users will. Can be maintained separately, and user statistics could be collected to monitor how much the tool is used.

**Comment by ankostis** [comment] 2020-02-18 21:44
Sorry to intervene, though i'm not affiliated to the project in any other way than as a casual user.

While @generic-user is not impolite and it is making a constructive criticism, i don't like it that his attitude lacks empathy attitude.

**Comment by half2me** [comment] 2020-02-19 10:43
@ankostis I have to aggree with @generic-user .
He makes some very good points including:
- Don't ask for admin privileges right off the bat, and if you do, explain why you need them. Nobody should blindly give admin privileges to an application without knowing what its going to do. For some examples, I really like [Apple's guidelines on requesting permission on ios](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/requesting-permission/). Only request what you need, always explain to the user why you need it, and make it possible to run your app without the privileges in case the user decides not to grant permission.
- Stay in your scope. I don't think anyone installing an app is expecting that app to go to some completely unrelated folder and rename existing files that belong to some other app. I understand why they did it, and the reasons are legit, but its not the right way to fix things. @generic-user suggested some very good alternatives. But at the least, the user should be aware of what is happening. Stupid example, probably very unlikely, but those files could have been put there by the user for something else, and actually needed. Good luck trying to debug why your other app is suddenly failing :)

So while I'm not involved in this project, I will add my suggestions because they inspire good practice, and I'm glad others do to.
Anyway a big thank you to all the people contributing to this project, and making it awesome! ❤️

**Comment by generic-user** [comment] 2020-02-19 12:49
> Sorry to intervene, though i'm not affiliated to the project in any other way than as a casual user.
> 
> While @generic-user is not impolite and he is making a constructive criticism, i don't like that the attitude lacks empathy.`

I'm sorry if I offended anyone, it was not my intention. I just wanted to contribute my view points. Now I did, so I'm out 😉 

Thanks for the hard work on the project everyone! I really appreciate it. 🎉

**Comment by MysticOdin** [comment] 2020-03-08 19:45
@ferdnyc I don't know much about zlib, but it looks like its entire source is available, maybe statically link it? this way you don't have to go looking for DLLs

**Comment by BadMisterFrosty** [comment] 2020-06-11 19:02
Aside from the Zlib DLL chaos above, is there any reason why you cannot provide a zip of the application where you simply unzip and run? Many other software packages offer this type of "install". It allows the user to copy to their folder and run it from there.

**Comment by ganego** [comment] 2020-10-01 13:15
Wondered the same. Testing various video editing programs right now.
Shotcut has portable, Olive has portable, KDEnlive has portable, Natron has portable, ...

**Comment by ferdnyc** [comment] 2020-10-02 13:19
@ganego Ah, my mistake. I'm always surprised by how much of their software collection KDE makes available as Windows builds, though I really shouldn't be anymore.

**Comment by francisco-lafe** [comment] 2021-11-16 20:08
To me it's still relevant, we don't have admin rights on our stations, it would be nice to have this installed under the user!
Thanks

**Comment by jonoomph** [comment] 2021-11-17 04:58
We currently use Inno Setup for our Windows installer. This is from their official documentation: 

> Inno Setup's own installers accept an additional /PORTABLE=1 command line parameter to enable portable mode which causes the installers to install to the desktop by default and to not create an uninstaller nor an entry in the Add/Remove Programs Control Panel applet. For example:
> 
> /portable=1 /silent /currentuser

I have not tried this yet, but in theory, you can already install OpenShot in "Portable" mode, by passing along the correct argument to the installer. Please let me know how this works! 🤞

**Comment by generic-user** [comment] 2021-11-17 11:21
> Inno Setup's own installers accept an additional /PORTABLE=1 command line parameter to enable portable mode which causes the installers to install to the desktop by default and to not create an uninstaller nor an entry in the Add/Remove Programs Control Panel applet. For example:
> /portable=1 /silent /currentuser

I just tried this. It still asks for administrative rights by presenting UAC prompt.

![image](https://user-images.githubusercontent.com/1516035/142191382-c38f904d-8323-4062-aff2-013379dd8d86.png)

**Comment by francisco-lafe** [comment] 2021-11-17 15:26
As did @generic-user , I tried and still got UAC prompted.

**Comment by francisco-lafe** [comment] 2021-11-17 15:27
Actually, is not even listed:
![image](https://user-images.githubusercontent.com/90066435/142229614-9e811ac5-db25-4650-a84a-dc03a5d5d6b3.png)

**Comment by JacksonRG** [comment] 2021-11-17 17:46
@francisco-lafe That's odd. I'll look into what version of inno we're using

**Comment by francisco-lafe** [comment] 2021-11-17 17:48
Is this the latest version from OpenShot website?
![image](https://user-images.githubusercontent.com/90066435/142254521-1866ee47-1a2c-4cff-bd28-5782b8e311f6.png)

**Comment by JacksonRG** [comment] 2021-11-17 17:58
Yes, 2.6.1 is the latest stable build. There are newer, less stable daily builds on the website but that's our official version. I'm trying to see if the `portable` flag we're talking about is supported by the version of Inno we use to install on Windows.

**Comment by francisco-lafe** [comment] 2021-11-17 20:56
Ok, thanks.
Regards,

**Comment by francisco-lafe** [comment] 2021-11-23 22:48
Hi @JacksonRG , is it possible to use it or I'm out of luck? 
Regards,

**Comment by jonoomph** [comment] 2021-12-02 22:49
We have a fix for this in a PR now! It required adding some additional arguments to our Windows installer, to allow for a fully portable mode. PR is #4570

**Comment by francisco-lafe** [comment] 2021-12-02 22:50
Great! Thanks for the update.

**Closed** 2021-12-02 22:57 UTC
Labels: question

**Comment by jonoomph** [comment] 2021-12-02 22:58
Daily builds will be ready in about 60 minutes (for testing). Instructions are detailed in #4570, but the basic idea is to add these 3 additional arguments to our installer (using the Windows command prompt):

```
OpenShot-v2.6.1-x86_64.exe /portable=1 /currentuser /noicons
```

**Comment by generic-user** [comment] 2021-12-03 11:23
@jonoomph 
> Daily builds will be ready in about 60 minutes (for testing). Instructions are detailed in #4570, but the basic idea is to add these 3 additional arguments to our installer (using the Windows command prompt):
> 
> ```
>  .\OpenShot-v2.6.1-dev-daily-8803-18bdad43-0fb4ab09-x86_64.exe /portable=1 /currentuser /noicons
> ```

I can confirm this is working! `Windows 10 Enterprise 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)`

Thank you for making this possible! 🥇 👍

**Comment by gillesB** [comment] 2022-06-17 11:51
As a comment for other new users: at the moment `/portable=1 /currentuser /noicons` does not work with the release 2.6.1.
Nevertheless the arguments work as expected with the `2.6.1-dev` daily builds.

**Comment by PyroghostX** [comment] 2022-12-15 18:55
thank you for the portable option! 
OpenShot-v3.0.0-x86_64.exe /portable=1 /currentuser /noicons
worked perfectly!
