### ISSUE TITLE
right click in Windows 10 has non-standard behaviour

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3619] opened 2020-07-22 21:40 UTC
2.5.1 Win10

Open Openshot; import two media files; add both to timeline
Select one clip, so that it is outlined in red.
Right click the other clip, and choose Remove Clip
Both clips are removed.
In every other case I know in Windows (eg particularly the File Explorer), right click would deselect the first clip, and only the second clip would be removed.

Not a disaster, as it can be undone, but it is a fault I think, if the claim is 'easy to use'.

**Comment by ferdnyc** [comment] 2020-07-27 01:45
@rexdk Mmm, yeah, another variation of #2911 looks like. (Broad summary: "Our timeline multi-selection logic is all kinds of weird.")

In fact, if you don't mind I'm going to migrate your comment over to that bug and close this one as a duplicate, just so that all of the info about multi-selection pathologies is together in one place. Not that your bug was a duplicate of that one when you originally _opened_ it, but like I said it helps to consolidate them since this is yet another aspect of the same underlying issue.

Closing as "duplicated-to" #2911

**Closed by ferdnyc** 2020-07-27 01:45 UTC
Labels: :beetle: bug

**Comment by rexdk** [comment] 2020-07-27 06:47
@ferdnyc Thanks, that's sensible
