### ISSUE TITLE
not sound in video

### ISSUE THREAD

**Issue by nickg001** [OpenShot/openshot-qt#1651] opened 2018-06-05 14:23 UTC
**Describe the bug**
When I put the video on website and play it with a web browser there is not sound in video If I play the video file only with a web browse e.g firefox :  same problem
With VLC only, I get sound.
I tried different videos profil  I get the same problem.

I tried different videos profil  I get the same problem.
**System Details (please complete the following information):**
 - Operating System /  [mageia 6 Linux ]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
1-    file>video export option : mp4 h.264 video, profil 1024x575 16:9 pal

**Expected behavior**
I should have sound with video when I use a web browser

**Screenshots**
on video the sound button is always off
![video](https://user-images.githubusercontent.com/39922087/40981397-1abc5686-68db-11e8-946f-d13320ded5d9.png)

**Comment by nickg001** [comment] 2018-06-05 15:18
![video1](https://user-images.githubusercontent.com/39922087/40985452-7252d628-68e4-11e8-9f2c-2fdc3ce09d7f.png)

**Comment by peanutbutterandcrackers** [comment] 2018-06-06 07:54
The problem is that the media player (including firefox) could not decode the audio stream. A simpler solution would be to transcode the video exported from OpenShot using [HandBrake](https://handbrake.fr/) to 'web profile' or something similar. That should solve this issue.

Another way would be to run this command: `ffmpeg -i output_from_openshot.mp4 better_output.mkv`

Hope that helps!

**Comment by DylanC** [comment] 2018-07-02 10:00
@nickg001 Can you try v2.4.2 and let us know if you have any success?

**Comment by nickg001** [comment] 2018-07-03 10:33
the problem was about my software package codex it is ok now
thanks for your answer

**Comment by peanutbutterandcrackers** [comment] 2018-07-03 10:38
@nickg001 - Still, version 2.4.2 has switched to a more commonly used audio codec by default so it should work better.

Closing this, then. :+1:

**Closed by peanutbutterandcrackers** 2018-07-03 10:38 UTC
