### ISSUE TITLE
[question] Simple parallax background possible?

### ISSUE THREAD

**Issue by littlelum** [OpenShot/openshot-qt#2646] opened 2019-02-27 04:30 UTC
Hi. I have two images that I want to use for a parallax scrolling background. What I want to know, is that would it be possible to have it so when a portion of one of the images go off screen, (to the left for example) could it appear on the other side (on the right for example) so it would appear as a continuous loop? Thank for taking the time to answer my question.

**Comment by littlelum** [comment] 2019-02-27 04:33
Ps for future reference, how would I add tags?

**Comment by N3WWN** [comment] 2019-02-27 14:30
I'm not sure how to add tags as I don't believe I have permissions to do so, but regarding the scrolling background, I think the answer is to get the background doing what you want it to once (scrolling fully from right to left, if I understand correctly), then select the clip, copy it and paste it where you want it to repeat from.  You can do this as many times as you need to get the duration required.  

If the desired output has a lot of repetitions, you could get one set up correctly, copy and paste it to have 2, copy and paste both so you have 4, copy and paste all 4 so you have 8, etc.

**Comment by littlelum** [comment] 2019-02-27 19:52
Ok, but what would I do if the picture won't even show up in the preview after I drag it into the timeline? Exactly how do I make it scroll? And after looking at the options, I don't see anywhere where it says that "if a portion of it goes off on the left, it will appear on the right, even though the remaining portion is still on the left" (or something like that) Could you elaborate a little more please?
(if you need me to be more specific on what the scrolling background should be like, take the results screen from Super Mario Kart (SNES) for example)

**Comment by N3WWN** [comment] 2019-02-28 14:22
If you'd like to change how the animation is implemented, you can do so by adjusting the curves used in the keyframes: https://www.openshot.org/static/files/user-guide/animation.html#key-frames

Here's a sight which helps you to understand how each curve behaves:  https://easings.net/

In your case, since you want a constant rate, you would select `Linear` instead of `Constant` or `Bezier`.  The reason you don't want `Constant` is that the value does not change over time when set to `Constant`.

Regarding the copy and paste, using `Constant` makes it relatively easy to get the scrolling to line up without gaps since each frame moves the same amount.  

Here's one way you could do it (I'm assuming a new project with nothing else on any track for clarity):

- Place your background image on the timeline so it starts at 00:00:00:01 (first frame)
- Adjust the length of the clip for how long you want that image to appear on screen (I'll use 4s in this example)
- Put the playhead on the first frame of the image
- Set the `Location X` property to `1.00` in order to move the image all the way to the right (for a right to left animation) so that it cannot be seen
- Right-click on the function box to the right of the `1.00` in the `Location X` property and set it to `Linear`, if it isn't already
- Put the playhead on the last frame of the image
- Set the `Location X` property to `-1.00` in order to move the image all the way to the left
- Right-click on the function box to the right of the `1.00` in the `Location X` property and set it to `Linear`, if it isn't already

That is one cycle of the scrolling background image.  Now let's reproduce it to make a seamless scrolling background that is 10s long:

- Since it now takes 2s for our 4s long image to be perfectly centered in the output window, move the playhead to 00:00:02:01
- Select the background clip that we have just been working with (make sure nothing else is selected) and right-click and select `Copy` -> `Clip` (or use <kbd>CTRL-C</kbd>)
- Right-click somewhere on another track and paste the copied clip
- Without moving the playhead, left-click and drag the freshly pasted clip to the playhead location

If you render this or click play in the preview window, you will see the image scroll from right to left with another copy of the image scrolling right to left right behind it.

Should there be a slight gap (or an overlap) between the images ruining the seamlessness, you can select the 2nd clip and nudge it left or right with <kbd>SHIFT-LEFT</kbd> or <kbd>SHIFT-RIGHT</kbd> to position it perfectly.

We now have a 6s long scrolling background composed of the original 4s clip and the second 4s clip with a 2s overlap.

- Using the mouse, draw a selection box that touches both clips to select them both
- Right-click and `Copy`
- Right-click and `Paste` further down the timeline
- Select the two newly pasted clips and drag them to the end of the first clip

This will result in the clips on both tracks being placed one after the other with a total length of 10s.  We want a 10s duration, but it scrolls in and out and I'd like the background to fill the screen all the time, so let's paste and drag one more time so we end up with a 14s long clip.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/19431804/53572559-8611d100-3b39-11e9-8060-0ba76c1d1217.png">

Next is to cut it down to size:

- Move the playhead to 00:00:02:01 which is the first frame of the 2nd clip that we made
- Right-click on the blue "triangle" portion of the playhead 
- Select `Slice All` -> `Keep Right Side` to get rid of everything from 0s to 2s
- Move the playhead to the end of the clip near 00:00:12:01
- Right-click on the blue "triangle" portion of the playhead 
- Select `Slice All` -> `Keep Left Side` to get rid of everything from 12s to 14s
- Draw a selection box around all of the clips (or use <kbd>CTRL-A</kbd>)
- Drag all of the clips to the far left so our remaining 10s starts at 0s

You should end up with a timeline that looks like this:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/19431804/53572729-eef94900-3b39-11e9-9173-0ef35be28bd9.png">

And you should have your seamless scrolling background 😁

**Comment by littlelum** [comment] 2019-02-28 18:31
Thanks! One problem, though. When I shorten the duration, the start value changes from 0 to the length I removed from the clip. When I modify the start time (In the properties menu, the timeline can't change it) the duration resets back to 10 seconds.

**Comment by N3WWN** [comment] 2019-02-28 18:56
Can you post some screenshots showing the duration reset issue that you're encountering?  I'm not sure I understand.

If you have a 30 fps profile selected, `00:00:00:31` should never show up on the timeline (where it says `00:00:11:57` in my last image above).  The playhead should go from `00:00:00:30` to `00:00:01:01`.  It's not apparent, but the time is displayed in HH:MM:SS:ff format where HH = hours, MM = minutes, SS = seconds and ff = frames.

You are correct the `00:00:01:01` is the first frame of the 2nd second into the timeline.  (`00:00:00:01` - `00:00:00:30` being the 1st second).

**Comment by littlelum** [comment] 2019-02-28 22:48
![capture](https://user-images.githubusercontent.com/25493246/53603815-8a54e300-3b67-11e9-9bbf-39e71efc6673.PNG)
![capture2](https://user-images.githubusercontent.com/25493246/53603818-92148780-3b67-11e9-96f1-c6d3bb68df1d.PNG)
![capture3](https://user-images.githubusercontent.com/25493246/53603821-9771d200-3b67-11e9-92f0-df0f70ecf425.PNG)
It is 30 fps, but it still shows a 00:00:00:31
The second and third demonstate the problem relating to the stat time and the duration.

**Comment by N3WWN** [comment] 2019-03-01 14:00
Ah, it seems that 2.4.3 has adjusted how the timeline is calculated (probably a good thing as there were off-by-one issues before) and it is now possible to get `00:00:00:31` in the output.  I was looking at my dev version of 2.4.1 when I responded about that not being possible.  Sorry for the confusion.  

Basically, since there is no frame 0, frames go from 1 to 31 each second (for a 30fps profile).

I see what you're talking about now with regards to the duration, but the properties are not what you think they are. 😁 

The `Start` property is the position in the original source file that the clip on the timeline starts at.  If you cut the first two seconds off the beginning of the clip, the `Start` property will always be `2.00`, regardless of where on the timeline the clip is actually located.

The `Position` property defines the horizontal position of the clip on the timeline, i.e. when in the project the clip will start.

**Comment by littlelum** [comment] 2019-03-01 21:30
What do I do if clips are randomly visible or invisible, and sometimes only visible on random frames? (I can't find a setting for that, and it also happens on the top layer, not just the bottom.)

**Comment by N3WWN** [comment] 2019-03-04 19:29
Hi @littlelum ... I'm sorry, but from your description, there's no way to know what you're seeing.  Can you post some screenshots or a video which show the problem(s)?

**Comment by littlelum** [comment] 2019-03-05 03:10
Since I don't know how to convey this in screenshots, so I'll try to elaborate on that.
Sometimes, when I drag a clip onto the timeline, it appears completely black on the playback screen. It is completely random when it happens, (to the best of my knowledge) and once It flickered back and forth between being visible and black.
On the other problem, when you try to shorten a clip by dragging the left of the clip edge inward, (on the timeline) the length of the clip shortens as expected (as deas the size of the clip on the timeline). But if I try to do that by dragging the right side inward, it automatically shortens to a duration of 0.03 and on the timeline it appears as a slim red bar.
I hope I described it well enough.  :)

**Comment by N3WWN** [comment] 2019-03-05 13:54
> Sometimes, when I drag a clip onto the timeline, it appears completely black on the playback screen. It is completely random when it happens, (to the best of my knowledge) and once It flickered back and forth between being visible and black.

Does the clip flicker in the final rendered output or just in the preview?  

If you move the playhead over the frames that change from visible to black, do you see any changes in the clip properties?  If you see a small green tick at the bottom of the clip where the visibility changes, or you see the name of a property change to green within a frame or two of where the visibility changes, then there are keyframes affecting the visibility.

> On the other problem, when you try to shorten a clip by dragging the left of the clip edge inward, (on the timeline) the length of the clip shortens as expected (as deas the size of the clip on the timeline). But if I try to do that by dragging the right side inward, it automatically shortens to a duration of 0.03 and on the timeline it appears as a slim red bar.

Are these clips images or videos (or doesn't it matter)?  Do you experience the same problems if you slice the clip instead of dragging the edges of the clip?

I often change the duration of static image clips on the timeline by dragging the right side of the clip, but always slice video clips.

**Comment by littlelum** [comment] 2019-03-06 20:31
On the first one, the problem gets fixed if I try to extend the clip by dragging the left side. It only (I don't know what caused the flickering, as that only happened once.) EDIT: nevermind, it only makes it visible until I let go of the mouse button. It only happens with static clips as regular clips work perfectly fine.

On the second problem, the trouble is with static frames. Slicing it works perfectly fine, the problem just occurs when dragging static clips inward from the right side.

**Comment by N3WWN** [comment] 2019-03-07 13:45
This is the first that I've heard of these issues, although I'm not intimately involved in OpenShot dev at this time, so am somewhat removed.  

If you feel these are problems with OpenShot, please open a new issue as a [Bug Report](https://github.com/OpenShot/openshot-qt/issues/new?assignees=&labels=bug&template=bug-report.md&title=Give+your+bug+report+a+descriptive+title) and be sure to include as much of the requested information as possible (especially the `System Details` and `Steps to reproduce the behavior` sections).

**Comment by DylanC** [comment] 2019-03-22 08:54
Closing as answered.

**Closed by DylanC** 2019-03-22 08:54 UTC
Labels: question
