### ISSUE TITLE
Openshot 2.3.4 doesn't run

### ISSUE THREAD

**Issue by 109Natsu** [OpenShot/openshot-qt#699] opened 2017-06-01 08:15 UTC
**System Details:** 
* Operating System / Distro: Windows 10
* OpenShot Version: OpenShot-v2.3.4-x86_64
* _Please attach log files if crash_
![image](https://cloud.githubusercontent.com/assets/28969934/26670735/c5ed2ba4-46ed-11e7-8b9b-b76df40bab8d.png)

**Issue Description and steps to reproduce:**
I just downloaded the new 2.3.4 version hoping to fix the 2:33 bug, but it turns out to not work at all?

**Comment by SunDancerGE** [comment] 2017-06-01 11:32
- Operating  System / Distro: Windows 7 Pro
- OpenShot Version: OpenShot-v2.3.4-x86_64

Same error windows as OP

**Comment by TheDcoder** [comment] 2017-06-01 12:55
* Operating System /Distro: Windows 8 Enterprise
* OpenShot Version: OpenShot-v2.3.4-x86_64

Can confirm this error, same error as OP:
![launch_2017-06-01_18-24-37](https://cloud.githubusercontent.com/assets/6347576/26680584/9bc028a4-46f7-11e7-825b-dc2c04fb31cb.png)

**Comment by rafik24** [comment] 2017-06-01 13:52
Have the same on Win 7 too

**Comment by vales** [comment] 2017-06-01 13:57
Have the same on Win 10

**Comment by TheDcoder** [comment] 2017-06-01 14:04
I hope we get an emergency patch/fix for this bug

**Comment by jonaspm** [comment] 2017-06-01 22:34
Same here... looks like Openshot is expecting python3 files to be in C:\msys64, however, the libs are already in C:\Program Files\OpenShot Video Editor\lib\python3.5
though it doesn't read them.

Copying Openshot's lib folder to C:\msys64 doesnt' work.

Must be a build problem of Openshot v2.3.4

**Comment by jonoomph** [comment] 2017-06-01 22:45
This has been fixed. It was caused by a few mixing files in the Windows installer. Please download the 2.3.4 installer again and reopen if the issue keeps happening. Fingers crossed!

**Closed by jonoomph** 2017-06-01 22:45 UTC

**Comment by jonaspm** [comment] 2017-06-01 23:01
![imagen](https://cloud.githubusercontent.com/assets/7599554/26704395/fe18afdc-46eb-11e7-873f-86c0935ce185.png)
Fixed!

**Comment by 109Natsu** [comment] 2017-06-02 01:15
Thank you for the fix :)

The audio bug at 2:33 still needs fixing :(
