### ISSUE TITLE
I tried opening a previous project and it says " Failed to load project file (My File Name) OSP.osp: invalid load key, '\x00'. " what does this mean and how do i fix it? i tried opening a different osp file and it worked so why wont this one work?

### ISSUE THREAD

**Issue by CameronR02** [OpenShot/openshot-qt#2627] opened 2019-02-18 17:48 UTC
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by jdriviere** [comment] 2019-09-21 03:25
**Description of the Bug:**
OpenShot refuses to open a previously saved file.  I find it strange, because I've been using it for about 2 weeks (with intervals, of course), and the error just suddenly appeared. At first, the program would take forever to load, then be slow at rendering my project; and now it won't open my file anymore. When I open an older version of the project, I receive another error, and most of my files appear to be missing.

**Steps to Reproduce the Bug:**
Quite tricky because it may or may not happen to everyone. Either way, you go to "File --> Open --> [File Name.osp]"

**Expected Behavior:**
I expected it to open my file without error messages or warnings.

**System Details:**
- PC: HP Laptop with 6GB RAM i3-4005U (1.70GHz) Windows 10 Home
- OpenShot: v2.4.4

**Log Files:**
It's not in my folder...

**Exception/Stacktrace:**
The following message is all I get...

```bash
Failed to load project file C:/Users/Jessica/Pictures/Wedding Video Project_02.osp: invalid load key, '\x00'.
```

**Screenshots:**
N/A

**Comment by ferdnyc** [comment] 2019-09-22 00:58
> **Log Files:**
> It's not in my folder...

Your logs would be at `C:\Users\[User]\.openshot_qt\openshot-qt.log`

We'd really need to see either the logs, or the project file in question — preferably both. The data in your project file can't be read by OpenShot, but what exactly the problem is or how it happened we couldn't possibly say just by guessing.

However, if you post the project file, we can most likely repair it so it's loadable again. You can upload `.log` files directly as comment attachments. To post `.osp` files you can either add a `.txt` extension to the filename (e.g. `File Name.osp.txt`) or place it inside a `.zip` archive and upload that. (The Zip file is probably a better choice if the `.osp` is corrupted, posting it as `.txt` might cause data loss.)

**Comment by jdriviere** [comment] 2019-09-22 03:29
@ferdnyc Ah, I already uninstalled the program. But I appreciate your help nonetheless.  Thank you..

**Comment by mikelacsa** [comment] 2019-10-03 21:53
Closing this issue as it has been over 7 days after it was labeled "needs info"

**Closed by mikelacsa** 2019-10-03 21:53 UTC
Labels: :beetle: bug, :question: needs info
