### ISSUE TITLE
jpg/transparent png errors grey screen blocks overlay in openshot

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1721] opened 2018-06-22 02:04 UTC
running linux mint 18.3 64 bit and ubuntu 18.04 64 bit

Hello everyone, i have serious issue with openshot
importing jpegs or transparent png's as a image sequence

openshot latest dev and rc5 will create the video file 
however it puts garbage lines of blocks of grey and sometimes
other colours along side it.

![openshot error png](https://user-images.githubusercontent.com/40479177/41754109-4d7c53b4-7614-11e8-9ed9-468ed98b7c7c.png)

as you can see by my example the picture on the left was
done in dev -136

the picture on the right was done with the latest dev 170
and even rc5.

I tried emailing the author several times and showing him
pictures, until now he has not  fixed the problem.

in his 1.43 linux older version it works perfectly.

im wondering if others experiencing the same for importing
 jpgs's or transparent png's as image sequence

thanks
  bob

**Comment by peanutbutterandcrackers** [comment] 2018-06-22 09:24
Hmm... I just did a 'quick' test (which turned out to be quite long because I had to A. Get a PNG file. B. Change the colors up and make 3 versions of them. C. Figure out a bash one-liner to make copies of it, without first figuring out that there is actually a stepping mechanism now in bash's brace expansion `{start..end..step}`. Agh. Anyways, I was not able to reproduce this issue. Does this issue only persist in the preview or is the render also suffering?

Also, regarding the author - He is Mr. Jonathan Thomas. A great man and a talented programmer. I am very grateful that he has given us this gem of a software. But he is mostly a one man army and has to do all the work all by himself. That is why he can't really reply instantly to our messages and stuff. I have jumped in to help him out with the issues. And so has DylanC (the good sir whom I am asking to test this issue, too). This is a community project, good sir. It is our software. We are the ones that decide how far it goes. We get to help make it, or we can just sit and complain and just let this awesome thing die away. OpenShot is really popular but doesn't have many contributors. Perhaps you'd care to just us, good sir. We'd really appreciate any help we can get.

Also, thank you for the bug report. We'll try to test it and try to get the devs' attention towards this issue and get it fixed, ASAP.

![screenshot from 2018-06-22 15 03 42](https://user-images.githubusercontent.com/26764547/41768970-8252d626-762d-11e8-9596-f065b10dd5c6.png)

Perhaps you'd like to send us the `.png`s that you used? We could test using the same files, too...

Here's my output: 
[Openshot png test #1.mp4.tar.gz](https://github.com/OpenShot/openshot-qt/files/2127031/Openshot.png.test.1.mp4.tar.gz)

@DylanC - Perhaps you could reproduce this bug, Cap'ain?

**Comment by bobcrikey** [comment] 2018-06-22 12:17
well here's the zip files with the original jpegs of the tardis spining, and its after the video is rendered
that you can see the block grays appearing if you drag the video into the time line and use the right 
arrow key you will be see what im experiencing, and yes peanuts and crackers i know jonathan is working hard , i did offer to help him but its ok i know he's busy, im sure its small bug in there. if you like see all the videos iv created with openshot their on youtube just look for bob crikey , i do mainly
star trek and dr who animations, all done with openshot and kdenlive, but i prefer working with openshot personally.cheers 
[tardis jpegs.tar.gz](https://github.com/OpenShot/openshot-qt/files/2127583/tardis.jpegs.tar.gz)

**Comment by N3WWN** [comment] 2018-06-22 13:22
I haven't delved into this too far, but I just downloaded your files and noticed that the ones that you archived for us are jpg files.  jpg does not support transparency.

Can you create an archive with the png files that you were originally working with?

Thanks!

**Comment by bobcrikey** [comment] 2018-06-23 10:48
well heres a png picture iv just done to demostrate the transparent image sequence error in openshot
the n3wwn, have a look at this, and you can see the results ok
![error in openshot](https://user-images.githubusercontent.com/40479177/41808803-7fd996ba-7726-11e8-9d17-27efa774a2da.png)

now here the png's in a zip file for you to put in the latest dev version, ok 
and this was done in openshot latest dev on ubuntu 18.04

thanks bob
[tardispngs.tar.gz](https://github.com/OpenShot/openshot-qt/files/2129841/tardispngs.tar.gz)

**Comment by bobcrikey** [comment] 2018-06-23 11:38
in fact iv just added the red arrows for N3WWN or any other devs to see the grey line blocks are not
part of the original png's not even present on any png's nor the jpegs of the tardis
![error in openshot2](https://user-images.githubusercontent.com/40479177/41809248-c39c836a-772d-11e8-8ea1-cb4f173286e0.png)


bob

**Comment by peanutbutterandcrackers** [comment] 2018-06-24 09:04
First and foremost, the `.png`s that you have attached, they do not have transparency, good sir. I opened them from GIMP and photo-viewer and it does not have transparency.
![screenshot from 2018-06-24 14 43 53](https://user-images.githubusercontent.com/26764547/41817570-6140d38e-77bd-11e8-87ff-ca4671701d3d.png)
![screenshot from 2018-06-24 14 43 28](https://user-images.githubusercontent.com/26764547/41817571-61daedfc-77bd-11e8-93fe-45cb6f11a6eb.png)

However, on my latest daily build of OpenShot on my buddy's Elementary OS 0.4.1 'Loki' machine, OpenShot freezes when I try to import the pictures as an image sequence. Also, it should not have the grey lines on your preview, though. Could you please try rendering/exporting it? Perhaps the grey lines won't appear in the final output?

Certainly a strange case.

**Comment by bobcrikey** [comment] 2018-06-24 12:17
hello again, im redoing the png's again, its time consuming but i should have it done by this time tomorow night my time, and i noticed also the png's werent transparent as well and i cant find the original png's either that i did, i have the original pictures i took 14 of them to make the tardis spin on it its own.
with my kitchen wall as back drop and you dont want to see that mate.:) or maybe you do haha

bob

**Comment by peanutbutterandcrackers** [comment] 2018-06-24 12:32
Hmm... that is strange. I suggest you [attach the logs](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) here, along with system specs and all. Also, I suggest you delete the existing logs first so that we don't have to deal with *enormous* logs.

**Comment by bobcrikey** [comment] 2018-06-25 03:02
hello again, iv redone the 14 pngs again , however there is still errors in openshot including cutting off
part of the screen and after rendering it, here are the new tardis png's, a video  and a still image to show you , if you look at the picture snapshot you can see the half the of the tardis right side door is missing
and you can see this also in the video

[new tardis png.tar.gz](https://github.com/OpenShot/openshot-qt/files/2131571/new.tardis.png.tar.gz)
![new tardis cut off error](https://user-images.githubusercontent.com/40479177/41828179-335318c8-7877-11e8-8e91-8b74d1e9a0f9.png)
[new png tardis.mp4.tar.gz](https://github.com/OpenShot/openshot-qt/files/2131576/new.png.tardis.mp4.tar.gz)

and peanuts mate, i did tell you my computer specs in the previous thread if you read it clearly i have 
an amd ryzen 1600 thats 6 cores 12 thread cpu with 16 gigs of 2400mzh ram, thats running linux mint

bob

here's my dr who video made with openshot https://youtu.be/PX69kb3dWDI

**Comment by peanutbutterandcrackers** [comment] 2018-06-25 03:17
I'm sorry. While juggling all the issues here on GitHub, I often forget the details about them and repeat the same thing over and over again. Hope you will pardon my confusion.

I have downloaded the files and will be testing out soon. I will get back at this ASAP.

**Comment by peanutbutterandcrackers** [comment] 2018-06-25 03:28
Good sir, I took a look at the new set of `.png`s and they are still - even now - without transparency. Here:
![screenshot from 2018-06-25 09 04 22](https://user-images.githubusercontent.com/26764547/41828767-caeebbb8-7856-11e8-97ed-db2c7398c128.png)

However, I think I will guide you through making `.png`s with transparency using the same files.

1. Open [GIMP](https://www.gimp.org/)
2. Open the Tardis image in GIMP
3. Use the 'Fuzzy Select Tool' to select the black part in the image
![screenshot from 2018-06-25 09 08 13](https://user-images.githubusercontent.com/26764547/41828862-527e86da-7857-11e8-8300-14b50ca79038.png)
4. Press 'Delete' on your keyboard
![screenshot from 2018-06-25 09 08 55](https://user-images.githubusercontent.com/26764547/41828886-69b04528-7857-11e8-881d-bb401fe0d036.png)
Now, export the `.png` file.
![1](https://user-images.githubusercontent.com/26764547/41828904-883721ba-7857-11e8-863b-d77b24fcefca.png)

Please try with the `.png`s that you get once you process the images using GIMP. All you have to do is remove the black background using the fuzzy select tool in GIMP.

For future references, you'll have to click on the layer and 'add alpha channel' if your original images do not have one. These one's did so I didn't put that step. If required, that would be step 2.5.

Hope that helps!

**Comment by N3WWN** [comment] 2018-06-25 15:46
When importing a sequence of images, the images need to be the same size or "odd" things may occur.  I'm guessing that the artifacts seen in the imported sequence are due to this.

>File: 1.png
Width                                    : 474 pixels
Height                                   : 928 pixels

>File: 10.png
Width                                    : 554 pixels
Height                                   : 917 pixels

>File: 11.png
Width                                    : 479 pixels
Height                                   : 907 pixels

>File: 12.png
Width                                    : 574 pixels
Height                                   : 898 pixels

>File: 13.png
Width                                    : 557 pixels
Height                                   : 882 pixels

>File: 14.png
Width                                    : 474 pixels
Height                                   : 928 pixels

>File: 2.png
Width                                    : 533 pixels
Height                                   : 920 pixels

>File: 3.png
Width                                    : 604 pixels
Height                                   : 932 pixels

>File: 4.png
Width                                    : 533 pixels
Height                                   : 922 pixels

>File: 5.png
Width                                    : 516 pixels
Height                                   : 912 pixels

>File: 6.png
Width                                    : 587 pixels
Height                                   : 906 pixels

>File: 7.png
Width                                    : 532 pixels
Height                                   : 903 pixels

>File: 8.png
Width                                    : 533 pixels
Height                                   : 904 pixels

>File: 9.png
Width                                    : 599 pixels
Height                                   : 926 pixels

Creating a virtual image of 604x932 pixels and centering the images into that virtual image, I was able to create images that were all the same size and maintained the transparent background.

I did this using ImageMagick's convert tool (this command line will only work on Mac, Linux or other *n*x-like OS):

`mkdir output; for i in *.png; do convert $i -gravity Center -background none -extent 604x932 output/$i; done`

Importing your original pngs results in the same cropped frames that you see.

After importing these new images as a sequence, none of the frames are cropped anymore.

**Comment by bobcrikey** [comment] 2018-06-26 00:50
Thats very interesting N3WWN, thanks for taking the time to look at that,

Were there any artifacts present when you recropped the images and brought
them into openshot -dev 170 or rc6 as an image sequence that you noticed?

**Comment by bobcrikey** [comment] 2018-06-26 01:51
Well thanks to N3WWN, i resized my png's and jpg's so each individual picture is the same width/height
and now no artifacts or grey blocks or crashing openshot(touch wood) at the moment, when brought
in as an image sequence.
cheers 
 bob

a 6 pack of beer is on the way to your place mate.

**Comment by peanutbutterandcrackers** [comment] 2018-06-26 04:57
Awesome! Thank you @N3WWN! You are always a great help, good sir!

Hope you create awesome videos with OpenShot, @bobcrikey!

Closing this as resolved.

**Closed by peanutbutterandcrackers** 2018-06-26 04:57 UTC

**Comment by LuvIsBadToTheBone** [comment] 2023-12-16 03:43
bob iam triing to reach out for u desperadely. i miss u very much and the time with u on the spotchatserver has good memories. i cant find contact info of u so i invite u to libera network channel is ##linuxmint regards, SexIsBadToTheBone, a fan. :)
