### ISSUE TITLE
I am getting this error when I try making an animated title

### ISSUE THREAD

**Issue by Eudakimau** [OpenShot/openshot-qt#493] opened 2017-02-04 17:44 UTC
Blender, the free open source 3D content creation suite is required for this action (http://www.blender.org).

Please check the preferences in OpenShot and be sure the Blender executable is correct.  This setting should be the path of the 'blender' executable on your computer.  Also, please be sure that it is pointing to Blender version 2.62 or greater.

Blender Path:
blender

Error Output:
No frame was found in the output from Blender

**Comment by alh54** [comment] 2017-02-04 23:25
hi,
I got the same problem. I am on fedora 25, blender-2.78a-4.fc25.x86_64 is installed from fedora updates repository. I can run blender without any problem.
openshot version: openshot-2.1.0-2.fc25.noarch
Regards

**Comment by mixedbredie** [comment] 2017-02-06 14:29
I made a [wiki page](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) for this as it appears to be the number one reported error in this issues list.  See if any of the fixes work for you.  

It's always a good idea to search the issues list.  The same problem has been reported many times and the solution(s) has been posted in a number of them.

**Comment by alh54** [comment] 2017-02-06 21:12
Sorry i did not read the wiki, in fact updating the blender scripts solves the worry.
Thank you.

**Comment by jonoomph** [comment] 2017-02-28 23:30
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!

**Closed by jonoomph** 2017-02-28 23:30 UTC

**Comment by mallapurbharat** [comment] 2018-01-07 07:58
I've faced this issue with the latest version of OpenShot appimage as well. I just downloaded Blender from it's website, extracted it to my home directory, and added the path to the Blender folder in my ~/.profile file. Rebooted the system to make sure that path gets updated and Openshot was able to create animated titles just fine (I tested Dissolve Text animation). Also updated Openshot preferences to point to the blender executable.

However, this error popped up again when I tried to customise the animation settings. By changing the font settings, this seemed to pop up. So, try using different animation settings if this happens. This error pops up even when the Blender path is set properly, because some argument is not "setting" properly.

HTH.

**Comment by Foadsf** [comment] 2019-08-31 14:58
I just got the same error on 

- Windows 10 Version 1903 build 18362.329
- OpenShot 2.4.4 installed via Chocolatey
- Blender 2.8 installed via Chocolatey

what I have done to fix the issue:

 * I have set the path to `C:/Program Files/Blender Foundation/Blender/blender.exe` in "Edit > Preferences>General>Blender Command(path)"
 * as suggested by @mixedbredie in [this page](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) I have searched for all `text_object.align` in `C:\Program Files\OpenShot Video Editor\blender` and the only ones were in comments of some Python scripts (which I changed to `text_object.align_x` anyway!)
 * as sugested [here](https://ubuntuforums.org/showthread.php?t=1674405&p=10423187#post10423187) I serched for all `CENTRAL`, there are none!

I don't know what else I should do. I would appreciate if you could help me with this issue.

**Comment by jasuk70** [comment] 2019-09-01 11:42
Same error here on Windows 10
After enabling debugging, I saw the command that ran and this was the error reported.
`PS C:\Users\mail> blender.exe -b 'C:\Program Files\OpenShot Video Editor\blender\blend\wireframe_text.blend' -P 'C:\Users\mail\.openshot_qt\blender\74e54088-ccac-11e9-b39a-983b8f950640\wireframe_text.py'
Blender 2.80 (sub 75) (hash f6cb5f54494e built 2019-07-29 09:44 AM)
Read prefs: C:\Users\mail\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Read blend: C:\Program Files\OpenShot Video Editor\blender\blend\wireframe_text.blend
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mail\.openshot_qt\blender\74e54088-ccac-11e9-b39a-983b8f950640\wireframe_text.py", line 141, in <module>
    material_object.diffuse_color = params["diffuse_color"]
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3`

**Comment by ferdnyc** [comment] 2019-09-01 13:40
@jasuk70 See #2901. OpenShot 2.4.4 release is not compatible with Blender 2.80.

**Comment by ferdnyc** [comment] 2019-09-01 13:41
(Oops. @Foadsf , same.)

**Comment by jasuk70** [comment] 2019-09-01 13:43
@ferdnyc Thanks, I'll grab the latest daily build.

**Comment by ferdnyc** [comment] 2019-09-01 13:56
I updated [that wiki page](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) @Foadsf mentioned with a big note at the top, as well.

**Comment by Foadsf** [comment] 2019-09-02 10:44
@ferdnyc thanka lot. any idea when a stable version including this feature will be released?

**Comment by ferdnyc** [comment] 2019-09-08 17:55
@Foadsf Not as yet, no. It'll likely be a while. (As in, "_probably_ before the end of the year, but no guarantees.") 

There are a **lot** of big changes already incorporated into the development tree, and quite a few more still being worked on or awaiting review. (Most of the 19 PRs in this repo, plus another 15 for libopenshot, will still need to be merged prior to even _starting_ the release branching process.)

And because the changes are so extensive and numerous, I'm personally going to argue for a much longer than usual beta period before the release goes out. Just to make sure everything is tested thoroughly, so we can ensure it's really where we want it to be.

**Comment by ashuk99** [comment] 2019-09-29 08:16
I fixed it!!
The problem is openshot v2.4.4 (your version) is not compatible with blender v2.80
How to fix:
Just download blender v2.78/2.79 and done ;)

**Comment by ProfessorFilipo** [comment] 2019-12-08 06:21
I was getting the same error on Win10 with OpenShot 2.4.4 and Blender 2.8. I just downloaded the latest OpenShot dev release and it solved everything.

**Comment by seanjmcm** [comment] 2020-02-08 21:32
Version 2.4.4, tried to do a flare and got this bug.

**Comment by ferdnyc** [comment] 2020-03-11 13:41
@seanjmcm OpenShot 2.5.1 is out now, with Blender 2.8 support. However, you may actually want to get the latest Daily Build install from https://openshot.org/download/, as there was a fix to the Blender rendering process that went in shortly after 2.5.1 was released.

**Comment by Giszmo** [comment] 2020-04-02 02:32
That's really unfortunate that this error keeps popping up over the years instead of some more graceful feature degradation.

**Comment by GGShinobi** [comment] 2020-04-27 13:22
I just downloaded the latest version of OpenShot as an AppImage from the website. I also installed blender 2.82 via snap. I'm running Ubuntu 18.04 LTS.

> I made a [wiki page](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) for this as it appears to be the number one reported error in this issues list. See if any of the fixes work for you.
> 
> It's always a good idea to search the issues list. The same problem has been reported many times and the solution(s) has been posted in a number of them.

I tried to follow the instructions in the wiki.
I have adjusted the path inside the blender preferences to point to /snap/bin/blender, but how can I access the blender scripts (that I assume are hidden inside the "OpenShot-v2.5.1-x86_64.AppImage" file), so that I can update them?

Also, no offence, just curious:  what is the reason that the scripts don't come already updated?

In case it helps here the console output from OpenShot and blender --version:

`~/VideoEditors$ ./OpenShot-v2.5.1-x86_64.AppImage 
Loaded modules from current directory: /tmp/.mount_UxbYat/usr/bin
         app:INFO ------------------------------------------------
         app:INFO             Mon Apr 27 15:02:54 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3
         app:INFO qt5 version: 5.2.1
         app:INFO pyqt5 version: 5.2.1
    language:INFO Qt Detected Languages: ['en-US', 'en']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /tmp/.mount_UxbYat/usr/bin/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
     version:INFO Found current version: {"openshot_version": "2.5.1"}
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
 files_model:INFO updating files model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:INFO Clear all thumbnails: /home/ggshinobi/.openshot_qt/thumbnail
 main_window:INFO Clear all animations: /home/ggshinobi/.openshot_qt/blender
 main_window:INFO Clear all titles: /home/ggshinobi/.openshot_qt/title
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['/tmp/.mount_UxbYat/usr/bin/openshot-qt']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HD 720p 30 fps
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
video_widget:INFO Set video widget pixel aspect ratio to: 1.0
 main_window:INFO updateStatusChanged
 main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
preview_thread:INFO onModeChanged
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO SetThumbAddress: http://127.0.0.1:42159/thumbnails/
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(908, 511)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO UpdateLayerIndex
     ui_util:INFO Initializing UI for Dialog
blender_model:INFO updating effects model.
blender_listview:INFO Using parameter file_name: File Name
blender_listview:INFO Using parameter title: Title
blender_listview:INFO Using parameter sub_title: Sub Title
blender_listview:INFO Using parameter extrude: Extrude
blender_listview:INFO Using parameter bevel_depth: Bevel Depth
blender_listview:INFO Using parameter fontname: Font Name
blender_listview:INFO Animation param fontname set to Bfont
blender_listview:INFO Using parameter spacemode: Text Alignment
blender_listview:INFO Animation param spacemode set to CENTER
blender_listview:INFO Using parameter text_size: Text Size
blender_listview:INFO Using parameter width: Text Width
blender_listview:INFO Using parameter diffuse_color: Diffuse Color
blender_listview:INFO Using parameter specular_color: Specular Color
blender_listview:INFO Using parameter specular_intensity: Specular Intensity
blender_listview:INFO Using parameter start_frame: Start Frame
blender_listview:INFO Using parameter end_frame: End Frame
blender_listview:INFO Using parameter animation_speed: Animation Length
blender_listview:INFO Animation param animation_speed set to 2
blender_listview:INFO Animation param animation_speed set to 1
blender_listview:INFO Previewing frame 105
blender_listview:INFO Blender command: /snap/bin/blender -b '/tmp/.mount_UxbYat/usr/bin/blender/blend/blinds.blend' -P '/home/ggshinobi/.openshot_qt/blender/3PY10OFNTZ/blinds.py'
blender_listview:ERROR Blender error output:
No frame was found in the output from Blender

~/VideoEditors$ blender --version
Blender 2.82 (sub 7)
	build date: 2020-03-12
	build time: 05:30:40
	build commit date: 2020-03-12
	build commit time: 05:06
	build hash: 375c7dc4caf4
	build platform: Linux
	build type: Release
	build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wnonnull -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable  -fuse-ld=gold -std=gnu11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0
	build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wuninitialized -Wundef -Wmissing-declarations  -fuse-ld=gold -std=c++11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0
	build link flags:  -Wl,--version-script='/home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/creator/blender.map'
	build system: CMake

`

**Comment by GGShinobi** [comment] 2020-04-27 16:10
> I just downloaded the latest version of OpenShot as an AppImage from the website. I also installed blender 2.82 via snap. I'm running Ubuntu 18.04 LTS.
> 
> > I made a [wiki page](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) for this as it appears to be the number one reported error in this issues list. See if any of the fixes work for you.
> > It's always a good idea to search the issues list. The same problem has been reported many times and the solution(s) has been posted in a number of them.
> 
> I tried to follow the instructions in the wiki.
> I have adjusted the path inside the blender preferences to point to /snap/bin/blender, but how can I access the blender scripts (that I assume are hidden inside the "OpenShot-v2.5.1-x86_64.AppImage" file), so that I can update them?
> 
> Also, no offence, just curious: what is the reason that the scripts don't come already updated?
> 
> In case it helps here the console output from OpenShot and blender --version:
> 
> `~/VideoEditors$ ./OpenShot-v2.5.1-x86_64.AppImage
> Loaded modules from current directory: /tmp/.mount_UxbYat/usr/bin
> app:INFO ------------------------------------------------
> app:INFO Mon Apr 27 15:02:54 2020
> app:INFO Starting new session
> app:INFO ------------------------------------------------
> app:INFO OpenShot (version 2.5.1)
> app:INFO ------------------------------------------------
> app:INFO openshot-qt version: 2.5.1
> app:INFO libopenshot version: 0.2.5
> app:INFO platform: Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
> app:INFO processor: x86_64
> app:INFO machine: x86_64
> app:INFO python version: 3.4.3
> app:INFO qt5 version: 5.2.1
> app:INFO pyqt5 version: 5.2.1
> language:INFO Qt Detected Languages: ['en-US', 'en']
> language:INFO LANG Environment Variable: en_US.UTF-8
> language:INFO LOCALE Environment Variable:
> language:INFO OpenShot Preference Language: Default
> project_data:INFO Setting default profile to HD 720p 30 fps
> app:INFO Setting font to /tmp/.mount_UxbYat/usr/bin/images/fonts/Ubuntu-R.ttf
> logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
> app:INFO Setting custom dark theme
> QMainWindow::addDockWidget: invalid 'area' argument
> ui_util:INFO Initializing UI for MainWindow
> files_model:INFO updating files model.
> transition_model:INFO updating transitions model.
> effects_model:INFO updating effects model.
> version:INFO Found current version: {"openshot_version": "2.5.1"}
> properties_model:INFO updating clip properties model.
> transition_model:INFO updating transitions model.
> files_model:INFO updating files model.
> main_window:INFO InitCacheSettings
> main_window:INFO cache-mode: CacheMemory
> main_window:INFO cache-limit-mb: 250
> main_window:INFO Creating CacheMemory object with 262144000 byte limit
> preview_thread:INFO QThread Start Method Invoked
> preview_thread:INFO initPlayer
> main_window:INFO Clear all thumbnails: /home/ggshinobi/.openshot_qt/thumbnail
> main_window:INFO Clear all animations: /home/ggshinobi/.openshot_qt/blender
> main_window:INFO Clear all titles: /home/ggshinobi/.openshot_qt/title
> main_window:INFO updateStatusChanged
> main_window:INFO updateStatusChanged
> app:INFO Process command-line arguments: ['/tmp/.mount_UxbYat/usr/bin/openshot-qt']
> main_window:INFO recover_backup
> project_data:INFO Setting default profile to HD 720p 30 fps
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
> video_widget:INFO Set video widget pixel aspect ratio to: 1.0
> main_window:INFO updateStatusChanged
> main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
> preview_thread:INFO onModeChanged
> properties_model:INFO Update item:
> properties_model:INFO updating clip properties model.
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> timeline_webview:INFO Qt Found!
> timeline_webview:INFO $scope.Qt = true;
> timeline_webview:INFO SetThumbAddress: http://127.0.0.1:42159/thumbnails/
> timeline_webview:INFO SortItems
> timeline_webview:INFO UpdateLayerIndex
> timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(908, 511)
> preview_thread:INFO refreshFrame
> preview_thread:INFO self.player.Position(): 1
> timeline_webview:INFO UpdateLayerIndex
> ui_util:INFO Initializing UI for Dialog
> blender_model:INFO updating effects model.
> blender_listview:INFO Using parameter file_name: File Name
> blender_listview:INFO Using parameter title: Title
> blender_listview:INFO Using parameter sub_title: Sub Title
> blender_listview:INFO Using parameter extrude: Extrude
> blender_listview:INFO Using parameter bevel_depth: Bevel Depth
> blender_listview:INFO Using parameter fontname: Font Name
> blender_listview:INFO Animation param fontname set to Bfont
> blender_listview:INFO Using parameter spacemode: Text Alignment
> blender_listview:INFO Animation param spacemode set to CENTER
> blender_listview:INFO Using parameter text_size: Text Size
> blender_listview:INFO Using parameter width: Text Width
> blender_listview:INFO Using parameter diffuse_color: Diffuse Color
> blender_listview:INFO Using parameter specular_color: Specular Color
> blender_listview:INFO Using parameter specular_intensity: Specular Intensity
> blender_listview:INFO Using parameter start_frame: Start Frame
> blender_listview:INFO Using parameter end_frame: End Frame
> blender_listview:INFO Using parameter animation_speed: Animation Length
> blender_listview:INFO Animation param animation_speed set to 2
> blender_listview:INFO Animation param animation_speed set to 1
> blender_listview:INFO Previewing frame 105
> blender_listview:INFO Blender command: /snap/bin/blender -b '/tmp/.mount_UxbYat/usr/bin/blender/blend/blinds.blend' -P '/home/ggshinobi/.openshot_qt/blender/3PY10OFNTZ/blinds.py'
> blender_listview:ERROR Blender error output:
> No frame was found in the output from Blender
> 
> ~/VideoEditors$ blender --version
> Blender 2.82 (sub 7)
> build date: 2020-03-12
> build time: 05:30:40
> build commit date: 2020-03-12
> build commit time: 05:06
> build hash: 375c7dc4caf4
> build platform: Linux
> build type: Release
> build c flags: -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wnonnull -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -fuse-ld=gold -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0
> build c++ flags: -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wuninitialized -Wundef -Wmissing-declarations -fuse-ld=gold -std=c++11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2 -D_GLIBCXX_USE_CXX11_ABI=0
> build link flags: -Wl,--version-script='/home/sources/buildbot-x86_64-slave/linux_glibc217_x86_64_cmake/blender.git/source/creator/blender.map'
> build system: CMake`
> 
> EDIT: by reading a bit about AppImages I found out that they are some kind of archive that gets extracted to a temporary file system (FUSE). I checked that directory (in my example: /tmp/.mount_aNjS2T/usr/bin/blender/scripts ) and found out that indeed all of the scripts already come updated! There was nothing left for me to do:
> 
> `/tmp/.mount_aNjS2T/usr/bin/blender/scripts$ grep text_object.align * blinds.py:text_object.align_x = params["spacemode"] blinds.py:text_object.align_x = params["spacemode"] blur.py:text_object.align_x = params["spacemode"] explode.py:#text_object.align = params["spacemode"] fly_by_1.py:text_object.align_x = params["spacemode"] fly_by_two_titles.py:text_object.align_x = params["spacemode"] fly_by_two_titles.py:text_object.align_x = params["spacemode"] glare.py:text_object.align_x = params["spacemode"] neon_curves.py:text_object.align_x = params["spacemode"] rotate_360.py:text_object.align_x = params["spacemode"] slide_left_to_right.py:text_object.align_x = params["spacemode"] wireframe_text.py:text_object.align_x = params["spacemode"] zoom_clapboard.py:text_object.align_x = params["spacemode"]`
> 
> So, why do I still get that error message?

Hey, it's me again. I found out that when I launch OpenShot with superuser-permissions, it works. :-/ So I guess the reason why it's not working has something to do with missing access permissions to some directories or files... but I was unable to find out, which.

I discovered that I have a .openshot_qt directory in my home folder (probably because I then also tried the older version from the Ubuntu repositories, which works, btw), and that folder and all it's files and subfolders have 700 permission. I changed that to 755 for directories and 644 for files for testing purposes and while that seemed to have helped to some degree, I still get the error message.

I will keep you updated if I find out anything new, but since the older versions of OpenShot and Blender (which come from the Ubuntu repositories) work for me so far it might well be possible I won't dig into this much further.

**Comment by Cinefou** [comment] 2020-05-24 12:08
Openshot 2.5.1 + Blender 2.8 works, at least on Windows 10

**Comment by ferdnyc** [comment] 2020-05-24 16:13
@GGShinobi 

> > I made a [wiki page](https://github.com/OpenShot/openshot-qt/wiki/How-to-troubleshoot-errors-with-animated-titles) for this as it appears to be the number one reported error in this issues list. See if any of the fixes work for you.
> > It's always a good idea to search the issues list. The same problem has been reported many times and the solution(s) has been posted in a number of them.
>
> I tried to follow the instructions in the wiki.
> I have adjusted the path inside the blender preferences to point to /snap/bin/blender, but how can I access the blender scripts (that I assume are hidden inside the "OpenShot-v2.5.1-x86_64.AppImage" file), so that I can update them?
> 
> Also, no offence, just curious: what is the reason that the scripts don't come already updated?
> 
> EDIT: by reading a bit about AppImages I found out that they are some kind of archive that gets extracted to a temporary file system (FUSE). I checked that directory (in my example: /tmp/.mount_aNjS2T/usr/bin/blender/scripts ) and found out that indeed all of the scripts already come updated! There was nothing left for me to do:

Correct. The wiki page in question was written in February 2017, it is hopelessly out of date at this point, and should not be referenced for current versions of OpenShot or Blender.

> I just downloaded the latest version of OpenShot as an AppImage from the website. I also installed blender 2.82 via snap. I'm running Ubuntu 18.04 LTS.

Which "latest version"? The current Daily Builds? Or the 2.5.1 release? A while back in this thread I mentioned:

> @seanjmcm OpenShot 2.5.1 is out now, with Blender 2.8 support. However, you may actually want to get the latest Daily Build install from https://openshot.org/download/, as there was a fix to the Blender rendering process that went in shortly after 2.5.1 was released.

So, that may be the issue. If you run the (a) recent Daily Build, though, things _should_ work. And if it doesn't, OpenShot now logs all of the Blender output it receives, so we can get an idea of what went wrong.

The only other thing I can think of is, are you running with a non-English locale by any chance? It's recently come to light that Blender localizes its console output, or at least it _can_, and since we're parsing that output to monitor the build status a non-English Blender's output unfortunately might not be recognized properly.

**Comment by sijanec** [comment] 2020-06-07 16:41
Same issue on `Linux host 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` with Blender from Applications store and OpenShot from the PPA.

**Comment by KiLLAAA** [comment] 2020-08-05 08:17
**Same error with daily build**, release 2.51 not working with Blender at all, having "2.80" in front of path regardless what is set!
         app:INFO ------------------------------------------------
         app:INFO             Wed Aug  5 09:52:48 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO          OpenShot (version 2.5.1-dev2)          
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1-dev2
         app:INFO libopenshot version: 0.2.5-dev2
         app:INFO platform: Linux-4.2.0-19-generic-x86_64-with-LinuxMint-17.3-rosa
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3
         app:INFO qt5 version: 5.2.1
         app:INFO pyqt5 version: 5.2.1

**Steps to reproduce:**
run OpenShot daily build from terminal (./OpenShot-v2.5.1-dev2-1595950874-bf0159bb-7cec1822-x86_64.AppImage)
set proper path to Blender(2.83-3 -> newest at this time)
click Tile, Animated Title

**ERROR:**
blender_listview:INFO Checking Blender version, command: '/home/. . . /blender-2.83.3-linux64/blender' -v
blender_listview:ERROR Worker exception: No Blender version detected in output

Running the command aside in terminal:
'/home/. . . /blender-2.83.3-linux64/blender' -v
Blender 2.83.3
	build date: 2020-07-22
	build time: 06:01:36
	build commit date: 2020-07-22
	build commit time: 06:01
	build hash: 353e5bd7493e
	build platform: Linux
	build type: Release

**Conclusion:**
most probably the parsing of Blender's output is broken!

**Comment by dejanmilo-dev** [comment] 2022-06-13 19:53
I had the same error and started Openshot on cli to see the error output. I had the following error:

```
/usr/lib/python3.10/site-packages/openshot_qt/blender/blend/explode0075.png: Permission denied
imb_savepng: Cannot open file for writing: '/usr/lib/python3.10/site-packages/openshot_qt/blender/blend/explode0075.png'
Error: Render error (Invalid argument) cannot save: '/usr/lib/python3.10/site-packages/openshot_qt/blender/blend/explode0075.png'
Time: 00:01.76 (Saving: 00:00.06)
Blender quit
```
The owner and group of /usr/lib/python3.10/site-packages/openshot_qt/blender/blend/ is root/root
After making a 
`sudo chmod 777 /usr/lib/python3.10/site-packages/openshot_qt/blender/blend/`
the issue with the animated titles disappeared, but not sure if a chmod 777 is the real best solution :)

**Comment by ammgws** [comment] 2022-10-29 16:00
@dejanmilo-dev Out of interest, what distro are you using?

EDIT: at first I thought it could be a packaging issue, but I found out some titles actually *do* work. It seems strange that the blender previews are being written to that dir, but I can't find any difference in the blender scripts in this repo. Apparently the output path is meant to be /tmp but some how not being respected by some animated titles?

EDIT2: might be a coincidence, but the only animated titles that dont work for me are the ones that use " ptcache.bake_all" in the script (apart from dissolve, which works)

**Comment by dejanmilo-dev** [comment] 2022-11-01 21:36
> @dejanmilo-dev Out of interest, what distro are you using?

I'm using Manjaro Linux.

**Comment by ammgws** [comment] 2022-12-12 04:58
Works for me now using Openshot 3.0 from Arch Linux repos

**Comment by Colorjet3** [comment] 2026-05-09 12:38
This should be all working in the latest v3.5.1 dev daily build found here:  openshot.org/download/#daily.
