### ISSUE TITLE
Selectable layer mixing algorithms

### ISSUE THREAD

**Issue by mkarg** [OpenShot/openshot-qt#3059] opened 2019-11-01 12:23 UTC
**Describe the new feature:**
OpenShort currently seems to have just *a single* **algorithm to mix layers** into final frames (alpha blending).

Several other picture and video editing software supports *different* mixer algorithms, and lets the user *choose* it *per layer*. The benefit of that is that you can produce **creative effects**, like using a black-white still image on a top layer as a "stencil" on bottom layer, or dynamically change bottom track's colors driven by the top track etc.

**Describe the solution you'd like:**
Allow the user to select the mixer algorithm per layer. Besides the current algorithm (alpha blending), there could be e. g. "Luminance" (which produces pixels having luminance from top layer but color from bottom layer).

**Describe alternatives you have considered:**
* Using third party VideoFX software.
* Let effects read pixels from more than one layer to be able to mix pixels from at least two layers.

**Comment by ferdnyc** [comment] 2019-11-08 06:54
Agreed, it would be nice to have.

I'm going to close this as there's already an issue open for libopenshot, and this would have to be implemented there first. (Some UI to select modes would also be needed in OpenShot, but library support is a prerequisite.) The request can be tracked there.

Duplicate of OpenShot/libopenshot#320

**Closed by ferdnyc** 2019-11-08 06:54 UTC
Labels: duplicate, 💡 enhancement

**Comment by mkarg** [comment] 2019-11-08 12:09
> Agreed, it would be nice to have.
> 
> I'm going to close this as there's already an issue open for libopenshot, and this would have to be implemented there first. (Some UI to select modes would also be needed in OpenShot, but library support is a prerequisite.) The request can be tracked there.
> 
> Duplicate of [OpenShot/libopenshot#320](https://github.com/OpenShot/libopenshot/issues/320)

Oops, sorry for creating the duplicate. :-)

**Comment by ferdnyc** [comment] 2019-11-09 22:12
@mkarg No worries, it's not even in the same _repo_. You could hardly have known!
