### ISSUE TITLE
Video preview hangs for several seconds or dies completely

### ISSUE THREAD

**Issue by acorns123** [OpenShot/openshot-qt#430] opened 2016-12-11 02:49 UTC
While editing a video, the video preview is hanging up for several seconds at a time or breaks completely. The rest of Openshot and the PC itself continues working normally, but I can't see what i'm doing in the preview, obviously. The preview is stuck in this state about 50% of the time, and working about 50% of the time. When it 'breaks' completely then I need to restart Openshot to make it work again, though that's relatively rare.

I'm working with a single 720p MP4 file, about 700MB in size, splitting using Slice All in multiple pieces, removing chunks, dragging with overlap to make transition.

Dell Inspiron (new)
Intel i7-7500u 7th gen 3.5ghz
windows 10 64 bit home edition
8GB ram 2400MHz DDR4
1TB 5400 rpm SATA Drive
AMD Radeon R7 M445 Graphics 4G GDDR5

Installed Openshot 2.1.0 using 64bit installer on your site.

Other than this I love Openshot, however I can't really use it like this.

Just need to get past this issue. :)

**Comment by DylanC** [comment] 2017-08-24 14:20
@acorns123 - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by DylanC** [comment] 2017-08-25 12:44
Duplicate of #427. We can track the issue there instead.

**Closed by DylanC** 2017-08-25 12:44 UTC
Labels: duplicate
