### ISSUE TITLE
Missing thumbnails when resources are reloaded from different source

### ISSUE THREAD

**Issue by cdalexndr** [OpenShot/openshot-qt#2995] opened 2019-09-13 11:03 UTC
When opening the project, if the resources are not available a pop-up appears to select the folder with the required resource.
After all resources have been resolved, the tracks fail to load segment thumbnails. All segmnets are shown with a question mark instead of thumbnail.
Saving the project to a new file and reopening it fixes the image and movie thumbnails, but audio thumbnails remain as question marks (should be a tune symbol image).

Note that playback works correctly even if thumbnails are invalid.

**Comment by mikelacsa** [comment] 2019-09-29 20:09
@cdalexndr Thanks for your input! This will greatly help to improve Openshot.

Can I ask if you have tried to test this using the latest daily build? https://www.openshot.org/download/

**Comment by cdalexndr** [comment] 2019-09-29 21:18
No, only using OpenShot version 2.4.4.

Additional info, after saving and loading, there are still image or movie thumbnails missing that are positioned outside of visible track (have to scroll to the right to see them).

**Comment by mikelacsa** [comment] 2019-10-15 18:36
Got it. Would you be able to help us with this and officially report a bug? Just follow the steps from the link below:
https://www.openshot.org/issues/new/

**Comment by ferdnyc** [comment] 2019-10-15 20:06
@mikelacsa I wouldn't worry, this is a known issue and there's at least one open bug on it. (To understate the situation greatly.) I'll scare one up and close it as a dupe.

**Comment by ferdnyc** [comment] 2019-10-15 20:08
#2310, is the reference we can use for issues with thumbnail loading after project/data file moves or changes.

Closing as duplicate of #2310.

**Closed by ferdnyc** 2019-10-15 20:08 UTC
Labels: :beetle: bug, :question: needs info, interface

**Comment by ferdnyc** [comment] 2019-10-15 20:10
(Hmm, but I can't change the labels from my phone. If you'd be so kind, @mikelacsa?)
