### ISSUE TITLE
Some keyboard Shortcuts Won't Work

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1451] opened 2018-03-30 12:45 UTC
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have tested some Keyboard Shortcuts and some of them won't work like the Split Clip Shortcut

**Comment by peanutbutterandcrackers** [comment] 2018-03-31 01:56
@DylanC - I can confirm. This shortcut does not work for me, either.

**Comment by DylanC** [comment] 2018-03-31 08:32
@peanutbutterandcrackers - I have seen something similar to this on my own program. Could be a Qt issue possibly. Suddenly many of my programs broken keyboard shortcuts started working on newer versions of Qt.

**Comment by MrTertius** [comment] 2018-03-31 20:06
I have a serious question regarding the old issues, are they resolved or not resolved because it makes the amount of issues go up

**Comment by peanutbutterandcrackers** [comment] 2018-04-06 03:40
@MrTertius - You can leave the issues that you have opened, open, until they are resolved. Even if you forget, @DylanC can close them once they are resolved. You do not have to close the issues after we notice them. In fact, it is better not to close any of the issues, *until* they are resolved in the source code itself. Hope that answers your question. :)

**Comment by MrTertius** [comment] 2018-04-06 13:12
Ah ok, because i was starting to think that no on got interested in my new issues that i keep finding in the daily builds

**Comment by peanutbutterandcrackers** [comment] 2018-04-07 12:54
No no. Not at all. These issues are very valuable, @MrTertius. It's just that we have only 2 active developers at the moment and 3 active contributors who have to squirrel their time away to work on OpenShot. Even I myself have to squirrel time away to help other people out here on github. I hope you understand.

**Closed** 2018-07-06 13:17 UTC
Labels: bug
