### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by khaledouf** [OpenShot/openshot-qt#2347] opened 2018-11-10 11:33 UTC
**My Question:**
the app not working in my windows 7 pro 86X not 64X  >> and display this massage (screenshot)

![10-nov-18 1-07-55 pm](https://user-images.githubusercontent.com/44921806/48300863-efb79200-e4ec-11e8-872d-cdf3d6d612ed.png)

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by peanutbutterandcrackers** [comment] 2018-11-27 08:07
Could please try deleting the `.openshot_qt` folder that is in your home directory (along with your 'My Documents' and all)? Deleting that has been known to fix things for a lot of people.

**Comment by peanutbutterandcrackers** [comment] 2018-11-27 18:31
@khaledouf - Could you please try out [this solution](https://github.com/OpenShot/openshot-qt/issues/2388#issuecomment-441957439) and see if that works for you?

**Comment by khaledouf** [comment] 2018-11-27 19:04
[launch.exe.txt](https://github.com/OpenShot/openshot-qt/files/2621487/launch.exe.txt)

**Comment by ferdnyc** [comment] 2018-11-29 16:35
@khaledouf Exactly the same issue as #2367 — there's a file `C:\Windows\System32\zlib1.dll` that some other software installed in the Windows system directory. (It's not part of Windows, and isn't supposed to be there.) That file is interfering with OpenShot being able to start, because it's being used instead of the `C:\Program Files\OpenShot Video Editor\zlib1.dll` that comes with OpenShot.

Deleting  `C:\Windows\System32\zlib1.dll` will allow OpenShot to launch. I can't say how it will affect other software installed on your system, but it won't harm Windows itself.

**Comment by khaledouf** [comment] 2018-11-29 17:37
wow .. it fixed
thank you very much ( ferdnyc ) 
after delet .. zlib1.dll .. now i enjoy openshot vedio editor

# important note #
1- after delete zlib1.dll from system32 .. openshot work .. but with more time to load .. and after use it make hang ..!!
2- so i try to make copy zlib1.dll from openshot and put it in system32 .. and try use app again .. what happened ?
load fast .. work fast .. no more hang .. very very very stable
now i enjoy openshot !!

anyway .. thank you very mush for everyone support me
god bless you

**Comment by ferdnyc** [comment] 2018-11-29 20:36
> 1- after delete zlib1.dll from system32 .. openshot work .. but with more time to load .. and after use it make hang ..!!
> 2- so i try to make copy zlib1.dll from openshot and put it in system32 .. and try use app again .. what happened ?
> load fast .. work fast .. no more hang .. very very very stable
> now i enjoy openshot !!

Hmm, that's very strange. I wouldn't normally expect that to be necessary.

It's _possible_ the slowness would've cleared up with a Windows restart after deleting `zlib1.dll`, without having to copy OpenShot's back in the Windows system space. (Possible something already running on the system was still looking for the deleted file, and slowing things down.)

But, if copying OpenShot's `zlib1.dll` there solved the problem, then whatever works! :+1:  Good tip, thanks.

**Comment by ferdnyc** [comment] 2018-12-02 00:18
I really wish I knew what software was installing (an out-of-date) `zlib1.dll` into `C:\Windows\System32\` on so many people's machines.

If this becomes a big enough problem, we may have to look for radical solutions, like perhaps renaming OpenShot's `zlib1.dll` to something else so that these rogue "system" versions won't override it. Tricky thing is, though, that it's not OpenShot that's linking to `zlib1.dll`, it's Qt. Not sure how we'd go about convincing Qt that it should load the DLL under a different name. 

(I mean, recompiling Qt from scratch would certainly do it, but I don't have the sort of Windows software-development environment that'd be required for that sort of thing... Nor would I be particularly enthused about taking on the task of maintaining what's essentially a fork of Qt for Windows, even if it only deviates from the official builds by one line of source code.)

**Comment by khaledouf** [comment] 2018-12-02 01:40
There may be a difference between the nature of the two files ..
But I just wanted to tell what happened to me as an experiment .. when I first delete the system32 file
Then I took a copy of the openShot with the same name .. and copied it into the system32 file

* I noticed:
1 - to delete the dll file from the system32 file was without any objection from the system of Windows 7 .. This assured me that it is not active files in the system .. Or was the rejection of deletion .. !!

2. So far, there have not been any problems. Especially I use all media and communications on my computer .. Strongly .. There has not been any problem so far.

* Proposals:
Is it possible with the installation openShot .. Deletes the file from Windows and puts it in the same program file .. zlib1.dll !!

* Anyway .. it works without any problems after changing the files .. !!
But openshot works with excellence .. and windows 7 no problem at all .. !!

**Comment by ferdnyc** [comment] 2018-12-02 14:09
> * I noticed:
>   1 - to delete the dll file from the system32 file was without any objection from the system of (Windows 7 32 bit)  .. This assured me that it is not active files in the system .. Or was the rejection of deletion .. !!

Correct, that file is _not_ part of the Windows install and was not put there by any component of Windows itself. Some third-party software stuck it in there(something that's _not_ supposed to be done, but shoddily-written programs or slapped-together installers still unfortunately do it. What would be interesting, from someone who encounters this file, would be to check the creation date of the `zlib1.dll` file and compare it to the install dates of the programs installed on the system. That could give a clue as to exactly what software is responsible for sticking the rogue DLL there. (In which case, we could at least warn people about the possibility of problems caused by the other software's misbehavior.)

> 1. So far, there have not been any problems. Especially I use all media and communications on my computer .. Strongly .. There has not been any problem so far.

Well, having the OpenShot `zlib1.dll` in place of the other one, I would expect that to be the case, since the OpenShot version must be (based on the nature of this problem) a newer version of the DLL than the one you replaced. So, even if software on the computer _is_ using that DLL, the OpenShot version should work equally well for that software. 

I still think it would be an interesting experiment to completely remove `zlib1.dll` from the `System32` directory, **restart Windows**, and see what the fallout is, if any. I'm not surprised that deleting it caused issues with the running system, but a restart would clear up any lingering handles that were open to the DLL, and then you'd be able to find out for real if not having it there actually breaks anything.

It's entirely possible that whatever software installed it there originally has since been corrected, and now has a `zlib1.dll` in its own install directory that it can load — just like OpenShot does. Even if that's the case, though, as long as some `zlib1.dll` is in `C:\Windows\System32\`, it'll override all uses of that DLL across the system.

> * Proposals:
>   Is it possible with the installation openShot .. Deletes the file from Windows and puts it in the same program file .. zlib1.dll !!

That would be compounding misbehavior with further misbehavior. Windows application installers are **not** supposed to muck around with `C:\Windows\System32\` or install their own files in there, because doing so causes problems exactly like this. It would be irresponsible for OpenShot to break that rule _again_ just because some other software previously broke it. And were OpenShot to do so, whatever action it takes could cause unpredictable behavior across the rest of the system, and that would be entirely OpenShot's fault.

**Comment by ferdnyc** [comment] 2019-09-05 02:13
I'm going to close this in favor of the more detailed #2748, for OpenShot 2.4.4.

And also because the Windows installer _does_ now rename — though not delete — `C:\Windows\System32\zlib1.dll` if it finds that file on the system. My personal objections have been noted, but were ultimately overridden. (IOW, I lost that debate.)

**Closed by ferdnyc** 2019-09-05 02:13 UTC
