### ISSUE TITLE
Install and keep separate versions of OpenShot at the same time on Windows with the installers

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#4382] opened 2021-09-02 10:59 UTC
**Describe the new feature:**
During install, an option to have many versions installed. Currently it just overwrites the other one.  
(Maybe it could be done with containers, I don't use them.)

**Describe the solution you'd like:**
Having installed 2.4.4, 2.5.1, 2.6.0 various daily builds etc., available for comparison and testing and for evading the bugs of each of the versions.

**Describe alternatives you have considered:**
The alternative is reinstalling after each test... Or maybe those containers, I don't know.

**Comment by speedytechdev** [comment] 2021-09-04 02:04
Hi @Twenkid , Unfortunately, I don't think this is possible. @JacksonRG Can you confirm this or am I wrong?

**Comment by Twenkid** [comment] 2021-09-04 10:27
What about just portable releases?

**Comment by ferdnyc** [comment] 2021-09-04 22:05
Duplicate of #4152.

**Closed by ferdnyc** 2021-09-04 22:05 UTC
Labels: duplicate, 💡 enhancement

**Comment by ferdnyc** [comment] 2021-09-04 22:18
I just took a look at the "unofficial portable version" mentioned in https://github.com/OpenShot/openshot-qt/issues/4152#issuecomment-900791841 — I'd feel a bit better if their exact packaging process was defined and logged somewhere public (maybe it is, but I'm not seeing it), but it _looks_ like they merely take the official installer build and re-package it for portability. (Actually, _builds_, since the portable app bundles 32-bit and 64-bit installs together, which is crazy wasteful but whatever.)

That's a good thing, as it means the build should be pretty comparable to the official package downloads. I'm tempted to link to the PortableApps distribution page from the README as an alternative download, in fact. No harm in giving people options.
