### ISSUE TITLE
Corrupted double-linked list when exporting video

### ISSUE THREAD

**Issue by TimUx** [OpenShot/openshot-qt#937] opened 2017-09-28 12:24 UTC
**System Details:**
* Operating System / Distro: Ubuntu 17.04 (MATE Desktop)
* OpenShot Version: 2.4.0+0+834+116+201709070431
* _Please attach log files if crash_

[openshot-crash1.txt](https://github.com/OpenShot/openshot-qt/files/1340789/openshot-crash1.txt)
[openshot-crash2.txt](https://github.com/OpenShot/openshot-qt/files/1340790/openshot-crash2.txt)

Everytime, when i start the video export, openshot crashed.

Somtimes at 25%, sometimes 80-90% (depends on Codec and render settings, resolution, ...)

IT doesn't matter, which codec, resolution or other settings I use.

Everytime the same Error: 

`*** Error in `/usr/bin/python3': corrupted double-linked list: 0x00007fb636a0d7d0 ***`

**Comment by TimUx** [comment] 2017-09-29 12:04
I've installed a new, clean Ubuntu Mate 17.04 an tried to export a video again.

No Look, but an other Error, see the log.

[openshot_crash3.txt](https://github.com/OpenShot/openshot-qt/files/1344272/openshot_crash3.txt)

**Comment by TimUx** [comment] 2017-10-02 08:11
I've installed OpenShot on two different PCs with Windows 10 64bit and tried to export a Video of the same projekt.

Same problem, crash of the launcher.exe at most 25%.

So, seems to be an general bug an this software is not usable at this moment.

**Comment by mateuszchmielewski** [comment] 2017-10-02 14:17
**System details**
- Ubuntu 14.04
- Openshot 2.4.0
- Log: [logifle.txt](https://github.com/OpenShot/openshot-qt/files/1349166/openshot_console.txt)

Unfortunately I'm facing exactly the same problem.

**Comment by DylanC** [comment] 2017-10-03 12:27
Just listing out the errors for the devs. Different errors but seems to be the same issue. Both are about a corrupted double-linked list.

17.04 Error
*** Error in `/usr/bin/python3': corrupted double-linked list: 0x00007fb636a0d7d0 ***

14.04 Error
*** Error in `/usr/bin/python3': malloc(): smallbin double linked list corrupted: 0x000000000370e3c0 ***
Caught signal 6 (SIGABRT)

**Comment by TimUx** [comment] 2017-10-21 17:10
Hi,
are there some news for die issue?

At the moment, the tool is useless some hours of work for an project was in vain.

**Comment by TimUx** [comment] 2017-11-10 16:11
Hi,
I've tried the newest daily build hand have now 4GB more of RAM (12GB ), still the same issue.

At 86% openshot crashes with the corrupted double-linked list error.

[crash_log.txt](https://github.com/OpenShot/openshot-qt/files/1461933/crash_log.txt)

**Comment by jonoomph** [comment] 2017-11-10 17:35
Hi! Are you running the AppImage, or the PPA version? I'm very curious if the AppImage would also crash on you.

**Comment by TimUx** [comment] 2017-11-10 17:56
Hi,
I'am using the PPA Version.

**Comment by jonoomph** [comment] 2017-11-10 17:57
Okay. Please try this AppImage: https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-12-g812560b-56-652-x86_64.AppImage. Download it, make it executable, and then run it. It won't install anything, so it's safe to try it out.  Let me know if you can reproduce the crash with it. Thanks!

**Comment by TimUx** [comment] 2017-11-10 18:02
copy that.
i will start a test with the appimage and tell you the result, ...

**Comment by TimUx** [comment] 2017-11-10 19:56
Hi,
openshot still crashes by exporting a video, but seems to be not the Corrupted double-linked list issue.

[openshot_log.txt](https://github.com/OpenShot/openshot-qt/files/1462569/openshot_log.txt)

**Comment by jonoomph** [comment] 2017-11-10 21:03
Interesting! You might try running your PPA version in a debugger, and see what it finds:

```
$ gdb openshot-qt
(gdb) run
```
And then once it crashes, run this command to get the debug trace from all threads:
```
(gdb) thread apply all bt
```

**Comment by TimUx** [comment] 2017-11-10 23:27
Hi,
gdb and ppa openshot does not work.

`Type "apropos word" to search for commands related to "word"...
"/usr/bin/openshot-qt": not in executable format: File format not recognized
(gdb) run
Starting program:  
No executable file specified.
Use the "file" or "exec-file" command.
(gdb) run openshot-qt
Starting program:  openshot-qt
No executable file specified.
Use the "file" or "exec-file" command.
(gdb) file
No executable file now.
No symbol file now.
(gdb) file openshot-qt
"/usr/bin/openshot-qt": not in executable format: File format not recognized
(gdb) exec-file openshot-qt
"/usr/bin/openshot-qt": not in executable format: File format not recognized
(gdb) 
`

**Comment by jonoomph** [comment] 2017-11-10 23:39
You might need to find the installed folder path of openshot-qt. 
```
gdb python3
run /INSTALLED_PATH/scr/launch.py
```

**Comment by TimUx** [comment] 2017-11-10 23:56
So,
i did the gdb with the AppImage and here we are:

` main_window:INFO auto_save_project
*** Error in `/tmp/.mount_3HfevD/usr/bin/launch': malloc(): smallbin double linked list corrupted: 0x00007fff100021a0 ***
======= Backtrace: =========`

Here the whole gdb log:

[openshot_log_1.txt](https://github.com/OpenShot/openshot-qt/files/1463066/openshot_log_1.txt)

**Comment by jonoomph** [comment] 2017-11-11 01:41
Great! Thanks for the debug output!

**Comment by jonoomph** [comment] 2017-11-11 06:47
Can you give this one a quick try: https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-12-g812560b-56-653-x86_64.AppImage

**Comment by TimUx** [comment] 2017-11-11 09:07
Hi,
it crashed again...
[openshot_log_2.txt](https://github.com/OpenShot/openshot-qt/files/1463591/openshot_log_2.txt)

**Comment by TimUx** [comment] 2017-11-11 10:07
Hi,
i did another test, removed some mp3 files, but...

`mp3 @ 0xeff19c0] Header missing
[AudioData @ 0x7fffffff6740] invalid NULL pointer for src[0]
 main_window:INFO auto_save_project
[New Thread 0x7fff0e7fc700 (LWP 6928)]
[New Thread 0x7fff0effd700 (LWP 6929)]
[New Thread 0x7fff0f7fe700 (LWP 6930)]
[New Thread 0x7fff0ffff700 (LWP 6931)]
*** Error in `/tmp/.mount_RPQ3wH/usr/bin/launch': malloc(): smallbin double linked list corrupted: 0x00007fff1a5ff040 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7908b)[0x7ffff723608b]
/lib/x86_64-linux-gnu/libc.so.6(+0x85008)[0x7ffff7242008]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7ffff7243984]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7ffff303eaf8]
/tmp/.mount_RPQ3wH/usr/bin/libQt5Gui.so.5(_ZN10QImageData6createERK5QSizeN6QImage6FormatEi+0x104)[0x7ffff3af79e4]
/tmp/.mount_RPQ3wH/usr/bin/libQt5Gui.so.5(_ZN6QImageC1EiiNS_6FormatE+0x3d)[0x7ffff3af7c4d]
/tmp/.mount_RPQ3wH/usr/bin/libopenshot.so.13(_ZN8openshot5Frame8AddColorEiiSs+0x5f)[0x7fffe11f2137]
/tmp/.mount_RPQ3wH/usr/bin/libopenshot.so.13(_ZN8openshot5Frame8GetImageEv+0x6b)[0x7fffe11f2b51]
/tmp/.mount_RPQ3wH/usr/bin/libopenshot.so.13(_ZN8openshot8Timeline9add_layerESt10shared_ptrINS_5FrameEEPNS_4ClipEllb+0x32a3)[0x7fffe120ff89]
/tmp/.mount_RPQ3wH/usr/bin/libopenshot.so.13(+0x138626)[0x7fffe1219626]
/tmp/.mount_RPQ3wH/usr/bin/libgomp.so.1(+0x834a)[0x7fffdebbe34a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76da)[0x7ffff758b6da]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x5f)[0x7ffff72c5d7f]
`

**Comment by jonoomph** [comment] 2017-11-11 22:36
Can you give me a bit more info:  
1) CPU specs?
2) Export settings (format / codec / profile - fps)
    - Also, can you try some different combinations (framerate + codec), just curious if all break the same
3) Can you try creating a project with just a single image on the timeline (stretched to the same length as your current project), and export that. I'm curious if the source content is affecting the crash.

Thanks, we'll get this figure out =)

**Comment by jonoomph** [comment] 2017-11-12 05:09
Another experimental build to try: https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.0-13-g542f432-56-654-x86_64.AppImage

**Comment by TimUx** [comment] 2017-11-12 08:12
Hi,
here some more informations:

CPU:
cpu family	: 6
model		: 42
model name	: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz


export settings:
bluray
1080p
25 fps
mp4
h264

I've tried different profiles, framrates, codecs an resolutions.
all tests crashed, some earlier, some later.

I will to do a Test-Projekt today and let you know the result.

Reagrds Timo

**Comment by TimUx** [comment] 2017-11-12 09:27
Hi,
with the last build, the export was successful.

**Comment by jonoomph** [comment] 2017-11-12 09:35
Nice! That's great news! The latest build added more protection around the spots in your crash logs, so I'm glad it helped!

**Comment by TimUx** [comment] 2017-11-12 09:37
OK, fine.

Maybe some other guys have also less export Problems now.

I've just one Problem with som Videos of my digicam.
The video is slow and audio is stocking.

i will try to re-encode the source Video and try it again.

Here the video infos:

But some Videos of my digicam are slow and sound is stocking.

{
    "acodec": "ac3",
    "audio_bit_rate": 256000,
    "audio_stream_index": 1,
    "audio_timebase": {
        "den": 90000,
        "num": 1
    },
    "channel_layout": 3,
    "channels": 2,
    "display_ratio": {
        "den": 9,
        "num": 16
    },
    "duration": 19.775999069213867,
    "file_size": "54853632",
    "fps": {
        "den": 1,
        "num": 25
    },
    "has_audio": true,
    "has_single_image": false,
    "has_video": true,
    "height": 1080,
    "id": "BN3RE29WLG",
    "interlaced_frame": false,
    "media_type": "video",
    "path": "/home/timo/Desktop/DiaShow/USA_2017-_0230.MTS",
    "pixel_format": 0,
    "pixel_ratio": {
        "den": 1,
        "num": 1
    },
    "sample_rate": 48000,
    "top_field_first": true,
    "type": "FFmpegReader",
    "vcodec": "h264",
    "video_bit_rate": 22189980,
    "video_length": "491",
    "video_stream_index": 0,
    "video_timebase": {
        "den": 90000,
        "num": 1
    },
    "width": 1920
}

**Comment by jonoomph** [comment] 2017-11-12 09:38
Let's go ahead and close this issue (since the double linked list crash is fixed), and feel free to create new issues as needed. =)

**Comment by TimUx** [comment] 2017-11-12 09:39
Jep, thats OK, ... :-)

Thank you very much.

**Closed by jonoomph** 2017-11-12 09:38 UTC

**Comment by TimUx** [comment] 2017-11-12 14:02
Hi,
i have to reopen this issue. 

I've change some videos in this projekt and the export crashes at 99% wit the double link error.

[libx264 @ 0x64cdb00] kb/s:37695.43
*** Error in `/tmp/.mount_6kcSpz/usr/bin/launch': corrupted double-linked list: 0x00007fffb87ec240 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7908b)[0x7ffff723608b]

[openshot_log_3.txt](https://github.com/OpenShot/openshot-qt/files/1464725/openshot_log_3.txt)
