### ISSUE TITLE
Software Requirement Specification Document

### ISSUE THREAD

**Issue by georgeathan** [OpenShot/openshot-qt#1251] opened 2018-02-05 17:27 UTC
Hello there OpenShot crew!
This is George Athanasiadis, undergraduate Computer Science student in Thessaloniki, Greece.
In the context of a university project concerning open source apps, I would like to contribute a Software Requirement Specification Document (see template here: https://web.cs.dal.ca/~hawkey/3130/srs_template-ieee.doc) for OpenShot. 
Would you care to use it/have it displayed once it is completed? Any response would be greatly appericiated.

Thanks in advance!

**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment] 2018-02-08 08:33
Not sure about that, but I think if you could submit some bug-fixes and stuff, it would be greatly appreciated. Since you're a CS student. Currently, it seems that Mr. Jonathan Thomas is doing all the heavy lifting all by himself.

**Comment by DylanC** [comment] 2018-02-08 08:52
@peanutbutterandcrackers - Yes, Jonathan has to do most of the work regarding the programming. I'm trying to manage the issues but the sheer amount of them is pretty overwhelming. Sadly I don't have time to test much issues and to see can I reproduce them.

I would like to help with the programming side of it but I don't know much Python at all.

**Comment by peanutbutterandcrackers** [comment] 2018-02-09 03:10
I do know some Python, but I don't know where to really start. But I kinda' plan to submit my first patch by the end of 2018, though --- to OpenShot, of course.

Here: http://www.diveintopython.net/ this is a good start for someone who, I presume, already knows programming. Else, this: http://inventwithpython.com/

I try to answer some of the issues so that I can contribute in closing them... doing the least of what I can do, right now. :)

**Comment by DylanC** [comment] 2018-02-09 08:37
@peanutbutterandcrackers - That's great! The more developers on this project, the better. I've been a professional developer for about 4 years and always have been working on hobby projects for even longer.

I started learning Python at around the 2.5/2.6 versions. However, then Python 3 came out and I didn't feel like starting all over again. I've experience with many programming languages but definitely not Python. Its on my TODO list to learn it. (maybe during 2018)

Helping to test issues and confirm bugs is the least I can do for now. :)

**Comment by peanutbutterandcrackers** [comment] 2018-02-09 10:18
@DylanC - I'm glad that at least we have you, as a moderator. Or else, it gets quite lonely here on OpenShot's github repo. But Mr. Thomas seems to be on fire these days. Adding new video effects and all. 😆 

Thank you for your work, too. :)

**Comment by DylanC** [comment] 2018-03-20 15:30
@georgeathan - I reckon your best bet would be to contact Jonathan directly about this.

**Closed by DylanC** 2018-03-20 15:30 UTC
Labels: question
