### ISSUE TITLE
openshot-qt doesn't start on Debian with i3wm.

### ISSUE THREAD

**Issue by MaBeuLux88** [OpenShot/openshot-qt#2958] opened 2019-08-30 18:53 UTC
**Problem**
When I start the process, I don't even get a window. I get a stack trace directly. It's a clean & fresh install.

**System details**
Debian Testing running i3wm.
Linux hafx 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
i3wm: i3 version 4.16.1 (2019-01-27)
openshot-qt --version:
Compiled translation resources missing!
Loading translations from: /usr/lib/python3/dist-packages/openshot_qt/language
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
OpenShot version 2.4.3

**Logs**
[https://pastebin.com/ffUQS6tp](https://pastebin.com/ffUQS6tp)

**Comment by ferdnyc** [comment] 2019-08-31 00:24
Effectively a dupe of #2953, I guess... I don't understand this sudden rash of Debian users who've just installed their distro's 11-month-old, outdated OpenShot package. My Debian knowledge is very limited, but isn't there some sort of package-update process that should've made 2.4.4 available in place of 2.4.3? (That's an honest question, I don't know much about how such things work when it comes to Debian specifically.)

**Comment by MaBeuLux88** [comment] 2019-08-31 00:43
https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html

I just checked debian stable, testing and unstable repos and they all point to the same version: 

```
# apt-cache policy openshot
openshot:
  Installed: (none)
  Candidate: 2.4.3+dfsg1-1
  Version table:
     2.4.3+dfsg1-1 500
        500 http://deb.debian.org/debian stable/main amd64 Packages
```

I guess you have a way to package openshot as a .deb package somewhere and you need to push your new releases to debian unstable so they can be promoted at some point to testing then stable at some point. I can't imagine that Debian would come an grab new versions for each project they package. They can't possibly track every project out there so I would assume it's the editor's job to push new packages to Debian repos when they consider a version production ready.

**Comment by ferdnyc** [comment] 2019-08-31 00:43
@MaBeuLux88 \*nod\* I've emailed @jonoomph asking for more info on our Debian releasing situation.

**Comment by mikelacsa** [comment] 2019-10-08 21:53
@MaBeuLux88 are you still experiencing this problem with the latest daily build?

**Comment by MaBeuLux88** [comment] 2019-10-08 23:19
Humm I have a problem installing the daily build on my laptop: 

```sh
root@xps:~# add-apt-repository ppa:openshot.developers/libopenshot-daily
 This PPA contains the most recent source code from libopenshot (OpenShot Video Library). These packages are only intended for testers of OpenShot 2.0, as the source code can be highly unstable during active development of libopenshot.

If you are looking for daily builds of OpenShot 1.x, please go here: https://code.launchpad.net/~openshot.developers/+archive/daily
 More info: https://launchpad.net/~openshot.developers/+archive/ubuntu/libopenshot-daily
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmplt8izzhv/pubring.gpg' created
gpg: /tmp/tmplt8izzhv/trustdb.gpg: trustdb created
gpg: key 52165BD6B9BA26FA: public key "Launchpad OpenShot Development PPA" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
```

Then : 
```sh
root@xps:/etc/apt/sources.list.d# apt-get update 
Hit:1 http://ftp.fr.debian.org/debian testing InRelease
Ign:2 http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu eoan InRelease                                                                                                                        
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                      
Hit:4 http://security.debian.org testing-security InRelease                                                                                                                                                       
Hit:5 http://download.virtualbox.org/virtualbox/debian buster InRelease                                                                                                                                           
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                                                                                                                                                        
Hit:7 http://ftp.fr.debian.org/debian testing-updates InRelease                                                                                                                                                   
Err:8 http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu eoan Release                                                                                   
  404  Not Found [IP: 91.189.95.83 80]
Hit:9 https://download.docker.com/linux/debian buster InRelease                                                                                                            
Hit:12 https://repo.nordvpn.com/deb/nordvpn/debian stable InRelease                                                            
Hit:11 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                      
Hit:13 https://repo.skype.com/deb stable InRelease                                            
Hit:14 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/openshot.developers/libopenshot-daily/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Did I do something wrong?
I followed the instructions in here: https://www.openshot.org/fr/ppa/

Just for the reference, I'm still pointing to Debian Testing.
```sh
root@xps:/etc/apt# cat sources.list
deb http://ftp.fr.debian.org/debian/ testing main contrib non-free
deb http://security.debian.org/ testing-security main contrib non-free
deb http://ftp.fr.debian.org/debian/ testing-updates main contrib non-free
```

**Comment by ferdnyc** [comment] 2019-10-09 02:33
@MaBeuLux88 Sorry for the misunderstanding, that's not the Daily Build @mikelacsa was referring to. The OpenShot PPA is in a... questionable state, lately, seems like.

The AppImage builds at https://openshot.org/downloads (click on "Daily Build" under the download link) will let you test the latest OpenShot builds independent of distribution packaging and other issues.

**Comment by ferdnyc** [comment] 2019-10-09 02:34
Whoops, sorry, typo. https://openshot.org/download/

**Comment by MaBeuLux88** [comment] 2019-10-09 02:50
Works for me.
I noticed a few bugs and warnings in the logs in the shell but it seems to work fine. At least it starts and I could import and play a video.

Here are the logs if you want to track the "bugs" in the logs. Let me know if you need anything else :+1:.

https://pastebin.com/xNFWr1P0

**Comment by ferdnyc** [comment] 2019-10-09 05:37
@MaBeuLux88 Thanks for the update, and the logs!

Most of what's going on there is business as usual... 

* the fontconfig noise is a known issue and harmless, it's due to the outdated version of the library we're packaging in the AppImages. That won't be a problem anymore if #3012 gets merged.

* The JavaScript call failures are handled automatically by `eval_js()`, and #2982 was already merged to make those less severe — it was supposed to have been included in that build, in fact, but unfortunately the update process for Daily Builds broke down recently and the builds are being generated without the past two weeks' worth of OpenShot commits. Still waiting on a fix for that.

* The keyPressEvent logging... that really needs to come out of the logs anyway, it's just pointless noise. I'll put together a PR to just remove those messages. Out of curiosity, though, do you know _what_ key it was that caused those odd messages to be logged? Were they actually logged in response to a genuine keypress, or was something else triggering OpenShot's keyboard-input handler?

   Regardless, they also fall under the "annoying but harmless" heading.

I'm going to close this as not an issue with the AppImage builds, then, since the PPA is its own thing really. Whatever's going on with that is sort of secondary, as long as users have the option to use a working AppImage build instead. Thanks again!

**Closed by ferdnyc** 2019-10-09 05:37 UTC
Labels: :beetle: bug

**Comment by MaBeuLux88** [comment] 2019-10-15 17:29
> The keyPressEvent logging... that really needs to come out of the logs anyway, it's just pointless noise. I'll put together a PR to just remove those messages. Out of curiosity, though, do you know what key it was that caused those odd messages to be logged? Were they actually logged in response to a genuine keypress, or was something else triggering OpenShot's keyboard-input handler?

I have no idea, sorry :-(. I just remember that I imported a random video and that's about it. It should not be very complicated to reproduce as I'm a complete novice so I didn't dig some complexe feature or when very far in the menus.

**Comment by MaBeuLux88** [comment] 2019-10-15 17:29
Thanks again for your help & time. I hope this will be available in Debian Testing soon then :+1:.

**Comment by ferdnyc** [comment] 2019-10-15 22:49
> I have no idea, sorry :-(.

Totally understandable, that's no problem at all. Thanks for the update!
