### ISSUE TITLE
OpenShot crashes when using the preview feature.

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#3968] opened 2021-01-15 04:21 UTC
After downloading the latest daily build version (January 13, 2021, 304 p.m. / 64-bit) I discovered that when I preview a file (video or audio), I am unable to close that window.  Clicking on the Red X to close the window causes the "Not Responding" message to be displayed and it just sits there.  After a few more times of clicking on the Red X it Windows displays the program is no longer responding and if I should wait for it
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5818340/openshot-qt.log)

 or close the program.  I've waited as long as a minute without a response and then forced the OpenShot program to close.  This is NOT happening in the production version (2.5.1).

I am unable to upload the libopenshot.log as a single file since github limits the size to 100MB.  So instead, I have split the file into multiples as you can see.
[libopenshotlogaa.log](https://github.com/OpenShot/openshot-qt/files/5818381/libopenshotlogaa.log)
[libopenshotlogab.log](https://github.com/OpenShot/openshot-qt/files/5818382/libopenshotlogab.log)
[libopenshotlogac.log](https://github.com/OpenShot/openshot-qt/files/5818383/libopenshotlogac.log)
[libopenshotlogad.log](https://github.com/OpenShot/openshot-qt/files/5818387/libopenshotlogad.log)
[libopenshotlogae.log](https://github.com/OpenShot/openshot-qt/files/5818389/libopenshotlogae.log)
[libopenshotlogaf.log](https://github.com/OpenShot/openshot-qt/files/5818390/libopenshotlogaf.log)
[libopenshotlogag.log](https://github.com/OpenShot/openshot-qt/files/5818391/libopenshotlogag.log)
[libopenshotlogah.log](https://github.com/OpenShot/openshot-qt/files/5818393/libopenshotlogah.log)
[libopenshotlogai.log](https://github.com/OpenShot/openshot-qt/files/5818395/libopenshotlogai.log)
[libopenshotlogaj.log](https://github.com/OpenShot/openshot-qt/files/5818396/libopenshotlogaj.log)
[libopenshotlogak.log](https://github.com/OpenShot/openshot-qt/files/5818397/libopenshotlogak.log)

Please let me know if I can provide additional information.  This issue is consistently repeatable.

Thank you,
Raffi

.  I am running in Windows 10 with the latest patches.

**Comment by Colorjet3** [comment] 2021-07-14 20:13
I am currently running build # 7793 and this issue seems to have been resolved.

**Comment by DanPinGF** [comment] 2021-10-11 00:15
Duplicate of #1197 - This actually has been a long-term issue. If you happen to use 'Time' (track speed) or change program settings (#4407) in all versions since 2.4.1, you're in tough luck; the problem has to do with a badly-written 'C Runtime' module (MSVCRT.DLL) which will trigger a crash if 1) the 'Time' function is applied at a rate higher than 'Normal [1x]', or 2) playing back a pre-existing project with OpenShot-wise settings that are also applicable to the projects themselves, which will retain prior settings if altered. Replacing the faulty module won't help.

If you're using 2.6.0 or higher, you'll get a similar but otherwise dangerous crash if you apply the 'Blur' effect with very high values, as it induces heap corruption for the most part which can be particularly insecure. (See #4202.)

**Comment by Colorjet3** [comment] 2022-02-18 20:28
This has long been resolved since build #7793 and currently not an issue in DEV Build #9122 either.

**Closed** 2022-02-18 20:28 UTC
Labels: :lady_beetle: bug
