### ISSUE TITLE
"cx_freeze: Python error in main script"

### ISSUE THREAD

**Issue by Djmixpako** [OpenShot/openshot-qt#1291] opened 2018-02-20 02:52 UTC
![error](https://user-images.githubusercontent.com/36652370/36405486-02b019b6-15bf-11e8-8125-83f56551a853.jpg)

 win10
OpenShot Version: 2.4.1

Good night I had the program openshot working well and I had to turn off my PC to force when I turned on the PC I wanted to open the program of openshot and I could not execute it I left a box with the following "cx_freeze: Python error in main script" I install it I install again and the same thing always happens !!! Is there a single option? I read that error was for damage in the libraries that had to be modified! I'm waiting for your help

**Comment by peanutbutterandcrackers** [comment] 2018-02-20 05:03
Could you please try this solution: https://github.com/OpenShot/openshot-qt/issues/1035#issuecomment-366859682 (or follow through the solutions in the thread) and see if that works? Hope that helps! :)

**Comment by DylanC** [comment] 2018-03-12 11:39
Closing this question as answered.

**Closed by DylanC** 2018-03-12 11:39 UTC
Labels: question

**Comment by peanutbutterandcrackers** [comment] 2018-03-12 11:51
Please do look forward to v2.4.2. This issue has been put on the list of the 'critical bugs to be fixed' for the release. OpenShot should finally work quite well on Windows Machines with v2.4.2. Please, do however continue to support OpenShot. Perhaps test the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) if you have the time and report the issues as you encounter them. Thanks!

**Comment by tybuch** [comment] 2020-09-13 10:39
How can we support a program that will not start and we cannot use. That is stupid. The majority of users get the "cx_Freeze Python error in main script" error message eventually. Even with a thorough uninstall, registry clean and manual removal of the ".openshot_qt" folder in the User folder the issue is chronic and permanent. I downloaded OpenShot on another laptop. Copied the OpenShot folder in Program Files onto a computer stick, put it into my main laptop, then clicked the "openshot-qt.exe" file - OpenShot opens. 

If I copy the folder onto the laptop and try to open it, I still get the cr_Freeze error.

I will have to stay with the shonky fix-it I have. Not much good me updating to a newer version when it comes out, I will still get the same error message..

Your coders should put the coffee cup down and fix something that is caused by your inability to effectively code.

I think you don't know how to fix it. Why don't you get someone outside of your "good ol' boys" group who knows what they are doing? Get a real professional. You are amateurs.

**Comment by DylanC** [comment] 2020-09-15 08:36
@tybuch - Feel free to fix it or hire a "real professional" for the project. :+1:
