### ISSUE TITLE
Transitions randomly not work in openshot 2.2.0

### ISSUE THREAD

**Issue by charrety** [OpenShot/openshot-qt#442] opened 2016-12-25 17:01 UTC
Hi. When i apply transitions, preview works. If i save the project, and i reopen it, previews don't work, but some transitions works and others not.

OS : linux mint 18
Ram : 16 Go
CPU : amd fx 6350
GPU : Nvidia GTX 960
I use proprietary drivers for video

**Comment by jonoomph** [comment] 2016-12-28 20:39
Hmmm, this looks really bad. I think it has something to do with saving a project, and a collision with the auto-save feature (which creates a backup.osp project). I'll see if I can figure this one quickly, so I can make a new release asap.

**Comment by charrety** [comment] 2016-12-29 13:19
Thank you for your reply. I don't use autosave.

**Comment by DylanC** [comment] 2017-09-18 13:10
Could not reproduce this issue on v2.4. Closing for now.

**Closed by DylanC** 2017-09-18 13:10 UTC
