### ISSUE TITLE
Openshot 2.0.7 fails to open on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by hyuce** [OpenShot/openshot-qt#238] opened 2016-07-07 15:25 UTC
When I start that OpenShot-2.0.7.AppImage
on OpenSUSE Tumbleweed, I see same error in the bottom line.

> /tmp/.mount_qxJwlj/usr/bin/openshot-qt.wrapper
> 
> (zenity:20652): Gtk-WARNING **: Could not find the icon 'dialog-question-ltr'. The 'hicolor' theme
> was not found either, perhaps you need to install it.
> You can get a copy from:
>   http://icon-theme.freedesktop.org/releases
> 
> (zenity:20652): Gtk-WARNING *_: Could not load a pixbuf from /org/gtk/libgtk/icons/48x48/status/image-missing.png.
> This may indicate that pixbuf loaders or the mime database could not be found.
> *_
> Gtk:ERROR:gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
> ./bin//openshot-qt.wrapper: line 68: 20652 Aborted                 (core dumped) LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT"
> Loaded modules from current directory: /tmp/.mount_qxJwlj/usr/bin
> Segmentation fault (core dumped)

**Comment by ankitpati** [comment] 2017-02-28 16:29
Dupe of #240.

Closing as fixed. Please reopen if necessary.

**Closed by ankitpati** 2017-02-28 16:29 UTC
