### ISSUE TITLE
add a "Close gap" function

### ISSUE THREAD

**Issue by PontiacCZ** [OpenShot/openshot-qt#3245] opened 2020-02-24 17:25 UTC
I like to add all clips to the timeline and then cut out portions I do not want to have there. I guess a lot of people does it like this. Good enough for simple home video. :)

When I make a clip on the timeline shorter, a gap is created. I sure can select all subsequent clips and move them to the left but that can be a lot of work (zoom out, select everything which might be tens of clips, do not omit anything, zoom in and finally shift the clips to close the gap). 

Why not right click the gap and choose "Close gap" from a context menu. It would move all subsequent clips in **all tracks** (so e.g. added audio does not get desynchronised)

![image](https://user-images.githubusercontent.com/9153595/75175296-5c7e8c00-5732-11ea-8715-af6e205fc822.png)

**Comment by ferdnyc** [comment] 2020-03-08 02:34
Duplicate of #3057 #2808

**Closed by ferdnyc** 2020-03-08 02:34 UTC
Labels: 💡 enhancement

**Comment by ghost** [comment] 2023-01-08 02:32
@ferdnyc, this wasn't a duplicate ticket and would be good to have re-opened. This ticket is about automatically eliminating gaps with a single command. Consider:

![openshot-14](https://user-images.githubusercontent.com/2131950/211177988-610a76a9-c0ff-4976-b8b3-b536e6a9e98d.png)

How do you remove all those gaps all at once? That is, how do you collapse the gaps such that all the clips are contiguously connected?

The other tickets were more about snapping and magnets and semi-automatic removal of gaps.

**Comment by Colorjet3** [comment] 2023-01-08 02:37
Thank you @DaveJarvis for your input.  I have added your comments to an existing enhancement request:  https://trello.com/c/wly7VcIS/2-snap-together-button

**Comment by ferdnyc** [comment] 2023-01-08 09:49
@DaveJarvis I'm not really involved here anymore, but if you read my comment https://github.com/OpenShot/openshot-qt/issues/3057#issuecomment-548653781, that aspect was part of the #3507 suggestions. (And was the whole reason I originally left #3507 open, despite it being itself a partial duplicate of #2808.)

I don't see anything in the original request here that wasn't also suggested in #3507. Which is closed because it Stale'd out of existence. A fate which would have befallen this issue as well, even if I hadn't closed it.

**Comment by larryhardin** [comment] 2024-05-13 18:05
This feature is really needed, even if it breaks the undo-ability of the merge and also takes a moment. When if you have a single frame to cut, this is extremely difficult to accomplish. 
Just merge the clips into a new track and then replace existing track with new one.

**Comment by Colorjet3** [comment] 2024-05-13 19:26
This feature is in the queue and has been approved by the lead developer.  There is much work that is needed on the UI for this feature to work, so that is currently taking priority and is in-progress (no ETA).

Here is the link to the [ticket](https://trello.com/c/tyVbvi59/112-eliminating-blank-empty-spaces-in-between-clips?search_id=ff742984-72cf-4966-891a-25e7c37a1c16)  If you can't see it directly with the link then filter on card #112 (or the title which has "eliminating blank/empty" in it).

**Comment by Colorjet3** [comment] 2024-10-15 00:33
Hello @PontiacCZ Remove "Gap" feature is now in the latest dev daily build.  Go to Openshot.org/download/#daily and download the latest.

Two function:
1.  Right click on a Gap and you will see the option "Remove Gap".  This will delete the gap and shift all clips to the right of it and snap it with the clip on its left or bring it to position 0:00.
2.  Right click on the Track label (i.e., Track 5) and you will see the option "Remove All Gaps".  This will delete all existing gaps on that track only and shift everything to the left snapped together.

At this time, you can not do this on multiple tracks.
