### ISSUE TITLE
fast forward don't work

### ISSUE THREAD

**Issue by jordigrau83** [OpenShot/openshot-qt#686] opened 2017-05-28 14:32 UTC
i add a clip and set the time to 8x and it renders ok on preview but the final output is not rendered

**Comment by dsnettleton** [comment] 2017-06-02 03:55
This bug effects me too. To be clear, using the Time function on a video clip shows the clip properly sped up in the preview window, but the clip runs at normal speed in the rendered (exported) file. The clips in question are .mkv files, and have been trimmed a bit at the ends; I'm not sure if that makes a difference or not. I'm running openshot-qt on Ubuntu 17.04.
I would consider this bug to be high priority, since the "Speed Up" feature is completely useless until it is resolved.

**Comment by reddn** [comment] 2017-06-16 04:07
Dup of #588 All playback speed related functions do not work on export.

**Comment by tbrandysky** [comment] 2017-07-17 15:02
I have the very same problem DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"

Openshot 2.3.4

**Comment by reddn** [comment] 2017-07-17 16:05
I did donate because the UI was great, and seemed he fixed the issues
pretty quickly.  Unfortunately this is not the case with the time shifting
feature that does not work.

**Comment by DylanC** [comment] 2017-11-14 10:57
Confirmed as fixed in #588

**Closed by DylanC** 2017-11-14 10:57 UTC
Labels: duplicate
