### ISSUE TITLE
OpenShot 2.2.0 opens only sometimes on Windows 10

### ISSUE THREAD

**Issue by ktecho** [OpenShot/openshot-qt#549] opened 2017-03-24 11:01 UTC
**System Details:**
* Operating System / Distro: Windows 10 latest updates
* OpenShot Version: 2.2.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
50% times I try to open OpenShot, it doesn't start. If I see Windows Task Manager I can see a new process "launch.exe". Sometimes I try to open it again, so i have 2 "launch.exe" processes. Then I try a third time and now I have 3 "launch.exe" processes. The fourth time OpenShot opens, leaving 3 stale "launch.exe" processes even when I close OpenShot.

**Comment by ankitpati** [comment] 2017-03-25 06:08
I have faced similar issues with other Windows applications. I have been able to resolve some of these issues by killing `explorer.exe` from the Task Manager, and restarting it.

Can you please try the same, and let us know if that works? When OpenShot does not open, and you can see a single instance of `launch.exe` in the Task Manager, try killing and restarting `explorer.exe`.

**Comment by ktecho** [comment] 2017-03-26 11:52
I've never ever seen that behaviour in any other app, and definitely it doesn't happen in my computer with other apps. Anyways, I think it's a bit of overkill to have to kill explorer.exe to make it work. It's definitely an OpenShot problem.

**Comment by ankitpati** [comment] 2017-03-26 12:19
I agree that it is an OpenShot problem, but can you please perform the steps so we know if it is indeed the problem that I am suspecting, or something else entirely?

**Comment by ktecho** [comment] 2017-03-26 16:39
Ok, I understand.

I've just tested what you told me. After killing and starting explorer.exe again, sometimes it opens flawlessly, other times it doesn't open.

**Comment by ankitpati** [comment] 2017-03-26 16:43
Thank you for the cooperation. We hope to fix this bug soon.

**Comment by jebeld17** [comment] 2017-03-27 14:57
Have you tried clearing your user data for Openshot? Open a command prompt as admin and type
`rmdir c:\users\<username>\.openshot_qt /s`

I had the exact same problem and this did the fix. I found out if the program either crashed in the past or was closed out incorrectly, some of your previous session's data would stay in there as corrupted fragments unreadable by the program upon opening it.

**Comment by ktecho** [comment] 2017-03-27 17:45
@ankitpati Thanks a lot!

@jebeld17 I just tried that and it didn't work. It opens 1 in each 3 times aprox.

**Comment by jebeld17** [comment] 2017-03-28 00:01
Uninstall the app using a bulk uninstallation program, such as Bulk Crap Uninstaller (http://klocmansoftware.weebly.com) and have it run a Leftovers Scan (and cleanup) afterwords.

Finish off the process by going back into CMD 
'rmdir c:\users\<username>\.openshot_qt /s'

Reboot, reinstall, reboot once more.

Hopefully the OpenShot team will be able to figure out what's the cause of the issue and I hope you don't have this problem again.

**Comment by jebeld17** [comment] 2017-03-28 00:02
^apologies, the mobile site may not have formatted my text correctly.

**Comment by ktecho** [comment] 2017-03-28 17:54
@jebeld17  Done all that steps. It still fails to open sometimes.

**Comment by ktecho** [comment] 2017-06-09 10:01
It seems to be fixed in OpenShot v2.3.4. I've opened and closed OpenShot 30 or 40 times and all the times it worked flawlessly.

What are your experiences? Can we close this issue?

**Comment by ankitpati** [comment] 2017-06-09 14:51
@ktecho Thank you for the report. Closing as fixed.

**Closed by ankitpati** 2017-06-09 14:51 UTC
