### ISSUE TITLE
Win10 86_64 Openshot 2.4.2-rc1 - Silently crashes after starting an export

### ISSUE THREAD

**Issue by cons0l3** [OpenShot/openshot-qt#1648] opened 2018-06-04 12:12 UTC
# Describe the bug

When exporting a project with default settings after a fresh install, after configuring and starting the export silently crashes (the openshot-qt launcher quits.

# System Details (please complete the following information):
- Windows 10, Build 17134.81
- OpenShot Version 2.4.1, 2.4.2-rc1

# To Reproduce

1. Open new project and add a clip (MOV)
1. Export button
1. leave Export Settings at default (does not matter, I have tried various different settings)
1. Start Export (tried different file and folder names and locations)
1. Export crashes silently.
1. Export produces an empty mp4 file.

# Expected behavior
Export of project works.

# Screenshots
not applicable, because of silent crash.

# Logs
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2068118/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2068119/libopenshot.log)

# Environment

- ImageMagick is installed an in path

λ magick -version
Version: ImageMagick 7.0.7-22 Q16 x64 2018-01-22 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 Im

ageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype gslib jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib

- VLC 3.0.3 is install

**Comment by ferdnyc** [comment] 2018-06-05 09:48
Eep. The contents of that `libopenshot.log` file are:

```
------------------------------------------
libopenshot logging: Mon Jun 04 13:53:01 2018
------------------------------------------
---- Unhandled Exception: Stack Trace ----
_C_specific_handler            7ffea9337bc0                            
_chkstk                        7ffeaaa7ecb0                            
RtlWalkFrameChain              7ffeaa9e5890                            
KiUserExceptionDispatcher      7ffeaaa7dcd0                            
ZN8openshot12FFmpegWriter10WriteFrameESt10shared_ptrINS_5FrameEE a6a1020                                 
PyInit__openshot               712666b0                                
PyCFunction_Call               69c10890                                
PyEval_EvalFrameDefault        69c81880                                
PyEval_EvalFrame               69c801f0                                
PyEval_EvalFrame               69c801f0                                
PyEval_EvalFrame               69c801f0                                
PyEval_EvalFrameDefault        69c81880                                
PyEval_EvalFrame               69c801f0                                
PyFunction_FastCallDict        69c88a00                                
PyObject_FastCallDict          69bcb350                                
PyObject_Call_Prepend          69bcb5e0                                
PyObject_Call                  69bcb220                                
PyInit_QtCore                  6f21e450                                
PyInit_QtCore                  6f21e450                                
PyInit_QtCore                  6f21e450                                
PyInit_QtCore                  6f21e450                                
PyInit_QtCore                  6f21e450                                
ZN11QMetaObject8activateEP7QObjectiiPPv 377fe20                                 
ZNK16QDialogButtonBox6buttonENS_14StandardButtonE 66372340                                
ZN16QDialogButtonBox18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv 663736e0                                
ZN11QMetaObject8activateEP7QObjectiiPPv 377fe20                                 
ZN15QAbstractButton7toggledEb  662e67b0                                
ZN15QAbstractButton11setIconSizeERK5QSize 662e7780                                
ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent 662e7ef0                                
???                           
ZN7QWidget5eventEP6QEvent      66244a80                                
???                           
ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent 66207c30                                
ZN12QApplication6notifyEP7QObjectP6QEvent 6620ec60                                
???                           
ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent 37551d0                                 
ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb 6620e1d0                                
ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv 66256d30                                
ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv 66256d30                                
ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent 66207c30                                
ZN12QApplication6notifyEP7QObjectP6QEvent 6620ec60                                
???                           
ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent 37551d0                                 
ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE 667b9600                                
ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE 667bb680                                
ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE 66791900                                
ZN28QEventDispatcherWin32Private14sendTimerEventEi 37ad830                                 
CallWindowProcW                7ffea9cd6800                            
DispatchMessageW               7ffea9cd64c0                            
ZN21QEventDispatcherWin3213processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE 37accf0                                 
qt_plugin_instance             6dd2a930                                
ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE 3753b20                                 
ZN7QDialog4execEv              663c6b20                                
???                           
PyCFunction_FastCallDict       69c10630                                
PyEval_EvalFrame               69c801f0                                
PyEval_EvalFrameDefault        69c81880                                
PyEval_EvalFrame               69c801f0                                
PyFunction_FastCallDict        69c88a00                                
PyObject_FastCallDict          69bcb350                                
---- End of Stack Trace ----
```

So, that's... not _great_. 

Also, I notice that the last line of `openshot-qt.log` is:

```
      export:INFO C:/Users/carst/OneDrive/Desktop/marokko/Ausgabe\Marokko in spanien.mp4
```

It may be nothing, but it's unusual to see mixed forward slashes and backslashes in a path like that.

You said the export _did_ create an empty file, though, @cons0l3 ? Was that file's path `C:\Users\carst\OneDrive\Desktop\marokko\Ausgabe\Marokko in spanien.mp4`? (If so, then I'm wrong and it probably isn't meaningful.)

**Comment by cons0l3** [comment] 2018-06-05 10:19
Hi @ferdnyc,
the file was created at the correct place, but hat zero length. Regarding the backslashes, here the screenshot of the "Export Video UI":

![image](https://user-images.githubusercontent.com/1457252/40970332-91396cde-68ba-11e8-87d1-c91c42da98ff.png)

Cheers
Carsten

**Comment by cons0l3** [comment] 2018-06-05 10:21
sorry, did not mean to close the bug!

**Comment by swwe** [comment] 2018-06-05 18:58
same problem here, y had created a new issue window for my case but is the same that have this user, but here it is more descriptive, i wait for a new dayly update or something, thanks

**Comment by ferdnyc** [comment] 2018-06-05 19:43
> the file was created at the correct place, but hat zero length. 
Gotcha, then it's probably nothing, thanks.

I was going to ask if either reporter had previously tried 2.4.2-rc1, and whether it worked for them (meaning the issue was something that changed for rc2)... but then I noticed, @cons0l3 your original report says that this ALSO happened with 2.4.1, is that correct? If so, any chance you could capture a `libopenshot.log` with that version, to see if you get a similar stack trace with the crash?

If this is a long-standing issue (in terms of OpenShot code) that goes all the way back to the previous release, it may be a more fundamental problem than I'd expected.

**Comment by swwe** [comment] 2018-06-05 19:48
i had uninstall openshot and instal the 2.4.2 and the problem is still there

**Comment by jonoomph** [comment] 2018-06-06 10:35
Can you turn on **debug mode** in the Preferences, close OpenShot, delete your 2 log files, and then re-launch OpenShot and trigger the crash again?  Thanks!

**Comment by ferdnyc** [comment] 2018-06-06 10:49
@swwe : Detailed log-collection instructions: [CONTRIBUTING.md](/OpenShot/openshot-qt/blob/master/CONTRIBUTING.md)

**Comment by swwe** [comment] 2018-06-06 17:29
Here they are

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2077452/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2077453/openshot-qt.log)

**Comment by cons0l3** [comment] 2018-06-06 18:59
Hi,

I have moved the source video to c:\temp and the export is directed to c:\temp\test.mp4. The attached logs are in debug mode. 
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2077756/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2077757/openshot-qt.log)

I can also confirm the error to be in 2.4.1. For debugging purposes I upgraded to 2.4.2-rc1 as requested by the issue-template.

If I do not add a file to the timeline, the export produces a file of size 2.404 bytes. Which starts in VLC or media player without error, of course without content either. The later file seems to be completely valid, but empty. And that is expected. Conclusion: Writing a file to c:\temp works.

**Comment by ferdnyc** [comment] 2018-06-07 00:11
Hmmm. @cons0l3 with yours it looks like libopenshot is hitting problems when it tries to process the first audio packet.

@jonoomph is the expert (and developer of OpenShot), but my suggestion would be to try this:

1. Set your project up same as before. 
1. Open Export, and choose your profile/target/etc in the Simple tab, again same as before.
1. Change to the Advanced tab, and open the "Audio Settings" panel.
1. Manually edit "Sample Rate" from the default `44100` to `48000`. (You can leave everything else alone, don't worry if some of the other parameters don't match my screenshot.)
   ![screenshot from 2018-06-06 20-03-52](https://user-images.githubusercontent.com/538020/41071440-aeeedab4-69c5-11e8-81f9-94a5af1bf63e.png)
1. Export the video.

A sample rate of 48000 matches your input video, so the audio won't need to be resampled for export. I'm just curious if the resampler could be the part that's crashing.

**Comment by swwe** [comment] 2018-06-07 02:41
@ferdnyc the only thing i change on the advanced exporting configuration on all my videos is the video bitrate, i had never change nothing on the audio settings, still i would try putting the 48000 sample rate and i will tell you what happened, give me 5 minutes (im from argentina by the way, so sorry if my english is not so good)

**Comment by swwe** [comment] 2018-06-07 03:01
@ferdnyc Well while i was writting the program had "crashed" again, but the exporting procces has take like 4 minutes for closing, i dont understand nothing, i attach the files again
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2078791/openshot-qt.log)

**Comment by swwe** [comment] 2018-06-07 03:02
the web dont let me upload the another file, it have 83 mb

**Comment by ferdnyc** [comment] 2018-06-07 05:45
> Well while i was writting the program had "crashed" again, but the exporting procces has take like 4 minutes for closing, i dont understand nothing, i attach the files again

Interesting, so it sounds like it got a _lot_ farther, then? (The export was crashing right at the start before, correct?)

> the web dont let me upload the another file, it have 83 mb

Yeah, that's pretty big. We probably only _really_ need to see a bunch of lines at the start and the end, everything in the middle will just be the export progress. But we can probably come up with somewhere for you to upload the whole thing.

**Comment by swwe** [comment] 2018-06-07 14:43
yes (before the export was "crashing" like 10 second after starting, not at the start but almost, now like 4 minutes after), any recomendation for uploading the file? i would attach the link here

**Comment by peanutbutterandcrackers** [comment] 2018-06-10 10:59
@ferdnyc - Good sir, I see that you are the one taking care of this case. I think @swwe has posted over at #1652. Would you please take a look at those? Sorry for the trouble...

**Comment by swwe** [comment] 2018-06-11 19:28
@peanutbutterandcrackers thank you jaja, i decided to download the previous version of the program right now, and at least i can export now (saving the issues)

**Comment by peanutbutterandcrackers** [comment] 2018-06-12 03:34
@swwe - Okay. I hope v2.4.2 (stable release) will be good enough for you to use. :)

**Comment by peanutbutterandcrackers** [comment] 2018-06-12 04:02
Also, the other day, I was able to export a video on my buddy's windows 10 machine with rc-1. It didn't crash. But then again, I was only testing with a few pictures and an audio file...

**Comment by peanutbutterandcrackers** [comment] 2018-06-18 02:00
@swwe - Could you please try out the latest release candidate - RC3? Maybe that'll help? Sorry for the inconvenience...

**Comment by DylanC** [comment] 2018-07-02 10:00
@cons0l3 Can you try v2.4.2 and let us know if you have any success?

**Closed** 2018-07-27 14:51 UTC
