### ISSUE TITLE
Can't open old project

### ISSUE THREAD

**Issue by XXLRay** [OpenShot/openshot-qt#85] opened 2016-02-11 13:38 UTC
I can't open the attached old project file that was created in Libreshot (fork of Openshot 1.4.4 ~alpha). Error message is:

Couldn't load project data file: Expecting value: line 1 column 1 (char 0)

Current version is openshot-qt 2.0.6

[Kdenlive_Cuttrim.osp.zip](https://github.com/OpenShot/openshot-qt/files/126439/Kdenlive_Cuttrim.osp.zip)

**Comment by jonoomph** [comment] 2016-02-11 20:52
Currently that is by design. It's on "the list". The project format changed pretty radically, and I've been trying to let it stabilize before writing an importer for the old project files. Sorry for the inconvenience.

**Comment by XXLRay** [comment] 2016-02-12 13:15
No inconvenience on my side. It was just a test case ;)

**Comment by jonoomph** [comment] 2016-03-17 04:06
We now have partial support for importing old 1.x project files. It currently supports: Files, Clips, Transitions, Fade In/Out, Volume Fade In/Out. In other words, it can open many simple and basic projects, and/or at least give you a head start. =)

**Comment by XXLRay** [comment] 2016-03-30 09:23
I tried Openshot 2.0.7 and it couldn't open one of my old projects. The error message now is:

Failed to load project file /home/anyuser/Documents/Videocut/Dummyproject/Dummyproject.osp: No module named 'classes.project'

As far as I know it doesn't contain effects. If it helps I am willing to provide the project data.

**Comment by kunguz** [comment] 2016-04-13 10:13
Same here

**Comment by jonoomph** [comment] 2016-04-13 20:59
Thanks for the bug report! I found the issue which causes the "classes.project" error and fixed it (in commit 850c1c6e157ffb6e0f5dd5d818d48136cc71ae94). 

Please download our latest daily installer (which might take an hour or two to appear):
www.openshot.org/download - click '**Other Installers**' link and grab the newest one, and see if this fix solves the problem. Thanks!

**Comment by XXLRay** [comment] 2016-04-19 08:42
Looks like I can open old projects now even though I still get an error message that says: "Failed to load project file /home/anyuser/.../anyfile": 'ba076ab0-d161-11e4-8761-d4bed91bf72e'. File and code vary with each project but are deterministic.
All files seem to be imported but the mentioned one is not placed properly in the timeline. I regularly update from the ppa but the version number still says 2.0.7. So I am not sure if I tried the latest build. I will check what the "Other Installers" option gives me when I find the time.

**Comment by jonoomph** [comment] 2016-04-19 21:49
Just committed a change to improve this error. It's having trouble loading (or finding) one of the files in your project. The newest daily build has a new commit (3b4ceffb05caba547f23ca7710a2046f611f4c38), which will display the paths of all files it can't find (or has trouble loading). This should help users find the issue and correct it. Let me know if it works for you. Thanks!

**Closed by jonoomph** 2016-04-19 21:49 UTC

**Comment by XXLRay** [comment] 2016-04-22 09:18
The error message now looks clearer (without the cryptic code) and it seems as if openshot-qt can't import the attached svg file while openshot can.
[Endslate_individual.svg.zip](https://github.com/OpenShot/openshot-qt/files/231489/Endslate_individual.svg.zip)

**Comment by ryanj** [comment] 2016-05-16 23:57
I'm getting `ERROR Failed to load project file`, and `No module named 'classes.project'` after updating to version 2.0.7

**Comment by fduraibi** [comment] 2016-05-23 14:54
I still get the same error message `Failed to load project file /home/.../Episode-7.osp: No module named 'classes.effect'`

Using the latest image `OpenShot-v2.0.7-22-gf35bad0-47-534-x86_64.AppImage`

**Comment by XXLRay** [comment] 2016-06-10 11:38
This attached
[Endslate_individual.svg.zip](https://github.com/OpenShot/openshot-qt/files/308895/Endslate_individual.svg.zip)
 svg file with the same content but a bit different structure works fine by the way.
