### ISSUE TITLE
Mac daily build OpenShot-v2.4.1-53-gb8c591b-59-688-x86_64.dmg crash

### ISSUE THREAD

**Issue by N3WWN** [OpenShot/openshot-qt#1445] opened 2018-03-29 23:02 UTC
**System Details:**
* Operating System / Distro: Mac OS X - High Sierra - 10.13
* OpenShot Version: OpenShot-v2.4.1-53-gb8c591b-59-688-x86_64.dmg
* Logs attached
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1862184/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1862185/openshot-qt.log)

**Issue Description and steps to reproduce:**
I downloaded OpenShot on my wife's "new to us" iMac to play with on here instead of Linux and saw the following errors in the logs after the application completely terminated:

> metrics:ERROR Failed to Track exception: Could not find a suitable TLS CA certificate bundle, invalid path: /Applications/OpenShot Video Editor.app/Contents/MacOS/lib/python36.zip/certifi/cacert.pem

> ==> libopenshot.log <==
---- Unhandled Exception: Stack Trace ----
  4   libopenshot.14.dylib                0x000000010b02d367 _ZN8openshot17AudioReaderSource17getNextAudioBlockERKN4juce22AudioSourceChannelInfoE + 1183
  5   libopenshot-audio.6.dylib           0x000000010c4a8c9d _ZN4juce20BufferingAudioSource19readNextBufferChunkEv + 589
  6   libopenshot-audio.6.dylib           0x000000010c4a8d8d _ZThn8_N4juce20BufferingAudioSource12useTimeSliceEv + 13
  7   libopenshot-audio.6.dylib           0x000000010c274e15 _ZN4juce15TimeSliceThread3runEv + 565
  8   libopenshot.14.dylib                0x000000010b0e99e2 _ZN8openshot19SafeTimeSliceThread3runEv + 24
  9   libopenshot-audio.6.dylib           0x000000010c27203b _ZN4juce6Thread16threadEntryPointEv + 155
  10  libopenshot-audio.6.dylib           0x000000010c292a5a threadEntryProc + 26
  11  libsystem_pthread.dylib             0x00007fff65c986c1 _pthread_body + 340
  12  libsystem_pthread.dylib             0x00007fff65c9856d _pthread_body + 0
  13  libsystem_pthread.dylib             0x00007fff65c97c5d thread_start + 13
---- End of Stack Trace ----

FYI, I loaded an existing project from my Linux system after copying it in its entirety, the preview initially populated, but when I hit play or move the playhead is when the app crashes.

There may be other errors/more info in the logs, but these are what jumped out at me.

I don't know if this is related for #1401 or not, but thought I should report this ASAP.

**Comment by DylanC** [comment] 2018-03-30 11:08
@N3WWN - Yes, I think Mr.Thomas mentioned something about certs getting broken if he upgraded the build pipeline.

**Comment by N3WWN** [comment] 2018-03-30 13:00
Thanks @DylanC !  That addresses one error... now we just need to address the unhandled exception within libopenshot! 😜

**Comment by DylanC** [comment] 2018-05-25 14:47
@N3WWN - Has this happened to you since your issue report?

**Comment by jonoomph** [comment] 2018-05-25 20:40
The bug with cacert.pem is related to the Python requests library failing due to the HTTPS redirect on openshot.org, combined with the fact we don't package the cacert.pem with our application. I've just merged in a change which will disable SSL verification for metrics and reporting exceptions, which will prevent that specific error. 

However, the real issue here is a crash in libopenshot during preview. Would be great if we could reproduce this crash.

**Closed** 2018-09-24 12:37 UTC
Labels: bug
