### ISSUE TITLE
Clip Properties Screen wont open

### ISSUE THREAD

**Issue by Teronte** [OpenShot/openshot-qt#541] opened 2017-03-20 20:54 UTC
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.2.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Hey there, I'm new to Openshot and I'm trying it out. 
Checking out in the tutorials there is a so called Clip Properties Screen, but it won't show up whenever I try to access it instead it opens a property tab next to the timeline. Any idea in how to fix this?  I'm using version 2.2.0 in a Windows 10 computer

**Comment by foobarbecue** [comment] 2017-03-28 21:44
Same here. Windows 10 build 10586.839, 2.2.0

**Comment by foobarbecue** [comment] 2017-03-28 21:46
Oh, that's because my properties pane is already open. Ok, but I can't figure out how to crop a clip (in x-y space, not trim in time).

**Comment by foobarbecue** [comment] 2017-03-28 21:49
Oh, wow, it's hidden in the advanced settings under the "scale" property. Not at all what I'd expect from the latest user's manual, which appears to be version 1.3...

**Comment by BluebellCW** [comment] 2017-04-09 22:28
I've been having the same problem. When I change the setting from "Best Fit" to "Crop", nothing happens, as far as I can tell. Am I missing something obvious? What should I do next?

**Comment by foobarbecue** [comment] 2017-04-11 13:56
Hm. So I actually never cropped anything, and I assumed the "scale" numbers would cause cropping if you changed them once you have it in "crop mode". Just tried, and they don't. So I have no idea how you're supposed to crop in Openshot. BluebellCW, how about you open an issue for that since we're off topic here.

**Comment by DylanC** [comment] 2017-08-25 13:01
@Teronte - Does this issue still occur in either the daily build or v2.3.4?

**Comment by DylanC** [comment] 2017-08-28 09:47
Duplicate of #530

**Comment by Vekuu** [comment] 2017-08-31 10:40
Doesn't help me. I want to change clip direction, that can be done in clip properties but properties windows  won't open. Any ideas how to make it open?

**Comment by DylanC** [comment] 2017-09-17 21:56
The properties screen does show on the left as a docked item currently. It does not appear as a window.
![properties](https://user-images.githubusercontent.com/4488048/30525276-6af63f16-9bfb-11e7-9cd1-31b8c630ed80.png)

**Closed by DylanC** 2017-09-17 21:56 UTC
Labels: duplicate
