### ISSUE TITLE
timeline zoom start preferences needed in openshot preferences dialog box

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1955] opened 2018-08-05 01:07 UTC
hello everyone, Its frustrating opening openshot sometimes to see the zoom level starts at 14 secs
on the time line or even 174 secs as its a chore to move the  zoom slider back to 1 secs when there
are alot of tracks with video and audio.

having an input start in preferences for zoom level would be handy so everytime you start openshot
it will start at your desired zoom level .
heres a photo to show what im talking about .
![timeline zoom mins](https://user-images.githubusercontent.com/40479177/43681725-b17d73c2-989f-11e8-9e3d-cb5771a9d558.jpg)

cheers bob

**Comment by DerGenaue** [comment] 2018-08-19 22:17
I think OpenShot should actually just save the last zoom level the user was at.
No need for an option with this solution.
Apparently this even used to exist...
Did it get removed to fix #1592?

Otherwise there might be a bug with the zoom level as whenever opening a recent project,
the level for me is way further out than it was before.

(Could it be that you save the zoom level in "seconds" and load it as a zoom level?
Aka. saving: "5s"; loading: 5th option = 20s)

**Comment by bobcrikey** [comment] 2018-08-22 12:37
@DerGenaue  I need a zoom level set at 1.00 due to the animations i make are always 1 secs.
when i have up to a mins worth of animation and audio having a reload always start at 174 secs is
not good , having the choice of of zoom level starts is most important as the user can input its own
starting zoom level.
 Check out my youtube animations all made with openshot 
https://www.youtube.com/channel/UCUEPlIJDPz3JeSBXxjvfurQ

im currently working on a starwars animation :), being made with openshot 2.4.2

cheers bob

**Comment by DerGenaue** [comment] 2018-08-30 18:16
Do the latest dev-builds solve your issue?

**Comment by ferdnyc** [comment] 2019-07-20 11:52
I'd just like to point out that `SecondsToZoom()` worked _fiiiiiiiine_ when I **wrote** it<sup>**1**</sup>. You know, before it got bikeshedded to death. [As I predicted.](https://github.com/OpenShot/openshot-qt/issues/1571#issuecomment-388491441) 😏 

(Though, one could make the argument that it was actually @DylanC 's [prediction](https://github.com/OpenShot/openshot-qt/issues/1571#issuecomment-387997460) that ultimately came true, there.)

Regardless, eventually @DerGenaue fixed it _properly_, and since then nobody's noticed, cared about, or meddled with zoom, because it was finally working correctly. (At the risk of belaboring the point: _also_ [as I predicted](https://github.com/OpenShot/openshot-qt/issues/1571#issuecomment-388487057).)

Closing this as (arguably) invalidated by the current implementation, and also very very old.


##### Notes
1. (Meaning, it functioned correctly and as designed in all situations, though the scale it produced was admittedly unideal.)

**Closed by ferdnyc** 2019-07-20 11:52 UTC
Labels: enhancement
