### ISSUE TITLE
Turn off GUI update while removing clips from the Library

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3110] opened 2019-12-03 19:57 UTC
**Describe the new feature:**

When removing multiple clips from the Library, the GUI element updates slowly and flickers. It seems it parses and redraws one-by-one all of the elements after each deleted element.

What about temporally disabling the GUI element/turning off the GUI update/message listener etc. until all clips are removed, and redrawing just once at the end of the operation.

* Common use case: a set of projects sharing some assets like intro, some titles etc., starting a new project by saving the old one with a new name, then removing part of the clips.

**Comment by ferdnyc** [comment] 2019-12-04 02:43
The situation is actually much worse than that, I'm afraid. Duplicate of #444.

From https://github.com/OpenShot/openshot-qt/issues/444#issuecomment-538687552
> This is all due to the fact that OpenShot unnecessarily rebuilds (not just redraws, but actually _deletes_ and completely recreates) the Files model for each and every individual add/remove operation..

**Closed by ferdnyc** 2019-12-04 02:43 UTC
Labels: 💡 enhancement

**Comment by codral** [comment] 2020-03-01 01:24
This might not be the right spot but while looking for fixes i figured out a workaround for this issue which speeds importing images up quite a lot and might help someone in my situation.

I start the images importing then i click into the Video tab, that way it doesn't constantly refresh and it seems to import at about 15% extra CPU load and about 10x as quick.  Hope this is helpful in some way, first time I've registered an account here and i'm not a programmer... Maybe you could code it to change tab to video whenever importing images and vice versa?

Cheers, Cod
