### ISSUE TITLE
No audio when previewing

### ISSUE THREAD

**Issue by CJCHProgrammer** [OpenShot/openshot-qt#4396] opened 2021-09-06 19:51 UTC
**Describe the bug**
When I would preview a video I had assembled, it wouldn't play any of the audio. I tried changing the volume of the video, and the volume of my pc, but no audio would play.

**Steps to reproduce the behavior:**
1. Import any audio file/ video file that has audio in it
2. Preview the video

**Expected behavior**
No audio will play when reproducing the behavior

**System Details**
- OpenShot Version: 2.6.0
- libopenshot Version:  0.2.6
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/g1f7gs8ily937joy78cezaerwzltgkgj/openshot-qt.zip) (12 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/g1f7gs8ily937joy78cezaerwzltgkgj/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by speedytechdev** [comment] 2021-09-07 03:29
@JacksonRG Do you think this is related to the headphones issue?

**Comment by speedytechdev** [comment] 2021-09-07 05:31
Hi @CJCHProgrammer, Do you use headphones when using Openshot?

**Comment by speedytechdev** [comment] 2021-09-08 04:16
So this is a common problem we are having with headphones. Our dev team is looking into this bug. The only workaround we have at the moment is you plug your headphones in before you launch Openshot. Our dev team will contact you if they need any information. Please feel free to reach out if you need any more support from us.  We do apologize for any inconvenience this has caused you.

Thank You and enjoy the rest of your day.
Speedytechlive - Support Team

**Comment by DanPinGF** [comment] 2021-10-19 01:40
Duplicate of #4303, if it has to do with headphones/sleep.

**Comment by Colorjet3** [comment] 2023-01-24 03:03
Headphones have been a known issue in the Windows environment. Try, this:

    Close OpenShot.
    Plug-in your headphone.
    Test the audio in Windows (outside of OpenShot to ensure it is working).
    Start OpenShot and go to Edit | Preferences | Preview.
    Check the "Playback Audio Device" and if it is set to Default, click on drop down arrow and find an entry for your headphone. It will be something like "Windows Audio: thenameofyourheadphone". Select it.
    Restart OpenShot and see if that takes care of the audio issue.
    You may have to do the reverse if/when you remove the headphone.

**Closed by Colorjet3** 2023-01-24 03:03 UTC
Labels: :lady_beetle: bug, 🔥 hot
